# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clinical', '0002_initial'),
        ('core', '0006_reason_categories_consultation_service'),
        ('orders', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='clinicalnoteevent',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalnoteevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='clinicalnoteevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clinical.clinicalnote'),
        ),
        migrations.AddField(
            model_name='clinicalnoteevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='clinical.clinicalnote'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='diagnosisevent',
            name='note',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clinical.clinicalnote'),
        ),
        migrations.AddField(
            model_name='diagnosisevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='diagnosisevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clinical.diagnosis'),
        ),
        migrations.AddField(
            model_name='diagnosisevent',
            name='recorded_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosisevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='icd10code',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_en'], name='clinical_icd10_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='icd10code',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_ar'], name='clinical_icd10_ar_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='diagnosisevent',
            name='icd10',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clinical.icd10code'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='icd10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinical.icd10code'),
        ),
        migrations.AddField(
            model_name='chronicconditionevent',
            name='icd10',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clinical.icd10code'),
        ),
        migrations.AddField(
            model_name='chroniccondition',
            name='icd10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinical.icd10code'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='icd10code',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_icd10codeevent" ("active", "chapter", "code", "id", "is_leaf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title_ar", "title_en") VALUES (NEW."active", NEW."chapter", NEW."code", NEW."id", NEW."is_leaf", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title_ar", NEW."title_en"); RETURN NULL;', hash='c355dd8376493624325a4d853bd6bcfde0e1c342', operation='INSERT', pgid='pgtrigger_insert_insert_5b7e6', table='clinical_icd10code', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='icd10code',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_icd10codeevent" ("active", "chapter", "code", "id", "is_leaf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title_ar", "title_en") VALUES (NEW."active", NEW."chapter", NEW."code", NEW."id", NEW."is_leaf", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title_ar", NEW."title_en"); RETURN NULL;', hash='b8fcf33ae0a2c007d17ee9b3eeda03115f653ac2', operation='UPDATE', pgid='pgtrigger_update_update_3d20c', table='clinical_icd10code', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='icd10code',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_icd10codeevent" ("active", "chapter", "code", "id", "is_leaf", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title_ar", "title_en") VALUES (OLD."active", OLD."chapter", OLD."code", OLD."id", OLD."is_leaf", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title_ar", OLD."title_en"); RETURN NULL;', hash='3ee3f1f0cb71d3cb0fe43d7ca72033044e95c4cc', operation='DELETE', pgid='pgtrigger_delete_delete_2d562', table='clinical_icd10code', when='AFTER')),
        ),
        migrations.AddField(
            model_name='icd10codeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='icd10codeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clinical.icd10code'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='service_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to='orders.serviceline'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='nursingnoteevent',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnoteevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='nursingnoteevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clinical.nursingnote'),
        ),
        migrations.AddField(
            model_name='nursingnoteevent',
            name='service_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.serviceline'),
        ),
        migrations.AddField(
            model_name='nursingnoteevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='orderset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='orderset',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Empty = shared with every doctor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersetevent',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='ordersetevent',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Empty = shared with every doctor.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersetevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='ordersetevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clinical.orderset'),
        ),
        migrations.AddField(
            model_name='ordersetitem',
            name='order_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.orderset'),
        ),
        migrations.AddField(
            model_name='ordersetitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='ordersetitemevent',
            name='order_set',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clinical.orderset'),
        ),
        migrations.AddField(
            model_name='ordersetitemevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='ordersetitemevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clinical.ordersetitem'),
        ),
        migrations.AddField(
            model_name='ordersetitemevent',
            name='service',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='referral',
            name='to_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.doctorprofile'),
        ),
        migrations.AddField(
            model_name='referral',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clinical.referral'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='referred_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='to_department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='to_doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.doctorprofile'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitals',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vitals', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='vitalsevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='vitalsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clinical.vitals'),
        ),
        migrations.AddField(
            model_name='vitalsevent',
            name='recorded_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['patient', 'status'], name='clinical_allergy_patient_idx'),
        ),
        migrations.AddConstraint(
            model_name='allergy',
            constraint=models.CheckConstraint(condition=models.Q(('allergen_type__in', ['drug', 'drug_class', 'food', 'environmental', 'other'])), name='clinical_allergy_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='allergy',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['mild', 'moderate', 'severe', 'life_threatening'])), name='clinical_allergy_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='allergy',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'entered_in_error'])), name='clinical_allergy_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='allergy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allergen_type', 'drug_class'), _negated=True), ('drug_class__isnull', False), _connector='OR'), name='clinical_allergy_class_named'),
        ),
        migrations.AddConstraint(
            model_name='allergy',
            constraint=models.CheckConstraint(condition=models.Q(('drug_class__isnull', False), ('item__isnull', False), models.Q(('substance', ''), _negated=True), _connector='OR'), name='clinical_allergy_has_allergen'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allergy',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_allergyevent" ("allergen_type", "drug_class_id", "id", "item_id", "note", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reaction", "recorded_at", "recorded_by_id", "severity", "status", "substance", "updated_at") VALUES (NEW."allergen_type", NEW."drug_class_id", NEW."id", NEW."item_id", NEW."note", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reaction", NEW."recorded_at", NEW."recorded_by_id", NEW."severity", NEW."status", NEW."substance", NEW."updated_at"); RETURN NULL;', hash='428c65c5800578240a3dfa01c6c9e319243dae39', operation='INSERT', pgid='pgtrigger_insert_insert_96d48', table='clinical_allergy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allergy',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_allergyevent" ("allergen_type", "drug_class_id", "id", "item_id", "note", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reaction", "recorded_at", "recorded_by_id", "severity", "status", "substance", "updated_at") VALUES (NEW."allergen_type", NEW."drug_class_id", NEW."id", NEW."item_id", NEW."note", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reaction", NEW."recorded_at", NEW."recorded_by_id", NEW."severity", NEW."status", NEW."substance", NEW."updated_at"); RETURN NULL;', hash='b0e3ae981eb37bdbc94e2b83939deb9f27f9c458', operation='UPDATE', pgid='pgtrigger_update_update_21701', table='clinical_allergy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allergy',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_allergyevent" ("allergen_type", "drug_class_id", "id", "item_id", "note", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reaction", "recorded_at", "recorded_by_id", "severity", "status", "substance", "updated_at") VALUES (OLD."allergen_type", OLD."drug_class_id", OLD."id", OLD."item_id", OLD."note", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reaction", OLD."recorded_at", OLD."recorded_by_id", OLD."severity", OLD."status", OLD."substance", OLD."updated_at"); RETURN NULL;', hash='2edc1ed3cabd733f9611f92c2052a8b40b9824b0', operation='DELETE', pgid='pgtrigger_delete_delete_37194', table='clinical_allergy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allergyevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='65ad82db13bfeb4b63794a5103cc1fffc871df52', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e9585', table='clinical_allergyevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['visit'], name='clinical_note_visit_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalnote',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'signed'])), name='clinical_note_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='clinicalnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'signed'), _negated=True), ('signed_at__isnull', False), _connector='OR'), name='clinical_note_signed_has_time'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clinicalnote',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_clinicalnoteevent" ("assessment", "author_id", "complaint", "created_at", "examination", "history", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan", "signed_at", "status", "updated_at", "visit_id") VALUES (NEW."assessment", NEW."author_id", NEW."complaint", NEW."created_at", NEW."examination", NEW."history", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plan", NEW."signed_at", NEW."status", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='a85d7ed31e8240aaaeaf8ac1f8cbfc4c0c47b034', operation='INSERT', pgid='pgtrigger_insert_insert_8b339', table='clinical_clinicalnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clinicalnote',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_clinicalnoteevent" ("assessment", "author_id", "complaint", "created_at", "examination", "history", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan", "signed_at", "status", "updated_at", "visit_id") VALUES (NEW."assessment", NEW."author_id", NEW."complaint", NEW."created_at", NEW."examination", NEW."history", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plan", NEW."signed_at", NEW."status", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='3fdadd64192fa72bbf4d1b742c2d08a02d5f15d6', operation='UPDATE', pgid='pgtrigger_update_update_8894c', table='clinical_clinicalnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clinicalnote',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_clinicalnoteevent" ("assessment", "author_id", "complaint", "created_at", "examination", "history", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan", "signed_at", "status", "updated_at", "visit_id") VALUES (OLD."assessment", OLD."author_id", OLD."complaint", OLD."created_at", OLD."examination", OLD."history", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plan", OLD."signed_at", OLD."status", OLD."updated_at", OLD."visit_id"); RETURN NULL;', hash='a9f8ac25019dfe3e7850177ff77ee962280c4737', operation='DELETE', pgid='pgtrigger_delete_delete_df69d', table='clinical_clinicalnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clinicalnoteevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f501d6ba0d25f1531c74968079b3adb94bac93de', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_6e6b9', table='clinical_clinicalnoteevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='diagnosisevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='fc86672a2890dc4d0e15151e2bcb17bfe9349175', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3e9e6', table='clinical_diagnosisevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['icd10', 'recorded_at'], name='clinical_diagnosis_icd_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['primary', 'secondary'])), name='clinical_diagnosis_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.CheckConstraint(condition=models.Q(('certainty__in', ['provisional', 'confirmed'])), name='clinical_diagnosis_certainty_valid'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.CheckConstraint(condition=models.Q(('icd10__isnull', False), models.Q(('text', ''), _negated=True), _connector='OR'), name='clinical_diagnosis_named'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='diagnosis',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_diagnosisevent" ("certainty", "icd10_id", "id", "kind", "note_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_at", "recorded_by_id", "text", "visit_id") VALUES (NEW."certainty", NEW."icd10_id", NEW."id", NEW."kind", NEW."note_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."recorded_at", NEW."recorded_by_id", NEW."text", NEW."visit_id"); RETURN NULL;', hash='1dc76cea184263d87548493993c7d69f6a1584e0', operation='INSERT', pgid='pgtrigger_insert_insert_5667c', table='clinical_diagnosis', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='diagnosis',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_diagnosisevent" ("certainty", "icd10_id", "id", "kind", "note_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_at", "recorded_by_id", "text", "visit_id") VALUES (NEW."certainty", NEW."icd10_id", NEW."id", NEW."kind", NEW."note_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."recorded_at", NEW."recorded_by_id", NEW."text", NEW."visit_id"); RETURN NULL;', hash='d32b54659a131dc2acee0aa3a54e61b3992a9c1b', operation='UPDATE', pgid='pgtrigger_update_update_0e1ff', table='clinical_diagnosis', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='diagnosis',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_diagnosisevent" ("certainty", "icd10_id", "id", "kind", "note_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_at", "recorded_by_id", "text", "visit_id") VALUES (OLD."certainty", OLD."icd10_id", OLD."id", OLD."kind", OLD."note_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recorded_at", OLD."recorded_by_id", OLD."text", OLD."visit_id"); RETURN NULL;', hash='60aaf2b6c5bb8efe8fb48ce60383e77425a1e778', operation='DELETE', pgid='pgtrigger_delete_delete_a2aa1', table='clinical_diagnosis', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chronicconditionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='a7ef3668afb92d049fcc734063b6907eaf49cce7', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_9b489', table='clinical_chronicconditionevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='chroniccondition',
            index=models.Index(fields=['patient', 'status'], name='clinical_condition_patient_idx'),
        ),
        migrations.AddConstraint(
            model_name='chroniccondition',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'entered_in_error'])), name='clinical_condition_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='chroniccondition',
            constraint=models.CheckConstraint(condition=models.Q(('icd10__isnull', False), models.Q(('name', ''), _negated=True), _connector='OR'), name='clinical_condition_named'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chroniccondition',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_chronicconditionevent" ("icd10_id", "id", "name", "note", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_at", "recorded_by_id", "since", "status", "updated_at") VALUES (NEW."icd10_id", NEW."id", NEW."name", NEW."note", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."recorded_at", NEW."recorded_by_id", NEW."since", NEW."status", NEW."updated_at"); RETURN NULL;', hash='3597c2f6d202e552512ed4c150a3af0df23a4e5b', operation='INSERT', pgid='pgtrigger_insert_insert_c1d47', table='clinical_chroniccondition', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chroniccondition',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_chronicconditionevent" ("icd10_id", "id", "name", "note", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_at", "recorded_by_id", "since", "status", "updated_at") VALUES (NEW."icd10_id", NEW."id", NEW."name", NEW."note", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."recorded_at", NEW."recorded_by_id", NEW."since", NEW."status", NEW."updated_at"); RETURN NULL;', hash='bc298695794d72d25f0b6c2a679efa514e957716', operation='UPDATE', pgid='pgtrigger_update_update_e3813', table='clinical_chroniccondition', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='chroniccondition',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_chronicconditionevent" ("icd10_id", "id", "name", "note", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_at", "recorded_by_id", "since", "status", "updated_at") VALUES (OLD."icd10_id", OLD."id", OLD."name", OLD."note", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recorded_at", OLD."recorded_by_id", OLD."since", OLD."status", OLD."updated_at"); RETURN NULL;', hash='374d2b9892a2ea6be2d2d045fc1321152bc6b76c', operation='DELETE', pgid='pgtrigger_delete_delete_7320d', table='clinical_chroniccondition', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='icd10codeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0367b4113ba4cfee5c64c3fbfa3aaa5a058acae0', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_85b02', table='clinical_icd10codeevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='nursingnote',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['general', 'procedure', 'handover'])), name='clinical_nursingnote_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='nursingnote',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='clinical_nursingnote_has_text'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nursingnote',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_nursingnoteevent" ("author_id", "created_at", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_line_id", "text", "visit_id") VALUES (NEW."author_id", NEW."created_at", NEW."id", NEW."kind", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."service_line_id", NEW."text", NEW."visit_id"); RETURN NULL;', hash='a389b957fbaea674df5487ff49d9291bad289830', operation='INSERT', pgid='pgtrigger_insert_insert_b6b66', table='clinical_nursingnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nursingnote',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_nursingnoteevent" ("author_id", "created_at", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_line_id", "text", "visit_id") VALUES (NEW."author_id", NEW."created_at", NEW."id", NEW."kind", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."service_line_id", NEW."text", NEW."visit_id"); RETURN NULL;', hash='7fee6affa10ab8daa6fc66fbc82b1edbeddc23aa', operation='UPDATE', pgid='pgtrigger_update_update_bb3ef', table='clinical_nursingnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nursingnote',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_nursingnoteevent" ("author_id", "created_at", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_line_id", "text", "visit_id") VALUES (OLD."author_id", OLD."created_at", OLD."id", OLD."kind", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."service_line_id", OLD."text", OLD."visit_id"); RETURN NULL;', hash='3888df531c12a6c9f033ef2862726e402b526e2f', operation='DELETE', pgid='pgtrigger_delete_delete_d7cf9', table='clinical_nursingnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nursingnoteevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='ade67a566a99a2364e0fe8c8c97d412b910672b2', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_7eb36', table='clinical_nursingnoteevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderset',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_ordersetevent" ("active", "created_at", "department_id", "id", "name_ar", "name_en", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at") VALUES (NEW."active", NEW."created_at", NEW."department_id", NEW."id", NEW."name_ar", NEW."name_en", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order", NEW."updated_at"); RETURN NULL;', hash='c98a36d0733484d4a7b90c2e41b79e329323e9ab', operation='INSERT', pgid='pgtrigger_insert_insert_003b9', table='clinical_orderset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderset',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_ordersetevent" ("active", "created_at", "department_id", "id", "name_ar", "name_en", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at") VALUES (NEW."active", NEW."created_at", NEW."department_id", NEW."id", NEW."name_ar", NEW."name_en", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order", NEW."updated_at"); RETURN NULL;', hash='d830e9eb57abfb698c5a6cd2ddf4db15226748f7', operation='UPDATE', pgid='pgtrigger_update_update_fd397', table='clinical_orderset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderset',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_ordersetevent" ("active", "created_at", "department_id", "id", "name_ar", "name_en", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at") VALUES (OLD."active", OLD."created_at", OLD."department_id", OLD."id", OLD."name_ar", OLD."name_en", OLD."owner_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order", OLD."updated_at"); RETURN NULL;', hash='9a9c0805f3c79d2b462ccf913ad589ef57d2b95c', operation='DELETE', pgid='pgtrigger_delete_delete_68743', table='clinical_orderset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordersetevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='54e3ebae123e8ef1bd309cf10beb19a39fdb1e5d', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_10ad9', table='clinical_ordersetevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='ordersetitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='clinical_orderset_qty_positive'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordersetitem',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_ordersetitemevent" ("dose", "duration_days", "frequency_code", "id", "instructions", "order_set_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "service_id", "sort_order") VALUES (NEW."dose", NEW."duration_days", NEW."frequency_code", NEW."id", NEW."instructions", NEW."order_set_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."quantity", NEW."service_id", NEW."sort_order"); RETURN NULL;', hash='70939383f939554b3bce46afc8daeecdbf6b3737', operation='INSERT', pgid='pgtrigger_insert_insert_f67cd', table='clinical_ordersetitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordersetitem',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_ordersetitemevent" ("dose", "duration_days", "frequency_code", "id", "instructions", "order_set_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "service_id", "sort_order") VALUES (NEW."dose", NEW."duration_days", NEW."frequency_code", NEW."id", NEW."instructions", NEW."order_set_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."quantity", NEW."service_id", NEW."sort_order"); RETURN NULL;', hash='6ad4cbf6961df625c3d50a57968eae9aa377a55a', operation='UPDATE', pgid='pgtrigger_update_update_e3b8a', table='clinical_ordersetitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordersetitem',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_ordersetitemevent" ("dose", "duration_days", "frequency_code", "id", "instructions", "order_set_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "service_id", "sort_order") VALUES (OLD."dose", OLD."duration_days", OLD."frequency_code", OLD."id", OLD."instructions", OLD."order_set_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."quantity", OLD."service_id", OLD."sort_order"); RETURN NULL;', hash='4c5518c21809e22cb7b3d85f1018dde42e831b6f', operation='DELETE', pgid='pgtrigger_delete_delete_c911c', table='clinical_ordersetitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordersetitemevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='89bb28aae8147c8fea9f9c6cca6cfef56501ca55', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_9ffee', table='clinical_ordersetitemevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['internal', 'external'])), name='clinical_referral_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('urgency__in', ['routine', 'urgent', 'emergency'])), name='clinical_referral_urgency_valid'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['issued', 'completed', 'cancelled'])), name='clinical_referral_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'internal'), _negated=True), ('to_department__isnull', False), _connector='OR'), name='clinical_referral_internal_has_department'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'external'), _negated=True), models.Q(('external_facility', ''), _negated=True), _connector='OR'), name='clinical_referral_external_has_facility'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='clinical_referral_has_reason'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_referralevent" ("clinical_summary", "created_at", "external_facility", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "referred_by_id", "status", "to_department_id", "to_doctor_id", "updated_at", "urgency", "visit_id") VALUES (NEW."clinical_summary", NEW."created_at", NEW."external_facility", NEW."id", NEW."kind", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason", NEW."referred_by_id", NEW."status", NEW."to_department_id", NEW."to_doctor_id", NEW."updated_at", NEW."urgency", NEW."visit_id"); RETURN NULL;', hash='4b07a3ff4bb2dbd3c4b2e5c71ba35ca280457b12', operation='INSERT', pgid='pgtrigger_insert_insert_bde2a', table='clinical_referral', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_referralevent" ("clinical_summary", "created_at", "external_facility", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "referred_by_id", "status", "to_department_id", "to_doctor_id", "updated_at", "urgency", "visit_id") VALUES (NEW."clinical_summary", NEW."created_at", NEW."external_facility", NEW."id", NEW."kind", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason", NEW."referred_by_id", NEW."status", NEW."to_department_id", NEW."to_doctor_id", NEW."updated_at", NEW."urgency", NEW."visit_id"); RETURN NULL;', hash='2a3080454616ba369e8dcbcfc62f44c9f4ce40bb', operation='UPDATE', pgid='pgtrigger_update_update_49255', table='clinical_referral', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_referralevent" ("clinical_summary", "created_at", "external_facility", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "referred_by_id", "status", "to_department_id", "to_doctor_id", "updated_at", "urgency", "visit_id") VALUES (OLD."clinical_summary", OLD."created_at", OLD."external_facility", OLD."id", OLD."kind", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reason", OLD."referred_by_id", OLD."status", OLD."to_department_id", OLD."to_doctor_id", OLD."updated_at", OLD."urgency", OLD."visit_id"); RETURN NULL;', hash='b502c389fd40b9cbe32d19c994295ac9c4dd747d', operation='DELETE', pgid='pgtrigger_delete_delete_884be', table='clinical_referral', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referralevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='ecaaa2fb156b84a777beef44a4a268700bc33e22', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0615e', table='clinical_referralevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='vitals',
            index=models.Index(fields=['visit', '-recorded_at'], name='clinical_vitals_visit_idx'),
        ),
        migrations.AddConstraint(
            model_name='vitals',
            constraint=models.CheckConstraint(condition=models.Q(('temperature_c__isnull', True), models.Q(('temperature_c__gte', 25), ('temperature_c__lte', 45)), _connector='OR'), name='clinical_vitals_temperature_range'),
        ),
        migrations.AddConstraint(
            model_name='vitals',
            constraint=models.CheckConstraint(condition=models.Q(('pulse_bpm__isnull', True), ('pulse_bpm__lte', 300), _connector='OR'), name='clinical_vitals_pulse_range'),
        ),
        migrations.AddConstraint(
            model_name='vitals',
            constraint=models.CheckConstraint(condition=models.Q(('respiratory_rate__isnull', True), ('respiratory_rate__lte', 120), _connector='OR'), name='clinical_vitals_rr_range'),
        ),
        migrations.AddConstraint(
            model_name='vitals',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bp_systolic__isnull', True), ('bp_systolic__lte', 350), _connector='OR'), models.Q(('bp_diastolic__isnull', True), ('bp_diastolic__lte', 250), _connector='OR')), name='clinical_vitals_bp_range'),
        ),
        migrations.AddConstraint(
            model_name='vitals',
            constraint=models.CheckConstraint(condition=models.Q(('spo2_percent__isnull', True), ('spo2_percent__lte', 100), _connector='OR'), name='clinical_vitals_spo2_range'),
        ),
        migrations.AddConstraint(
            model_name='vitals',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('weight_kg__isnull', True), models.Q(('weight_kg__gt', 0), ('weight_kg__lte', 500)), _connector='OR'), models.Q(('height_cm__isnull', True), models.Q(('height_cm__gt', 0), ('height_cm__lte', 272)), _connector='OR')), name='clinical_vitals_body_range'),
        ),
        migrations.AddConstraint(
            model_name='vitals',
            constraint=models.CheckConstraint(condition=models.Q(('pain_score__isnull', True), ('pain_score__lte', 10), _connector='OR'), name='clinical_vitals_pain_range'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='vitals',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_vitalsevent" ("blood_glucose_mg_dl", "bp_diastolic", "bp_systolic", "created_at", "height_cm", "id", "note", "pain_score", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pulse_bpm", "recorded_at", "recorded_by_id", "respiratory_rate", "spo2_percent", "temperature_c", "visit_id", "weight_kg") VALUES (NEW."blood_glucose_mg_dl", NEW."bp_diastolic", NEW."bp_systolic", NEW."created_at", NEW."height_cm", NEW."id", NEW."note", NEW."pain_score", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pulse_bpm", NEW."recorded_at", NEW."recorded_by_id", NEW."respiratory_rate", NEW."spo2_percent", NEW."temperature_c", NEW."visit_id", NEW."weight_kg"); RETURN NULL;', hash='4c9c5e0fab8dbb56a4cca97791bc8565a5c07e57', operation='INSERT', pgid='pgtrigger_insert_insert_d66d0', table='clinical_vitals', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='vitals',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_vitalsevent" ("blood_glucose_mg_dl", "bp_diastolic", "bp_systolic", "created_at", "height_cm", "id", "note", "pain_score", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pulse_bpm", "recorded_at", "recorded_by_id", "respiratory_rate", "spo2_percent", "temperature_c", "visit_id", "weight_kg") VALUES (NEW."blood_glucose_mg_dl", NEW."bp_diastolic", NEW."bp_systolic", NEW."created_at", NEW."height_cm", NEW."id", NEW."note", NEW."pain_score", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pulse_bpm", NEW."recorded_at", NEW."recorded_by_id", NEW."respiratory_rate", NEW."spo2_percent", NEW."temperature_c", NEW."visit_id", NEW."weight_kg"); RETURN NULL;', hash='6507027ab94c3b889fd5bcd28b3c6c2c12338943', operation='UPDATE', pgid='pgtrigger_update_update_d361f', table='clinical_vitals', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='vitals',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_vitalsevent" ("blood_glucose_mg_dl", "bp_diastolic", "bp_systolic", "created_at", "height_cm", "id", "note", "pain_score", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pulse_bpm", "recorded_at", "recorded_by_id", "respiratory_rate", "spo2_percent", "temperature_c", "visit_id", "weight_kg") VALUES (OLD."blood_glucose_mg_dl", OLD."bp_diastolic", OLD."bp_systolic", OLD."created_at", OLD."height_cm", OLD."id", OLD."note", OLD."pain_score", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pulse_bpm", OLD."recorded_at", OLD."recorded_by_id", OLD."respiratory_rate", OLD."spo2_percent", OLD."temperature_c", OLD."visit_id", OLD."weight_kg"); RETURN NULL;', hash='f022076f6b1fe65a3664fdc50645b0961aef8138', operation='DELETE', pgid='pgtrigger_delete_delete_583ae', table='clinical_vitals', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='vitalsevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='db2d05f4a404abbb591b1307cd7a5478248de217', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4a75b', table='clinical_vitalsevent', when='BEFORE')),
        ),
    ]
