"""Seed common ICD-10 (WHO) codes with English and Arabic titles (FEATURES 3.3).

A starter list for a Sudanese outpatient center: infectious and tropical diseases (malaria,
typhoid, schistosomiasis, leishmaniasis), chronic diseases (diabetes, hypertension, sickle
cell), maternal and child health, common injuries and Z codes. The full classification can
be imported later; rows that exist are left untouched (a center's edits survive), so the
seed is safe to re-run. ``apps.catalog.tests.seeding`` re-runs it after transactional tests.
"""

from django.db import migrations

# (code, English title, Arabic title, chapter)
ICD10 = [
    # I. Certain infectious and parasitic diseases (A00-B99)
    ("A00.9", "Cholera, unspecified", "الكوليرا، غير محددة", "I"),
    ("A01.0", "Typhoid fever", "حمى التيفوئيد", "I"),
    ("A01.4", "Paratyphoid fever, unspecified", "حمى نظيرة التيفوئيد، غير محددة", "I"),
    ("A02.0", "Salmonella enteritis", "التهاب الأمعاء بالسالمونيلا", "I"),
    ("A03.9", "Shigellosis, unspecified", "داء الشيغيلات، غير محدد", "I"),
    ("A06.0", "Acute amoebic dysentery", "الزحار الأميبي الحاد", "I"),
    ("A07.1", "Giardiasis [lambliasis]", "داء الجيارديات", "I"),
    ("A08.4", "Viral intestinal infection, unspecified", "عدوى معوية فيروسية، غير محددة", "I"),
    (
        "A09.0",
        "Other and unspecified gastroenteritis and colitis of infectious origin",
        "التهاب المعدة والأمعاء والقولون من منشأ معدٍ",
        "I",
    ),
    (
        "A09.9",
        "Gastroenteritis and colitis of unspecified origin",
        "التهاب المعدة والأمعاء والقولون غير محدد المنشأ (إسهال)",
        "I",
    ),
    ("A15.0", "Tuberculosis of lung, confirmed", "سل الرئة، مؤكد", "I"),
    (
        "A16.9",
        "Respiratory tuberculosis unspecified, without bacteriological or histological "
        "confirmation",
        "سل تنفسي غير محدد دون تأكيد جرثومي أو نسيجي",
        "I",
    ),
    ("A18.0", "Tuberculosis of bones and joints", "سل العظام والمفاصل", "I"),
    ("A19.9", "Miliary tuberculosis, unspecified", "السل الدخني، غير محدد", "I"),
    ("A30.9", "Leprosy, unspecified", "الجذام، غير محدد", "I"),
    ("A33", "Tetanus neonatorum", "كزاز الوليد", "I"),
    ("A35", "Other tetanus", "الكزاز", "I"),
    ("A36.9", "Diphtheria, unspecified", "الخناق (الدفتيريا)، غير محدد", "I"),
    ("A37.9", "Whooping cough, unspecified", "السعال الديكي، غير محدد", "I"),
    ("A38", "Scarlet fever", "الحمى القرمزية", "I"),
    ("A39.0", "Meningococcal meningitis", "التهاب السحايا بالمكورات السحائية", "I"),
    ("A41.9", "Sepsis, unspecified", "الإنتان (تعفن الدم)، غير محدد", "I"),
    ("A46", "Erysipelas", "الحمرة", "I"),
    ("A49.9", "Bacterial infection, unspecified", "عدوى جرثومية، غير محددة", "I"),
    ("A50.9", "Congenital syphilis, unspecified", "الزهري الخلقي، غير محدد", "I"),
    ("A53.9", "Syphilis, unspecified", "الزهري، غير محدد", "I"),
    ("A54.9", "Gonococcal infection, unspecified", "عدوى السيلان، غير محددة", "I"),
    (
        "A56.2",
        "Chlamydial infection of genitourinary tract, unspecified",
        "عدوى المتدثرة في الجهاز البولي التناسلي، غير محددة",
        "I",
    ),
    ("A59.0", "Urogenital trichomoniasis", "داء المشعرات البولي التناسلي", "I"),
    (
        "A60.0",
        "Herpesviral infection of genitalia and urogenital tract",
        "عدوى الحلأ (الهربس) في الأعضاء التناسلية",
        "I",
    ),
    ("A82.9", "Rabies, unspecified", "داء الكلب، غير محدد", "I"),
    ("A90", "Dengue fever [classical dengue]", "حمى الضنك", "I"),
    ("A91", "Dengue haemorrhagic fever", "حمى الضنك النزفية", "I"),
    ("A92.0", "Chikungunya virus disease", "داء فيروس شيكونغونيا", "I"),
    ("A95.9", "Yellow fever, unspecified", "الحمى الصفراء، غير محددة", "I"),
    ("A98.4", "Ebola virus disease", "داء فيروس إيبولا", "I"),
    ("B00.9", "Herpesviral infection, unspecified", "عدوى الحلأ (الهربس)، غير محددة", "I"),
    ("B01.9", "Varicella without complication", "جدري الماء دون مضاعفات", "I"),
    ("B02.9", "Zoster without complication", "الحزام الناري دون مضاعفات", "I"),
    ("B05.9", "Measles without complication", "الحصبة دون مضاعفات", "I"),
    ("B06.9", "Rubella without complication", "الحصبة الألمانية دون مضاعفات", "I"),
    ("B08.1", "Molluscum contagiosum", "المليساء المعدية", "I"),
    ("B15.9", "Hepatitis A without hepatic coma", "التهاب الكبد أ دون غيبوبة كبدية", "I"),
    (
        "B16.9",
        "Acute hepatitis B without delta-agent and without hepatic coma",
        "التهاب الكبد ب الحاد دون عامل دلتا ودون غيبوبة كبدية",
        "I",
    ),
    ("B17.1", "Acute hepatitis C", "التهاب الكبد ج الحاد", "I"),
    (
        "B18.1",
        "Chronic viral hepatitis B without delta-agent",
        "التهاب الكبد الفيروسي ب المزمن دون عامل دلتا",
        "I",
    ),
    ("B18.2", "Chronic viral hepatitis C", "التهاب الكبد الفيروسي ج المزمن", "I"),
    (
        "B19.9",
        "Unspecified viral hepatitis without hepatic coma",
        "التهاب الكبد الفيروسي غير المحدد دون غيبوبة كبدية",
        "I",
    ),
    (
        "B24",
        "Unspecified human immunodeficiency virus [HIV] disease",
        "مرض فيروس العوز المناعي البشري (الإيدز)، غير محدد",
        "I",
    ),
    ("B26.9", "Mumps without complication", "النكاف دون مضاعفات", "I"),
    ("B27.9", "Infectious mononucleosis, unspecified", "كثرة الوحيدات العدوائية، غير محددة", "I"),
    ("B30.9", "Viral conjunctivitis, unspecified", "التهاب الملتحمة الفيروسي، غير محدد", "I"),
    ("B34.9", "Viral infection, unspecified", "عدوى فيروسية، غير محددة", "I"),
    ("B35.0", "Tinea barbae and tinea capitis", "سعفة اللحية وسعفة الرأس", "I"),
    ("B35.3", "Tinea pedis", "سعفة القدم", "I"),
    ("B35.4", "Tinea corporis", "سعفة الجسد", "I"),
    ("B35.6", "Tinea cruris", "سعفة الفخذ", "I"),
    ("B36.0", "Pityriasis versicolor", "النخالية المبرقشة", "I"),
    ("B37.0", "Candidal stomatitis", "التهاب الفم المبيضي (السلاق)", "I"),
    ("B37.3", "Candidiasis of vulva and vagina", "داء المبيضات الفرجي المهبلي", "I"),
    ("B37.9", "Candidiasis, unspecified", "داء المبيضات، غير محدد", "I"),
    (
        "B50.0",
        "Plasmodium falciparum malaria with cerebral complications",
        "ملاريا المتصورة المنجلية مع مضاعفات دماغية",
        "I",
    ),
    (
        "B50.9",
        "Plasmodium falciparum malaria, unspecified",
        "ملاريا المتصورة المنجلية، غير محددة",
        "I",
    ),
    (
        "B51.9",
        "Plasmodium vivax malaria without complication",
        "ملاريا المتصورة النشيطة دون مضاعفات",
        "I",
    ),
    ("B54", "Unspecified malaria", "الملاريا، غير محددة", "I"),
    ("B55.0", "Visceral leishmaniasis", "داء الليشمانيات الحشوي (الكلازار)", "I"),
    ("B55.1", "Cutaneous leishmaniasis", "داء الليشمانيات الجلدي", "I"),
    ("B56.9", "African trypanosomiasis, unspecified", "داء المثقبيات الأفريقي (مرض النوم)", "I"),
    (
        "B65.0",
        "Schistosomiasis due to Schistosoma haematobium [urinary schistosomiasis]",
        "البلهارسيا البولية",
        "I",
    ),
    (
        "B65.1",
        "Schistosomiasis due to Schistosoma mansoni [intestinal schistosomiasis]",
        "البلهارسيا المعوية",
        "I",
    ),
    ("B65.9", "Schistosomiasis, unspecified", "البلهارسيا، غير محددة", "I"),
    (
        "B67.9",
        "Echinococcosis, other and unspecified",
        "داء المشوكات (الأكياس المائية)، غير محدد",
        "I",
    ),
    ("B68.9", "Taeniasis, unspecified", "داء الشريطيات، غير محدد", "I"),
    ("B74.0", "Filariasis due to Wuchereria bancrofti", "داء الفيلاريات البنكروفتية", "I"),
    ("B76.9", "Hookworm disease, unspecified", "داء الديدان الشصية، غير محدد", "I"),
    ("B77.9", "Ascariasis, unspecified", "داء الصفر (الأسكارس)، غير محدد", "I"),
    ("B80", "Enterobiasis", "داء الدودة الدبوسية", "I"),
    ("B82.9", "Intestinal parasitism, unspecified", "طفيليات معوية، غير محددة", "I"),
    ("B85.0", "Pediculosis due to Pediculus humanus capitis", "قمل الرأس", "I"),
    ("B86", "Scabies", "الجرب", "I"),
    ("B99", "Other and unspecified infectious diseases", "أمراض معدية أخرى وغير محددة", "I"),
    # II. Neoplasms (C00-D48)
    ("C15.9", "Malignant neoplasm of oesophagus, unspecified", "ورم خبيث في المريء", "II"),
    ("C16.9", "Malignant neoplasm of stomach, unspecified", "ورم خبيث في المعدة", "II"),
    ("C18.9", "Malignant neoplasm of colon, unspecified", "ورم خبيث في القولون", "II"),
    ("C22.0", "Liver cell carcinoma", "سرطانة الخلايا الكبدية", "II"),
    (
        "C34.9",
        "Malignant neoplasm of bronchus or lung, unspecified",
        "ورم خبيث في القصبة أو الرئة",
        "II",
    ),
    ("C50.9", "Malignant neoplasm of breast, unspecified", "ورم خبيث في الثدي", "II"),
    ("C53.9", "Malignant neoplasm of cervix uteri, unspecified", "ورم خبيث في عنق الرحم", "II"),
    ("C61", "Malignant neoplasm of prostate", "ورم خبيث في البروستاتا", "II"),
    ("C85.9", "Non-Hodgkin lymphoma, unspecified type", "لمفومة لاهودجكينية، غير محددة", "II"),
    ("C91.0", "Acute lymphoblastic leukaemia", "ابيضاض الدم الليمفاوي الحاد", "II"),
    ("C92.0", "Acute myeloblastic leukaemia", "ابيضاض الدم النقوي الحاد", "II"),
    ("D17.9", "Benign lipomatous neoplasm, unspecified", "ورم شحمي حميد", "II"),
    ("D24", "Benign neoplasm of breast", "ورم حميد في الثدي", "II"),
    ("D25.9", "Leiomyoma of uterus, unspecified", "الورم العضلي الأملس الرحمي (الليفي)", "II"),
    ("D36.9", "Benign neoplasm of unspecified site", "ورم حميد في موضع غير محدد", "II"),
    # III. Blood and immune mechanism (D50-D89)
    ("D50.9", "Iron deficiency anaemia, unspecified", "فقر الدم بعوز الحديد، غير محدد", "III"),
    (
        "D51.9",
        "Vitamin B12 deficiency anaemia, unspecified",
        "فقر الدم بعوز فيتامين ب12، غير محدد",
        "III",
    ),
    ("D52.9", "Folate deficiency anaemia, unspecified", "فقر الدم بعوز الفولات، غير محدد", "III"),
    ("D56.9", "Thalassaemia, unspecified", "الثلاسيميا، غير محددة", "III"),
    ("D57.0", "Sickle-cell anaemia with crisis", "فقر الدم المنجلي مع نوبة", "III"),
    ("D57.1", "Sickle-cell anaemia without crisis", "فقر الدم المنجلي دون نوبة", "III"),
    ("D64.9", "Anaemia, unspecified", "فقر الدم، غير محدد", "III"),
    ("D69.6", "Thrombocytopenia, unspecified", "نقص الصفيحات، غير محدد", "III"),
    ("D70", "Agranulocytosis", "ندرة المحببات", "III"),
    ("D75.1", "Secondary polycythaemia", "كثرة الحمر الثانوية", "III"),
    # IV. Endocrine, nutritional and metabolic (E00-E90)
    ("E03.9", "Hypothyroidism, unspecified", "قصور الغدة الدرقية، غير محدد", "IV"),
    ("E04.9", "Nontoxic goitre, unspecified", "تضخم الدرقية غير السمي، غير محدد", "IV"),
    ("E05.9", "Thyrotoxicosis, unspecified", "الانسمام الدرقي (فرط الدرقية)، غير محدد", "IV"),
    (
        "E10.1",
        "Insulin-dependent diabetes mellitus with ketoacidosis",
        "داء السكري المعتمد على الإنسولين مع حماض كيتوني",
        "IV",
    ),
    (
        "E10.9",
        "Insulin-dependent diabetes mellitus without complications",
        "داء السكري المعتمد على الإنسولين (النوع الأول) دون مضاعفات",
        "IV",
    ),
    (
        "E11.2",
        "Non-insulin-dependent diabetes mellitus with renal complications",
        "داء السكري غير المعتمد على الإنسولين مع مضاعفات كلوية",
        "IV",
    ),
    (
        "E11.3",
        "Non-insulin-dependent diabetes mellitus with ophthalmic complications",
        "داء السكري غير المعتمد على الإنسولين مع مضاعفات عينية",
        "IV",
    ),
    (
        "E11.4",
        "Non-insulin-dependent diabetes mellitus with neurological complications",
        "داء السكري غير المعتمد على الإنسولين مع مضاعفات عصبية",
        "IV",
    ),
    (
        "E11.5",
        "Non-insulin-dependent diabetes mellitus with peripheral circulatory complications",
        "داء السكري غير المعتمد على الإنسولين مع مضاعفات دورانية طرفية (القدم السكرية)",
        "IV",
    ),
    (
        "E11.9",
        "Non-insulin-dependent diabetes mellitus without complications",
        "داء السكري غير المعتمد على الإنسولين (النوع الثاني) دون مضاعفات",
        "IV",
    ),
    (
        "E14.9",
        "Unspecified diabetes mellitus without complications",
        "داء السكري غير المحدد دون مضاعفات",
        "IV",
    ),
    ("E16.2", "Hypoglycaemia, unspecified", "نقص سكر الدم، غير محدد", "IV"),
    ("E28.2", "Polycystic ovarian syndrome", "متلازمة تكيس المبايض", "IV"),
    ("E40", "Kwashiorkor", "الكواشيوركور", "IV"),
    ("E41", "Nutritional marasmus", "السغل (الهزال) الغذائي", "IV"),
    (
        "E43",
        "Unspecified severe protein-energy malnutrition",
        "سوء التغذية البروتيني الطاقي الشديد",
        "IV",
    ),
    (
        "E44.0",
        "Moderate protein-energy malnutrition",
        "سوء التغذية البروتيني الطاقي المعتدل",
        "IV",
    ),
    (
        "E46",
        "Unspecified protein-energy malnutrition",
        "سوء التغذية البروتيني الطاقي، غير محدد",
        "IV",
    ),
    ("E55.9", "Vitamin D deficiency, unspecified", "عوز فيتامين د، غير محدد", "IV"),
    ("E61.1", "Iron deficiency", "عوز الحديد", "IV"),
    ("E66.9", "Obesity, unspecified", "السمنة، غير محددة", "IV"),
    ("E78.0", "Pure hypercholesterolaemia", "فرط كوليستيرول الدم الصرف", "IV"),
    ("E78.5", "Hyperlipidaemia, unspecified", "فرط شحميات الدم، غير محدد", "IV"),
    (
        "E79.0",
        "Hyperuricaemia without signs of inflammatory arthritis and tophaceous disease",
        "فرط حمض اليوريك في الدم دون التهاب مفاصل",
        "IV",
    ),
    ("E83.5", "Disorders of calcium metabolism", "اضطرابات استقلاب الكالسيوم", "IV"),
    ("E86", "Volume depletion", "نقص الحجم (التجفاف)", "IV"),
    ("E87.1", "Hypo-osmolality and hyponatraemia", "نقص الأسمولية ونقص صوديوم الدم", "IV"),
    ("E87.6", "Hypokalaemia", "نقص بوتاسيوم الدم", "IV"),
    # V. Mental and behavioural disorders (F00-F99)
    ("F03", "Unspecified dementia", "الخرف، غير محدد", "V"),
    (
        "F10.2",
        "Mental and behavioural disorders due to use of alcohol: dependence syndrome",
        "اضطرابات ناجمة عن الكحول: متلازمة الاعتماد",
        "V",
    ),
    (
        "F17.2",
        "Mental and behavioural disorders due to use of tobacco: dependence syndrome",
        "اضطرابات ناجمة عن التبغ: متلازمة الاعتماد",
        "V",
    ),
    ("F20.9", "Schizophrenia, unspecified", "الفصام، غير محدد", "V"),
    ("F31.9", "Bipolar affective disorder, unspecified", "الاضطراب الوجداني ثنائي القطب", "V"),
    ("F32.9", "Depressive episode, unspecified", "نوبة اكتئابية، غير محددة", "V"),
    ("F41.1", "Generalized anxiety disorder", "اضطراب القلق المعمم", "V"),
    ("F41.9", "Anxiety disorder, unspecified", "اضطراب القلق، غير محدد", "V"),
    ("F43.1", "Post-traumatic stress disorder", "اضطراب الكرب التالي للصدمة", "V"),
    ("F45.9", "Somatoform disorder, unspecified", "اضطراب جسدي الشكل، غير محدد", "V"),
    ("F51.0", "Nonorganic insomnia", "الأرق غير العضوي", "V"),
    ("F84.0", "Childhood autism", "التوحد الطفولي", "V"),
    ("F90.0", "Disturbance of activity and attention", "اضطراب النشاط والانتباه", "V"),
    # VI. Nervous system (G00-G99)
    ("G00.9", "Bacterial meningitis, unspecified", "التهاب السحايا الجرثومي، غير محدد", "VI"),
    ("G03.9", "Meningitis, unspecified", "التهاب السحايا، غير محدد", "VI"),
    (
        "G04.9",
        "Encephalitis, myelitis and encephalomyelitis, unspecified",
        "التهاب الدماغ والنخاع، غير محدد",
        "VI",
    ),
    ("G20", "Parkinson disease", "داء باركنسون", "VI"),
    ("G30.9", "Alzheimer disease, unspecified", "داء ألزهايمر، غير محدد", "VI"),
    ("G35", "Multiple sclerosis", "التصلب المتعدد", "VI"),
    ("G40.9", "Epilepsy, unspecified", "الصرع، غير محدد", "VI"),
    ("G41.9", "Status epilepticus, unspecified", "الحالة الصرعية، غير محددة", "VI"),
    ("G43.9", "Migraine, unspecified", "الشقيقة (الصداع النصفي)، غير محددة", "VI"),
    ("G44.2", "Tension-type headache", "صداع التوتر", "VI"),
    (
        "G45.9",
        "Transient cerebral ischaemic attack, unspecified",
        "نوبة إقفار دماغي عابرة، غير محددة",
        "VI",
    ),
    ("G51.0", "Bell palsy", "شلل بل (شلل العصب الوجهي)", "VI"),
    ("G56.0", "Carpal tunnel syndrome", "متلازمة النفق الرسغي", "VI"),
    ("G62.9", "Polyneuropathy, unspecified", "اعتلال الأعصاب المتعدد، غير محدد", "VI"),
    ("G80.9", "Cerebral palsy, unspecified", "الشلل الدماغي، غير محدد", "VI"),
    # VII. Eye and adnexa (H00-H59)
    (
        "H00.0",
        "Hordeolum and other deep inflammation of eyelid",
        "الشحاذ (دمل الجفن) والتهاب الجفن العميق",
        "VII",
    ),
    ("H01.0", "Blepharitis", "التهاب حافة الجفن", "VII"),
    ("H10.1", "Acute atopic conjunctivitis", "التهاب الملتحمة التأتبي الحاد (التحسسي)", "VII"),
    ("H10.9", "Conjunctivitis, unspecified", "التهاب الملتحمة، غير محدد", "VII"),
    ("H11.0", "Pterygium", "الظفرة", "VII"),
    ("H16.9", "Keratitis, unspecified", "التهاب القرنية، غير محدد", "VII"),
    ("H25.9", "Senile cataract, unspecified", "الساد الشيخوخي (المياه البيضاء)", "VII"),
    ("H26.9", "Cataract, unspecified", "الساد (المياه البيضاء)، غير محدد", "VII"),
    ("H36.0", "Diabetic retinopathy", "اعتلال الشبكية السكري", "VII"),
    ("H40.9", "Glaucoma, unspecified", "الزرق (المياه الزرقاء)، غير محدد", "VII"),
    ("H52.1", "Myopia", "قصر النظر", "VII"),
    ("H52.4", "Presbyopia", "طول النظر الشيخوخي", "VII"),
    ("H57.1", "Ocular pain", "ألم العين", "VII"),
    # VIII. Ear and mastoid process (H60-H95)
    ("H60.9", "Otitis externa, unspecified", "التهاب الأذن الخارجية، غير محدد", "VIII"),
    ("H61.2", "Impacted cerumen", "انحشار الصملاخ (شمع الأذن)", "VIII"),
    (
        "H65.9",
        "Nonsuppurative otitis media, unspecified",
        "التهاب الأذن الوسطى غير القيحي، غير محدد",
        "VIII",
    ),
    ("H66.0", "Acute suppurative otitis media", "التهاب الأذن الوسطى القيحي الحاد", "VIII"),
    ("H66.9", "Otitis media, unspecified", "التهاب الأذن الوسطى، غير محدد", "VIII"),
    ("H81.1", "Benign paroxysmal vertigo", "الدوار الانتيابي الحميد", "VIII"),
    ("H91.9", "Hearing loss, unspecified", "فقدان السمع، غير محدد", "VIII"),
    ("H92.0", "Otalgia", "ألم الأذن", "VIII"),
    # IX. Circulatory system (I00-I99)
    (
        "I00",
        "Rheumatic fever without mention of heart involvement",
        "الحمى الرثوية دون إصابة القلب",
        "IX",
    ),
    ("I05.0", "Mitral stenosis", "تضيق الصمام التاجي", "IX"),
    ("I09.9", "Rheumatic heart disease, unspecified", "داء القلب الرثوي، غير محدد", "IX"),
    ("I10", "Essential (primary) hypertension", "ارتفاع ضغط الدم الأساسي", "IX"),
    (
        "I11.9",
        "Hypertensive heart disease without (congestive) heart failure",
        "داء القلب الناتج عن ارتفاع الضغط دون قصور قلب",
        "IX",
    ),
    (
        "I12.9",
        "Hypertensive renal disease without renal failure",
        "داء الكلى الناتج عن ارتفاع الضغط دون قصور كلوي",
        "IX",
    ),
    ("I20.9", "Angina pectoris, unspecified", "الذبحة الصدرية، غير محددة", "IX"),
    ("I21.9", "Acute myocardial infarction, unspecified", "احتشاء عضلة القلب الحاد", "IX"),
    ("I25.1", "Atherosclerotic heart disease", "داء القلب التصلبي العصيدي", "IX"),
    (
        "I26.9",
        "Pulmonary embolism without mention of acute cor pulmonale",
        "الانصمام الرئوي دون قلب رئوي حاد",
        "IX",
    ),
    ("I42.9", "Cardiomyopathy, unspecified", "اعتلال عضلة القلب، غير محدد", "IX"),
    (
        "I48.9",
        "Atrial fibrillation and atrial flutter, unspecified",
        "الرجفان والرفرفة الأذينية، غير محددين",
        "IX",
    ),
    ("I49.9", "Cardiac arrhythmia, unspecified", "اضطراب نظم القلب، غير محدد", "IX"),
    ("I50.0", "Congestive heart failure", "قصور القلب الاحتقاني", "IX"),
    ("I50.9", "Heart failure, unspecified", "قصور القلب، غير محدد", "IX"),
    ("I61.9", "Intracerebral haemorrhage, unspecified", "نزف داخل المخ، غير محدد", "IX"),
    ("I63.9", "Cerebral infarction, unspecified", "احتشاء دماغي، غير محدد", "IX"),
    (
        "I64",
        "Stroke, not specified as haemorrhage or infarction",
        "سكتة دماغية غير محددة بنزف أو احتشاء",
        "IX",
    ),
    (
        "I70.2",
        "Atherosclerosis of arteries of extremities",
        "التصلب العصيدي لشرايين الأطراف",
        "IX",
    ),
    (
        "I80.2",
        "Phlebitis and thrombophlebitis of other deep vessels of lower extremities",
        "الخثار الوريدي العميق في الطرف السفلي",
        "IX",
    ),
    (
        "I83.9",
        "Varicose veins of lower extremities without ulcer or inflammation",
        "دوالي الطرفين السفليين دون قرحة أو التهاب",
        "IX",
    ),
    ("I95.9", "Hypotension, unspecified", "انخفاض ضغط الدم، غير محدد", "IX"),
    # X. Respiratory system (J00-J99)
    ("J00", "Acute nasopharyngitis [common cold]", "التهاب البلعوم الأنفي الحاد (الزكام)", "X"),
    ("J01.9", "Acute sinusitis, unspecified", "التهاب الجيوب الأنفية الحاد، غير محدد", "X"),
    ("J02.0", "Streptococcal pharyngitis", "التهاب البلعوم بالعقديات", "X"),
    ("J02.9", "Acute pharyngitis, unspecified", "التهاب البلعوم الحاد، غير محدد", "X"),
    ("J03.9", "Acute tonsillitis, unspecified", "التهاب اللوزتين الحاد، غير محدد", "X"),
    ("J04.0", "Acute laryngitis", "التهاب الحنجرة الحاد", "X"),
    ("J05.0", "Acute obstructive laryngitis [croup]", "التهاب الحنجرة الانسدادي الحاد (الخانوق)", "X"),
    (
        "J06.9",
        "Acute upper respiratory infection, unspecified",
        "عدوى حادة في الجهاز التنفسي العلوي، غير محددة",
        "X",
    ),
    (
        "J11.1",
        "Influenza with other respiratory manifestations, virus not identified",
        "الإنفلونزا مع مظاهر تنفسية، فيروس غير محدد",
        "X",
    ),
    ("J12.9", "Viral pneumonia, unspecified", "الالتهاب الرئوي الفيروسي، غير محدد", "X"),
    ("J15.9", "Bacterial pneumonia, unspecified", "الالتهاب الرئوي الجرثومي، غير محدد", "X"),
    ("J18.0", "Bronchopneumonia, unspecified", "الالتهاب القصبي الرئوي، غير محدد", "X"),
    ("J18.9", "Pneumonia, unspecified", "الالتهاب الرئوي، غير محدد", "X"),
    ("J20.9", "Acute bronchitis, unspecified", "التهاب القصبات الحاد، غير محدد", "X"),
    ("J21.9", "Acute bronchiolitis, unspecified", "التهاب القصيبات الحاد، غير محدد", "X"),
    (
        "J22",
        "Unspecified acute lower respiratory infection",
        "عدوى حادة في الجهاز التنفسي السفلي، غير محددة",
        "X",
    ),
    ("J30.4", "Allergic rhinitis, unspecified", "التهاب الأنف التحسسي، غير محدد", "X"),
    ("J31.0", "Chronic rhinitis", "التهاب الأنف المزمن", "X"),
    ("J32.9", "Chronic sinusitis, unspecified", "التهاب الجيوب الأنفية المزمن، غير محدد", "X"),
    ("J34.2", "Deviated nasal septum", "انحراف الحاجز الأنفي", "X"),
    ("J35.0", "Chronic tonsillitis", "التهاب اللوزتين المزمن", "X"),
    ("J35.2", "Hypertrophy of adenoids", "تضخم اللحمية (الزوائد الأنفية)", "X"),
    ("J42", "Unspecified chronic bronchitis", "التهاب القصبات المزمن، غير محدد", "X"),
    (
        "J44.9",
        "Chronic obstructive pulmonary disease, unspecified",
        "الداء الرئوي الانسدادي المزمن، غير محدد",
        "X",
    ),
    ("J45.9", "Asthma, unspecified", "الربو، غير محدد", "X"),
    ("J46", "Status asthmaticus", "الحالة الربوية", "X"),
    ("J47", "Bronchiectasis", "توسع القصبات", "X"),
    ("J81", "Pulmonary oedema", "وذمة الرئة", "X"),
    ("J90", "Pleural effusion, not elsewhere classified", "الانصباب الجنبي", "X"),
    ("J93.9", "Pneumothorax, unspecified", "استرواح الصدر، غير محدد", "X"),
    ("J96.0", "Acute respiratory failure", "القصور التنفسي الحاد", "X"),
    # XI. Digestive system (K00-K93)
    ("K02.9", "Dental caries, unspecified", "تسوس الأسنان، غير محدد", "XI"),
    ("K04.7", "Periapical abscess without sinus", "خراج ذروي دون ناسور (خراج السن)", "XI"),
    ("K05.1", "Chronic gingivitis", "التهاب اللثة المزمن", "XI"),
    (
        "K08.8",
        "Other specified disorders of teeth and supporting structures",
        "اضطرابات أخرى محددة في الأسنان وما يدعمها (ألم الأسنان)",
        "XI",
    ),
    ("K12.0", "Recurrent oral aphthae", "القلاع الفموي المتكرر", "XI"),
    (
        "K21.9",
        "Gastro-oesophageal reflux disease without oesophagitis",
        "داء الجزر المعدي المريئي دون التهاب المريء",
        "XI",
    ),
    (
        "K25.9",
        "Gastric ulcer, unspecified as acute or chronic, without haemorrhage or perforation",
        "قرحة المعدة دون نزف أو انثقاب",
        "XI",
    ),
    (
        "K26.9",
        "Duodenal ulcer, unspecified as acute or chronic, without haemorrhage or perforation",
        "قرحة الاثني عشر دون نزف أو انثقاب",
        "XI",
    ),
    (
        "K27.9",
        "Peptic ulcer, site unspecified, without haemorrhage or perforation",
        "القرحة الهضمية في موضع غير محدد دون نزف أو انثقاب",
        "XI",
    ),
    ("K29.7", "Gastritis, unspecified", "التهاب المعدة، غير محدد", "XI"),
    ("K30", "Functional dyspepsia", "عسر الهضم الوظيفي", "XI"),
    ("K35.8", "Acute appendicitis, other and unspecified", "التهاب الزائدة الدودية الحاد", "XI"),
    ("K37", "Unspecified appendicitis", "التهاب الزائدة الدودية، غير محدد", "XI"),
    (
        "K40.9",
        "Unilateral or unspecified inguinal hernia, without obstruction or gangrene",
        "الفتق الإربي دون انسداد أو غنغرينة",
        "XI",
    ),
    (
        "K42.9",
        "Umbilical hernia without obstruction or gangrene",
        "الفتق السري دون انسداد أو غنغرينة",
        "XI",
    ),
    (
        "K44.9",
        "Diaphragmatic hernia without obstruction or gangrene",
        "فتق الحجاب الحاجز دون انسداد أو غنغرينة",
        "XI",
    ),
    (
        "K52.9",
        "Noninfective gastroenteritis and colitis, unspecified",
        "التهاب المعدة والأمعاء والقولون غير المعدي، غير محدد",
        "XI",
    ),
    (
        "K56.6",
        "Other and unspecified intestinal obstruction",
        "انسداد معوي آخر وغير محدد",
        "XI",
    ),
    (
        "K58.9",
        "Irritable bowel syndrome without diarrhoea",
        "متلازمة القولون المتهيج (العصبي) دون إسهال",
        "XI",
    ),
    ("K59.0", "Constipation", "الإمساك", "XI"),
    ("K60.2", "Anal fissure, unspecified", "الشق الشرجي، غير محدد", "XI"),
    ("K61.0", "Anal abscess", "خراج شرجي", "XI"),
    ("K64.9", "Haemorrhoids, unspecified", "البواسير، غير محددة", "XI"),
    ("K70.3", "Alcoholic cirrhosis of liver", "تشمع الكبد الكحولي", "XI"),
    ("K74.6", "Other and unspecified cirrhosis of liver", "تشمع (تليف) الكبد، غير محدد", "XI"),
    ("K76.0", "Fatty (change of) liver, not elsewhere classified", "الكبد الدهني", "XI"),
    (
        "K80.2",
        "Calculus of gallbladder without cholecystitis",
        "حصوات المرارة دون التهاب المرارة",
        "XI",
    ),
    ("K81.0", "Acute cholecystitis", "التهاب المرارة الحاد", "XI"),
    ("K85.9", "Acute pancreatitis, unspecified", "التهاب البنكرياس الحاد، غير محدد", "XI"),
    ("K92.2", "Gastrointestinal haemorrhage, unspecified", "نزف هضمي، غير محدد", "XI"),
    # XII. Skin and subcutaneous tissue (L00-L99)
    ("L01.0", "Impetigo", "القوباء", "XII"),
    (
        "L02.9",
        "Cutaneous abscess, furuncle and carbuncle, unspecified",
        "خراج جلدي ودمل وجمرة، غير محدد",
        "XII",
    ),
    ("L03.9", "Cellulitis, unspecified", "التهاب النسيج الخلوي، غير محدد", "XII"),
    (
        "L08.9",
        "Local infection of skin and subcutaneous tissue, unspecified",
        "عدوى موضعية في الجلد والنسيج تحت الجلد",
        "XII",
    ),
    ("L20.9", "Atopic dermatitis, unspecified", "التهاب الجلد التأتبي (الأكزيما)", "XII"),
    ("L21.9", "Seborrhoeic dermatitis, unspecified", "التهاب الجلد الدهني، غير محدد", "XII"),
    ("L22", "Diaper [napkin] dermatitis", "التهاب جلد الحفاض", "XII"),
    (
        "L23.9",
        "Allergic contact dermatitis, unspecified cause",
        "التهاب الجلد التماسي التحسسي",
        "XII",
    ),
    (
        "L25.9",
        "Unspecified contact dermatitis, unspecified cause",
        "التهاب الجلد التماسي، غير محدد",
        "XII",
    ),
    ("L30.9", "Dermatitis, unspecified", "التهاب الجلد، غير محدد", "XII"),
    ("L40.0", "Psoriasis vulgaris", "الصدفية الشائعة", "XII"),
    ("L50.9", "Urticaria, unspecified", "الشرى (الأرتيكاريا)، غير محدد", "XII"),
    ("L60.0", "Ingrowing nail", "الظفر الناشب", "XII"),
    ("L70.0", "Acne vulgaris", "حب الشباب", "XII"),
    ("L80", "Vitiligo", "البهاق", "XII"),
    (
        "L89.9",
        "Decubitus ulcer and pressure area, unspecified",
        "قرحة الفراش (قرحة الضغط)، غير محددة",
        "XII",
    ),
    (
        "L98.4",
        "Chronic ulcer of skin, not elsewhere classified",
        "قرحة جلدية مزمنة",
        "XII",
    ),
    # XIII. Musculoskeletal system and connective tissue (M00-M99)
    ("M06.9", "Rheumatoid arthritis, unspecified", "التهاب المفاصل الروماتويدي، غير محدد", "XIII"),
    ("M10.9", "Gout, unspecified", "النقرس، غير محدد", "XIII"),
    ("M13.9", "Arthritis, unspecified", "التهاب المفاصل، غير محدد", "XIII"),
    ("M16.9", "Coxarthrosis, unspecified", "الفصال العظمي في الورك (خشونة الورك)", "XIII"),
    ("M17.9", "Gonarthrosis, unspecified", "الفصال العظمي في الركبة (خشونة الركبة)", "XIII"),
    ("M19.9", "Arthrosis, unspecified", "الفصال العظمي، غير محدد", "XIII"),
    ("M25.5", "Pain in joint", "ألم المفصل", "XIII"),
    (
        "M32.9",
        "Systemic lupus erythematosus, unspecified",
        "الذئبة الحمامية الجهازية، غير محددة",
        "XIII",
    ),
    ("M45", "Ankylosing spondylitis", "التهاب الفقار اللاصق", "XIII"),
    ("M47.9", "Spondylosis, unspecified", "داء الفقار (خشونة الفقرات)، غير محدد", "XIII"),
    (
        "M51.2",
        "Other specified intervertebral disc displacement",
        "انزياح القرص بين الفقرات (الانزلاق الغضروفي)",
        "XIII",
    ),
    ("M54.2", "Cervicalgia", "ألم الرقبة", "XIII"),
    ("M54.4", "Lumbago with sciatica", "ألم أسفل الظهر مع عرق النسا", "XIII"),
    ("M54.5", "Low back pain", "ألم أسفل الظهر", "XIII"),
    ("M54.9", "Dorsalgia, unspecified", "ألم الظهر، غير محدد", "XIII"),
    ("M62.6", "Muscle strain", "إجهاد عضلي", "XIII"),
    ("M75.0", "Adhesive capsulitis of shoulder", "التهاب محفظة الكتف اللاصق (الكتف المتجمد)", "XIII"),
    ("M77.1", "Lateral epicondylitis", "التهاب اللقيمة الوحشية (مرفق التنس)", "XIII"),
    ("M79.1", "Myalgia", "ألم عضلي", "XIII"),
    ("M79.6", "Pain in limb", "ألم في الطرف", "XIII"),
    ("M81.9", "Osteoporosis, unspecified", "تخلخل (هشاشة) العظام، غير محدد", "XIII"),
    ("M86.9", "Osteomyelitis, unspecified", "التهاب العظم والنقي، غير محدد", "XIII"),
    # XIV. Genitourinary system (N00-N99)
    (
        "N03.9",
        "Chronic nephritic syndrome, unspecified",
        "المتلازمة الالتهابية الكلوية المزمنة، غير محددة",
        "XIV",
    ),
    ("N04.9", "Nephrotic syndrome, unspecified", "المتلازمة الكلائية، غير محددة", "XIV"),
    (
        "N10",
        "Acute tubulo-interstitial nephritis",
        "التهاب الكلية الخلالي الأنبوبي الحاد (التهاب الحويضة والكلية)",
        "XIV",
    ),
    ("N17.9", "Acute renal failure, unspecified", "القصور الكلوي الحاد، غير محدد", "XIV"),
    ("N18.5", "Chronic kidney disease, stage 5", "مرض الكلى المزمن، المرحلة الخامسة", "XIV"),
    ("N18.9", "Chronic kidney disease, unspecified", "مرض الكلى المزمن، غير محدد", "XIV"),
    ("N20.0", "Calculus of kidney", "حصوات الكلى", "XIV"),
    ("N20.1", "Calculus of ureter", "حصوات الحالب", "XIV"),
    ("N23", "Unspecified renal colic", "المغص الكلوي، غير محدد", "XIV"),
    ("N30.0", "Acute cystitis", "التهاب المثانة الحاد", "XIV"),
    ("N34.1", "Nonspecific urethritis", "التهاب الإحليل غير النوعي", "XIV"),
    (
        "N39.0",
        "Urinary tract infection, site not specified",
        "عدوى المسالك البولية، الموضع غير محدد",
        "XIV",
    ),
    ("N40", "Hyperplasia of prostate", "تضخم البروستاتا", "XIV"),
    ("N41.0", "Acute prostatitis", "التهاب البروستاتا الحاد", "XIV"),
    ("N43.3", "Hydrocele, unspecified", "القيلة المائية، غير محددة", "XIV"),
    (
        "N45.9",
        "Orchitis, epididymitis and epididymo-orchitis without abscess",
        "التهاب الخصية والبربخ دون خراج",
        "XIV",
    ),
    ("N46", "Male infertility", "العقم عند الذكور", "XIV"),
    ("N63", "Unspecified lump in breast", "كتلة في الثدي، غير محددة", "XIV"),
    ("N70.9", "Salpingitis and oophoritis, unspecified", "التهاب البوق والمبيض، غير محدد", "XIV"),
    (
        "N73.9",
        "Female pelvic inflammatory disease, unspecified",
        "الداء الالتهابي الحوضي عند الأنثى، غير محدد",
        "XIV",
    ),
    ("N76.0", "Acute vaginitis", "التهاب المهبل الحاد", "XIV"),
    ("N83.2", "Other and unspecified ovarian cysts", "كيسات المبيض، غير محددة", "XIV"),
    ("N91.2", "Amenorrhoea, unspecified", "انقطاع الطمث، غير محدد", "XIV"),
    (
        "N92.0",
        "Excessive and frequent menstruation with regular cycle",
        "غزارة الطمث وتواتره مع دورة منتظمة",
        "XIV",
    ),
    ("N94.6", "Dysmenorrhoea, unspecified", "عسر الطمث، غير محدد", "XIV"),
    (
        "N95.1",
        "Menopausal and female climacteric states",
        "حالات سن الضهي (انقطاع الطمث)",
        "XIV",
    ),
    ("N97.9", "Female infertility, unspecified", "العقم عند الإناث، غير محدد", "XIV"),
    # XV. Pregnancy, childbirth and the puerperium (O00-O99)
    ("O00.9", "Ectopic pregnancy, unspecified", "الحمل خارج الرحم، غير محدد", "XV"),
    (
        "O03.9",
        "Spontaneous abortion, complete or unspecified, without complication",
        "الإجهاض التلقائي، كامل أو غير محدد، دون مضاعفات",
        "XV",
    ),
    (
        "O06.9",
        "Unspecified abortion, complete or unspecified, without complication",
        "إجهاض غير محدد دون مضاعفات",
        "XV",
    ),
    (
        "O13",
        "Gestational [pregnancy-induced] hypertension without significant proteinuria",
        "ارتفاع ضغط الدم الحملي دون بيلة بروتينية هامة",
        "XV",
    ),
    ("O14.9", "Pre-eclampsia, unspecified", "مقدمات الارتعاج (تسمم الحمل)، غير محددة", "XV"),
    ("O15.9", "Eclampsia, unspecified as to time period", "الارتعاج، غير محدد التوقيت", "XV"),
    ("O20.0", "Threatened abortion", "الإجهاض المنذر (المهدد)", "XV"),
    ("O21.0", "Mild hyperemesis gravidarum", "القيء الحملي المفرط الخفيف", "XV"),
    ("O21.9", "Vomiting of pregnancy, unspecified", "قيء الحمل، غير محدد", "XV"),
    (
        "O23.4",
        "Unspecified infection of urinary tract in pregnancy",
        "عدوى المسالك البولية في الحمل، غير محددة",
        "XV",
    ),
    (
        "O24.4",
        "Diabetes mellitus arising in pregnancy",
        "داء السكري الناشئ في الحمل (سكري الحمل)",
        "XV",
    ),
    ("O26.9", "Pregnancy-related condition, unspecified", "حالة متعلقة بالحمل، غير محددة", "XV"),
    (
        "O36.5",
        "Maternal care for known or suspected poor fetal growth",
        "رعاية الأم لضعف نمو الجنين المعروف أو المشتبه",
        "XV",
    ),
    (
        "O42.9",
        "Premature rupture of membranes, unspecified",
        "تمزق الأغشية الباكر، غير محدد",
        "XV",
    ),
    ("O47.9", "False labour, unspecified", "المخاض الكاذب، غير محدد", "XV"),
    ("O60.0", "Preterm labour without delivery", "مخاض باكر دون ولادة", "XV"),
    ("O72.1", "Other immediate postpartum haemorrhage", "نزف تالٍ للوضع فوري", "XV"),
    ("O80.9", "Single spontaneous delivery, unspecified", "ولادة عفوية مفردة، غير محددة", "XV"),
    ("O82.9", "Delivery by caesarean section, unspecified", "ولادة قيصرية، غير محددة", "XV"),
    (
        "O98.6",
        "Protozoal diseases complicating pregnancy, childbirth and the puerperium",
        "أمراض الأوالي (كالملاريا) المضاعفة للحمل والولادة والنفاس",
        "XV",
    ),
    (
        "O99.0",
        "Anaemia complicating pregnancy, childbirth and the puerperium",
        "فقر الدم المضاعف للحمل والولادة والنفاس",
        "XV",
    ),
    # XVI. Perinatal period (P00-P96)
    ("P05.9", "Slow fetal growth, unspecified", "بطء نمو الجنين، غير محدد", "XVI"),
    ("P07.3", "Other preterm infants", "رضع خدج آخرون", "XVI"),
    ("P21.9", "Birth asphyxia, unspecified", "اختناق الولادة، غير محدد", "XVI"),
    (
        "P22.0",
        "Respiratory distress syndrome of newborn",
        "متلازمة الضائقة التنفسية عند الوليد",
        "XVI",
    ),
    ("P36.9", "Bacterial sepsis of newborn, unspecified", "إنتان الوليد الجرثومي، غير محدد", "XVI"),
    ("P59.9", "Neonatal jaundice, unspecified", "يرقان الوليد، غير محدد", "XVI"),
    # XVII. Congenital malformations (Q00-Q99)
    ("Q21.0", "Ventricular septal defect", "عيب الحاجز بين البطينين", "XVII"),
    ("Q21.1", "Atrial septal defect", "عيب الحاجز بين الأذينين", "XVII"),
    ("Q35.9", "Cleft palate, unspecified", "شق الحنك، غير محدد", "XVII"),
    ("Q53.9", "Undescended testicle, unspecified", "الخصية الهاجرة (غير النازلة)", "XVII"),
    ("Q66.0", "Talipes equinovarus", "القدم الحنفاء", "XVII"),
    ("Q90.9", "Down syndrome, unspecified", "متلازمة داون، غير محددة", "XVII"),
    # XVIII. Symptoms, signs and abnormal findings (R00-R99)
    ("R00.0", "Tachycardia, unspecified", "تسرع القلب، غير محدد", "XVIII"),
    ("R04.0", "Epistaxis", "الرعاف (نزف الأنف)", "XVIII"),
    ("R05", "Cough", "السعال", "XVIII"),
    ("R06.0", "Dyspnoea", "ضيق التنفس", "XVIII"),
    ("R07.4", "Chest pain, unspecified", "ألم الصدر، غير محدد", "XVIII"),
    ("R10.4", "Other and unspecified abdominal pain", "ألم البطن، غير محدد", "XVIII"),
    ("R11", "Nausea and vomiting", "الغثيان والقيء", "XVIII"),
    ("R17", "Unspecified jaundice", "اليرقان، غير محدد", "XVIII"),
    ("R18", "Ascites", "الحبن (الاستسقاء)", "XVIII"),
    ("R21", "Rash and other nonspecific skin eruption", "طفح جلدي غير نوعي", "XVIII"),
    ("R30.0", "Dysuria", "عسر التبول", "XVIII"),
    ("R31", "Unspecified haematuria", "البيلة الدموية، غير محددة", "XVIII"),
    ("R35", "Polyuria", "كثرة التبول", "XVIII"),
    ("R42", "Dizziness and giddiness", "الدوخة والدوار", "XVIII"),
    ("R50.9", "Fever, unspecified", "حمى، غير محددة", "XVIII"),
    ("R51", "Headache", "الصداع", "XVIII"),
    ("R52.9", "Pain, unspecified", "ألم، غير محدد", "XVIII"),
    ("R53", "Malaise and fatigue", "التوعك والتعب", "XVIII"),
    ("R55", "Syncope and collapse", "الإغماء والانهيار", "XVIII"),
    ("R56.0", "Febrile convulsions", "الاختلاجات الحموية", "XVIII"),
    ("R59.9", "Enlarged lymph nodes, unspecified", "تضخم العقد اللمفاوية، غير محدد", "XVIII"),
    ("R60.0", "Localized oedema", "وذمة موضعية", "XVIII"),
    ("R63.4", "Abnormal weight loss", "نقص الوزن غير الطبيعي", "XVIII"),
    ("R73.9", "Hyperglycaemia, unspecified", "فرط سكر الدم، غير محدد", "XVIII"),
    # XIX. Injury, poisoning and other consequences of external causes (S00-T98)
    ("S00.9", "Superficial injury of head, part unspecified", "إصابة سطحية في الرأس", "XIX"),
    ("S01.9", "Open wound of head, part unspecified", "جرح مفتوح في الرأس", "XIX"),
    ("S06.0", "Concussion", "ارتجاج الدماغ", "XIX"),
    ("S09.9", "Unspecified injury of head", "إصابة في الرأس، غير محددة", "XIX"),
    ("S42.0", "Fracture of clavicle", "كسر الترقوة", "XIX"),
    ("S52.5", "Fracture of lower end of radius", "كسر الطرف السفلي للكعبرة", "XIX"),
    ("S52.9", "Fracture of forearm, part unspecified", "كسر الساعد، غير محدد", "XIX"),
    (
        "S61.9",
        "Open wound of wrist and hand, part unspecified",
        "جرح مفتوح في الرسغ واليد",
        "XIX",
    ),
    ("S62.6", "Fracture of other finger", "كسر إصبع آخر", "XIX"),
    ("S72.0", "Fracture of neck of femur", "كسر عنق الفخذ", "XIX"),
    ("S82.9", "Fracture of lower leg, part unspecified", "كسر الساق، غير محدد", "XIX"),
    (
        "S83.6",
        "Sprain and strain of other and unspecified parts of knee",
        "التواء ووثء الركبة",
        "XIX",
    ),
    ("S93.4", "Sprain and strain of ankle", "التواء الكاحل", "XIX"),
    ("T14.0", "Superficial injury of unspecified body region", "إصابة سطحية في منطقة غير محددة", "XIX"),
    ("T14.1", "Open wound of unspecified body region", "جرح مفتوح في منطقة غير محددة", "XIX"),
    ("T14.2", "Fracture of unspecified body region", "كسر في منطقة غير محددة", "XIX"),
    ("T14.9", "Injury, unspecified", "إصابة، غير محددة", "XIX"),
    (
        "T30.0",
        "Burn of unspecified body region, unspecified degree",
        "حرق في منطقة غير محددة، درجة غير محددة",
        "XIX",
    ),
    (
        "T50.9",
        "Poisoning by other and unspecified drugs, medicaments and biological substances",
        "تسمم بأدوية ومواد حيوية أخرى وغير محددة",
        "XIX",
    ),
    (
        "T60.0",
        "Toxic effect of organophosphate and carbamate insecticides",
        "التأثير السمي لمبيدات الحشرات الفوسفورية العضوية والكارباماتية",
        "XIX",
    ),
    ("T63.0", "Toxic effect of snake venom", "التأثير السمي لسم الأفعى (لدغة ثعبان)", "XIX"),
    ("T63.2", "Toxic effect of venom of scorpion", "التأثير السمي لسم العقرب (لدغة عقرب)", "XIX"),
    ("T67.0", "Heatstroke and sunstroke", "ضربة الحر وضربة الشمس", "XIX"),
    ("T78.2", "Anaphylactic shock, unspecified", "صدمة تأقية، غير محددة", "XIX"),
    ("T78.4", "Allergy, unspecified", "أرجية (حساسية)، غير محددة", "XIX"),
    (
        "T88.7",
        "Unspecified adverse effect of drug or medicament",
        "تأثير ضار لدواء، غير محدد",
        "XIX",
    ),
    # XX. External causes of morbidity and mortality (V01-Y98)
    ("W54", "Bitten or struck by dog", "عضة كلب أو صدمة منه", "XX"),
    # XXI. Factors influencing health status and contact with health services (Z00-Z99)
    ("Z00.0", "General medical examination", "فحص طبي عام", "XXI"),
    ("Z00.1", "Routine child health examination", "فحص صحي روتيني للطفل", "XXI"),
    ("Z01.4", "Gynaecological examination (general)(routine)", "فحص نسائي روتيني", "XXI"),
    ("Z02.7", "Issue of medical certificate", "إصدار شهادة طبية", "XXI"),
    (
        "Z09.9",
        "Follow-up examination after unspecified treatment for other conditions",
        "فحص متابعة بعد علاج غير محدد",
        "XXI",
    ),
    (
        "Z23.5",
        "Need for immunization against tetanus alone",
        "الحاجة إلى التحصين ضد الكزاز وحده",
        "XXI",
    ),
    (
        "Z24.6",
        "Need for immunization against viral hepatitis",
        "الحاجة إلى التحصين ضد التهاب الكبد الفيروسي",
        "XXI",
    ),
    (
        "Z30.0",
        "General counselling and advice on contraception",
        "المشورة العامة حول منع الحمل",
        "XXI",
    ),
    ("Z32.1", "Pregnancy confirmed", "حمل مؤكد", "XXI"),
    ("Z34.9", "Supervision of normal pregnancy, unspecified", "متابعة حمل طبيعي", "XXI"),
    ("Z39.2", "Routine postpartum follow-up", "متابعة روتينية بعد الولادة", "XXI"),
    (
        "Z48.0",
        "Attention to surgical dressings and sutures",
        "العناية بالضمادات والغرز الجراحية",
        "XXI",
    ),
    ("Z71.9", "Counselling, unspecified", "مشورة، غير محددة", "XXI"),
    ("Z76.0", "Issue of repeat prescription", "إصدار وصفة متكررة", "XXI"),
    ("Z95.0", "Presence of cardiac pacemaker", "وجود ناظمة قلبية", "XXI"),
]


def seed(apps, schema_editor):
    Icd10Code = apps.get_model("clinical", "Icd10Code")
    existing = set(Icd10Code.objects.values_list("code", flat=True))
    Icd10Code.objects.bulk_create(
        [
            Icd10Code(code=code, title_en=title_en, title_ar=title_ar, chapter=chapter)
            for code, title_en, title_ar, chapter in ICD10
            if code not in existing
        ]
    )


def unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("clinical", "0003_initial"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
