# Generated by Django 5.2.17 on 2026-10-07 20:42

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_seed_icd10'),
        ('orders', '0003_remove_serviceline_line_guard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(choices=[('item', 'Same drug'), ('drug_class', 'Same drug class'), ('substance', 'Named substance')], max_length=20)),
                ('reason', models.TextField()),
                ('overridden_at', models.DateTimeField()),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='clinical.allergy')),
                ('overridden_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergy_overrides', to='orders.serviceline')),
            ],
            options={
                'verbose_name': 'allergy override',
                'ordering': ['service_line', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('match__in', ['item', 'drug_class', 'substance'])), name='clinical_allergyoverride_match_valid'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='clinical_allergyoverride_has_reason'), models.UniqueConstraint(fields=('service_line', 'allergy'), name='clinical_allergyoverride_unique')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allergyoverride',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='16e7e6bf9fd5b76da95a94aba08e23a3d8a320a1', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_fd7b4', table='clinical_allergyoverride', when='BEFORE')),
        ),
    ]
