# Generated by Django 5.2.17 on 2026-10-08 21:11

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


def document_old_cancellations(apps, schema_editor):
    """Referrals cancelled before a reason was required get an explicit placeholder, the
    referrer and their last change time, so the new constraint holds (invariant 4)."""
    Referral = apps.get_model("clinical", "Referral")
    for referral in Referral.objects.filter(status="cancelled", cancelled_at__isnull=True):
        referral.cancel_reason = referral.cancel_reason or "Not recorded (cancelled before 0006)"
        referral.cancelled_by_id = referral.cancelled_by_id or referral.referred_by_id
        referral.cancelled_at = referral.updated_at
        referral.save(update_fields=["cancel_reason", "cancelled_by", "cancelled_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_priceitem_item_guard_pricelistversion_version_guard'),
        ('clinical', '0005_allergy_override'),
        ('core', '0010_merge_wave_a_admin_patients'),
        ('visits', '0003_appointment_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='ordersetitem',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='ordersetitem',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='ordersetitem',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='referral',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='referral',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='referral',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='ordersetitem',
            name='as_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersetitem',
            name='dose_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Base units per dose, when computable.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ordersetitem',
            name='route',
            field=models.CharField(blank=True, help_text='Drugs: e.g. oral, iv.', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersetitemevent',
            name='as_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersetitemevent',
            name='dose_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Base units per dose, when computable.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ordersetitemevent',
            name='route',
            field=models.CharField(blank=True, help_text='Drugs: e.g. oral, iv.', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordersetitem',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_ordersetitemevent" ("as_needed", "dose", "dose_quantity", "duration_days", "frequency_code", "id", "instructions", "order_set_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "route", "service_id", "sort_order") VALUES (NEW."as_needed", NEW."dose", NEW."dose_quantity", NEW."duration_days", NEW."frequency_code", NEW."id", NEW."instructions", NEW."order_set_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."quantity", NEW."route", NEW."service_id", NEW."sort_order"); RETURN NULL;', hash='74139b42a0bbab3b26c63899d54be69a8d795efc', operation='INSERT', pgid='pgtrigger_insert_insert_f67cd', table='clinical_ordersetitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordersetitem',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_ordersetitemevent" ("as_needed", "dose", "dose_quantity", "duration_days", "frequency_code", "id", "instructions", "order_set_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "route", "service_id", "sort_order") VALUES (NEW."as_needed", NEW."dose", NEW."dose_quantity", NEW."duration_days", NEW."frequency_code", NEW."id", NEW."instructions", NEW."order_set_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."quantity", NEW."route", NEW."service_id", NEW."sort_order"); RETURN NULL;', hash='4a7ca5eb6c395ceae344681bd2d3d031f0bf6d58', operation='UPDATE', pgid='pgtrigger_update_update_e3b8a', table='clinical_ordersetitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ordersetitem',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_ordersetitemevent" ("as_needed", "dose", "dose_quantity", "duration_days", "frequency_code", "id", "instructions", "order_set_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity", "route", "service_id", "sort_order") VALUES (OLD."as_needed", OLD."dose", OLD."dose_quantity", OLD."duration_days", OLD."frequency_code", OLD."id", OLD."instructions", OLD."order_set_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."quantity", OLD."route", OLD."service_id", OLD."sort_order"); RETURN NULL;', hash='fda4a955cc12de765056c34a5ddfcafbce284590', operation='DELETE', pgid='pgtrigger_delete_delete_c911c', table='clinical_ordersetitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_referralevent" ("cancel_reason", "cancelled_at", "cancelled_by_id", "clinical_summary", "created_at", "external_facility", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "referred_by_id", "status", "to_department_id", "to_doctor_id", "updated_at", "urgency", "visit_id") VALUES (NEW."cancel_reason", NEW."cancelled_at", NEW."cancelled_by_id", NEW."clinical_summary", NEW."created_at", NEW."external_facility", NEW."id", NEW."kind", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason", NEW."referred_by_id", NEW."status", NEW."to_department_id", NEW."to_doctor_id", NEW."updated_at", NEW."urgency", NEW."visit_id"); RETURN NULL;', hash='8358901f373e7386b37fb12b10b7139c1dc79498', operation='INSERT', pgid='pgtrigger_insert_insert_bde2a', table='clinical_referral', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clinical_referralevent" ("cancel_reason", "cancelled_at", "cancelled_by_id", "clinical_summary", "created_at", "external_facility", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "referred_by_id", "status", "to_department_id", "to_doctor_id", "updated_at", "urgency", "visit_id") VALUES (NEW."cancel_reason", NEW."cancelled_at", NEW."cancelled_by_id", NEW."clinical_summary", NEW."created_at", NEW."external_facility", NEW."id", NEW."kind", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason", NEW."referred_by_id", NEW."status", NEW."to_department_id", NEW."to_doctor_id", NEW."updated_at", NEW."urgency", NEW."visit_id"); RETURN NULL;', hash='9d566313873adfb5c07c40bb70d22fd6d439f81c', operation='UPDATE', pgid='pgtrigger_update_update_49255', table='clinical_referral', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clinical_referralevent" ("cancel_reason", "cancelled_at", "cancelled_by_id", "clinical_summary", "created_at", "external_facility", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "referred_by_id", "status", "to_department_id", "to_doctor_id", "updated_at", "urgency", "visit_id") VALUES (OLD."cancel_reason", OLD."cancelled_at", OLD."cancelled_by_id", OLD."clinical_summary", OLD."created_at", OLD."external_facility", OLD."id", OLD."kind", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reason", OLD."referred_by_id", OLD."status", OLD."to_department_id", OLD."to_doctor_id", OLD."updated_at", OLD."urgency", OLD."visit_id"); RETURN NULL;', hash='7f9ed05e68b956dc93d93d66c7a4dc0e5311c927', operation='DELETE', pgid='pgtrigger_delete_delete_884be', table='clinical_referral', when='AFTER')),
        ),
        migrations.RunPython(document_old_cancellations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ordersetitem',
            constraint=models.CheckConstraint(condition=models.Q(('dose_quantity__isnull', True), ('dose_quantity__gt', 0), _connector='OR'), name='clinical_orderset_dose_positive'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(models.Q(('cancel_reason', ''), _negated=True), ('cancelled_by__isnull', False), ('cancelled_at__isnull', False)), _connector='OR'), name='clinical_referral_cancel_documented'),
        ),
    ]
