# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('value_type', models.CharField(choices=[('numeric', 'Number'), ('text', 'Free text'), ('choice', 'One of a list'), ('pos_neg', 'Positive / negative')], default='numeric', max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, help_text="Allowed values for 'choice'.")),
                ('decimals', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'lab parameter',
                'ordering': ['test', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_approved_at', models.DateTimeField(blank=True, help_text='Turnaround time end (FEATURES 9.8).', null=True)),
            ],
            options={
                'verbose_name': 'result set',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResultSetEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_approved_at', models.DateTimeField(blank=True, help_text='Turnaround time end (FEATURES 9.8).', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_text', models.CharField(blank=True, max_length=500)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reference_text', models.CharField(blank=True, max_length=100)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical_low', 'Critically low'), ('critical_high', 'Critically high'), ('abnormal', 'Abnormal'), ('none', 'No range')], default='none', max_length=20)),
            ],
            options={
                'verbose_name': 'result value',
                'ordering': ['version', 'parameter'],
            },
        ),
        migrations.CreateModel(
            name='ResultValueEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_text', models.CharField(blank=True, max_length=500)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reference_text', models.CharField(blank=True, max_length=100)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical_low', 'Critically low'), ('critical_high', 'Critically high'), ('abnormal', 'Abnormal'), ('none', 'No range')], default='none', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('amended', 'Amended (superseded)')], default='draft', max_length=10)),
                ('amendment_note', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'result version',
                'ordering': ['result_set', 'version_no'],
            },
        ),
        migrations.CreateModel(
            name='ResultVersionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('version_no', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('amended', 'Amended (superseded)')], default='draft', max_length=10)),
                ('amendment_note', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(max_length=30, unique=True)),
                ('sample_type', models.CharField(choices=[('whole_blood', 'Whole blood'), ('serum', 'Serum'), ('plasma', 'Plasma'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('csf', 'Cerebrospinal fluid'), ('fluid', 'Other body fluid'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('received', 'Received in lab'), ('rejected', 'Rejected')], default='collected', max_length=20)),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.CharField(blank=True, max_length=300)),
                ('label_printed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sample',
                'ordering': ['-collected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SampleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('accession_no', models.CharField(max_length=30)),
                ('sample_type', models.CharField(choices=[('whole_blood', 'Whole blood'), ('serum', 'Serum'), ('plasma', 'Plasma'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('csf', 'Cerebrospinal fluid'), ('fluid', 'Other body fluid'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('received', 'Received in lab'), ('rejected', 'Rejected')], default='collected', max_length=20)),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.CharField(blank=True, max_length=300)),
                ('label_printed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('sample_type', models.CharField(choices=[('whole_blood', 'Whole blood'), ('serum', 'Serum'), ('plasma', 'Plasma'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('csf', 'Cerebrospinal fluid'), ('fluid', 'Other body fluid'), ('other', 'Other')], max_length=20)),
                ('container', models.CharField(blank=True, help_text='e.g. EDTA, plain tube.', max_length=60)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('turnaround_minutes', models.PositiveIntegerField(default=60)),
                ('instructions_ar', models.CharField(blank=True, max_length=300)),
                ('instructions_en', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lab_test', to='catalog.service')),
            ],
            options={
                'verbose_name': 'lab test',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LabParameterEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=30)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('value_type', models.CharField(choices=[('numeric', 'Number'), ('text', 'Free text'), ('choice', 'One of a list'), ('pos_neg', 'Positive / negative')], default='numeric', max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, help_text="Allowed values for 'choice'.")),
                ('decimals', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='lab.labparameter')),
                ('test', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lab.labtest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='labparameter',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.labtest'),
        ),
        migrations.CreateModel(
            name='LabTestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=30)),
                ('sample_type', models.CharField(choices=[('whole_blood', 'Whole blood'), ('serum', 'Serum'), ('plasma', 'Plasma'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('csf', 'Cerebrospinal fluid'), ('fluid', 'Other body fluid'), ('other', 'Other')], max_length=20)),
                ('container', models.CharField(blank=True, help_text='e.g. EDTA, plain tube.', max_length=60)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('turnaround_minutes', models.PositiveIntegerField(default=60)),
                ('instructions_ar', models.CharField(blank=True, max_length=300)),
                ('instructions_en', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='lab.labtest')),
                ('service', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('age_min_days', models.PositiveIntegerField(default=0)),
                ('age_max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('critical_high', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('normal_text', models.CharField(blank=True, help_text='Normal value for text/choice parameters.', max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.labparameter')),
            ],
            options={
                'verbose_name': 'reference range',
                'ordering': ['parameter', 'sex', 'age_min_days'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceRangeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('sex', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('age_min_days', models.PositiveIntegerField(default=0)),
                ('age_max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('critical_high', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('normal_text', models.CharField(blank=True, help_text='Normal value for text/choice parameters.', max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('parameter', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lab.labparameter')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='lab.referencerange')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
