# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_reason_categories_consultation_service'),
        ('lab', '0002_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='resultsetevent',
            name='sample',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lab.sample'),
        ),
        migrations.AddField(
            model_name='resultset',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_sets', to='lab.sample'),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='collected_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='lab.sample'),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='received_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'sample_reject'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='sampleevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.CheckConstraint(condition=models.Q(('sample_type__in', ['whole_blood', 'serum', 'plasma', 'urine', 'stool', 'swab', 'sputum', 'csf', 'fluid', 'other'])), name='lab_test_sample_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.CheckConstraint(condition=models.Q(('turnaround_minutes__gte', 1)), name='lab_test_turnaround_positive'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='labtest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_labtestevent" ("active", "code", "container", "id", "instructions_ar", "instructions_en", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sample_type", "service_id", "sort_order", "turnaround_minutes") VALUES (NEW."active", NEW."code", NEW."container", NEW."id", NEW."instructions_ar", NEW."instructions_en", NEW."method", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sample_type", NEW."service_id", NEW."sort_order", NEW."turnaround_minutes"); RETURN NULL;', hash='709f0d866487b5757526d12d99cafe00ef8edc36', operation='INSERT', pgid='pgtrigger_insert_insert_c7d0b', table='lab_labtest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='labtest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lab_labtestevent" ("active", "code", "container", "id", "instructions_ar", "instructions_en", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sample_type", "service_id", "sort_order", "turnaround_minutes") VALUES (NEW."active", NEW."code", NEW."container", NEW."id", NEW."instructions_ar", NEW."instructions_en", NEW."method", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sample_type", NEW."service_id", NEW."sort_order", NEW."turnaround_minutes"); RETURN NULL;', hash='e78cb5a21981ff596277e2de00d93b71c668e46f', operation='UPDATE', pgid='pgtrigger_update_update_5586e', table='lab_labtest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='labtest',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_labtestevent" ("active", "code", "container", "id", "instructions_ar", "instructions_en", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sample_type", "service_id", "sort_order", "turnaround_minutes") VALUES (OLD."active", OLD."code", OLD."container", OLD."id", OLD."instructions_ar", OLD."instructions_en", OLD."method", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sample_type", OLD."service_id", OLD."sort_order", OLD."turnaround_minutes"); RETURN NULL;', hash='ad59866f341ee1478d61f0d601b8cabe39369cab', operation='DELETE', pgid='pgtrigger_delete_delete_2d5a4', table='lab_labtest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='labparameterevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='a144c6e4011700de73d3ec9cd7b6ccf14eb4b7e2', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c26ba', table='lab_labparameterevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='labparameter',
            constraint=models.CheckConstraint(condition=models.Q(('value_type__in', ['numeric', 'text', 'choice', 'pos_neg'])), name='lab_parameter_value_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='labparameter',
            constraint=models.UniqueConstraint(fields=('test', 'code'), name='lab_parameter_unique'),
        ),
        migrations.AddConstraint(
            model_name='labparameter',
            constraint=models.CheckConstraint(condition=models.Q(('decimals__lte', 6)), name='lab_parameter_decimals'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='labparameter',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_labparameterevent" ("active", "choices", "code", "decimals", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "test_id", "unit", "value_type") VALUES (NEW."active", NEW."choices", NEW."code", NEW."decimals", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order", NEW."test_id", NEW."unit", NEW."value_type"); RETURN NULL;', hash='b42188b66962052b505570bf02f0132ff28227f0', operation='INSERT', pgid='pgtrigger_insert_insert_92c2f', table='lab_labparameter', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='labparameter',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lab_labparameterevent" ("active", "choices", "code", "decimals", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "test_id", "unit", "value_type") VALUES (NEW."active", NEW."choices", NEW."code", NEW."decimals", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order", NEW."test_id", NEW."unit", NEW."value_type"); RETURN NULL;', hash='db1c72542b08699d17ee4f8aab88ed9c642d55a6', operation='UPDATE', pgid='pgtrigger_update_update_4705d', table='lab_labparameter', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='labparameter',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_labparameterevent" ("active", "choices", "code", "decimals", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "test_id", "unit", "value_type") VALUES (OLD."active", OLD."choices", OLD."code", OLD."decimals", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order", OLD."test_id", OLD."unit", OLD."value_type"); RETURN NULL;', hash='18cdbcf52d4bee18d7d8f1d20589224b9434c922', operation='DELETE', pgid='pgtrigger_delete_delete_b08ef', table='lab_labparameter', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='labtestevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bfcaaebf76692c35570e69934a01e363e57c75d5', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0e29c', table='lab_labtestevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='referencerange',
            constraint=models.CheckConstraint(condition=models.Q(('sex__in', ['any', 'male', 'female'])), name='lab_range_sex_valid'),
        ),
        migrations.AddConstraint(
            model_name='referencerange',
            constraint=models.CheckConstraint(condition=models.Q(('age_max_days__isnull', True), ('age_max_days__gte', models.F('age_min_days')), _connector='OR'), name='lab_range_age_order'),
        ),
        migrations.AddConstraint(
            model_name='referencerange',
            constraint=models.CheckConstraint(condition=models.Q(('low__isnull', True), ('high__isnull', True), ('high__gte', models.F('low')), _connector='OR'), name='lab_range_low_le_high'),
        ),
        migrations.AddConstraint(
            model_name='referencerange',
            constraint=models.CheckConstraint(condition=models.Q(('critical_low__isnull', True), ('low__isnull', True), ('critical_low__lte', models.F('low')), _connector='OR'), name='lab_range_critical_low_below_low'),
        ),
        migrations.AddConstraint(
            model_name='referencerange',
            constraint=models.CheckConstraint(condition=models.Q(('critical_high__isnull', True), ('high__isnull', True), ('critical_high__gte', models.F('high')), _connector='OR'), name='lab_range_critical_high_above_high'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referencerange',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_referencerangeevent" ("age_max_days", "age_min_days", "critical_high", "critical_low", "high", "id", "low", "normal_text", "note", "parameter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sex") VALUES (NEW."age_max_days", NEW."age_min_days", NEW."critical_high", NEW."critical_low", NEW."high", NEW."id", NEW."low", NEW."normal_text", NEW."note", NEW."parameter_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sex"); RETURN NULL;', hash='a929e996a593738f8ffb50ad4b2f8b4ff69ddedc', operation='INSERT', pgid='pgtrigger_insert_insert_e6edc', table='lab_referencerange', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referencerange',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lab_referencerangeevent" ("age_max_days", "age_min_days", "critical_high", "critical_low", "high", "id", "low", "normal_text", "note", "parameter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sex") VALUES (NEW."age_max_days", NEW."age_min_days", NEW."critical_high", NEW."critical_low", NEW."high", NEW."id", NEW."low", NEW."normal_text", NEW."note", NEW."parameter_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sex"); RETURN NULL;', hash='2df4545f7e602c10d8f32ab5cb91d85a1d90c777', operation='UPDATE', pgid='pgtrigger_update_update_c6f8c', table='lab_referencerange', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referencerange',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_referencerangeevent" ("age_max_days", "age_min_days", "critical_high", "critical_low", "high", "id", "low", "normal_text", "note", "parameter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sex") VALUES (OLD."age_max_days", OLD."age_min_days", OLD."critical_high", OLD."critical_low", OLD."high", OLD."id", OLD."low", OLD."normal_text", OLD."note", OLD."parameter_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sex"); RETURN NULL;', hash='b02d2c986a99570036e1e6629fb451233b5d0b3e', operation='DELETE', pgid='pgtrigger_delete_delete_0c9b6', table='lab_referencerange', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referencerangeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='bd4561e9c5c9d7b721c050153a2d4d17ca30cbad', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_fbee6', table='lab_referencerangeevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='resultversion',
            index=models.Index(fields=['status', 'approved_at'], name='lab_version_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'amended'])), name='lab_version_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='resultversion',
            constraint=models.UniqueConstraint(fields=('result_set', 'version_no'), name='lab_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='resultversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('result_set',), name='lab_version_one_draft'),
        ),
        migrations.AddConstraint(
            model_name='resultversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('result_set',), name='lab_version_one_current'),
        ),
        migrations.AddConstraint(
            model_name='resultversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='lab_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='resultversion',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='lab_version_approval_documented'),
        ),
        migrations.AddConstraint(
            model_name='resultversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'amended'), _negated=True), models.Q(('superseded_at__isnull', False), ('superseded_by__isnull', False)), _connector='OR'), name='lab_version_supersession_documented'),
        ),
        migrations.AddConstraint(
            model_name='resultversion',
            constraint=models.CheckConstraint(condition=models.Q(('amends__isnull', True), ('amendment_reason__isnull', False), _connector='OR'), name='lab_version_amendment_has_reason'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultversion',
            trigger=pgtrigger.compiler.Trigger(name='result_version_guard', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'approved\', \'amended\'))', func="\n    IF OLD.status = 'amended' THEN\n        RAISE EXCEPTION 'RESULT_FROZEN: amended result version % never changes (operation %)',\n            OLD.id, TG_OP;\n    END IF;\n    IF OLD.status = 'approved' THEN\n        IF TG_OP = 'DELETE' THEN\n            RAISE EXCEPTION 'RESULT_FROZEN: approved result version % cannot be deleted', OLD.id;\n        END IF;\n        IF NEW.status <> 'amended'\n           OR NEW.superseded_at IS NULL OR NEW.superseded_by_id IS NULL\n           OR (to_jsonb(NEW) - ARRAY['status', 'superseded_at', 'superseded_by_id'])\n              IS DISTINCT FROM\n              (to_jsonb(OLD) - ARRAY['status', 'superseded_at', 'superseded_by_id']) THEN\n            RAISE EXCEPTION\n                'RESULT_FROZEN: approved result version % can only be marked amended', OLD.id;\n        END IF;\n    END IF;\n    IF TG_OP = 'DELETE' THEN\n        RETURN OLD;\n    END IF;\n    RETURN NEW;\n", hash='ef2eab0b1c82e2919b81605fa05be7541129469e', operation='UPDATE OR DELETE', pgid='pgtrigger_result_version_guard_16a47', table='lab_resultversion', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultversion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_resultversionevent" ("amendment_note", "amendment_reason_id", "amends_id", "approved_at", "approved_by_id", "comment", "entered_at", "entered_by_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "result_set_id", "status", "superseded_at", "superseded_by_id", "version_no") VALUES (NEW."amendment_note", NEW."amendment_reason_id", NEW."amends_id", NEW."approved_at", NEW."approved_by_id", NEW."comment", NEW."entered_at", NEW."entered_by_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."result_set_id", NEW."status", NEW."superseded_at", NEW."superseded_by_id", NEW."version_no"); RETURN NULL;', hash='ad32b5bf60bffc972d578d173ef1efe75306bf61', operation='INSERT', pgid='pgtrigger_insert_insert_1f732', table='lab_resultversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultversion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lab_resultversionevent" ("amendment_note", "amendment_reason_id", "amends_id", "approved_at", "approved_by_id", "comment", "entered_at", "entered_by_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "result_set_id", "status", "superseded_at", "superseded_by_id", "version_no") VALUES (NEW."amendment_note", NEW."amendment_reason_id", NEW."amends_id", NEW."approved_at", NEW."approved_by_id", NEW."comment", NEW."entered_at", NEW."entered_by_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."result_set_id", NEW."status", NEW."superseded_at", NEW."superseded_by_id", NEW."version_no"); RETURN NULL;', hash='dee6f2f6218d58bb913af5cc9e5f1c4989aaba1a', operation='UPDATE', pgid='pgtrigger_update_update_26258', table='lab_resultversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultversion',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_resultversionevent" ("amendment_note", "amendment_reason_id", "amends_id", "approved_at", "approved_by_id", "comment", "entered_at", "entered_by_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "result_set_id", "status", "superseded_at", "superseded_by_id", "version_no") VALUES (OLD."amendment_note", OLD."amendment_reason_id", OLD."amends_id", OLD."approved_at", OLD."approved_by_id", OLD."comment", OLD."entered_at", OLD."entered_by_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."result_set_id", OLD."status", OLD."superseded_at", OLD."superseded_by_id", OLD."version_no"); RETURN NULL;', hash='ee93cfe7cba65e991b2e83e1fd5ee6bd4dfd66c3', operation='DELETE', pgid='pgtrigger_delete_delete_f5625', table='lab_resultversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultvalueevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0a14094d77fa56e531bfaf95c66f27e3e1a5b1c4', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3c03c', table='lab_resultvalueevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='resultvalue',
            constraint=models.CheckConstraint(condition=models.Q(('flag__in', ['normal', 'low', 'high', 'critical_low', 'critical_high', 'abnormal', 'none'])), name='lab_value_flag_valid'),
        ),
        migrations.AddConstraint(
            model_name='resultvalue',
            constraint=models.UniqueConstraint(fields=('version', 'parameter'), name='lab_value_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultvalue',
            trigger=pgtrigger.compiler.Trigger(name='value_needs_draft_version', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM lab_resultversion p WHERE p.id = OLD.version_id AND p.status = 'draft'\n            ) AND EXISTS (SELECT 1 FROM lab_resultversion p WHERE p.id = OLD.version_id) THEN\n                RAISE EXCEPTION 'RESULT_FROZEN: parent % of % row is locked', OLD.version_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM lab_resultversion p WHERE p.id = NEW.version_id AND p.status = 'draft'\n            ) THEN\n                RAISE EXCEPTION 'RESULT_FROZEN: parent % of % row is locked', NEW.version_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='78c77af54cf4ea2289896e1ce9b1ca8f4fa4360a', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_value_needs_draft_version_a5f53', table='lab_resultvalue', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultvalue',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_resultvalueevent" ("flag", "id", "parameter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_high", "reference_low", "reference_text", "unit", "value_numeric", "value_text", "version_id") VALUES (NEW."flag", NEW."id", NEW."parameter_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_high", NEW."reference_low", NEW."reference_text", NEW."unit", NEW."value_numeric", NEW."value_text", NEW."version_id"); RETURN NULL;', hash='f1ac8c34e91a47e0ff2ce480dac85220c3216043', operation='INSERT', pgid='pgtrigger_insert_insert_815f2', table='lab_resultvalue', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultvalue',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lab_resultvalueevent" ("flag", "id", "parameter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_high", "reference_low", "reference_text", "unit", "value_numeric", "value_text", "version_id") VALUES (NEW."flag", NEW."id", NEW."parameter_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_high", NEW."reference_low", NEW."reference_text", NEW."unit", NEW."value_numeric", NEW."value_text", NEW."version_id"); RETURN NULL;', hash='616d7f913f05b3aa066be3f00b86762f974ebbcc', operation='UPDATE', pgid='pgtrigger_update_update_3b807', table='lab_resultvalue', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultvalue',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_resultvalueevent" ("flag", "id", "parameter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_high", "reference_low", "reference_text", "unit", "value_numeric", "value_text", "version_id") VALUES (OLD."flag", OLD."id", OLD."parameter_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reference_high", OLD."reference_low", OLD."reference_text", OLD."unit", OLD."value_numeric", OLD."value_text", OLD."version_id"); RETURN NULL;', hash='5aa26cd45180fef9c75d6aada6e2d4d92185d82b', operation='DELETE', pgid='pgtrigger_delete_delete_8ef69', table='lab_resultvalue', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultversionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0b18e074ebd7d527a38956ffa7b611e43d97de80', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e6f06', table='lab_resultversionevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['visit'], name='lab_sample_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status', 'collected_at'], name='lab_sample_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(('sample_type__in', ['whole_blood', 'serum', 'plasma', 'urine', 'stool', 'swab', 'sputum', 'csf', 'fluid', 'other'])), name='lab_sample_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['collected', 'received', 'rejected'])), name='lab_sample_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'received'), _negated=True), models.Q(('received_at__isnull', False), ('received_by__isnull', False)), _connector='OR'), name='lab_sample_receipt_documented'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), ('rejection_reason__isnull', False), _connector='OR'), name='lab_sample_rejection_has_reason'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sample',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_sampleevent" ("accession_no", "collected_at", "collected_by_id", "id", "label_printed_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "rejection_note", "rejection_reason_id", "sample_type", "status", "visit_id") VALUES (NEW."accession_no", NEW."collected_at", NEW."collected_by_id", NEW."id", NEW."label_printed_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."rejection_note", NEW."rejection_reason_id", NEW."sample_type", NEW."status", NEW."visit_id"); RETURN NULL;', hash='ff8ce0da52dfe6c50d503551fcc2664c0b9b8661', operation='INSERT', pgid='pgtrigger_insert_insert_53d12', table='lab_sample', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sample',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lab_sampleevent" ("accession_no", "collected_at", "collected_by_id", "id", "label_printed_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "rejection_note", "rejection_reason_id", "sample_type", "status", "visit_id") VALUES (NEW."accession_no", NEW."collected_at", NEW."collected_by_id", NEW."id", NEW."label_printed_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."rejection_note", NEW."rejection_reason_id", NEW."sample_type", NEW."status", NEW."visit_id"); RETURN NULL;', hash='93756f262078b65a3b1908047f6c00367914b6f5', operation='UPDATE', pgid='pgtrigger_update_update_ce83c', table='lab_sample', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sample',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_sampleevent" ("accession_no", "collected_at", "collected_by_id", "id", "label_printed_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "rejection_note", "rejection_reason_id", "sample_type", "status", "visit_id") VALUES (OLD."accession_no", OLD."collected_at", OLD."collected_by_id", OLD."id", OLD."label_printed_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."received_at", OLD."received_by_id", OLD."rejection_note", OLD."rejection_reason_id", OLD."sample_type", OLD."status", OLD."visit_id"); RETURN NULL;', hash='a326441bb1f52720be435d6ef9b878ba20dc2049', operation='DELETE', pgid='pgtrigger_delete_delete_67449', table='lab_sample', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultsetevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='291820ba4be288304004739d246e0b2d0723ce15', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_42a06', table='lab_resultsetevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='resultset',
            index=models.Index(fields=['test', 'first_approved_at'], name='lab_resultset_tat_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultset',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_resultsetevent" ("created_at", "first_approved_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sample_id", "service_line_id", "test_id") VALUES (NEW."created_at", NEW."first_approved_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sample_id", NEW."service_line_id", NEW."test_id"); RETURN NULL;', hash='ef1742eb794c3ec2bf6c48964b997a83fa06341e', operation='INSERT', pgid='pgtrigger_insert_insert_a1c14', table='lab_resultset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultset',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lab_resultsetevent" ("created_at", "first_approved_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sample_id", "service_line_id", "test_id") VALUES (NEW."created_at", NEW."first_approved_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sample_id", NEW."service_line_id", NEW."test_id"); RETURN NULL;', hash='6b19c5e500ebe0058366d06d58934ac569035aed', operation='UPDATE', pgid='pgtrigger_update_update_067e6', table='lab_resultset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultset',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lab_resultsetevent" ("created_at", "first_approved_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sample_id", "service_line_id", "test_id") VALUES (OLD."created_at", OLD."first_approved_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sample_id", OLD."service_line_id", OLD."test_id"); RETURN NULL;', hash='1075f7ba815f013df4f5c74bf0aa94982bf6dc07', operation='DELETE', pgid='pgtrigger_delete_delete_b8bb0', table='lab_resultset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sampleevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6867ac2f48fb6382d27391a4b71b21ce8e11bece', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4d039', table='lab_sampleevent', when='BEFORE')),
        ),
    ]
