# Generated by Django 5.2.17 on 2026-10-07 16:57

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_initial'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='resultvalue',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='bc46db56deebe6cfafceb5602b8a886ac930e822', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_61b03', table='lab_resultvalue', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='resultversion',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='9b13a42ba957864d35419398bcf8d7bd216e1202', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_37272', table='lab_resultversion', when='BEFORE')),
        ),
    ]
