# Generated by Django 5.2.17 on 2026-10-07 11:49

import apps.core.db
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0001_initial'),
        ('core', '0006_reason_categories_consultation_service'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reference_norm', models.GeneratedField(db_persist=True, expression=apps.core.db.NormalizeReference(models.F('reference')), output_field=models.TextField())),
                ('received_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payer payment',
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayerPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payer payment allocation',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayerPaymentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('received_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('responded', 'Response recorded'), ('closed', 'Closed'), ('void', 'Void')], default='draft', max_length=20)),
                ('claimed_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('accepted_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rejected_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='catalog.payer')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'claim',
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('responded', 'Response recorded'), ('closed', 'Closed'), ('void', 'Void')], default='draft', max_length=20)),
                ('claimed_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('accepted_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rejected_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.payer')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='claims.claim')),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Awaiting response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially accepted'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('accepted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rejected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payer_reason', models.CharField(blank=True, max_length=300)),
                ('payer_reference', models.CharField(blank=True, max_length=100)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('none', 'Not resolved'), ('rebilled', 'Rebilled to the patient'), ('written_off', 'Written off')], default='none', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='claims.claim')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='billing.invoiceline')),
                ('resolution_reason', models.ForeignKey(blank=True, limit_choices_to={'category': 'writeoff'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'claim line',
                'ordering': ['claim', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Awaiting response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially accepted'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('accepted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rejected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payer_reason', models.CharField(blank=True, max_length=300)),
                ('payer_reference', models.CharField(blank=True, max_length=100)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('none', 'Not resolved'), ('rebilled', 'Rebilled to the patient'), ('written_off', 'Written off')], default='none', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='claims.claim')),
                ('invoice_line', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.invoiceline')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='claims.claimline')),
                ('resolution_reason', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'writeoff'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode')),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
