# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import django.db.models.expressions
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('claims', '0001_initial'),
        ('payments', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payerpayment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer_payments', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='catalog.payer'),
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payerpaymentallocation',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_allocations', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='payerpaymentallocation',
            name='claim_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='claims.claimline'),
        ),
        migrations.AddField(
            model_name='payerpaymentallocation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payerpaymentallocation',
            name='payer_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='claims.payerpayment'),
        ),
        migrations.AddField(
            model_name='payerpaymentallocation',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='claims.payerpaymentallocation'),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='payer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.payer'),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='claims.payerpayment'),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='recorded_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['payer', 'status'], name='claims_claim_payer_idx'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'responded', 'closed', 'void'])), name='claims_claim_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='claims_claim_period_order'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('claimed_total__gte', 0), ('accepted_total__gte', 0), ('rejected_total__gte', 0)), name='claims_claim_totals_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_total__lte', django.db.models.expressions.CombinedExpression(models.F('claimed_total'), '-', models.F('rejected_total')))), name='claims_claim_totals_within_claimed'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'void']), models.Q(('submitted_at__isnull', False), ('submitted_by__isnull', False)), _connector='OR'), name='claims_claim_submission_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claim',
            trigger=pgtrigger.compiler.Trigger(name='claim_final', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'closed\', \'void\'))', func="RAISE EXCEPTION 'CLAIM_FINAL: closed or void claims never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='9ae5c19a5f0d21faf60757301a7bb4066d1a3b56', operation='UPDATE OR DELETE', pgid='pgtrigger_claim_final_b905f', table='claims_claim', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claim',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_claimevent" ("accepted_total", "claimed_total", "closed_at", "created_at", "created_by_id", "id", "note", "number", "payer_id", "period_end", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_total", "response_at", "status", "submitted_at", "submitted_by_id", "updated_at") VALUES (NEW."accepted_total", NEW."claimed_total", NEW."closed_at", NEW."created_at", NEW."created_by_id", NEW."id", NEW."note", NEW."number", NEW."payer_id", NEW."period_end", NEW."period_start", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rejected_total", NEW."response_at", NEW."status", NEW."submitted_at", NEW."submitted_by_id", NEW."updated_at"); RETURN NULL;', hash='9894aecffcf9017ce7cb5c28766a7f5ac25a9cd3', operation='INSERT', pgid='pgtrigger_insert_insert_df8fa', table='claims_claim', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claim',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "claims_claimevent" ("accepted_total", "claimed_total", "closed_at", "created_at", "created_by_id", "id", "note", "number", "payer_id", "period_end", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_total", "response_at", "status", "submitted_at", "submitted_by_id", "updated_at") VALUES (NEW."accepted_total", NEW."claimed_total", NEW."closed_at", NEW."created_at", NEW."created_by_id", NEW."id", NEW."note", NEW."number", NEW."payer_id", NEW."period_end", NEW."period_start", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rejected_total", NEW."response_at", NEW."status", NEW."submitted_at", NEW."submitted_by_id", NEW."updated_at"); RETURN NULL;', hash='01ec4d5cd36b75b8aa028d2f89ea7ddbf78981ae', operation='UPDATE', pgid='pgtrigger_update_update_fe4ba', table='claims_claim', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claim',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_claimevent" ("accepted_total", "claimed_total", "closed_at", "created_at", "created_by_id", "id", "note", "number", "payer_id", "period_end", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_total", "response_at", "status", "submitted_at", "submitted_by_id", "updated_at") VALUES (OLD."accepted_total", OLD."claimed_total", OLD."closed_at", OLD."created_at", OLD."created_by_id", OLD."id", OLD."note", OLD."number", OLD."payer_id", OLD."period_end", OLD."period_start", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rejected_total", OLD."response_at", OLD."status", OLD."submitted_at", OLD."submitted_by_id", OLD."updated_at"); RETURN NULL;', hash='ad8ba7cc7f557a80a710f6c5a6ac708b6bad4592', operation='DELETE', pgid='pgtrigger_delete_delete_dbf31', table='claims_claim', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0342f9354d975fc258a2169f5a68f2fcb6b672f7', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_aeef3', table='claims_claimevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='claimline',
            index=models.Index(fields=['status', 'resolution'], name='claims_line_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'rejected', 'partial', 'withdrawn'])), name='claims_line_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__in', ['none', 'rebilled', 'written_off'])), name='claims_line_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_claimed__gt', 0), ('accepted_amount__gte', 0), ('rejected_amount__gte', 0)), name='claims_line_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'withdrawn']), ('accepted_amount', django.db.models.expressions.CombinedExpression(models.F('amount_claimed'), '-', models.F('rejected_amount'))), _connector='OR'), name='claims_line_response_adds_up'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'accepted'), _negated=True), ('rejected_amount', 0), _connector='OR'), name='claims_line_accepted_has_no_rejection'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), ('accepted_amount', 0), _connector='OR'), name='claims_line_rejected_has_no_acceptance'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'partial'), _negated=True), models.Q(('accepted_amount__gt', 0), ('rejected_amount__gt', 0)), _connector='OR'), name='claims_line_partial_has_both'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('resolution', 'none'), models.Q(('rejected_amount__gt', 0), ('resolution_reason__isnull', False), ('resolved_at__isnull', False), ('resolved_by__isnull', False)), _connector='OR'), name='claims_line_resolution_documented'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'withdrawn'), _negated=True), fields=('invoice_line',), name='claims_line_invoice_line_claimed_once'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status") VALUES (NEW."accepted_amount", NEW."amount_claimed", NEW."claim_id", NEW."id", NEW."invoice_line_id", NEW."payer_reason", NEW."payer_reference", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rejected_amount", NEW."resolution", NEW."resolution_note", NEW."resolution_reason_id", NEW."resolved_at", NEW."resolved_by_id", NEW."responded_at", NEW."responded_by_id", NEW."status"); RETURN NULL;', hash='686a5bad10a254bdbc2498091ff38cfa0ee6526d', operation='INSERT', pgid='pgtrigger_insert_insert_334cc', table='claims_claimline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status") VALUES (NEW."accepted_amount", NEW."amount_claimed", NEW."claim_id", NEW."id", NEW."invoice_line_id", NEW."payer_reason", NEW."payer_reference", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rejected_amount", NEW."resolution", NEW."resolution_note", NEW."resolution_reason_id", NEW."resolved_at", NEW."resolved_by_id", NEW."responded_at", NEW."responded_by_id", NEW."status"); RETURN NULL;', hash='747f0e86d92811518c7b7920ec01b3e12ac37d8f', operation='UPDATE', pgid='pgtrigger_update_update_ac8fa', table='claims_claimline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status") VALUES (OLD."accepted_amount", OLD."amount_claimed", OLD."claim_id", OLD."id", OLD."invoice_line_id", OLD."payer_reason", OLD."payer_reference", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rejected_amount", OLD."resolution", OLD."resolution_note", OLD."resolution_reason_id", OLD."resolved_at", OLD."resolved_by_id", OLD."responded_at", OLD."responded_by_id", OLD."status"); RETURN NULL;', hash='0324b0f6159e007038f9424b41980199d0fc0095', operation='DELETE', pgid='pgtrigger_delete_delete_33d41', table='claims_claimline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimlineevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='13ca2a7bcfa8ffb001bc8066e515d26ce170c8f3', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_afe7b', table='claims_claimlineevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['bank_transfer', 'cheque', 'cash'])), name='claims_payerpayment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='claims_payerpayment_positive'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'bank_transfer'), _negated=True), models.Q(('bank__isnull', False), models.Q(('reference', ''), _negated=True)), _connector='OR'), name='claims_payerpayment_transfer_has_reference'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('bank__isnull', False), models.Q(('reference', ''), _negated=True)), fields=('bank', 'reference_norm'), name='claims_payerpayment_reference_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='payer_payment_money_readonly', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."number" IS DISTINCT FROM (NEW."number") OR OLD."payer_id" IS DISTINCT FROM (NEW."payer_id") OR OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."method" IS DISTINCT FROM (NEW."method") OR OLD."bank_id" IS DISTINCT FROM (NEW."bank_id") OR OLD."reference" IS DISTINCT FROM (NEW."reference") OR OLD."received_on" IS DISTINCT FROM (NEW."received_on"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='66f44c6c78b848bdd25a6df57c9cf2bdc05f91b5', operation='UPDATE', pgid='pgtrigger_payer_payment_money_readonly_9af17', table='claims_payerpayment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='payer_payment_no_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'PAYMENT_PERMANENT: payer payments are never deleted (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='2d3e83d5f3f532c63ab6409967f37c83ba3cbc36', operation='DELETE', pgid='pgtrigger_payer_payment_no_delete_fc31c', table='claims_payerpayment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_payerpaymentevent" ("amount", "bank_id", "id", "method", "note", "number", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "recorded_at", "recorded_by_id", "reference") VALUES (NEW."amount", NEW."bank_id", NEW."id", NEW."method", NEW."note", NEW."number", NEW."payer_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_on", NEW."recorded_at", NEW."recorded_by_id", NEW."reference"); RETURN NULL;', hash='cd80302578507fa87cbbf4c16ad09b5c732e819d', operation='INSERT', pgid='pgtrigger_insert_insert_05db8', table='claims_payerpayment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."bank_id" IS DISTINCT FROM (NEW."bank_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."method" IS DISTINCT FROM (NEW."method") OR OLD."note" IS DISTINCT FROM (NEW."note") OR OLD."number" IS DISTINCT FROM (NEW."number") OR OLD."payer_id" IS DISTINCT FROM (NEW."payer_id") OR OLD."received_on" IS DISTINCT FROM (NEW."received_on") OR OLD."recorded_at" IS DISTINCT FROM (NEW."recorded_at") OR OLD."recorded_by_id" IS DISTINCT FROM (NEW."recorded_by_id") OR OLD."reference" IS DISTINCT FROM (NEW."reference"))', func='INSERT INTO "claims_payerpaymentevent" ("amount", "bank_id", "id", "method", "note", "number", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "recorded_at", "recorded_by_id", "reference") VALUES (NEW."amount", NEW."bank_id", NEW."id", NEW."method", NEW."note", NEW."number", NEW."payer_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_on", NEW."recorded_at", NEW."recorded_by_id", NEW."reference"); RETURN NULL;', hash='dd7dfddb6af380de3975cda70f1140bcf22e88c5', operation='UPDATE', pgid='pgtrigger_update_update_83feb', table='claims_payerpayment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_payerpaymentevent" ("amount", "bank_id", "id", "method", "note", "number", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "recorded_at", "recorded_by_id", "reference") VALUES (OLD."amount", OLD."bank_id", OLD."id", OLD."method", OLD."note", OLD."number", OLD."payer_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."received_on", OLD."recorded_at", OLD."recorded_by_id", OLD."reference"); RETURN NULL;', hash='4acd4d979cfff2522f288a3e879fe842ccd752c8', operation='DELETE', pgid='pgtrigger_delete_delete_4289c', table='claims_payerpayment', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='payerpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_of__isnull', True), ('amount__gt', 0)), models.Q(('reversal_of__isnull', False), ('amount__lt', 0)), _connector='OR'), name='claims_payeralloc_amount_sign'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpaymentallocation',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='424551ecf99da0616cdbc8a093971b9b6e8cbd53', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a08ce', table='claims_payerpaymentallocation', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpaymentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='32015927d8ebb626ad084ff7a666802984972b61', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a066c', table='claims_payerpaymentevent', when='BEFORE')),
        ),
    ]
