# Generated by Django 5.2.17 on 2026-10-07 17:20

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _fill_reference_norm(table: str, bank_only: bool):
    """Write ``reference_norm`` from the domain's one definition (it replaces the SQL
    function, whose normalization differed). User triggers are off for the backfill: the
    money columns of these rows are read-only and rejected payments never change."""

    def run(apps, schema_editor):
        from domain.payments import normalize_reference

        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"SELECT id, reference, {'method' if bank_only else 'NULL'} FROM {table}")
            rows = cursor.fetchall()
            if not rows:
                return
            cursor.execute(f"ALTER TABLE {table} DISABLE TRIGGER USER")
            for pk, reference, method in rows:
                keep = not bank_only or method in ("bank_transfer", "qr", "card")
                norm = normalize_reference(reference or "") if keep else ""
                cursor.execute(f"UPDATE {table} SET reference_norm = %s WHERE id = %s", [norm, pk])
            cursor.execute(f"ALTER TABLE {table} ENABLE TRIGGER USER")

    return run


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_creditnote_credit_note_consistent_and_more'),
        ('catalog', '0003_priceitem_item_guard_pricelistversion_version_guard'),
        ('claims', '0002_initial'),
        ('core', '0008_printtemplate_printtemplateevent_and_more'),
        ('payments', '0004_remove_cashhandover_shift_must_be_open_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='claimline',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='claimline',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='claimline',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payerpayment',
            name='payer_payment_money_readonly',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payerpayment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payerpayment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payerpayment',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='claimline',
            name='withdraw_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='claimline',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimline',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimline',
            name='written_off_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accepted amount the payer short-paid, written off.', max_digits=14),
        ),
        migrations.AddField(
            model_name='claimline',
            name='written_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimline',
            name='written_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimline',
            name='written_off_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claimline',
            name='written_off_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'writeoff'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='withdraw_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='written_off_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accepted amount the payer short-paid, written off.', max_digits=14),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='written_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='written_off_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='written_off_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='written_off_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'writeoff'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='cleared_at',
            field=models.DateTimeField(blank=True, help_text='A cheque cleared.', null=True),
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='reverse_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='shift',
            field=models.ForeignKey(blank=True, help_text="Payer cash goes into the recording cashier's open shift.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer_payments', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='cleared_at',
            field=models.DateTimeField(blank=True, help_text='A cheque cleared.', null=True),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='cleared_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='reverse_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='reversed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payerpaymentevent',
            name='shift',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Payer cash goes into the recording cashier's open shift.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.shift'),
        ),
        migrations.RemoveConstraint(
            model_name='payerpayment',
            name='claims_payerpayment_reference_unique',
        ),
        migrations.RemoveField(
            model_name='payerpayment',
            name='reference_norm',
        ),
        migrations.AddField(
            model_name='payerpayment',
            name='reference_norm',
            field=models.CharField(blank=True, default='', editable=False, help_text='``domain.payments.normalize_reference(reference)``, written by the service.', max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(_fill_reference_norm('claims_payerpayment', False), migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('bank__isnull', False), models.Q(('reference', ''), _negated=True)), fields=('bank', 'reference_norm'), name='claims_payerpayment_reference_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='ac8bcf863451cb67f2d3417ba93f71f57b3923ca', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_ef326', table='claims_claimline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='claim_line_guard', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE claim_status text;', func="\n                    IF TG_OP = 'DELETE' THEN\n                        RAISE EXCEPTION 'CLAIM_LINE_PERMANENT: claim line % is never deleted',\n                            OLD.id;\n                    END IF;\n                    SELECT k.status INTO claim_status FROM claims_claim k WHERE k.id = NEW.claim_id;\n                    IF TG_OP = 'INSERT' THEN\n                        IF claim_status <> 'draft' OR NEW.status <> 'pending' THEN\n                            RAISE EXCEPTION\n                                'CLAIM_STATUS_INVALID: lines join a draft claim as pending';\n                        END IF;\n                        IF NEW.amount_claimed > (\n                            SELECT il.payer_share - coalesce((\n                                SELECT sum(cl.payer_share) FROM billing_creditnoteline cl\n                                  JOIN billing_creditnote cn ON cn.id = cl.credit_note_id\n                                 WHERE cl.invoice_line_id = il.id AND cn.status = 'approved'\n                            ), 0)\n                              FROM billing_invoiceline il\n                             WHERE il.id = NEW.invoice_line_id AND il.frozen\n                        ) IS NOT FALSE THEN\n                            RAISE EXCEPTION\n                                'CLAIM_LINE_NOT_ACCRUED: claim line claims more than is accrued';\n                        END IF;\n                        RETURN NEW;\n                    END IF;\n                    IF claim_status IN ('closed', 'void') THEN\n                        RAISE EXCEPTION 'CLAIM_FINAL: claim line % of a % claim never changes',\n                            OLD.id, claim_status;\n                    END IF;\n                    IF NEW.claim_id IS DISTINCT FROM OLD.claim_id\n                       OR NEW.invoice_line_id IS DISTINCT FROM OLD.invoice_line_id\n                       OR NEW.amount_claimed IS DISTINCT FROM OLD.amount_claimed THEN\n                        RAISE EXCEPTION 'CLAIM_LINE_READONLY: claim line % claims a fixed amount',\n                            OLD.id;\n                    END IF;\n                    IF NEW.status IS DISTINCT FROM OLD.status AND NOT (\n                        (OLD.status = 'pending' AND (\n                            NEW.status IN ('accepted', 'rejected', 'partial')\n                            OR (NEW.status = 'withdrawn'\n                                AND claim_status IN ('draft', 'submitted', 'responded'))\n                        ))\n                        -- An answered line nothing was collected or resolved on is withdrawn\n                        -- when a credit note takes its whole payer share back.\n                        OR (OLD.status IN ('accepted', 'rejected', 'partial')\n                            AND NEW.status = 'withdrawn'\n                            AND OLD.resolution = 'none' AND OLD.written_off_amount = 0\n                            AND coalesce((\n                                SELECT sum(a.amount) FROM claims_payerpaymentallocation a\n                                 WHERE a.claim_line_id = OLD.id), 0) = 0)\n                    ) THEN\n                        RAISE EXCEPTION 'CLAIM_LINE_TRANSITION: claim line % cannot go from % to %',\n                            OLD.id, OLD.status, NEW.status;\n                    END IF;\n                    IF OLD.status <> 'pending' AND (\n                        NEW.accepted_amount IS DISTINCT FROM OLD.accepted_amount\n                        OR NEW.rejected_amount IS DISTINCT FROM OLD.rejected_amount) THEN\n                        RAISE EXCEPTION 'CLAIM_LINE_READONLY: the payer answer of % is recorded',\n                            OLD.id;\n                    END IF;\n                    IF OLD.resolution <> 'none'\n                       AND NEW.resolution IS DISTINCT FROM OLD.resolution THEN\n                        RAISE EXCEPTION 'CLAIM_LINE_READONLY: the rejection of % is resolved',\n                            OLD.id;\n                    END IF;\n                    IF OLD.written_off_amount > 0\n                       AND NEW.written_off_amount < OLD.written_off_amount THEN\n                        RAISE EXCEPTION 'CLAIM_LINE_READONLY: a write-off of % is final', OLD.id;\n                    END IF;\n                    RETURN NEW;\n                ", hash='5ae08f2bc4b99dd37c4445c7480a1993d458b0a3', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_claim_line_guard_cae3a', table='claims_claimline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status", "withdraw_note", "withdrawn_at", "withdrawn_by_id", "written_off_amount", "written_off_at", "written_off_by_id", "written_off_note", "written_off_reason_id") VALUES (NEW."accepted_amount", NEW."amount_claimed", NEW."claim_id", NEW."id", NEW."invoice_line_id", NEW."payer_reason", NEW."payer_reference", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rejected_amount", NEW."resolution", NEW."resolution_note", NEW."resolution_reason_id", NEW."resolved_at", NEW."resolved_by_id", NEW."responded_at", NEW."responded_by_id", NEW."status", NEW."withdraw_note", NEW."withdrawn_at", NEW."withdrawn_by_id", NEW."written_off_amount", NEW."written_off_at", NEW."written_off_by_id", NEW."written_off_note", NEW."written_off_reason_id"); RETURN NULL;', hash='e2b44503fa95c589a7dee973efde219640cc71b7', operation='INSERT', pgid='pgtrigger_insert_insert_334cc', table='claims_claimline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status", "withdraw_note", "withdrawn_at", "withdrawn_by_id", "written_off_amount", "written_off_at", "written_off_by_id", "written_off_note", "written_off_reason_id") VALUES (NEW."accepted_amount", NEW."amount_claimed", NEW."claim_id", NEW."id", NEW."invoice_line_id", NEW."payer_reason", NEW."payer_reference", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rejected_amount", NEW."resolution", NEW."resolution_note", NEW."resolution_reason_id", NEW."resolved_at", NEW."resolved_by_id", NEW."responded_at", NEW."responded_by_id", NEW."status", NEW."withdraw_note", NEW."withdrawn_at", NEW."withdrawn_by_id", NEW."written_off_amount", NEW."written_off_at", NEW."written_off_by_id", NEW."written_off_note", NEW."written_off_reason_id"); RETURN NULL;', hash='fcb05b84bf1187aff419d4c7785637650d3088f4', operation='UPDATE', pgid='pgtrigger_update_update_ac8fa', table='claims_claimline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status", "withdraw_note", "withdrawn_at", "withdrawn_by_id", "written_off_amount", "written_off_at", "written_off_by_id", "written_off_note", "written_off_reason_id") VALUES (OLD."accepted_amount", OLD."amount_claimed", OLD."claim_id", OLD."id", OLD."invoice_line_id", OLD."payer_reason", OLD."payer_reference", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rejected_amount", OLD."resolution", OLD."resolution_note", OLD."resolution_reason_id", OLD."resolved_at", OLD."resolved_by_id", OLD."responded_at", OLD."responded_by_id", OLD."status", OLD."withdraw_note", OLD."withdrawn_at", OLD."withdrawn_by_id", OLD."written_off_amount", OLD."written_off_at", OLD."written_off_by_id", OLD."written_off_note", OLD."written_off_reason_id"); RETURN NULL;', hash='32cd3c71a3735846edc9986c269049386723d8d9', operation='DELETE', pgid='pgtrigger_delete_delete_33d41', table='claims_claimline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='38457ed8d1cd7588b411318620f35cc1cc74fcaa', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_d3541', table='claims_payerpayment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='payer_payment_money_readonly', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."number" IS DISTINCT FROM (NEW."number") OR OLD."payer_id" IS DISTINCT FROM (NEW."payer_id") OR OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."method" IS DISTINCT FROM (NEW."method") OR OLD."bank_id" IS DISTINCT FROM (NEW."bank_id") OR OLD."reference" IS DISTINCT FROM (NEW."reference") OR OLD."reference_norm" IS DISTINCT FROM (NEW."reference_norm") OR OLD."received_on" IS DISTINCT FROM (NEW."received_on") OR OLD."shift_id" IS DISTINCT FROM (NEW."shift_id"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='d5cf266fd345e139a7fef23d7e28bc1ca475cb25', operation='UPDATE', pgid='pgtrigger_payer_payment_money_readonly_9af17', table='claims_payerpayment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='payer_payment_reversed_final', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."reversed_at" IS NOT NULL)', func="RAISE EXCEPTION 'PAYMENT_PERMANENT: a reversed payer payment never changes (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='bd780f6419d0e90916aa7279090c6bd65576f341', operation='UPDATE', pgid='pgtrigger_payer_payment_reversed_final_a1db9', table='claims_payerpayment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id) THEN\n                PERFORM 1 FROM payments_shift s\n                 WHERE s.id = NEW.shift_id AND s.status = 'open' FOR SHARE;\n                IF NOT FOUND THEN\n                    RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                        NEW.shift_id, TG_TABLE_NAME;\n                END IF;\n            END IF;\n            RETURN NEW;\n        ", hash='3b232d721a0c3523adc6792a06c5ec3c84430f42', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_340d5', table='claims_payerpayment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_payerpaymentevent" ("amount", "bank_id", "cleared_at", "cleared_by_id", "id", "method", "note", "number", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "recorded_at", "recorded_by_id", "reference", "reverse_note", "reversed_at", "reversed_by_id", "shift_id") VALUES (NEW."amount", NEW."bank_id", NEW."cleared_at", NEW."cleared_by_id", NEW."id", NEW."method", NEW."note", NEW."number", NEW."payer_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_on", NEW."recorded_at", NEW."recorded_by_id", NEW."reference", NEW."reverse_note", NEW."reversed_at", NEW."reversed_by_id", NEW."shift_id"); RETURN NULL;', hash='059d067466bef0784b65a9a7d7b43f6d83e361e9', operation='INSERT', pgid='pgtrigger_insert_insert_05db8', table='claims_payerpayment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."bank_id" IS DISTINCT FROM (NEW."bank_id") OR OLD."cleared_at" IS DISTINCT FROM (NEW."cleared_at") OR OLD."cleared_by_id" IS DISTINCT FROM (NEW."cleared_by_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."method" IS DISTINCT FROM (NEW."method") OR OLD."note" IS DISTINCT FROM (NEW."note") OR OLD."number" IS DISTINCT FROM (NEW."number") OR OLD."payer_id" IS DISTINCT FROM (NEW."payer_id") OR OLD."received_on" IS DISTINCT FROM (NEW."received_on") OR OLD."recorded_at" IS DISTINCT FROM (NEW."recorded_at") OR OLD."recorded_by_id" IS DISTINCT FROM (NEW."recorded_by_id") OR OLD."reference" IS DISTINCT FROM (NEW."reference") OR OLD."reverse_note" IS DISTINCT FROM (NEW."reverse_note") OR OLD."reversed_at" IS DISTINCT FROM (NEW."reversed_at") OR OLD."reversed_by_id" IS DISTINCT FROM (NEW."reversed_by_id") OR OLD."shift_id" IS DISTINCT FROM (NEW."shift_id"))', func='INSERT INTO "claims_payerpaymentevent" ("amount", "bank_id", "cleared_at", "cleared_by_id", "id", "method", "note", "number", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "recorded_at", "recorded_by_id", "reference", "reverse_note", "reversed_at", "reversed_by_id", "shift_id") VALUES (NEW."amount", NEW."bank_id", NEW."cleared_at", NEW."cleared_by_id", NEW."id", NEW."method", NEW."note", NEW."number", NEW."payer_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_on", NEW."recorded_at", NEW."recorded_by_id", NEW."reference", NEW."reverse_note", NEW."reversed_at", NEW."reversed_by_id", NEW."shift_id"); RETURN NULL;', hash='6376569cca9a4dfd1eb5bfc24222dbbb3ed8d6b8', operation='UPDATE', pgid='pgtrigger_update_update_83feb', table='claims_payerpayment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpayment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_payerpaymentevent" ("amount", "bank_id", "cleared_at", "cleared_by_id", "id", "method", "note", "number", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "recorded_at", "recorded_by_id", "reference", "reverse_note", "reversed_at", "reversed_by_id", "shift_id") VALUES (OLD."amount", OLD."bank_id", OLD."cleared_at", OLD."cleared_by_id", OLD."id", OLD."method", OLD."note", OLD."number", OLD."payer_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."received_on", OLD."recorded_at", OLD."recorded_by_id", OLD."reference", OLD."reverse_note", OLD."reversed_at", OLD."reversed_by_id", OLD."shift_id"); RETURN NULL;', hash='eeee2588c4782250cc261c483818ecb47b265b0d', operation='DELETE', pgid='pgtrigger_delete_delete_4289c', table='claims_payerpayment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerpaymentallocation',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='428de44ab1088fc5d63f493059c8ad359f46c2e3', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_5333e', table='claims_payerpaymentallocation', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'withdrawn'), _negated=True), models.Q(('withdrawn_at__isnull', False), ('withdrawn_by__isnull', False), models.Q(('withdraw_note', ''), _negated=True)), _connector='OR'), name='claims_line_withdrawal_documented'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('written_off_amount', 0), models.Q(('written_off_amount__gt', 0), ('status__in', ['accepted', 'partial']), ('written_off_amount__lte', models.F('accepted_amount')), ('written_off_at__isnull', False), ('written_off_by__isnull', False), ('written_off_reason__isnull', False)), _connector='OR'), name='claims_line_write_off_documented'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('written_off_amount__gte', 0)), name='claims_line_write_off_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'cash'), _negated=True), ('shift__isnull', False), _connector='OR'), name='claims_payerpayment_cash_in_shift'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('cleared_at__isnull', True), models.Q(('method', 'cheque'), ('cleared_by__isnull', False)), _connector='OR'), name='claims_payerpayment_clearing_documented'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_at__isnull', True), models.Q(models.Q(('method', 'cash'), _negated=True), ('reversed_by__isnull', False), models.Q(('reverse_note', ''), _negated=True)), _connector='OR'), name='claims_payerpayment_reversal_documented'),
        ),
    ]
