# Generated by Django 5.2.17 on 2026-10-10 11:40

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_creditnote_credit_note_consistent_and_more'),
        ('claims', '0003_remove_claimline_insert_insert_and_more'),
        ('core', '0014_display_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='claimline',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='claimline',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='claimline',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='claimline',
            name='resolution_approved_by',
            field=models.ForeignKey(blank=True, help_text='The second person who approved the rebill or write-off (ADR 0018).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimline',
            name='written_off_approved_by',
            field=models.ForeignKey(blank=True, help_text='The second person who approved the short-payment write-off (ADR 0018).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='resolution_approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The second person who approved the rebill or write-off (ADR 0018).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimlineevent',
            name='written_off_approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The second person who approved the short-payment write-off (ADR 0018).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_approved_by_id", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status", "withdraw_note", "withdrawn_at", "withdrawn_by_id", "written_off_amount", "written_off_approved_by_id", "written_off_at", "written_off_by_id", "written_off_note", "written_off_reason_id") VALUES (NEW."accepted_amount", NEW."amount_claimed", NEW."claim_id", NEW."id", NEW."invoice_line_id", NEW."payer_reason", NEW."payer_reference", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rejected_amount", NEW."resolution", NEW."resolution_approved_by_id", NEW."resolution_note", NEW."resolution_reason_id", NEW."resolved_at", NEW."resolved_by_id", NEW."responded_at", NEW."responded_by_id", NEW."status", NEW."withdraw_note", NEW."withdrawn_at", NEW."withdrawn_by_id", NEW."written_off_amount", NEW."written_off_approved_by_id", NEW."written_off_at", NEW."written_off_by_id", NEW."written_off_note", NEW."written_off_reason_id"); RETURN NULL;', hash='5ae31aa4dbdfb70c9712dad545a70f3025303830', operation='INSERT', pgid='pgtrigger_insert_insert_334cc', table='claims_claimline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_approved_by_id", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status", "withdraw_note", "withdrawn_at", "withdrawn_by_id", "written_off_amount", "written_off_approved_by_id", "written_off_at", "written_off_by_id", "written_off_note", "written_off_reason_id") VALUES (NEW."accepted_amount", NEW."amount_claimed", NEW."claim_id", NEW."id", NEW."invoice_line_id", NEW."payer_reason", NEW."payer_reference", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rejected_amount", NEW."resolution", NEW."resolution_approved_by_id", NEW."resolution_note", NEW."resolution_reason_id", NEW."resolved_at", NEW."resolved_by_id", NEW."responded_at", NEW."responded_by_id", NEW."status", NEW."withdraw_note", NEW."withdrawn_at", NEW."withdrawn_by_id", NEW."written_off_amount", NEW."written_off_approved_by_id", NEW."written_off_at", NEW."written_off_by_id", NEW."written_off_note", NEW."written_off_reason_id"); RETURN NULL;', hash='0b78d53feafc4a409ed57418cd3e42536b916869', operation='UPDATE', pgid='pgtrigger_update_update_ac8fa', table='claims_claimline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='claimline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "claims_claimlineevent" ("accepted_amount", "amount_claimed", "claim_id", "id", "invoice_line_id", "payer_reason", "payer_reference", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejected_amount", "resolution", "resolution_approved_by_id", "resolution_note", "resolution_reason_id", "resolved_at", "resolved_by_id", "responded_at", "responded_by_id", "status", "withdraw_note", "withdrawn_at", "withdrawn_by_id", "written_off_amount", "written_off_approved_by_id", "written_off_at", "written_off_by_id", "written_off_note", "written_off_reason_id") VALUES (OLD."accepted_amount", OLD."amount_claimed", OLD."claim_id", OLD."id", OLD."invoice_line_id", OLD."payer_reason", OLD."payer_reference", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rejected_amount", OLD."resolution", OLD."resolution_approved_by_id", OLD."resolution_note", OLD."resolution_reason_id", OLD."resolved_at", OLD."resolved_by_id", OLD."responded_at", OLD."responded_by_id", OLD."status", OLD."withdraw_note", OLD."withdrawn_at", OLD."withdrawn_by_id", OLD."written_off_amount", OLD."written_off_approved_by_id", OLD."written_off_at", OLD."written_off_by_id", OLD."written_off_note", OLD."written_off_reason_id"); RETURN NULL;', hash='b2550c15617c4cc3680b86057b1c5563e72a0da7', operation='DELETE', pgid='pgtrigger_delete_delete_33d41', table='claims_claimline', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_approved_by__isnull', True), models.Q(('resolution_approved_by', models.F('resolved_by')), _negated=True), _connector='OR'), name='claims_line_resolution_second_person'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.CheckConstraint(condition=models.Q(('written_off_approved_by__isnull', True), models.Q(('written_off_approved_by', models.F('written_off_by')), _negated=True), _connector='OR'), name='claims_line_write_off_second_person'),
        ),
    ]
