# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('nightly', 'Nightly'), ('manual', 'Manual'), ('pre_update', 'Before an update')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial (some files missing)'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('cloud_status', models.CharField(choices=[('pending', 'Waiting for internet'), ('uploaded', 'Uploaded'), ('failed', 'Upload failed'), ('skipped', 'Not configured')], default='pending', max_length=20)),
                ('cloud_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'backup run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRunEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('nightly', 'Nightly'), ('manual', 'Manual'), ('pre_update', 'Before an update')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial (some files missing)'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('cloud_status', models.CharField(choices=[('pending', 'Waiting for internet'), ('uploaded', 'Uploaded'), ('failed', 'Upload failed'), ('skipped', 'Not configured')], default='pending', max_length=20)),
                ('cloud_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ops.backuprun')),
                ('triggered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestoreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_tests', to='ops.backuprun')),
            ],
            options={
                'verbose_name': 'restore test',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreTestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('backup', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='ops.backuprun')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ops.restoretest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='backuprun',
            index=models.Index(fields=['status', '-started_at'], name='ops_backup_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='backuprun',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['nightly', 'manual', 'pre_update'])), name='ops_backup_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='backuprun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['running', 'succeeded', 'partial', 'failed'])), name='ops_backup_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='backuprun',
            constraint=models.CheckConstraint(condition=models.Q(('cloud_status__in', ['pending', 'uploaded', 'failed', 'skipped'])), name='ops_backup_cloud_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='backuprun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='ops_backup_finish_after_start'),
        ),
        migrations.AddConstraint(
            model_name='backuprun',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__isnull', True), ('size_bytes__gte', 0), _connector='OR'), name='ops_backup_size_non_negative'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='backuprun',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_backuprunevent" ("checksum", "cloud_status", "cloud_uploaded_at", "finished_at", "id", "kind", "location", "message", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size_bytes", "started_at", "status", "triggered_by_id") VALUES (NEW."checksum", NEW."cloud_status", NEW."cloud_uploaded_at", NEW."finished_at", NEW."id", NEW."kind", NEW."location", NEW."message", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."size_bytes", NEW."started_at", NEW."status", NEW."triggered_by_id"); RETURN NULL;', hash='a747030fa98d18609183ac427f6d6be3cb238aee', operation='INSERT', pgid='pgtrigger_insert_insert_daab4', table='ops_backuprun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='backuprun',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ops_backuprunevent" ("checksum", "cloud_status", "cloud_uploaded_at", "finished_at", "id", "kind", "location", "message", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size_bytes", "started_at", "status", "triggered_by_id") VALUES (NEW."checksum", NEW."cloud_status", NEW."cloud_uploaded_at", NEW."finished_at", NEW."id", NEW."kind", NEW."location", NEW."message", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."size_bytes", NEW."started_at", NEW."status", NEW."triggered_by_id"); RETURN NULL;', hash='4e1ea89278c328b5bbb18146b1735a746620a24b', operation='UPDATE', pgid='pgtrigger_update_update_9be80', table='ops_backuprun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='backuprun',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_backuprunevent" ("checksum", "cloud_status", "cloud_uploaded_at", "finished_at", "id", "kind", "location", "message", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size_bytes", "started_at", "status", "triggered_by_id") VALUES (OLD."checksum", OLD."cloud_status", OLD."cloud_uploaded_at", OLD."finished_at", OLD."id", OLD."kind", OLD."location", OLD."message", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."size_bytes", OLD."started_at", OLD."status", OLD."triggered_by_id"); RETURN NULL;', hash='435e2b9a3972f66aa7b74fd6c030e63a8e27f107', operation='DELETE', pgid='pgtrigger_delete_delete_4c15d', table='ops_backuprun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='backuprunevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0ff5bc4b38d89821bf70923c4b7af631a5fb29f8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_fbee1', table='ops_backuprunevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='restoretest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['running', 'passed', 'failed'])), name='ops_restore_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='restoretest',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='ops_restore_finish_after_start'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='restoretest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_restoretestevent" ("backup_id", "checks", "finished_at", "id", "message", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started_at", "status") VALUES (NEW."backup_id", NEW."checks", NEW."finished_at", NEW."id", NEW."message", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."started_at", NEW."status"); RETURN NULL;', hash='b5fbccb79b93f80d232068c89bd922c06050f7d2', operation='INSERT', pgid='pgtrigger_insert_insert_eb5aa', table='ops_restoretest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='restoretest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ops_restoretestevent" ("backup_id", "checks", "finished_at", "id", "message", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started_at", "status") VALUES (NEW."backup_id", NEW."checks", NEW."finished_at", NEW."id", NEW."message", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."started_at", NEW."status"); RETURN NULL;', hash='efdeb6feb05c93ecdfc328e187e01922d50887f2', operation='UPDATE', pgid='pgtrigger_update_update_4ad66', table='ops_restoretest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='restoretest',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_restoretestevent" ("backup_id", "checks", "finished_at", "id", "message", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started_at", "status") VALUES (OLD."backup_id", OLD."checks", OLD."finished_at", OLD."id", OLD."message", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."started_at", OLD."status"); RETURN NULL;', hash='eb20d2540c23ddd59ae787c96550d9645e224e7c', operation='DELETE', pgid='pgtrigger_delete_delete_49e62', table='ops_restoretest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='restoretestevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='b9ff2bb27d4a2925a9b4799dac3df7e08ff07ab3', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d3993', table='ops_restoretestevent', when='BEFORE')),
        ),
    ]
