# Generated by Django 5.2.17 on 2026-10-07 16:57

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('previous_version', models.CharField(blank=True, max_length=50)),
                ('release_notes', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'update run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateRunEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('version', models.CharField(max_length=50)),
                ('previous_version', models.CharField(blank=True, max_length=50)),
                ('release_notes', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ops.updaterun')),
                ('started_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='updaterun',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ['running', 'succeeded', 'failed', 'rolled_back'])), name='ops_update_result_valid'),
        ),
        migrations.AddConstraint(
            model_name='updaterun',
            constraint=models.CheckConstraint(condition=models.Q(('result', 'running'), ('finished_at__isnull', False), _connector='OR'), name='ops_update_finished_documented'),
        ),
        migrations.AddConstraint(
            model_name='updaterun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='ops_update_finish_after_start'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='updaterun',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_updaterunevent" ("finished_at", "id", "log", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_version", "release_notes", "result", "started_at", "started_by_id", "version") VALUES (NEW."finished_at", NEW."id", NEW."log", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."previous_version", NEW."release_notes", NEW."result", NEW."started_at", NEW."started_by_id", NEW."version"); RETURN NULL;', hash='c01c33eaa7d39cdef7d924a14e5ed4fc3c254aa4', operation='INSERT', pgid='pgtrigger_insert_insert_46752', table='ops_updaterun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='updaterun',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ops_updaterunevent" ("finished_at", "id", "log", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_version", "release_notes", "result", "started_at", "started_by_id", "version") VALUES (NEW."finished_at", NEW."id", NEW."log", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."previous_version", NEW."release_notes", NEW."result", NEW."started_at", NEW."started_by_id", NEW."version"); RETURN NULL;', hash='36acec814626994bdab87eac63def580e222ea69', operation='UPDATE', pgid='pgtrigger_update_update_bdf0d', table='ops_updaterun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='updaterun',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_updaterunevent" ("finished_at", "id", "log", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_version", "release_notes", "result", "started_at", "started_by_id", "version") VALUES (OLD."finished_at", OLD."id", OLD."log", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."previous_version", OLD."release_notes", OLD."result", OLD."started_at", OLD."started_by_id", OLD."version"); RETURN NULL;', hash='591078e9c0c3a031fbf71212aa40789c305709b2', operation='DELETE', pgid='pgtrigger_delete_delete_f3fb9', table='ops_updaterun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='updaterunevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='a925fef1fe9952965bd233396a45c1800bb0f4aa', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a4eaa', table='ops_updaterunevent', when='BEFORE')),
        ),
    ]
