# Generated by Django 5.2.17 on 2026-10-09 23:42

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_updaterun_updaterunevent_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the backup service'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial (some files missing)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dump_file', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'backup request',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BackupRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the backup service'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial (some files missing)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dump_file', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ops.backuprequest')),
                ('requested_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tables', models.JSONField(default=list)),
                ('row_counts', models.JSONField(blank=True, default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data export',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DataExportEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tables', models.JSONField(default=list)),
                ('row_counts', models.JSONField(blank=True, default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ops.dataexport')),
                ('requested_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='backuprequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'succeeded', 'partial', 'failed'])), name='ops_backup_request_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='backuprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('status',), name='ops_backup_request_one_pending'),
        ),
        migrations.AddConstraint(
            model_name='backuprequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'running')), ('finished_at__isnull', False), _connector='OR'), name='ops_backup_request_finish_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='backuprequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_backuprequestevent" ("dump_file", "finished_at", "id", "message", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requested_at", "requested_by_id", "started_at", "status") VALUES (NEW."dump_file", NEW."finished_at", NEW."id", NEW."message", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requested_at", NEW."requested_by_id", NEW."started_at", NEW."status"); RETURN NULL;', hash='7c380fe55c1ec97751617608625e0b29ca2b91fd', operation='INSERT', pgid='pgtrigger_insert_insert_b1774', table='ops_backuprequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='backuprequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ops_backuprequestevent" ("dump_file", "finished_at", "id", "message", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requested_at", "requested_by_id", "started_at", "status") VALUES (NEW."dump_file", NEW."finished_at", NEW."id", NEW."message", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requested_at", NEW."requested_by_id", NEW."started_at", NEW."status"); RETURN NULL;', hash='082ec0e38627c89e9cb8dbf51792f7a80e6a552c', operation='UPDATE', pgid='pgtrigger_update_update_532c4', table='ops_backuprequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='backuprequest',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_backuprequestevent" ("dump_file", "finished_at", "id", "message", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requested_at", "requested_by_id", "started_at", "status") VALUES (OLD."dump_file", OLD."finished_at", OLD."id", OLD."message", OLD."note", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."requested_at", OLD."requested_by_id", OLD."started_at", OLD."status"); RETURN NULL;', hash='db05b02119d4620837cfe83be0fca8ec445780d8', operation='DELETE', pgid='pgtrigger_delete_delete_af88b', table='ops_backuprequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='backuprequestevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c3e17e78ad993100f6b165d2f4a0663ea1fc98f8', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_6dd01', table='ops_backuprequestevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='dataexport',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__isnull', True), ('size_bytes__gte', 0), _connector='OR'), name='ops_export_size_non_negative'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dataexport',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_dataexportevent" ("created_at", "finished_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requested_by_id", "row_counts", "size_bytes", "tables") VALUES (NEW."created_at", NEW."finished_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requested_by_id", NEW."row_counts", NEW."size_bytes", NEW."tables"); RETURN NULL;', hash='aef4a91e5047c412d3319c089a53e2bb8495ae77', operation='INSERT', pgid='pgtrigger_insert_insert_eda29', table='ops_dataexport', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dataexport',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ops_dataexportevent" ("created_at", "finished_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requested_by_id", "row_counts", "size_bytes", "tables") VALUES (NEW."created_at", NEW."finished_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requested_by_id", NEW."row_counts", NEW."size_bytes", NEW."tables"); RETURN NULL;', hash='2422cfc483cbc12e720cc9fcc4a67e9006f61a48', operation='UPDATE', pgid='pgtrigger_update_update_7710d', table='ops_dataexport', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dataexport',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_dataexportevent" ("created_at", "finished_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requested_by_id", "row_counts", "size_bytes", "tables") VALUES (OLD."created_at", OLD."finished_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."requested_by_id", OLD."row_counts", OLD."size_bytes", OLD."tables"); RETURN NULL;', hash='54527b7d8268bf48e69852e4dcfb9b45092d46d7', operation='DELETE', pgid='pgtrigger_delete_delete_56c28', table='ops_dataexport', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dataexportevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='da7d4d048f3570e425cf152af06725ceabe17ac7', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_7dbbc', table='ops_dataexportevent', when='BEFORE')),
        ),
    ]
