# Generated by Django 5.2.17 on 2026-10-10 12:53

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_backup_request_data_export'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='updaterun',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='updaterun',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='updaterun',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='updaterun',
            name='backup_file',
            field=models.CharField(blank=True, db_default='', default='', max_length=500),
        ),
        migrations.AddField(
            model_name='updaterun',
            name='db_restored',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='updaterun',
            name='detail',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='updaterun',
            name='migration_plan',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='updaterun',
            name='migrations_applied',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='updaterun',
            name='run_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='updaterunevent',
            name='backup_file',
            field=models.CharField(blank=True, db_default='', default='', max_length=500),
        ),
        migrations.AddField(
            model_name='updaterunevent',
            name='db_restored',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='updaterunevent',
            name='detail',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='updaterunevent',
            name='migration_plan',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='updaterunevent',
            name='migrations_applied',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='updaterunevent',
            name='run_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='updaterun',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_updaterunevent" ("backup_file", "db_restored", "detail", "finished_at", "id", "log", "migration_plan", "migrations_applied", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_version", "release_notes", "result", "run_key", "started_at", "started_by_id", "version") VALUES (NEW."backup_file", NEW."db_restored", NEW."detail", NEW."finished_at", NEW."id", NEW."log", NEW."migration_plan", NEW."migrations_applied", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."previous_version", NEW."release_notes", NEW."result", NEW."run_key", NEW."started_at", NEW."started_by_id", NEW."version"); RETURN NULL;', hash='b616494ed29ad6ee0acc1af24c0b76ebb6bdc207', operation='INSERT', pgid='pgtrigger_insert_insert_46752', table='ops_updaterun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='updaterun',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ops_updaterunevent" ("backup_file", "db_restored", "detail", "finished_at", "id", "log", "migration_plan", "migrations_applied", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_version", "release_notes", "result", "run_key", "started_at", "started_by_id", "version") VALUES (NEW."backup_file", NEW."db_restored", NEW."detail", NEW."finished_at", NEW."id", NEW."log", NEW."migration_plan", NEW."migrations_applied", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."previous_version", NEW."release_notes", NEW."result", NEW."run_key", NEW."started_at", NEW."started_by_id", NEW."version"); RETURN NULL;', hash='f16ebb225b194f4ecfe71d87fa38f184fa50dacb', operation='UPDATE', pgid='pgtrigger_update_update_bdf0d', table='ops_updaterun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='updaterun',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ops_updaterunevent" ("backup_file", "db_restored", "detail", "finished_at", "id", "log", "migration_plan", "migrations_applied", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_version", "release_notes", "result", "run_key", "started_at", "started_by_id", "version") VALUES (OLD."backup_file", OLD."db_restored", OLD."detail", OLD."finished_at", OLD."id", OLD."log", OLD."migration_plan", OLD."migrations_applied", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."previous_version", OLD."release_notes", OLD."result", OLD."run_key", OLD."started_at", OLD."started_by_id", OLD."version"); RETURN NULL;', hash='dbbe0ca034b4b5cc5a72098fc4e9c02bfbc21959', operation='DELETE', pgid='pgtrigger_delete_delete_f3fb9', table='ops_updaterun', when='AFTER')),
        ),
    ]
