# Generated by Django 5.2.17 on 2026-10-06 10:38

import apps.core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterProfileEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.FileField(blank=True, upload_to='center/')),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('tax_no', models.CharField(blank=True, max_length=100)),
                ('digits', models.CharField(choices=[('latin', 'Latin (0123)'), ('arabic', 'Arabic-Indic (٠١٢٣)')], default='latin', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_ar', models.CharField(blank=True, max_length=150)),
                ('specialty_en', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfileEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('specialty_ar', models.CharField(blank=True, max_length=150)),
                ('specialty_en', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('default_pay_first', models.BooleanField(default=True)),
                ('follow_up_window_days', models.PositiveSmallIntegerField(default=7)),
                ('follow_up_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('discount_limit_percent', models.JSONField(default=apps.core.models._default_discount_limits, help_text='Maximum discount percent per role code, e.g. {"cashier": 0}.')),
                ('session_idle_minutes', models.PositiveIntegerField(default=480, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('perform_first_roles', models.JSONField(default=apps.core.models._default_perform_first_roles, help_text='Role codes allowed to authorize perform-first exceptions.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policy',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('default_pay_first', models.BooleanField(default=True)),
                ('follow_up_window_days', models.PositiveSmallIntegerField(default=7)),
                ('follow_up_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('discount_limit_percent', models.JSONField(default=apps.core.models._default_discount_limits, help_text='Maximum discount percent per role code, e.g. {"cashier": 0}.')),
                ('session_idle_minutes', models.PositiveIntegerField(default=480, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('perform_first_roles', models.JSONField(default=apps.core.models._default_perform_first_roles, help_text='Role codes allowed to authorize perform-first exceptions.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('code', models.CharField(max_length=40)),
                ('label_ar', models.CharField(max_length=200)),
                ('label_en', models.CharField(max_length=200)),
                ('requires_note', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReasonCodeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('category', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40)),
                ('label_ar', models.CharField(max_length=200)),
                ('label_en', models.CharField(max_length=200)),
                ('requires_note', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('allowed', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=100)),
                ('allowed', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoomEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['code', '-year'],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name_ar', models.CharField(blank=True, max_length=150)),
                ('full_name_en', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('warm', 'Warm')], default='light', max_length=10)),
                ('must_change_password', models.BooleanField(default=True, help_text='Forces a password change at next login (FEATURES 0.1).')),
                ('password_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name_ar', models.CharField(blank=True, max_length=150)),
                ('full_name_en', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('warm', 'Warm')], default='light', max_length=10)),
                ('must_change_password', models.BooleanField(default=True, help_text='Forces a password change at next login (FEATURES 0.1).')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['username'],
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login_success', 'Login succeeded'), ('login_failed', 'Login failed'), ('login_locked', 'Login refused: account locked'), ('account_locked', 'Account locked after repeated failures'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('password_change_failed', 'Password change rejected')], max_length=30)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CenterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.FileField(blank=True, upload_to='center/')),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('tax_no', models.CharField(blank=True, max_length=100)),
                ('digits', models.CharField(choices=[('latin', 'Latin (0123)'), ('arabic', 'Arabic-Indic (٠١٢٣)')], default='latin', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'center profile',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='core_centerprofile_single')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='centerprofile',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_centerprofileevent" ("address", "digits", "id", "logo", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "registration_no", "tax_no", "updated_at") VALUES (NEW."address", NEW."digits", NEW."id", NEW."logo", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."registration_no", NEW."tax_no", NEW."updated_at"); RETURN NULL;', hash='64b6ad40b1d9f6ddf0a4a2df1154a66ebe9b73fc', operation='INSERT', pgid='pgtrigger_insert_insert_9ee7e', table='core_centerprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='centerprofile',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_centerprofileevent" ("address", "digits", "id", "logo", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "registration_no", "tax_no", "updated_at") VALUES (NEW."address", NEW."digits", NEW."id", NEW."logo", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."registration_no", NEW."tax_no", NEW."updated_at"); RETURN NULL;', hash='db1be130530c36ad7f24929ae3ec0a3fe30212df', operation='UPDATE', pgid='pgtrigger_update_update_b57fd', table='core_centerprofile', when='AFTER')),
        ),
        migrations.AddField(
            model_name='centerprofileevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='centerprofileevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.centerprofile'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='department',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_departmentevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='a6686308d313bf6caeaaba4d92e59ecaed862f1a', operation='INSERT', pgid='pgtrigger_insert_insert_77e15', table='core_department', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='department',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_departmentevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='65e227a1d1d6197b849fc8e1affd8b11e01aab58', operation='UPDATE', pgid='pgtrigger_update_update_ad22d', table='core_department', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='department',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_departmentevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (OLD."active", OLD."code", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order"); RETURN NULL;', hash='592b3716a823db10471554cd47d6309cfb6d5cff', operation='DELETE', pgid='pgtrigger_delete_delete_028c2', table='core_department', when='AFTER')),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.department'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='core.department'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofileevent',
            name='department',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='doctorprofileevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='doctorprofileevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofileevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='core_policy_single'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('follow_up_discount_percent__gte', 0), ('follow_up_discount_percent__lte', 100)), name='core_policy_follow_up_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('session_idle_minutes__gte', 5), ('session_idle_minutes__lte', 1440)), name='core_policy_session_idle_range'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_policyevent" ("allow_partial_payment", "default_pay_first", "discount_limit_percent", "follow_up_discount_percent", "follow_up_window_days", "id", "perform_first_roles", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "session_idle_minutes", "updated_at") VALUES (NEW."allow_partial_payment", NEW."default_pay_first", NEW."discount_limit_percent", NEW."follow_up_discount_percent", NEW."follow_up_window_days", NEW."id", NEW."perform_first_roles", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."session_idle_minutes", NEW."updated_at"); RETURN NULL;', hash='13c93df5ffce6796059887e3ada2f4770caac73b', operation='INSERT', pgid='pgtrigger_insert_insert_9bcd2', table='core_policy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_policyevent" ("allow_partial_payment", "default_pay_first", "discount_limit_percent", "follow_up_discount_percent", "follow_up_window_days", "id", "perform_first_roles", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "session_idle_minutes", "updated_at") VALUES (NEW."allow_partial_payment", NEW."default_pay_first", NEW."discount_limit_percent", NEW."follow_up_discount_percent", NEW."follow_up_window_days", NEW."id", NEW."perform_first_roles", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."session_idle_minutes", NEW."updated_at"); RETURN NULL;', hash='720dbb69335f4364ed354bffee0c7426529eebaa', operation='UPDATE', pgid='pgtrigger_update_update_2cbb2', table='core_policy', when='AFTER')),
        ),
        migrations.AddField(
            model_name='policyevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='policyevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.policy'),
        ),
        migrations.AddConstraint(
            model_name='reasoncode',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='core_reasoncode_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reasoncode',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_reasoncodeevent" ("active", "category", "code", "id", "label_ar", "label_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requires_note", "sort_order") VALUES (NEW."active", NEW."category", NEW."code", NEW."id", NEW."label_ar", NEW."label_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requires_note", NEW."sort_order"); RETURN NULL;', hash='9fc6445e8175271b5bfac717d74c76ef1a0cb5c6', operation='INSERT', pgid='pgtrigger_insert_insert_214d8', table='core_reasoncode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reasoncode',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_reasoncodeevent" ("active", "category", "code", "id", "label_ar", "label_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requires_note", "sort_order") VALUES (NEW."active", NEW."category", NEW."code", NEW."id", NEW."label_ar", NEW."label_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requires_note", NEW."sort_order"); RETURN NULL;', hash='d6a3ca0a39590e07863ae5dc420c5c283a0daad3', operation='UPDATE', pgid='pgtrigger_update_update_1fa44', table='core_reasoncode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reasoncode',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_reasoncodeevent" ("active", "category", "code", "id", "label_ar", "label_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requires_note", "sort_order") VALUES (OLD."active", OLD."category", OLD."code", OLD."id", OLD."label_ar", OLD."label_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."requires_note", OLD."sort_order"); RETURN NULL;', hash='5327dba741e33d0440b634da71a54a168dcabbe0', operation='DELETE', pgid='pgtrigger_delete_delete_b1fc8', table='core_reasoncode', when='AFTER')),
        ),
        migrations.AddField(
            model_name='reasoncodeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='reasoncodeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.reasoncode'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='role',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_roleevent" ("code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='48d9d876fde6d8ee93e760f2145761d9a75d5093', operation='INSERT', pgid='pgtrigger_insert_insert_9f0d5', table='core_role', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='role',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_roleevent" ("code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='75b3fd59b252237564aea62253b2bab4af982287', operation='UPDATE', pgid='pgtrigger_update_update_b1fe6', table='core_role', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='role',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_roleevent" ("code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."code", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='fa8bc239b492afb38052602bb5944de8cef3b66f', operation='DELETE', pgid='pgtrigger_delete_delete_ed3d7', table='core_role', when='AFTER')),
        ),
        migrations.AddField(
            model_name='roleevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='roleevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='core.role'),
        ),
        migrations.AddField(
            model_name='rolepermissionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='rolepermissionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.rolepermission'),
        ),
        migrations.AddField(
            model_name='rolepermissionevent',
            name='role',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.role'),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.department'),
        ),
        migrations.AddField(
            model_name='roomevent',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='roomevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='roomevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.room'),
        ),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.UniqueConstraint(fields=('code', 'year'), name='core_sequence_unique'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_users', to='core.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='core.UserRole', to='core.role'),
        ),
        migrations.AddField(
            model_name='userroleevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='userroleevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.userrole'),
        ),
        migrations.AddField(
            model_name='userroleevent',
            name='role',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.role'),
        ),
        migrations.AddField(
            model_name='userroleevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='authevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='da0dbb96c3d49f3c1b0172f4c08611bef9968c19', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_28d14', table='core_authevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='centerprofileevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d4556f5fb935dcf74271a71bde21d6cc4bb49c45', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_90b27', table='core_centerprofileevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='departmentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='cb443e273dc1fbf0558946a580193fb5ae0a2445', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e4cee', table='core_departmentevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorprofile',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_doctorprofileevent" ("active", "department_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "specialty_ar", "specialty_en", "user_id") VALUES (NEW."active", NEW."department_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."specialty_ar", NEW."specialty_en", NEW."user_id"); RETURN NULL;', hash='90e71b0ca78981d818da977d22eee4b2e7fe40f2', operation='INSERT', pgid='pgtrigger_insert_insert_bf06f', table='core_doctorprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorprofile',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_doctorprofileevent" ("active", "department_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "specialty_ar", "specialty_en", "user_id") VALUES (NEW."active", NEW."department_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."specialty_ar", NEW."specialty_en", NEW."user_id"); RETURN NULL;', hash='ca4fe486014304d7f4cc0d1198cdfa2c42813a97', operation='UPDATE', pgid='pgtrigger_update_update_e3d00', table='core_doctorprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorprofile',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_doctorprofileevent" ("active", "department_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "specialty_ar", "specialty_en", "user_id") VALUES (OLD."active", OLD."department_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."specialty_ar", OLD."specialty_en", OLD."user_id"); RETURN NULL;', hash='2d468a5271c084c4bda5546ea51a28366c1256d8', operation='DELETE', pgid='pgtrigger_delete_delete_8134a', table='core_doctorprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorprofileevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='98a0575e5e6d47330a533b6717b50ddf56fc53c5', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b7c5e', table='core_doctorprofileevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='core_notif_user_read_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policyevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='dcf43549c6e65e8ef10968da915923f52e2aba33', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e0e82', table='core_policyevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reasoncodeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='dd98257e2bf7431c8217153db5d7bc45ce435de9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_72761', table='core_reasoncodeevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='roleevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='54dd678cae291d3fe6a2d0c1c461f65a5d88207a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b571b', table='core_roleevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'code'), name='core_rolepermission_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rolepermission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_rolepermissionevent" ("allowed", "code", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "updated_at") VALUES (NEW."allowed", NEW."code", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."updated_at"); RETURN NULL;', hash='b5a9fed22d93d30ad33c8864fb7d9e2d6fb67bff', operation='INSERT', pgid='pgtrigger_insert_insert_5eeae', table='core_rolepermission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rolepermission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_rolepermissionevent" ("allowed", "code", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "updated_at") VALUES (NEW."allowed", NEW."code", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_id", NEW."updated_at"); RETURN NULL;', hash='1ef0f7dd46b8a1c4c6eadaa0bfd46232177b41fd', operation='UPDATE', pgid='pgtrigger_update_update_d368f', table='core_rolepermission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rolepermission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_rolepermissionevent" ("allowed", "code", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "updated_at") VALUES (OLD."allowed", OLD."code", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role_id", OLD."updated_at"); RETURN NULL;', hash='64865a4e4394309c8a9a5d857908f22d7eac30ae', operation='DELETE', pgid='pgtrigger_delete_delete_9a3e1', table='core_rolepermission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rolepermissionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='08a636587f87cb6f7d69ba7fadc976b58b12fbc7', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_6a8c8', table='core_rolepermissionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='room',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_roomevent" ("active", "code", "department_id", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."code", NEW."department_id", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='c52d2d321ae34330f2193c4e55ae9b9efe8820bf', operation='INSERT', pgid='pgtrigger_insert_insert_46786', table='core_room', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='room',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_roomevent" ("active", "code", "department_id", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."code", NEW."department_id", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='4355004b08dc2e03fa5200e4b14e2d19b28c5130', operation='UPDATE', pgid='pgtrigger_update_update_a9fa7', table='core_room', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='room',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_roomevent" ("active", "code", "department_id", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."active", OLD."code", OLD."department_id", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='cd0d4cd646a6b44b2c2ab6d1915368bbd667c0dc', operation='DELETE', pgid='pgtrigger_delete_delete_430c5', table='core_room', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='roomevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='1a06a9c56817177ad3c28d094bbaa63ae09e34af', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d3a29', table='core_roomevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6c831c7829668854425dc56f04bf5cdb370a36ff', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_1b55a', table='core_userevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='core_userrole_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userrole',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_userroleevent" ("created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "user_id") VALUES (NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."user_id"); RETURN NULL;', hash='79daeef310c675ea84730f33997bb64d11a3c065', operation='INSERT', pgid='pgtrigger_insert_insert_f0109', table='core_userrole', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userrole',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_userroleevent" ("created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "user_id") VALUES (OLD."created_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role_id", OLD."user_id"); RETURN NULL;', hash='e271ea4dbecc2965064278a4b74374a5be959bfc', operation='DELETE', pgid='pgtrigger_delete_delete_f7990', table='core_userrole', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_userevent" ("date_joined", "email", "first_name", "full_name_ar", "full_name_en", "id", "is_active", "is_staff", "is_superuser", "language", "last_name", "must_change_password", "password_changed_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "theme", "username") VALUES (NEW."date_joined", NEW."email", NEW."first_name", NEW."full_name_ar", NEW."full_name_en", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."language", NEW."last_name", NEW."must_change_password", NEW."password_changed_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."theme", NEW."username"); RETURN NULL;', hash='efc64713f9880cb0c4b24fe2834cdfa5362ecc96', operation='INSERT', pgid='pgtrigger_insert_insert_45de6', table='core_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."date_joined" IS DISTINCT FROM (NEW."date_joined") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."full_name_ar" IS DISTINCT FROM (NEW."full_name_ar") OR OLD."full_name_en" IS DISTINCT FROM (NEW."full_name_en") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."language" IS DISTINCT FROM (NEW."language") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."must_change_password" IS DISTINCT FROM (NEW."must_change_password") OR OLD."password_changed_at" IS DISTINCT FROM (NEW."password_changed_at") OR OLD."phone" IS DISTINCT FROM (NEW."phone") OR OLD."theme" IS DISTINCT FROM (NEW."theme") OR OLD."username" IS DISTINCT FROM (NEW."username"))', func='INSERT INTO "core_userevent" ("date_joined", "email", "first_name", "full_name_ar", "full_name_en", "id", "is_active", "is_staff", "is_superuser", "language", "last_name", "must_change_password", "password_changed_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "theme", "username") VALUES (NEW."date_joined", NEW."email", NEW."first_name", NEW."full_name_ar", NEW."full_name_en", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."language", NEW."last_name", NEW."must_change_password", NEW."password_changed_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."theme", NEW."username"); RETURN NULL;', hash='850f625199e169e125f0ab3025515c849e8b4381', operation='UPDATE', pgid='pgtrigger_update_update_6ccff', table='core_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='userroleevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='470b2e390a437c1111097b3a7f2edf9e215f3c8a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c7580', table='core_userroleevent', when='BEFORE')),
        ),
    ]
