# Generated by Django 5.2.17 on 2026-10-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_roles_and_singletons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='kind',
            field=models.CharField(choices=[('login_success', 'Login succeeded'), ('login_failed', 'Login failed'), ('login_locked', 'Login refused: account locked'), ('account_locked', 'Account locked after repeated failures'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('password_change_failed', 'Password change rejected'), ('login_throttled', 'Login refused: too many failures from this address'), ('account_unlocked', 'Account unlocked by an administrator')], max_length=30),
        ),
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('ip', 'Failed logins per client address'), ('username', 'Failed logins for a username that does not exist')], max_length=10)),
                ('key', models.CharField(max_length=150)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='core_throttle_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='core_loginthrottle_unique')],
            },
        ),
    ]
