# Generated by Django 5.2.17 on 2026-10-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_login_throttle_and_auth_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'العربية'), ('en', 'English')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('warm', 'Warm')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'العربية'), ('en', 'English')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('warm', 'Warm')], default='', max_length=10),
        ),
    ]
