# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0005_search_functions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasoncode',
            options={'ordering': ['category', 'sort_order', 'code'], 'verbose_name': 'reason code'},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='doctorprofile',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='doctorprofile',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='doctorprofile',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_service',
            field=models.ForeignKey(blank=True, help_text="Consultation fee service (kind 'consultation') for visits with this doctor.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_doctors', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='doctorprofileevent',
            name='consultation_service',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Consultation fee service (kind 'consultation') for visits with this doctor.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service'),
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='category',
            field=models.CharField(choices=[('line_cancel', 'Service line cancellation'), ('visit_cancel', 'Visit cancellation'), ('discount', 'Discount or exemption'), ('refund', 'Refund'), ('credit_note', 'Credit note'), ('stock_adjust', 'Stock adjustment'), ('variance', 'Shift cash variance'), ('override', 'Supervisor override'), ('writeoff', 'Payer rejection: rebill or write off'), ('perform_first', 'Perform-first authorization'), ('transfer_reject', 'Bank transfer rejection'), ('result_amend', 'Lab result amendment'), ('sample_reject', 'Lab sample rejection')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='reasoncodeevent',
            name='category',
            field=models.CharField(choices=[('line_cancel', 'Service line cancellation'), ('visit_cancel', 'Visit cancellation'), ('discount', 'Discount or exemption'), ('refund', 'Refund'), ('credit_note', 'Credit note'), ('stock_adjust', 'Stock adjustment'), ('variance', 'Shift cash variance'), ('override', 'Supervisor override'), ('writeoff', 'Payer rejection: rebill or write off'), ('perform_first', 'Perform-first authorization'), ('transfer_reject', 'Bank transfer rejection'), ('result_amend', 'Lab result amendment'), ('sample_reject', 'Lab sample rejection')], max_length=40),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorprofile',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_doctorprofileevent" ("active", "consultation_service_id", "department_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "specialty_ar", "specialty_en", "user_id") VALUES (NEW."active", NEW."consultation_service_id", NEW."department_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."specialty_ar", NEW."specialty_en", NEW."user_id"); RETURN NULL;', hash='8ab6ee2f5c9ca5de388c0f9713a8099a8215a77e', operation='INSERT', pgid='pgtrigger_insert_insert_bf06f', table='core_doctorprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorprofile',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_doctorprofileevent" ("active", "consultation_service_id", "department_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "specialty_ar", "specialty_en", "user_id") VALUES (NEW."active", NEW."consultation_service_id", NEW."department_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."specialty_ar", NEW."specialty_en", NEW."user_id"); RETURN NULL;', hash='0ed28c19c7dbf15ab674698d2ded390ffe25b914', operation='UPDATE', pgid='pgtrigger_update_update_e3d00', table='core_doctorprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorprofile',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_doctorprofileevent" ("active", "consultation_service_id", "department_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "specialty_ar", "specialty_en", "user_id") VALUES (OLD."active", OLD."consultation_service_id", OLD."department_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."specialty_ar", OLD."specialty_en", OLD."user_id"); RETURN NULL;', hash='d6d8ef86c064103d8d766b45f31f7b56db3a52e3', operation='DELETE', pgid='pgtrigger_delete_delete_8134a', table='core_doctorprofile', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='reasoncode',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['line_cancel', 'visit_cancel', 'discount', 'refund', 'credit_note', 'stock_adjust', 'variance', 'override', 'writeoff', 'perform_first', 'transfer_reject', 'result_amend', 'sample_reject'])), name='core_reasoncode_category_valid'),
        ),
    ]
