# Generated by Django 5.2.17 on 2026-10-07 16:57

import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_reason_codes'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('prescription', 'Prescription'), ('lab_result', 'Lab result'), ('claim_export', 'Claim export'), ('shift_report', 'Shift report')], max_length=20)),
                ('paper', models.CharField(choices=[('a4', 'A4'), ('thermal_80', 'Thermal 80 mm')], default='a4', max_length=20)),
                ('show_logo', models.BooleanField(default=True)),
                ('header_ar', models.TextField(blank=True)),
                ('header_en', models.TextField(blank=True)),
                ('footer_ar', models.TextField(blank=True)),
                ('footer_en', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'print template',
                'ordering': ['document', 'paper'],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplateEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('document', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('prescription', 'Prescription'), ('lab_result', 'Lab result'), ('claim_export', 'Claim export'), ('shift_report', 'Shift report')], max_length=20)),
                ('paper', models.CharField(choices=[('a4', 'A4'), ('thermal_80', 'Thermal 80 mm')], default='a4', max_length=20)),
                ('show_logo', models.BooleanField(default=True)),
                ('header_ar', models.TextField(blank=True)),
                ('header_en', models.TextField(blank=True)),
                ('footer_ar', models.TextField(blank=True)),
                ('footer_en', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='policy',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='policy',
            name='update_update',
        ),
        migrations.AddField(
            model_name='policy',
            name='partial_dispense_remainder',
            field=models.CharField(choices=[('defer', 'Keep it open to dispense later'), ('refund', 'Cancel it and refund the patient')], default='defer', help_text='Default for the undispensed rest of a line when stock runs short (FLOW 6).', max_length=10),
        ),
        migrations.AddField(
            model_name='policy',
            name='pending_transfer_alert_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Alert verifiers about transfers pending longer than this (FEATURES 0.13).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='policy',
            name='show_estimated_cost',
            field=models.BooleanField(default=False, help_text='Doctors with the permission may see an estimated cost of orders (3.8).'),
        ),
        migrations.AddField(
            model_name='policyevent',
            name='partial_dispense_remainder',
            field=models.CharField(choices=[('defer', 'Keep it open to dispense later'), ('refund', 'Cancel it and refund the patient')], default='defer', help_text='Default for the undispensed rest of a line when stock runs short (FLOW 6).', max_length=10),
        ),
        migrations.AddField(
            model_name='policyevent',
            name='pending_transfer_alert_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Alert verifiers about transfers pending longer than this (FEATURES 0.13).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='policyevent',
            name='show_estimated_cost',
            field=models.BooleanField(default=False, help_text='Doctors with the permission may see an estimated cost of orders (3.8).'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='default_pay_first',
            field=models.BooleanField(default=True, help_text='Always on: perform-first needs an authorization (invariant 1).'),
        ),
        migrations.AlterField(
            model_name='policyevent',
            name='default_pay_first',
            field=models.BooleanField(default=True, help_text='Always on: perform-first needs an authorization (invariant 1).'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_policyevent" ("allow_partial_payment", "default_pay_first", "discount_limit_percent", "follow_up_discount_percent", "follow_up_window_days", "id", "partial_dispense_remainder", "pending_transfer_alert_days", "perform_first_roles", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "session_idle_minutes", "show_estimated_cost", "updated_at") VALUES (NEW."allow_partial_payment", NEW."default_pay_first", NEW."discount_limit_percent", NEW."follow_up_discount_percent", NEW."follow_up_window_days", NEW."id", NEW."partial_dispense_remainder", NEW."pending_transfer_alert_days", NEW."perform_first_roles", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."session_idle_minutes", NEW."show_estimated_cost", NEW."updated_at"); RETURN NULL;', hash='3fd940a41526fc1ab849ea98d770da8c5e175764', operation='INSERT', pgid='pgtrigger_insert_insert_9bcd2', table='core_policy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_policyevent" ("allow_partial_payment", "default_pay_first", "discount_limit_percent", "follow_up_discount_percent", "follow_up_window_days", "id", "partial_dispense_remainder", "pending_transfer_alert_days", "perform_first_roles", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "session_idle_minutes", "show_estimated_cost", "updated_at") VALUES (NEW."allow_partial_payment", NEW."default_pay_first", NEW."discount_limit_percent", NEW."follow_up_discount_percent", NEW."follow_up_window_days", NEW."id", NEW."partial_dispense_remainder", NEW."pending_transfer_alert_days", NEW."perform_first_roles", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."session_idle_minutes", NEW."show_estimated_cost", NEW."updated_at"); RETURN NULL;', hash='b4f076af6a6289b349be476f78a98f606c1b763f', operation='UPDATE', pgid='pgtrigger_update_update_2cbb2', table='core_policy', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('default_pay_first', True)), name='core_policy_pay_first_always'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('pending_transfer_alert_days__gte', 1), ('pending_transfer_alert_days__lte', 90)), name='core_policy_transfer_alert_range'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('partial_dispense_remainder__in', ['defer', 'refund'])), name='core_policy_partial_dispense_valid'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.UniqueConstraint(fields=('document', 'paper'), name='core_printtemplate_one_per_paper'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('document__in', ['invoice', 'receipt', 'prescription', 'lab_result', 'claim_export', 'shift_report'])), name='core_printtemplate_document_valid'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('paper__in', ['a4', 'thermal_80'])), name='core_printtemplate_paper_valid'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='printtemplate',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_printtemplateevent" ("active", "document", "footer_ar", "footer_en", "header_ar", "header_en", "id", "paper", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "show_logo", "updated_at") VALUES (NEW."active", NEW."document", NEW."footer_ar", NEW."footer_en", NEW."header_ar", NEW."header_en", NEW."id", NEW."paper", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."show_logo", NEW."updated_at"); RETURN NULL;', hash='480114ce4f57d9cc6cc8fe6202fa5d4fcbd81a0c', operation='INSERT', pgid='pgtrigger_insert_insert_cf81f', table='core_printtemplate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='printtemplate',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_printtemplateevent" ("active", "document", "footer_ar", "footer_en", "header_ar", "header_en", "id", "paper", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "show_logo", "updated_at") VALUES (NEW."active", NEW."document", NEW."footer_ar", NEW."footer_en", NEW."header_ar", NEW."header_en", NEW."id", NEW."paper", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."show_logo", NEW."updated_at"); RETURN NULL;', hash='2ad788f09b7345f583fe591b857ebbc3dfa80f24', operation='UPDATE', pgid='pgtrigger_update_update_4094f', table='core_printtemplate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='printtemplate',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_printtemplateevent" ("active", "document", "footer_ar", "footer_en", "header_ar", "header_en", "id", "paper", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "show_logo", "updated_at") VALUES (OLD."active", OLD."document", OLD."footer_ar", OLD."footer_en", OLD."header_ar", OLD."header_en", OLD."id", OLD."paper", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."show_logo", OLD."updated_at"); RETURN NULL;', hash='e502fc68a61cab5077ed4af9b100a84223cefe84', operation='DELETE', pgid='pgtrigger_delete_delete_4bc7a', table='core_printtemplate', when='AFTER')),
        ),
        migrations.AddField(
            model_name='printtemplateevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='printtemplateevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.printtemplate'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='printtemplateevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6a8216aebb4eb02b87c1ff315f85e60d31ae0662', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_5d347', table='core_printtemplateevent', when='BEFORE')),
        ),
    ]
