# Generated by Django 5.2.17 on 2026-10-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_printtemplate_printtemplateevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='kind',
            field=models.CharField(choices=[('login_success', 'Login succeeded'), ('login_failed', 'Login failed'), ('login_locked', 'Login refused: account locked'), ('account_locked', 'Account locked after repeated failures'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('password_change_failed', 'Password change rejected'), ('login_throttled', 'Login refused: too many failures from this address'), ('account_unlocked', 'Account unlocked by an administrator'), ('password_reset', 'Password reset by an administrator')], max_length=30),
        ),
    ]
