# Generated by Django 5.2.17 on 2026-10-08 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_authevent_password_reset"),
        ("core", "0009_reason_categories_merge_appointment"),
    ]

    operations = []
