# Generated by Django 5.2.17 on 2026-10-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_wave_a_admin_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('user', 'key'), name='core_notification_key_once'),
        ),
    ]
