# Generated by Django 5.2.17 on 2026-10-10 10:04

"""Reason category for admissions made in error (FEATURES 10.5, invariant 4, ADR 0018).

Seeds its default codes: a frozen copy of the matching rows of
``apps.core.reason_codes.REASON_CODES`` (``apps/core/tests/test_seeds.py`` keeps them in
sync). Existing rows are left alone so a center's edits survive.
"""

from django.db import migrations, models

REASON_CODES = [
    ('admission_cancel', 'WRONG_PATIENT', 'تنويم مريض آخر بالخطأ', 'Wrong patient admitted', False),
    ('admission_cancel', 'NOT_ADMITTED', 'المريض لم يُنوَّم', 'Patient was not admitted', False),
    ('admission_cancel', 'DUPLICATE_ADMISSION', 'تنويم مكرر', 'Admitted twice', False),
    ('admission_cancel', 'OTHER', 'سبب آخر', 'Other', True),
]

# Sort orders continue after the codes seeded by 0007 and 0009.
FIRST_SORT_ORDER = 90


def seed(apps, schema_editor):
    ReasonCode = apps.get_model("core", "ReasonCode")
    for order, (category, code, label_ar, label_en, requires_note) in enumerate(REASON_CODES):
        ReasonCode.objects.get_or_create(
            category=category,
            code=code,
            defaults={
                "label_ar": label_ar,
                "label_en": label_en,
                "requires_note": requires_note,
                "sort_order": FIRST_SORT_ORDER + order,
            },
        )


def unseed(apps, schema_editor):
    # Reason codes are referenced by documents; leave them in place when migrating backwards.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reasoncode',
            name='core_reasoncode_category_valid',
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='category',
            field=models.CharField(choices=[('line_cancel', 'Service line cancellation'), ('visit_cancel', 'Visit cancellation'), ('discount', 'Discount or exemption'), ('refund', 'Refund'), ('credit_note', 'Credit note'), ('stock_adjust', 'Stock adjustment'), ('variance', 'Shift cash variance'), ('override', 'Supervisor override'), ('writeoff', 'Payer rejection: rebill or write off'), ('perform_first', 'Perform-first authorization'), ('transfer_reject', 'Bank transfer rejection'), ('result_amend', 'Lab result amendment'), ('sample_reject', 'Lab sample rejection'), ('patient_merge', 'Patient file merge'), ('appointment_cancel', 'Appointment cancellation'), ('admission_cancel', 'Admission made in error')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='reasoncodeevent',
            name='category',
            field=models.CharField(choices=[('line_cancel', 'Service line cancellation'), ('visit_cancel', 'Visit cancellation'), ('discount', 'Discount or exemption'), ('refund', 'Refund'), ('credit_note', 'Credit note'), ('stock_adjust', 'Stock adjustment'), ('variance', 'Shift cash variance'), ('override', 'Supervisor override'), ('writeoff', 'Payer rejection: rebill or write off'), ('perform_first', 'Perform-first authorization'), ('transfer_reject', 'Bank transfer rejection'), ('result_amend', 'Lab result amendment'), ('sample_reject', 'Lab sample rejection'), ('patient_merge', 'Patient file merge'), ('appointment_cancel', 'Appointment cancellation'), ('admission_cancel', 'Admission made in error')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='reasoncode',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['line_cancel', 'visit_cancel', 'discount', 'refund', 'credit_note', 'stock_adjust', 'variance', 'override', 'writeoff', 'perform_first', 'transfer_reject', 'result_amend', 'sample_reject', 'patient_merge', 'appointment_cancel', 'admission_cancel'])), name='core_reasoncode_category_valid'),
        ),
        migrations.RunPython(seed, unseed),
    ]
