# Generated by Django 5.2.17 on 2026-10-10 11:41

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_display_role'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='policy',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='policy',
            name='update_update',
        ),
        migrations.AddField(
            model_name='policy',
            name='claims_second_approver',
            field=models.BooleanField(default=True, help_text='Rebills and write-offs of payer rejections need a second person besides the recording user (FEATURES 11.5, ADR 0018).'),
        ),
        migrations.AddField(
            model_name='policyevent',
            name='claims_second_approver',
            field=models.BooleanField(default=True, help_text='Rebills and write-offs of payer rejections need a second person besides the recording user (FEATURES 11.5, ADR 0018).'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_policyevent" ("allow_partial_payment", "claims_second_approver", "default_pay_first", "discount_limit_percent", "follow_up_discount_percent", "follow_up_window_days", "id", "partial_dispense_remainder", "pending_transfer_alert_days", "perform_first_roles", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "session_idle_minutes", "show_estimated_cost", "updated_at") VALUES (NEW."allow_partial_payment", NEW."claims_second_approver", NEW."default_pay_first", NEW."discount_limit_percent", NEW."follow_up_discount_percent", NEW."follow_up_window_days", NEW."id", NEW."partial_dispense_remainder", NEW."pending_transfer_alert_days", NEW."perform_first_roles", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."session_idle_minutes", NEW."show_estimated_cost", NEW."updated_at"); RETURN NULL;', hash='b387ddc80e1557edf657fca75acf9e1b0621c3f7', operation='INSERT', pgid='pgtrigger_insert_insert_9bcd2', table='core_policy', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='policy',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_policyevent" ("allow_partial_payment", "claims_second_approver", "default_pay_first", "discount_limit_percent", "follow_up_discount_percent", "follow_up_window_days", "id", "partial_dispense_remainder", "pending_transfer_alert_days", "perform_first_roles", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "session_idle_minutes", "show_estimated_cost", "updated_at") VALUES (NEW."allow_partial_payment", NEW."claims_second_approver", NEW."default_pay_first", NEW."discount_limit_percent", NEW."follow_up_discount_percent", NEW."follow_up_window_days", NEW."id", NEW."partial_dispense_remainder", NEW."pending_transfer_alert_days", NEW."perform_first_roles", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."session_idle_minutes", NEW."show_estimated_cost", NEW."updated_at"); RETURN NULL;', hash='431c263f024e8c472edfef5d5135003bb35bc842', operation='UPDATE', pgid='pgtrigger_update_update_2cbb2', table='core_policy', when='AFTER')),
        ),
    ]
