# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_reason_categories_consultation_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformAuthorizationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('insurance_approval', 'Insurance approval'), ('emergency', 'Emergency'), ('credit_account', 'Approved credit account'), ('other', 'Other')], max_length=30)),
                ('reason_note', models.TextField(blank=True)),
                ('approval_reference', models.CharField(blank=True, help_text='Payer pre-approval or credit account reference.', max_length=100)),
                ('authorized_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(help_text="As written, e.g. '500 mg' or '1 tablet'.", max_length=60)),
                ('dose_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Base units per dose, when computable.', max_digits=14, null=True)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('rectal', 'Rectal'), ('ophthalmic', 'Eye'), ('otic', 'Ear'), ('nasal', 'Nasal'), ('other', 'Other')], default='oral', max_length=20)),
                ('frequency_code', models.CharField(blank=True, help_text='e.g. OD, BID, TID.', max_length=20)),
                ('frequency_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('as_needed', models.BooleanField(default=False)),
                ('instructions', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'prescription detail',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetailEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('dose', models.CharField(help_text="As written, e.g. '500 mg' or '1 tablet'.", max_length=60)),
                ('dose_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Base units per dose, when computable.', max_digits=14, null=True)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('rectal', 'Rectal'), ('ophthalmic', 'Eye'), ('otic', 'Ear'), ('nasal', 'Nasal'), ('other', 'Other')], default='oral', max_length=20)),
                ('frequency_code', models.CharField(blank=True, help_text='e.g. OD, BID, TID.', max_length=20)),
                ('frequency_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('as_needed', models.BooleanField(default=False)),
                ('instructions', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], help_text='Copy of service.kind at order time.', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('pre_approval_ref', models.CharField(blank=True, max_length=100)),
                ('order_source', models.CharField(choices=[('consultation_fee', 'Consultation fee (automatic)'), ('doctor', 'Doctor order'), ('reception', 'Reception'), ('nurse', 'Nurse'), ('bed_charge', 'Daily bed charge'), ('pharmacy_sale', 'Walk-in pharmacy sale')], default='doctor', max_length=20)),
                ('order_note', models.CharField(blank=True, max_length=500)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('billing_status', models.CharField(choices=[('unbilled', 'Not invoiced'), ('invoiced', 'Invoiced'), ('settled', 'Settled'), ('credited', 'Credited')], default='unbilled', max_length=20)),
                ('fulfilment_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('performed', 'Performed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('performed_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity actually performed (partial dispense).', max_digits=14, null=True)),
                ('performed_note', models.CharField(blank=True, max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'service line',
                'ordering': ['visit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], help_text='Copy of service.kind at order time.', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('pre_approval_ref', models.CharField(blank=True, max_length=100)),
                ('order_source', models.CharField(choices=[('consultation_fee', 'Consultation fee (automatic)'), ('doctor', 'Doctor order'), ('reception', 'Reception'), ('nurse', 'Nurse'), ('bed_charge', 'Daily bed charge'), ('pharmacy_sale', 'Walk-in pharmacy sale')], default='doctor', max_length=20)),
                ('order_note', models.CharField(blank=True, max_length=500)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('billing_status', models.CharField(choices=[('unbilled', 'Not invoiced'), ('invoiced', 'Invoiced'), ('settled', 'Settled'), ('credited', 'Credited')], default='unbilled', max_length=20)),
                ('fulfilment_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('performed', 'Performed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('performed_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity actually performed (partial dispense).', max_digits=14, null=True)),
                ('performed_note', models.CharField(blank=True, max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('insurance_approval', 'Insurance approval'), ('emergency', 'Emergency'), ('credit_account', 'Approved credit account'), ('other', 'Other')], max_length=30)),
                ('reason_note', models.TextField(blank=True)),
                ('approval_reference', models.CharField(blank=True, help_text='Payer pre-approval or credit account reference.', max_length=100)),
                ('authorized_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_note', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason_code', models.ForeignKey(limit_choices_to={'category': 'perform_first'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perform-first authorization',
                'ordering': ['-authorized_at', '-id'],
            },
        ),
    ]
