# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0006_reason_categories_consultation_service'),
        ('orders', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performauthorization',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perform_authorizations', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='performauthorizationevent',
            name='authorized_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performauthorizationevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='performauthorizationevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='orders.performauthorization'),
        ),
        migrations.AddField(
            model_name='performauthorizationevent',
            name='reason_code',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'category': 'perform_first'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='performauthorizationevent',
            name='requested_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performauthorizationevent',
            name='revoked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performauthorizationevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='prescriptiondetailevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='prescriptiondetailevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='orders.prescriptiondetail'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.performauthorization'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'line_cancel'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Performing department at order time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='core.department'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='payer',
            field=models.ForeignKey(blank=True, help_text='Payer this line will be billed to; empty = the patient pays (cash).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='catalog.payer'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_lines', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='prescriptiondetailevent',
            name='line',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.serviceline'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='orders.serviceline'),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='authorization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.performauthorization'),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'line_cancel'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Performing department at order time.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='ordered_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='payer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Payer this line will be billed to; empty = the patient pays (cash).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.payer'),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='orders.serviceline'),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='service',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='started_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicelineevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='performauthorization',
            index=models.Index(fields=['authorized_at'], name='orders_auth_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='performauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['insurance_approval', 'emergency', 'credit_account', 'other'])), name='orders_authorization_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='performauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', False), _connector='OR'), name='orders_authorization_revoke_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='performauthorization',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "orders_performauthorizationevent" ("approval_reference", "authorized_at", "authorized_by_id", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "requested_by_id", "revoke_note", "revoked_at", "revoked_by_id", "visit_id") VALUES (NEW."approval_reference", NEW."authorized_at", NEW."authorized_by_id", NEW."id", NEW."kind", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason_code_id", NEW."reason_note", NEW."requested_by_id", NEW."revoke_note", NEW."revoked_at", NEW."revoked_by_id", NEW."visit_id"); RETURN NULL;', hash='b507161e000eee199c95f104733a4ad0f4deb2d0', operation='INSERT', pgid='pgtrigger_insert_insert_d27c8', table='orders_performauthorization', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='performauthorization',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "orders_performauthorizationevent" ("approval_reference", "authorized_at", "authorized_by_id", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "requested_by_id", "revoke_note", "revoked_at", "revoked_by_id", "visit_id") VALUES (NEW."approval_reference", NEW."authorized_at", NEW."authorized_by_id", NEW."id", NEW."kind", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason_code_id", NEW."reason_note", NEW."requested_by_id", NEW."revoke_note", NEW."revoked_at", NEW."revoked_by_id", NEW."visit_id"); RETURN NULL;', hash='f1cdc6aad41d6aae27ab02b87d6bc8fd094522ec', operation='UPDATE', pgid='pgtrigger_update_update_6d919', table='orders_performauthorization', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='performauthorization',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "orders_performauthorizationevent" ("approval_reference", "authorized_at", "authorized_by_id", "id", "kind", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "requested_by_id", "revoke_note", "revoked_at", "revoked_by_id", "visit_id") VALUES (OLD."approval_reference", OLD."authorized_at", OLD."authorized_by_id", OLD."id", OLD."kind", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reason_code_id", OLD."reason_note", OLD."requested_by_id", OLD."revoke_note", OLD."revoked_at", OLD."revoked_by_id", OLD."visit_id"); RETURN NULL;', hash='0a84b64c34d3dc1129813dca9eb067961a6a6c25', operation='DELETE', pgid='pgtrigger_delete_delete_21537', table='orders_performauthorization', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='performauthorizationevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='04720c388ef9b8e74240e392d2518eb86023a321', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4cef5', table='orders_performauthorizationevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(condition=models.Q(('fulfilment_status__in', ['pending', 'in_progress'])), fields=['kind', 'department', 'billing_status'], name='orders_line_worklist_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['billing_status', 'ordered_at'], name='orders_line_billing_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['fulfilment_status', 'performed_at'], name='orders_line_performed_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['consultation', 'lab', 'procedure', 'drug', 'consumable', 'bed'])), name='orders_line_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(('billing_status__in', ['unbilled', 'invoiced', 'settled', 'credited'])), name='orders_line_billing_valid'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilment_status__in', ['pending', 'in_progress', 'performed', 'cancelled'])), name='orders_line_fulfilment_valid'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(('order_source__in', ['consultation_fee', 'doctor', 'reception', 'nurse', 'bed_charge', 'pharmacy_sale'])), name='orders_line_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orders_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(('performed_quantity__isnull', True), models.Q(('performed_quantity__gte', 0), ('performed_quantity__lte', models.F('quantity'))), _connector='OR'), name='orders_line_performed_qty_range'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fulfilment_status', 'cancelled'), _negated=True), models.Q(('cancel_reason__isnull', False), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False)), _connector='OR'), name='orders_line_cancel_documented'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fulfilment_status', 'performed'), _negated=True), models.Q(('performed_at__isnull', False), ('performed_by__isnull', False)), _connector='OR'), name='orders_line_performed_documented'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fulfilment_status', 'in_progress'), _negated=True), ('started_at__isnull', False), _connector='OR'), name='orders_line_started_documented'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(('billing_status', 'unbilled'), ('invoiced_at__isnull', False), _connector='OR'), name='orders_line_invoiced_has_time'),
        ),
        migrations.AddConstraint(
            model_name='serviceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_status', 'credited'), _negated=True), ('credited_at__isnull', False), _connector='OR'), name='orders_line_credited_has_time'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='serviceline',
            trigger=pgtrigger.compiler.Trigger(name='line_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n    IF TG_OP = 'DELETE' THEN\n        RAISE EXCEPTION 'LINE_NOT_DELETABLE: service line % cannot be deleted; cancel it',\n            OLD.id;\n    END IF;\n    IF TG_OP = 'UPDATE' THEN\n        IF OLD.fulfilment_status IN ('performed', 'cancelled')\n           AND NEW.fulfilment_status IS DISTINCT FROM OLD.fulfilment_status THEN\n            RAISE EXCEPTION 'LINE_TERMINAL: service line % is already %',\n                OLD.id, OLD.fulfilment_status;\n        END IF;\n        IF NEW.billing_status IS DISTINCT FROM OLD.billing_status AND NOT (\n            (OLD.billing_status = 'unbilled' AND NEW.billing_status IN ('invoiced', 'settled'))\n            OR (OLD.billing_status = 'invoiced' AND NEW.billing_status IN ('settled', 'credited'))\n            OR (OLD.billing_status = 'settled' AND NEW.billing_status IN ('invoiced', 'credited'))\n        ) THEN\n            RAISE EXCEPTION 'LINE_BILLING_TRANSITION: service line % cannot go from % to %',\n                OLD.id, OLD.billing_status, NEW.billing_status;\n        END IF;\n    END IF;\n    IF NEW.fulfilment_status IN ('in_progress', 'performed')\n       AND (TG_OP = 'INSERT' OR NEW.fulfilment_status IS DISTINCT FROM OLD.fulfilment_status)\n       AND NEW.billing_status <> 'settled'\n       AND NOT EXISTS (\n           SELECT 1 FROM orders_performauthorization a\n           WHERE a.id = NEW.authorization_id AND a.revoked_at IS NULL\n       ) THEN\n        RAISE EXCEPTION\n            'LINE_NOT_ELIGIBLE: service line % is neither settled nor authorized to perform',\n            NEW.id;\n    END IF;\n    RETURN NEW;\n", hash='cb5adf90dae0f6eea595f7a2d71df4753064873d', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_line_guard_6e979', table='orders_serviceline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='serviceline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "orders_servicelineevent" ("authorization_id", "billing_status", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "credited_at", "department_id", "fulfilment_status", "id", "invoiced_at", "kind", "order_note", "order_source", "ordered_at", "ordered_by_id", "payer_id", "performed_at", "performed_by_id", "performed_note", "performed_quantity", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "quantity", "service_id", "settled_at", "started_at", "started_by_id", "updated_at", "visit_id") VALUES (NEW."authorization_id", NEW."billing_status", NEW."cancel_note", NEW."cancel_reason_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."credited_at", NEW."department_id", NEW."fulfilment_status", NEW."id", NEW."invoiced_at", NEW."kind", NEW."order_note", NEW."order_source", NEW."ordered_at", NEW."ordered_by_id", NEW."payer_id", NEW."performed_at", NEW."performed_by_id", NEW."performed_note", NEW."performed_quantity", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pre_approval_ref", NEW."quantity", NEW."service_id", NEW."settled_at", NEW."started_at", NEW."started_by_id", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='ef70f1945d8054f805f8a0a5f7a5b8034bfcf05f', operation='INSERT', pgid='pgtrigger_insert_insert_d3560', table='orders_serviceline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='serviceline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "orders_servicelineevent" ("authorization_id", "billing_status", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "credited_at", "department_id", "fulfilment_status", "id", "invoiced_at", "kind", "order_note", "order_source", "ordered_at", "ordered_by_id", "payer_id", "performed_at", "performed_by_id", "performed_note", "performed_quantity", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "quantity", "service_id", "settled_at", "started_at", "started_by_id", "updated_at", "visit_id") VALUES (NEW."authorization_id", NEW."billing_status", NEW."cancel_note", NEW."cancel_reason_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."credited_at", NEW."department_id", NEW."fulfilment_status", NEW."id", NEW."invoiced_at", NEW."kind", NEW."order_note", NEW."order_source", NEW."ordered_at", NEW."ordered_by_id", NEW."payer_id", NEW."performed_at", NEW."performed_by_id", NEW."performed_note", NEW."performed_quantity", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pre_approval_ref", NEW."quantity", NEW."service_id", NEW."settled_at", NEW."started_at", NEW."started_by_id", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='82bfd108c48ccf10081ee30569dc1c288e5cf282', operation='UPDATE', pgid='pgtrigger_update_update_e8e2f', table='orders_serviceline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='serviceline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "orders_servicelineevent" ("authorization_id", "billing_status", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "credited_at", "department_id", "fulfilment_status", "id", "invoiced_at", "kind", "order_note", "order_source", "ordered_at", "ordered_by_id", "payer_id", "performed_at", "performed_by_id", "performed_note", "performed_quantity", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "quantity", "service_id", "settled_at", "started_at", "started_by_id", "updated_at", "visit_id") VALUES (OLD."authorization_id", OLD."billing_status", OLD."cancel_note", OLD."cancel_reason_id", OLD."cancelled_at", OLD."cancelled_by_id", OLD."credited_at", OLD."department_id", OLD."fulfilment_status", OLD."id", OLD."invoiced_at", OLD."kind", OLD."order_note", OLD."order_source", OLD."ordered_at", OLD."ordered_by_id", OLD."payer_id", OLD."performed_at", OLD."performed_by_id", OLD."performed_note", OLD."performed_quantity", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pre_approval_ref", OLD."quantity", OLD."service_id", OLD."settled_at", OLD."started_at", OLD."started_by_id", OLD."updated_at", OLD."visit_id"); RETURN NULL;', hash='3356228e57c4a77f0db285ee7924e304239ed9e7', operation='DELETE', pgid='pgtrigger_delete_delete_61aae', table='orders_serviceline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prescriptiondetailevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='cc15e99ff14a8fd1b538b645e1b55698fc90e665', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_66a16', table='orders_prescriptiondetailevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondetail',
            constraint=models.CheckConstraint(condition=models.Q(('route__in', ['oral', 'iv', 'im', 'sc', 'topical', 'inhaled', 'rectal', 'ophthalmic', 'otic', 'nasal', 'other'])), name='orders_prescription_route_valid'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondetail',
            constraint=models.CheckConstraint(condition=models.Q(('dose_quantity__isnull', True), ('dose_quantity__gt', 0), _connector='OR'), name='orders_prescription_dose_positive'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondetail',
            constraint=models.CheckConstraint(condition=models.Q(('frequency_per_day__isnull', True), ('frequency_per_day__gt', 0), _connector='OR'), name='orders_prescription_frequency_positive'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prescriptiondetail',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "orders_prescriptiondetailevent" ("as_needed", "dose", "dose_quantity", "duration_days", "frequency_code", "frequency_per_day", "id", "instructions", "line_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route") VALUES (NEW."as_needed", NEW."dose", NEW."dose_quantity", NEW."duration_days", NEW."frequency_code", NEW."frequency_per_day", NEW."id", NEW."instructions", NEW."line_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."route"); RETURN NULL;', hash='a4815d112af5d586cbe99eb93d3e810e9ac06c70', operation='INSERT', pgid='pgtrigger_insert_insert_1ea28', table='orders_prescriptiondetail', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prescriptiondetail',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "orders_prescriptiondetailevent" ("as_needed", "dose", "dose_quantity", "duration_days", "frequency_code", "frequency_per_day", "id", "instructions", "line_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route") VALUES (NEW."as_needed", NEW."dose", NEW."dose_quantity", NEW."duration_days", NEW."frequency_code", NEW."frequency_per_day", NEW."id", NEW."instructions", NEW."line_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."route"); RETURN NULL;', hash='632aa123946213d26c58e12c20780b7a8736f77e', operation='UPDATE', pgid='pgtrigger_update_update_cc6e2', table='orders_prescriptiondetail', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prescriptiondetail',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "orders_prescriptiondetailevent" ("as_needed", "dose", "dose_quantity", "duration_days", "frequency_code", "frequency_per_day", "id", "instructions", "line_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "route") VALUES (OLD."as_needed", OLD."dose", OLD."dose_quantity", OLD."duration_days", OLD."frequency_code", OLD."frequency_per_day", OLD."id", OLD."instructions", OLD."line_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."route"); RETURN NULL;', hash='ff370a7fa1f0951086246464b5a499b25bbe9327', operation='DELETE', pgid='pgtrigger_delete_delete_c8a9b', table='orders_prescriptiondetail', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='servicelineevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='ad85cd27b0889090028a04ddaaa5c43a4280937a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b0cfc', table='orders_servicelineevent', when='BEFORE')),
        ),
    ]
