# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(blank=True, help_text='Assigned at approval.', max_length=30, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('void', 'Void')], default='draft', max_length=10)),
                ('reason_note', models.TextField(blank=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payer_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('patient_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payer_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('patient_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cancels_service_line', models.BooleanField(default=False, help_text='The credited service line is also cancelled (not performed).')),
                ('frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'credit note line',
                'ordering': ['credit_note', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('line_no', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payer_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('patient_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cancels_service_line', models.BooleanField(default=False, help_text='The credited service line is also cancelled (not performed).')),
                ('frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Assigned at approval.', max_length=30, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('void', 'Void')], default='draft', max_length=10)),
                ('priced_on', models.DateField(blank=True, help_text='Date whose price list versions priced the lines.', null=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payer_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('patient_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'invoice',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(blank=True, help_text='Assigned at approval.', max_length=30, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('void', 'Void')], default='draft', max_length=10)),
                ('priced_on', models.DateField(blank=True, help_text='Date whose price list versions priced the lines.', null=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payer_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('patient_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], max_length=20)),
                ('description_ar', models.CharField(max_length=200)),
                ('description_en', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_note', models.CharField(blank=True, max_length=500)),
                ('excluded', models.BooleanField(default=False, help_text='A payer exclusion routed this line 100% to the patient.')),
                ('payer_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('patient_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pre_approval_ref', models.CharField(blank=True, max_length=100)),
                ('frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'invoice line',
                'ordering': ['invoice', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('line_no', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], max_length=20)),
                ('description_ar', models.CharField(max_length=200)),
                ('description_en', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_note', models.CharField(blank=True, max_length=500)),
                ('excluded', models.BooleanField(default=False, help_text='A payer exclusion routed this line 100% to the patient.')),
                ('payer_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('patient_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pre_approval_ref', models.CharField(blank=True, max_length=100)),
                ('frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Assigned at approval.', max_length=30, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('void', 'Void')], default='draft', max_length=10)),
                ('reason_note', models.TextField(blank=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payer_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('patient_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_note', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credit note',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
