# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('catalog', '0001_initial'),
        ('core', '0006_reason_categories_consultation_service'),
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnoteevent',
            name='invoice',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceevent',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceevent',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceevent',
            name='patient',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='invoiceevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='invoiceevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceevent',
            name='visit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='invoiceevent',
            name='voided_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='coverage_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.coveragerule'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='discount_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'discount'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.payer'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='price_list_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.pricelistversion'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='service_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='orders.serviceline'),
        ),
        migrations.AddField(
            model_name='creditnotelineevent',
            name='invoice_line',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.invoiceline'),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='invoice_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_lines', to='billing.invoiceline'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='coverage_rule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.coveragerule'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='discount_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'discount'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='invoice',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='payer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.payer'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.invoiceline'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='price_list_version',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.pricelistversion'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='service',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='service_line',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.serviceline'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['visit', 'status'], name='billing_invoice_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', 'status'], name='billing_invoice_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'approved_at'], name='billing_invoice_approved_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'void'])), name='billing_invoice_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('gross_total__gte', 0), ('discount_total__gte', 0), ('payer_total__gte', 0), ('patient_total__gte', 0)), name='billing_invoice_totals_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('patient_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_total'), '-', models.F('discount_total')), '-', models.F('payer_total')))), name='billing_invoice_totals_balance'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('number__isnull', False), ('priced_on__isnull', False)), _connector='OR'), name='billing_invoice_approval_documented'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), _negated=True), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_note', ''), _negated=True)), _connector='OR'), name='billing_invoice_void_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoice',
            trigger=pgtrigger.compiler.Trigger(name='invoice_frozen', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'approved\', \'void\'))', func="RAISE EXCEPTION 'INVOICE_FROZEN: approved or void invoices never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='8eb479519620d8e1e77f77ec4b917d285e02d989', operation='UPDATE OR DELETE', pgid='pgtrigger_invoice_frozen_805c9', table='billing_invoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoice',
            trigger=pgtrigger.compiler.Trigger(name='invoice_consistent', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NEW."status" = \'approved\')', constraint='CONSTRAINT', declare='DECLARE n_lines integer; n_unfrozen integer; s_gross numeric; s_discount numeric; s_payer numeric; s_patient numeric;', func="\n        SELECT count(*), count(*) FILTER (WHERE NOT l.frozen),\n               coalesce(sum(l.gross), 0), coalesce(sum(l.discount), 0),\n               coalesce(sum(l.payer_share), 0), coalesce(sum(l.patient_share), 0)\n          INTO n_lines, n_unfrozen, s_gross, s_discount, s_payer, s_patient\n          FROM billing_invoiceline l WHERE l.invoice_id = NEW.id;\n        IF n_lines = 0 THEN\n            RAISE EXCEPTION 'INVOICE_EMPTY: approved % has no lines', NEW.id;\n        END IF;\n        IF n_unfrozen > 0 THEN\n            RAISE EXCEPTION 'INVOICE_LINES_NOT_FROZEN: approved % has % unfrozen lines',\n                NEW.id, n_unfrozen;\n        END IF;\n        IF s_gross <> NEW.gross_total OR s_discount <> NEW.discount_total\n           OR s_payer <> NEW.payer_total OR s_patient <> NEW.patient_total THEN\n            RAISE EXCEPTION 'INVOICE_TOTALS_MISMATCH: totals of % differ from its lines',\n                NEW.id;\n        END IF;\n        \n        RETURN NULL;\n    ", hash='e1f6760acbdde3ab5eccb9e654fbeb0f4c1bcc9e', operation='INSERT OR UPDATE', pgid='pgtrigger_invoice_consistent_a7692', table='billing_invoice', timing='DEFERRABLE INITIALLY DEFERRED', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoice',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_invoiceevent" ("approved_at", "approved_by_id", "created_at", "created_by_id", "discount_total", "gross_total", "id", "note", "number", "patient_id", "patient_total", "payer_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priced_on", "status", "updated_at", "visit_id", "void_note", "voided_at", "voided_by_id") VALUES (NEW."approved_at", NEW."approved_by_id", NEW."created_at", NEW."created_by_id", NEW."discount_total", NEW."gross_total", NEW."id", NEW."note", NEW."number", NEW."patient_id", NEW."patient_total", NEW."payer_total", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priced_on", NEW."status", NEW."updated_at", NEW."visit_id", NEW."void_note", NEW."voided_at", NEW."voided_by_id"); RETURN NULL;', hash='fc52ff6f87406ffe3295d90b3595ef6c8f9a0eca', operation='INSERT', pgid='pgtrigger_insert_insert_0c624', table='billing_invoice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoice',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_invoiceevent" ("approved_at", "approved_by_id", "created_at", "created_by_id", "discount_total", "gross_total", "id", "note", "number", "patient_id", "patient_total", "payer_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priced_on", "status", "updated_at", "visit_id", "void_note", "voided_at", "voided_by_id") VALUES (NEW."approved_at", NEW."approved_by_id", NEW."created_at", NEW."created_by_id", NEW."discount_total", NEW."gross_total", NEW."id", NEW."note", NEW."number", NEW."patient_id", NEW."patient_total", NEW."payer_total", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priced_on", NEW."status", NEW."updated_at", NEW."visit_id", NEW."void_note", NEW."voided_at", NEW."voided_by_id"); RETURN NULL;', hash='9a9997d7471a82d5f48b8ff4ca9125b789b1bfd9', operation='UPDATE', pgid='pgtrigger_update_update_28c43', table='billing_invoice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoice',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_invoiceevent" ("approved_at", "approved_by_id", "created_at", "created_by_id", "discount_total", "gross_total", "id", "note", "number", "patient_id", "patient_total", "payer_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priced_on", "status", "updated_at", "visit_id", "void_note", "voided_at", "voided_by_id") VALUES (OLD."approved_at", OLD."approved_by_id", OLD."created_at", OLD."created_by_id", OLD."discount_total", OLD."gross_total", OLD."id", OLD."note", OLD."number", OLD."patient_id", OLD."patient_total", OLD."payer_total", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."priced_on", OLD."status", OLD."updated_at", OLD."visit_id", OLD."void_note", OLD."voided_at", OLD."voided_by_id"); RETURN NULL;', hash='75289bd5e885b39ba49d8e3df1b1108099291a49', operation='DELETE', pgid='pgtrigger_delete_delete_6493d', table='billing_invoice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6fd2eae24bbec402bf9d99e99abd7e914a7e759e', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_969e8', table='billing_creditnoteevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['invoice', 'status'], name='billing_cn_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['patient', 'status'], name='billing_cn_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['status', 'approved_at'], name='billing_cn_approved_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'void'])), name='billing_creditnote_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('gross_total__gte', 0), ('discount_total__gte', 0), ('payer_total__gte', 0), ('patient_total__gte', 0)), name='billing_creditnote_totals_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('patient_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_total'), '-', models.F('discount_total')), '-', models.F('payer_total')))), name='billing_creditnote_totals_balance'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('number__isnull', False)), _connector='OR'), name='billing_creditnote_approval_documented'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), _negated=True), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_note', ''), _negated=True)), _connector='OR'), name='billing_creditnote_void_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnote',
            trigger=pgtrigger.compiler.Trigger(name='credit_note_frozen', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'approved\', \'void\'))', func="RAISE EXCEPTION 'CREDIT_NOTE_FROZEN: approved or void credit notes never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='5557069e8bea71faf52d0ab7c51bb08b5addc11a', operation='UPDATE OR DELETE', pgid='pgtrigger_credit_note_frozen_048d8', table='billing_creditnote', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnote',
            trigger=pgtrigger.compiler.Trigger(name='credit_note_consistent', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NEW."status" = \'approved\')', constraint='CONSTRAINT', declare='DECLARE n_lines integer; n_unfrozen integer; s_gross numeric; s_discount numeric; s_payer numeric; s_patient numeric;', func="\n        SELECT count(*), count(*) FILTER (WHERE NOT l.frozen),\n               coalesce(sum(l.gross), 0), coalesce(sum(l.discount), 0),\n               coalesce(sum(l.payer_share), 0), coalesce(sum(l.patient_share), 0)\n          INTO n_lines, n_unfrozen, s_gross, s_discount, s_payer, s_patient\n          FROM billing_creditnoteline l WHERE l.credit_note_id = NEW.id;\n        IF n_lines = 0 THEN\n            RAISE EXCEPTION 'CREDIT_NOTE_EMPTY: approved % has no lines', NEW.id;\n        END IF;\n        IF n_unfrozen > 0 THEN\n            RAISE EXCEPTION 'CREDIT_NOTE_LINES_NOT_FROZEN: approved % has % unfrozen lines',\n                NEW.id, n_unfrozen;\n        END IF;\n        IF s_gross <> NEW.gross_total OR s_discount <> NEW.discount_total\n           OR s_payer <> NEW.payer_total OR s_patient <> NEW.patient_total THEN\n            RAISE EXCEPTION 'CREDIT_NOTE_TOTALS_MISMATCH: totals of % differ from its lines',\n                NEW.id;\n        END IF;\n        \n        IF EXISTS (\n            SELECT 1\n              FROM billing_creditnoteline cl\n              JOIN billing_invoiceline il ON il.id = cl.invoice_line_id\n             WHERE cl.invoice_line_id IN (\n                       SELECT x.invoice_line_id FROM billing_creditnoteline x\n                        WHERE x.credit_note_id = NEW.id)\n               AND cl.frozen\n             GROUP BY il.id, il.quantity, il.gross, il.discount, il.payer_share, il.patient_share\n            HAVING sum(cl.quantity) > il.quantity OR sum(cl.gross) > il.gross\n                OR sum(cl.discount) > il.discount OR sum(cl.payer_share) > il.payer_share\n                OR sum(cl.patient_share) > il.patient_share\n        ) THEN\n            RAISE EXCEPTION 'CREDIT_EXCEEDS_INVOICE: credit note % credits more than invoiced',\n                NEW.id;\n        END IF;\n        IF EXISTS (\n            SELECT 1 FROM billing_creditnoteline cl\n              JOIN billing_invoiceline il ON il.id = cl.invoice_line_id\n             WHERE cl.credit_note_id = NEW.id AND il.invoice_id <> NEW.invoice_id\n        ) THEN\n            RAISE EXCEPTION 'CREDIT_WRONG_INVOICE: credit note % credits another invoice', NEW.id;\n        END IF;\n\n        RETURN NULL;\n    ", hash='d518b66a0582e7788c180c034d9d4e3544d6aee3', operation='INSERT OR UPDATE', pgid='pgtrigger_credit_note_consistent_c1a51', table='billing_creditnote', timing='DEFERRABLE INITIALLY DEFERRED', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnote',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_creditnoteevent" ("approved_at", "approved_by_id", "created_at", "created_by_id", "discount_total", "gross_total", "id", "invoice_id", "number", "patient_id", "patient_total", "payer_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "status", "updated_at", "void_note", "voided_at", "voided_by_id") VALUES (NEW."approved_at", NEW."approved_by_id", NEW."created_at", NEW."created_by_id", NEW."discount_total", NEW."gross_total", NEW."id", NEW."invoice_id", NEW."number", NEW."patient_id", NEW."patient_total", NEW."payer_total", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason_code_id", NEW."reason_note", NEW."status", NEW."updated_at", NEW."void_note", NEW."voided_at", NEW."voided_by_id"); RETURN NULL;', hash='809d246a3664e80a2f48677a347ebf07593201ad', operation='INSERT', pgid='pgtrigger_insert_insert_5150e', table='billing_creditnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnote',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_creditnoteevent" ("approved_at", "approved_by_id", "created_at", "created_by_id", "discount_total", "gross_total", "id", "invoice_id", "number", "patient_id", "patient_total", "payer_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "status", "updated_at", "void_note", "voided_at", "voided_by_id") VALUES (NEW."approved_at", NEW."approved_by_id", NEW."created_at", NEW."created_by_id", NEW."discount_total", NEW."gross_total", NEW."id", NEW."invoice_id", NEW."number", NEW."patient_id", NEW."patient_total", NEW."payer_total", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason_code_id", NEW."reason_note", NEW."status", NEW."updated_at", NEW."void_note", NEW."voided_at", NEW."voided_by_id"); RETURN NULL;', hash='9f597f476732c5d226301b3ae6297e52689ad2ae', operation='UPDATE', pgid='pgtrigger_update_update_685f3', table='billing_creditnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnote',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_creditnoteevent" ("approved_at", "approved_by_id", "created_at", "created_by_id", "discount_total", "gross_total", "id", "invoice_id", "number", "patient_id", "patient_total", "payer_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "status", "updated_at", "void_note", "voided_at", "voided_by_id") VALUES (OLD."approved_at", OLD."approved_by_id", OLD."created_at", OLD."created_by_id", OLD."discount_total", OLD."gross_total", OLD."id", OLD."invoice_id", OLD."number", OLD."patient_id", OLD."patient_total", OLD."payer_total", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reason_code_id", OLD."reason_note", OLD."status", OLD."updated_at", OLD."void_note", OLD."voided_at", OLD."voided_by_id"); RETURN NULL;', hash='84d50c85d3a0c2bca6355aa3534e5877d05a2442', operation='DELETE', pgid='pgtrigger_delete_delete_19a71', table='billing_creditnote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='05b718cad763793ddb677bf941071b79bc8029ff', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d262c', table='billing_invoiceevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['payer', 'frozen'], name='billing_invline_payer_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['consultation', 'lab', 'procedure', 'drug', 'consumable', 'bed'])), name='billing_invoiceline_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billing_invoiceline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('gross__gte', 0), ('discount__gte', 0), ('payer_share__gte', 0), ('patient_share__gte', 0)), name='billing_invoiceline_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('patient_share', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross'), '-', models.F('discount')), '-', models.F('payer_share')))), name='billing_invoiceline_shares_balance'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='billing_invoiceline_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('gross', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), 2))), name='billing_invoiceline_gross_is_qty_times_price'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('payer__isnull', False), ('payer_share', 0), _connector='OR'), name='billing_invoiceline_cash_has_no_payer_share'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('discount', 0), models.Q(('discount_approved_by__isnull', False), ('discount_reason__isnull', False)), _connector='OR'), name='billing_invoiceline_discount_documented'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('frozen', False), ('price_list_version__isnull', False), _connector='OR'), name='billing_invoiceline_frozen_has_price_version'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_no'), name='billing_invoiceline_line_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(condition=models.Q(('frozen', True)), fields=('service_line',), name='billing_invoiceline_service_line_billed_once'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='line_frozen', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."frozen")', func="RAISE EXCEPTION 'INVOICE_FROZEN: frozen invoice lines never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='adb91a8c28b3838d5277c986f37ce2f8fafa92c8', operation='UPDATE OR DELETE', pgid='pgtrigger_line_frozen_cbb22', table='billing_invoiceline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='line_needs_draft_invoice', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM billing_invoice p WHERE p.id = OLD.invoice_id AND p.status = 'draft'\n            ) AND EXISTS (SELECT 1 FROM billing_invoice p WHERE p.id = OLD.invoice_id) THEN\n                RAISE EXCEPTION 'INVOICE_FROZEN: parent % of % row is locked', OLD.invoice_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM billing_invoice p WHERE p.id = NEW.invoice_id AND p.status = 'draft'\n            ) THEN\n                RAISE EXCEPTION 'INVOICE_FROZEN: parent % of % row is locked', NEW.invoice_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='d850fcfb59946e990cb87fb4dbf3879738c147b0', operation='INSERT', pgid='pgtrigger_line_needs_draft_invoice_556fd', table='billing_invoiceline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_invoicelineevent" ("coverage_rule_id", "created_at", "department_id", "description_ar", "description_en", "discount", "discount_approved_by_id", "discount_note", "discount_reason_id", "excluded", "frozen", "gross", "id", "invoice_id", "kind", "line_no", "patient_share", "payer_id", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "price_list_version_id", "quantity", "service_id", "service_line_id", "unit_price") VALUES (NEW."coverage_rule_id", NEW."created_at", NEW."department_id", NEW."description_ar", NEW."description_en", NEW."discount", NEW."discount_approved_by_id", NEW."discount_note", NEW."discount_reason_id", NEW."excluded", NEW."frozen", NEW."gross", NEW."id", NEW."invoice_id", NEW."kind", NEW."line_no", NEW."patient_share", NEW."payer_id", NEW."payer_share", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pre_approval_ref", NEW."price_list_version_id", NEW."quantity", NEW."service_id", NEW."service_line_id", NEW."unit_price"); RETURN NULL;', hash='e814be0eb14f7405e8fdc76e56716e979473018d', operation='INSERT', pgid='pgtrigger_insert_insert_8c429', table='billing_invoiceline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_invoicelineevent" ("coverage_rule_id", "created_at", "department_id", "description_ar", "description_en", "discount", "discount_approved_by_id", "discount_note", "discount_reason_id", "excluded", "frozen", "gross", "id", "invoice_id", "kind", "line_no", "patient_share", "payer_id", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "price_list_version_id", "quantity", "service_id", "service_line_id", "unit_price") VALUES (NEW."coverage_rule_id", NEW."created_at", NEW."department_id", NEW."description_ar", NEW."description_en", NEW."discount", NEW."discount_approved_by_id", NEW."discount_note", NEW."discount_reason_id", NEW."excluded", NEW."frozen", NEW."gross", NEW."id", NEW."invoice_id", NEW."kind", NEW."line_no", NEW."patient_share", NEW."payer_id", NEW."payer_share", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pre_approval_ref", NEW."price_list_version_id", NEW."quantity", NEW."service_id", NEW."service_line_id", NEW."unit_price"); RETURN NULL;', hash='ab0011c6675991bb9bad104385c34284affbbc91', operation='UPDATE', pgid='pgtrigger_update_update_c2b22', table='billing_invoiceline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_invoicelineevent" ("coverage_rule_id", "created_at", "department_id", "description_ar", "description_en", "discount", "discount_approved_by_id", "discount_note", "discount_reason_id", "excluded", "frozen", "gross", "id", "invoice_id", "kind", "line_no", "patient_share", "payer_id", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "price_list_version_id", "quantity", "service_id", "service_line_id", "unit_price") VALUES (OLD."coverage_rule_id", OLD."created_at", OLD."department_id", OLD."description_ar", OLD."description_en", OLD."discount", OLD."discount_approved_by_id", OLD."discount_note", OLD."discount_reason_id", OLD."excluded", OLD."frozen", OLD."gross", OLD."id", OLD."invoice_id", OLD."kind", OLD."line_no", OLD."patient_share", OLD."payer_id", OLD."payer_share", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pre_approval_ref", OLD."price_list_version_id", OLD."quantity", OLD."service_id", OLD."service_line_id", OLD."unit_price"); RETURN NULL;', hash='4ff32e8498688e9261135a3e553e61721bb75581', operation='DELETE', pgid='pgtrigger_delete_delete_7184d', table='billing_invoiceline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnotelineevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='adf9325bbec5d161a9ac839436dc3a26b25f9e37', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_861c0', table='billing_creditnotelineevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='creditnoteline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billing_creditnoteline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditnoteline',
            constraint=models.CheckConstraint(condition=models.Q(('gross__gte', 0), ('discount__gte', 0), ('payer_share__gte', 0), ('patient_share__gte', 0)), name='billing_creditnoteline_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='creditnoteline',
            constraint=models.CheckConstraint(condition=models.Q(('patient_share', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross'), '-', models.F('discount')), '-', models.F('payer_share')))), name='billing_creditnoteline_shares_balance'),
        ),
        migrations.AddConstraint(
            model_name='creditnoteline',
            constraint=models.UniqueConstraint(fields=('credit_note', 'line_no'), name='billing_creditnoteline_line_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='creditnoteline',
            constraint=models.UniqueConstraint(fields=('credit_note', 'invoice_line'), name='billing_creditnoteline_invoice_line_once'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteline',
            trigger=pgtrigger.compiler.Trigger(name='line_frozen', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."frozen")', func="RAISE EXCEPTION 'CREDIT_NOTE_FROZEN: frozen credit note lines never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='b16f6e6935240547bc547b3ef8bd2c82f930e7c3', operation='UPDATE OR DELETE', pgid='pgtrigger_line_frozen_89e9f', table='billing_creditnoteline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteline',
            trigger=pgtrigger.compiler.Trigger(name='line_needs_draft_credit_note', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM billing_creditnote p WHERE p.id = OLD.credit_note_id AND p.status = 'draft'\n            ) AND EXISTS (SELECT 1 FROM billing_creditnote p WHERE p.id = OLD.credit_note_id) THEN\n                RAISE EXCEPTION 'CREDIT_NOTE_FROZEN: parent % of % row is locked', OLD.credit_note_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM billing_creditnote p WHERE p.id = NEW.credit_note_id AND p.status = 'draft'\n            ) THEN\n                RAISE EXCEPTION 'CREDIT_NOTE_FROZEN: parent % of % row is locked', NEW.credit_note_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='f55fa77050b8c07b19626f77ac0e31011d50b5c3', operation='INSERT', pgid='pgtrigger_line_needs_draft_credit_note_c5a4c', table='billing_creditnoteline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_creditnotelineevent" ("cancels_service_line", "created_at", "credit_note_id", "discount", "frozen", "gross", "id", "invoice_line_id", "line_no", "patient_share", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity") VALUES (NEW."cancels_service_line", NEW."created_at", NEW."credit_note_id", NEW."discount", NEW."frozen", NEW."gross", NEW."id", NEW."invoice_line_id", NEW."line_no", NEW."patient_share", NEW."payer_share", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."quantity"); RETURN NULL;', hash='9f103b6e8dbb8b5893ac60af85218d8225b49ec7', operation='INSERT', pgid='pgtrigger_insert_insert_7c157', table='billing_creditnoteline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_creditnotelineevent" ("cancels_service_line", "created_at", "credit_note_id", "discount", "frozen", "gross", "id", "invoice_line_id", "line_no", "patient_share", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity") VALUES (NEW."cancels_service_line", NEW."created_at", NEW."credit_note_id", NEW."discount", NEW."frozen", NEW."gross", NEW."id", NEW."invoice_line_id", NEW."line_no", NEW."patient_share", NEW."payer_share", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."quantity"); RETURN NULL;', hash='b7ea6979400f029211e639cefdd1d5c16e6fecd4', operation='UPDATE', pgid='pgtrigger_update_update_04ccb', table='billing_creditnoteline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_creditnotelineevent" ("cancels_service_line", "created_at", "credit_note_id", "discount", "frozen", "gross", "id", "invoice_line_id", "line_no", "patient_share", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "quantity") VALUES (OLD."cancels_service_line", OLD."created_at", OLD."credit_note_id", OLD."discount", OLD."frozen", OLD."gross", OLD."id", OLD."invoice_line_id", OLD."line_no", OLD."patient_share", OLD."payer_share", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."quantity"); RETURN NULL;', hash='b9a732b9e9a679b43a247fbe09fd03fd09c3a645', operation='DELETE', pgid='pgtrigger_delete_delete_b3eda', table='billing_creditnoteline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoicelineevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='28a67c0d362936d36df9d28de107fc9b54314738', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b8f95', table='billing_invoicelineevent', when='BEFORE')),
        ),
    ]
