# Generated by Django 5.2.17 on 2026-10-07 16:57

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
        ('catalog', '0003_priceitem_item_guard_pricelistversion_version_guard'),
        ('core', '0007_seed_reason_codes'),
        ('orders', '0003_remove_serviceline_line_guard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='creditnote',
            name='credit_note_consistent',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='creditnoteline',
            name='line_needs_draft_credit_note',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='invoiceline',
            name='line_needs_draft_invoice',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='invoiceline',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='invoiceline',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='invoiceline',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set when the discount was given as a percent of the patient share: approval derives the amount from the price effective that day (FEATURES 5.9).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineevent',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set when the discount was given as a percent of the patient share: approval derives the amount from the price effective that day (FEATURES 5.9).', max_digits=5, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnote',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='7fa5bbc968a2034d9fca6d391a3158c520bc0010', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_bb62f', table='billing_creditnote', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnote',
            trigger=pgtrigger.compiler.Trigger(name='credit_note_consistent', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NEW."status" = \'approved\')', constraint='CONSTRAINT', declare='DECLARE n_lines integer; n_unfrozen integer; s_gross numeric; s_discount numeric; s_payer numeric; s_patient numeric;', func="\n        SELECT count(*), count(*) FILTER (WHERE NOT l.frozen),\n               coalesce(sum(l.gross), 0), coalesce(sum(l.discount), 0),\n               coalesce(sum(l.payer_share), 0), coalesce(sum(l.patient_share), 0)\n          INTO n_lines, n_unfrozen, s_gross, s_discount, s_payer, s_patient\n          FROM billing_creditnoteline l WHERE l.credit_note_id = NEW.id;\n        IF n_lines = 0 THEN\n            RAISE EXCEPTION 'CREDIT_NOTE_EMPTY: approved % has no lines', NEW.id;\n        END IF;\n        IF n_unfrozen > 0 THEN\n            RAISE EXCEPTION 'CREDIT_NOTE_LINES_NOT_FROZEN: approved % has % unfrozen lines',\n                NEW.id, n_unfrozen;\n        END IF;\n        IF s_gross <> NEW.gross_total OR s_discount <> NEW.discount_total\n           OR s_payer <> NEW.payer_total OR s_patient <> NEW.patient_total THEN\n            RAISE EXCEPTION 'CREDIT_NOTE_TOTALS_MISMATCH: totals of % differ from its lines',\n                NEW.id;\n        END IF;\n        \n        IF EXISTS (\n            SELECT 1\n              FROM billing_creditnoteline cl\n              JOIN billing_invoiceline il ON il.id = cl.invoice_line_id\n             WHERE cl.invoice_line_id IN (\n                       SELECT x.invoice_line_id FROM billing_creditnoteline x\n                        WHERE x.credit_note_id = NEW.id)\n               AND cl.frozen\n             GROUP BY il.id, il.quantity, il.gross, il.discount, il.payer_share, il.patient_share\n            HAVING sum(cl.quantity) > il.quantity OR sum(cl.gross) > il.gross\n                OR sum(cl.discount) > il.discount OR sum(cl.payer_share) > il.payer_share\n                OR sum(cl.patient_share) > il.patient_share\n        ) THEN\n            RAISE EXCEPTION 'CREDIT_EXCEEDS_INVOICE: credit note % credits more than invoiced',\n                NEW.id;\n        END IF;\n        IF EXISTS (\n            SELECT 1 FROM billing_creditnoteline cl\n              JOIN billing_invoiceline il ON il.id = cl.invoice_line_id\n             WHERE cl.credit_note_id = NEW.id AND il.invoice_id <> NEW.invoice_id\n        ) THEN\n            RAISE EXCEPTION 'CREDIT_WRONG_INVOICE: credit note % credits another invoice', NEW.id;\n        END IF;\n        -- A payer share on a live claim is corrected through the claim (domain.claims).\n        IF EXISTS (\n            SELECT 1 FROM billing_creditnoteline cl\n              JOIN claims_claimline c ON c.invoice_line_id = cl.invoice_line_id\n              JOIN claims_claim k ON k.id = c.claim_id\n             WHERE cl.credit_note_id = NEW.id AND cl.payer_share > 0\n               AND c.status <> 'withdrawn' AND k.status <> 'void'\n        ) THEN\n            RAISE EXCEPTION 'CLAIM_LINE_LOCKED: credit note % credits a claimed payer share',\n                NEW.id;\n        END IF;\n\n        RETURN NULL;\n    ", hash='e8cfc9c663e5fa8ffc1372e6c68ed45ec9d15787', operation='INSERT OR UPDATE', pgid='pgtrigger_credit_note_consistent_c1a51', table='billing_creditnote', timing='DEFERRABLE INITIALLY DEFERRED', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteline',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='858d2d3904b3df55e6425cf0d1f30677fabc15e8', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_f0ea6', table='billing_creditnoteline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteline',
            trigger=pgtrigger.compiler.Trigger(name='line_needs_draft_credit_note', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM billing_creditnote p WHERE p.id = OLD.credit_note_id AND p.status = 'draft'\n            ) AND EXISTS (SELECT 1 FROM billing_creditnote p WHERE p.id = OLD.credit_note_id) THEN\n                RAISE EXCEPTION 'CREDIT_NOTE_FROZEN: parent % of % row is locked', OLD.credit_note_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM billing_creditnote p WHERE p.id = NEW.credit_note_id AND p.status = 'draft'\n            ) THEN\n                RAISE EXCEPTION 'CREDIT_NOTE_FROZEN: parent % of % row is locked', NEW.credit_note_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='6e2d27eac62000d8a721755b0c166b54d53bce9b', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_line_needs_draft_credit_note_c5a4c', table='billing_creditnoteline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='creditnoteline',
            trigger=pgtrigger.compiler.Trigger(name='line_parent_fixed', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."credit_note_id" IS DISTINCT FROM (NEW."credit_note_id") OR OLD."line_no" IS DISTINCT FROM (NEW."line_no") OR OLD."invoice_line_id" IS DISTINCT FROM (NEW."invoice_line_id"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='273bd9cdb126039d38556b20bf62c7f9e41020eb', operation='UPDATE', pgid='pgtrigger_line_parent_fixed_4355f', table='billing_creditnoteline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoice',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='db120730dd4eded10df8bdbff64a1acd6dcd3015', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_77612', table='billing_invoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='7ea1fd3370ca72fd01a9e4fdd752971a4039cb6a', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_f658c', table='billing_invoiceline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='line_needs_draft_invoice', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM billing_invoice p WHERE p.id = OLD.invoice_id AND p.status = 'draft'\n            ) AND EXISTS (SELECT 1 FROM billing_invoice p WHERE p.id = OLD.invoice_id) THEN\n                RAISE EXCEPTION 'INVOICE_FROZEN: parent % of % row is locked', OLD.invoice_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM billing_invoice p WHERE p.id = NEW.invoice_id AND p.status = 'draft'\n            ) THEN\n                RAISE EXCEPTION 'INVOICE_FROZEN: parent % of % row is locked', NEW.invoice_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='fd5c6d3b8b65ee0c8a1152a664cd6afe830be9d9', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_line_needs_draft_invoice_556fd', table='billing_invoiceline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='line_parent_fixed', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."invoice_id" IS DISTINCT FROM (NEW."invoice_id") OR OLD."line_no" IS DISTINCT FROM (NEW."line_no") OR OLD."service_line_id" IS DISTINCT FROM (NEW."service_line_id"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='7fa930278d3f145e8529bad79ed2cda408a3b316', operation='UPDATE', pgid='pgtrigger_line_parent_fixed_2e2ae', table='billing_invoiceline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_invoicelineevent" ("coverage_rule_id", "created_at", "department_id", "description_ar", "description_en", "discount", "discount_approved_by_id", "discount_note", "discount_percent", "discount_reason_id", "excluded", "frozen", "gross", "id", "invoice_id", "kind", "line_no", "patient_share", "payer_id", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "price_list_version_id", "quantity", "service_id", "service_line_id", "unit_price") VALUES (NEW."coverage_rule_id", NEW."created_at", NEW."department_id", NEW."description_ar", NEW."description_en", NEW."discount", NEW."discount_approved_by_id", NEW."discount_note", NEW."discount_percent", NEW."discount_reason_id", NEW."excluded", NEW."frozen", NEW."gross", NEW."id", NEW."invoice_id", NEW."kind", NEW."line_no", NEW."patient_share", NEW."payer_id", NEW."payer_share", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pre_approval_ref", NEW."price_list_version_id", NEW."quantity", NEW."service_id", NEW."service_line_id", NEW."unit_price"); RETURN NULL;', hash='9fb6e8eb0b45930decf96542ddd6864b5da25876', operation='INSERT', pgid='pgtrigger_insert_insert_8c429', table='billing_invoiceline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_invoicelineevent" ("coverage_rule_id", "created_at", "department_id", "description_ar", "description_en", "discount", "discount_approved_by_id", "discount_note", "discount_percent", "discount_reason_id", "excluded", "frozen", "gross", "id", "invoice_id", "kind", "line_no", "patient_share", "payer_id", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "price_list_version_id", "quantity", "service_id", "service_line_id", "unit_price") VALUES (NEW."coverage_rule_id", NEW."created_at", NEW."department_id", NEW."description_ar", NEW."description_en", NEW."discount", NEW."discount_approved_by_id", NEW."discount_note", NEW."discount_percent", NEW."discount_reason_id", NEW."excluded", NEW."frozen", NEW."gross", NEW."id", NEW."invoice_id", NEW."kind", NEW."line_no", NEW."patient_share", NEW."payer_id", NEW."payer_share", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pre_approval_ref", NEW."price_list_version_id", NEW."quantity", NEW."service_id", NEW."service_line_id", NEW."unit_price"); RETURN NULL;', hash='aae99124d1495f16f0ac6d1c0d4e2f600701e147', operation='UPDATE', pgid='pgtrigger_update_update_c2b22', table='billing_invoiceline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='invoiceline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_invoicelineevent" ("coverage_rule_id", "created_at", "department_id", "description_ar", "description_en", "discount", "discount_approved_by_id", "discount_note", "discount_percent", "discount_reason_id", "excluded", "frozen", "gross", "id", "invoice_id", "kind", "line_no", "patient_share", "payer_id", "payer_share", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pre_approval_ref", "price_list_version_id", "quantity", "service_id", "service_line_id", "unit_price") VALUES (OLD."coverage_rule_id", OLD."created_at", OLD."department_id", OLD."description_ar", OLD."description_en", OLD."discount", OLD."discount_approved_by_id", OLD."discount_note", OLD."discount_percent", OLD."discount_reason_id", OLD."excluded", OLD."frozen", OLD."gross", OLD."id", OLD."invoice_id", OLD."kind", OLD."line_no", OLD."patient_share", OLD."payer_id", OLD."payer_share", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pre_approval_ref", OLD."price_list_version_id", OLD."quantity", OLD."service_id", OLD."service_line_id", OLD."unit_price"); RETURN NULL;', hash='9102837ca7c60123b7deec3cf17bfa4823645416', operation='DELETE', pgid='pgtrigger_delete_delete_7184d', table='billing_invoiceline', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), models.Q(('discount_percent__gt', 0), ('discount_percent__lte', 100), ('discount_approved_by__isnull', False), ('discount_reason__isnull', False)), _connector='OR'), name='billing_invoiceline_discount_percent_valid'),
        ),
    ]
