# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_search_functions'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_kind', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], max_length=20)),
                ('rule_kind', models.CharField(choices=[('percentage', 'Payer pays a percentage'), ('copay', 'Patient pays a fixed copay'), ('ceiling', 'Payer pays up to a ceiling')], max_length=20)),
                ('payer_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('copay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ceiling_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('requires_pre_approval', models.BooleanField(default=False, help_text='The line needs a payer pre-approval reference (FEATURES 5.8).')),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'coverage rule',
                'ordering': ['payer', 'service', 'service_kind'],
            },
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_kind', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'coverage exclusion',
                'ordering': ['payer', 'service', 'service_kind'],
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('insurance', 'Insurance company'), ('company', 'Employer or company'), ('government', 'Government scheme'), ('ngo', 'NGO or charity'), ('other', 'Other')], default='insurance', max_length=20)),
                ('contract_no', models.CharField(blank=True, max_length=100)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('claim_period', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('requires_card_number', models.BooleanField(default=True)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'payer',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'price item',
                'ordering': ['version', 'service'],
            },
        ),
        migrations.CreateModel(
            name='PriceListEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=30)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('cash', 'Cash (self-pay)'), ('payer', 'Payer contract')], default='cash', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='The cash list used when a line has no payer list.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceListVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('percent_change', models.DecimalField(blank=True, decimal_places=2, help_text='Bulk change applied to based_on, e.g. 15.00 for +15%.', max_digits=6, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'price list version',
                'ordering': ['price_list', '-effective_from'],
                'get_latest_by': 'effective_from',
            },
        ),
        migrations.CreateModel(
            name='PriceListVersionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('effective_from', models.DateField()),
                ('percent_change', models.DecimalField(blank=True, decimal_places=2, help_text='Bulk change applied to based_on, e.g. 15.00 for +15%.', max_digits=6, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'service',
                'ordering': ['kind', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'service category',
                'verbose_name_plural': 'service categories',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategoryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=30)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExclusionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('service_kind', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='catalog.exclusion')),
                ('payer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.payer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exclusion',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='catalog.payer'),
        ),
        migrations.CreateModel(
            name='CoverageRuleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('service_kind', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], max_length=20)),
                ('rule_kind', models.CharField(choices=[('percentage', 'Payer pays a percentage'), ('copay', 'Patient pays a fixed copay'), ('ceiling', 'Payer pays up to a ceiling')], max_length=20)),
                ('payer_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('copay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ceiling_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('requires_pre_approval', models.BooleanField(default=False, help_text='The line needs a payer pre-approval reference (FEATURES 5.8).')),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='catalog.coveragerule')),
                ('payer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.payer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='catalog.payer'),
        ),
        migrations.CreateModel(
            name='PriceItemEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='catalog.priceitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('cash', 'Cash (self-pay)'), ('payer', 'Payer contract')], default='cash', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='The cash list used when a line has no payer list.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'price list',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['cash', 'payer'])), name='catalog_pricelist_kind_valid'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='catalog_pricelist_one_default'), models.CheckConstraint(condition=models.Q(('is_default', False), models.Q(('active', True), ('kind', 'cash')), _connector='OR'), name='catalog_pricelist_default_is_active_cash')],
            },
        ),
        migrations.CreateModel(
            name='PayerEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=30)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('insurance', 'Insurance company'), ('company', 'Employer or company'), ('government', 'Government scheme'), ('ngo', 'NGO or charity'), ('other', 'Other')], default='insurance', max_length=20)),
                ('contract_no', models.CharField(blank=True, max_length=100)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('claim_period', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('requires_card_number', models.BooleanField(default=True)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='catalog.payer')),
                ('price_list', models.ForeignKey(blank=True, db_constraint=False, help_text='Contract price list; the default cash list when empty.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.pricelist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payer',
            name='price_list',
            field=models.ForeignKey(blank=True, help_text='Contract price list; the default cash list when empty.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payers', to='catalog.pricelist'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelist',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_pricelistevent" ("active", "code", "created_at", "id", "is_default", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."active", NEW."code", NEW."created_at", NEW."id", NEW."is_default", NEW."kind", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='abdf2d5cb9bfa46051e17ac4076d7787b40bdadd', operation='INSERT', pgid='pgtrigger_insert_insert_5a322', table='catalog_pricelist', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelist',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "catalog_pricelistevent" ("active", "code", "created_at", "id", "is_default", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."active", NEW."code", NEW."created_at", NEW."id", NEW."is_default", NEW."kind", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='36d139a4464d3e0c16a9c5d6359b533e7cac9c9c', operation='UPDATE', pgid='pgtrigger_update_update_8ec16', table='catalog_pricelist', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelist',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_pricelistevent" ("active", "code", "created_at", "id", "is_default", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (OLD."active", OLD."code", OLD."created_at", OLD."id", OLD."is_default", OLD."kind", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at"); RETURN NULL;', hash='c1417b6fd78804262fa409b8fc75d19b5c38000c', operation='DELETE', pgid='pgtrigger_delete_delete_adb3c', table='catalog_pricelist', when='AFTER')),
        ),
        migrations.AddField(
            model_name='pricelistevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='pricelistevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='catalog.pricelist'),
        ),
        migrations.AddField(
            model_name='pricelistversion',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_versions', to='catalog.pricelistversion'),
        ),
        migrations.AddField(
            model_name='pricelistversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricelistversion',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.pricelist'),
        ),
        migrations.AddField(
            model_name='priceitemevent',
            name='version',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.pricelistversion'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.pricelistversion'),
        ),
        migrations.AddField(
            model_name='pricelistversionevent',
            name='based_on',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.pricelistversion'),
        ),
        migrations.AddField(
            model_name='pricelistversionevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricelistversionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='pricelistversionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='catalog.pricelistversion'),
        ),
        migrations.AddField(
            model_name='pricelistversionevent',
            name='price_list',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.pricelist'),
        ),
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Performing department (revenue dimension).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.department'),
        ),
        migrations.AddField(
            model_name='priceitemevent',
            name='service',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_items', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='exclusionevent',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='exclusion',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='coverageruleevent',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='coveragerule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='servicecategory',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_servicecategoryevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='913f4a2f1e9fbc79778e079276d7d2d847fad90b', operation='INSERT', pgid='pgtrigger_insert_insert_22048', table='catalog_servicecategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='servicecategory',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "catalog_servicecategoryevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='052f4e176b89fa6549690bf01cc27facdf1bf87d', operation='UPDATE', pgid='pgtrigger_update_update_4e3d2', table='catalog_servicecategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='servicecategory',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_servicecategoryevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (OLD."active", OLD."code", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order"); RETURN NULL;', hash='3b789ad9f4dd427197bf6a80dccf3d509b34c684', operation='DELETE', pgid='pgtrigger_delete_delete_a8376', table='catalog_servicecategory', when='AFTER')),
        ),
        migrations.AddField(
            model_name='servicecategoryevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='servicecategoryevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='catalog.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Performing department (revenue dimension).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='catalog.service'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payerevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='aeeb785ccffe8fe4fafd135b93031b03ca44bc6d', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_eaa02', table='catalog_payerevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['insurance', 'company', 'government', 'ngo', 'other'])), name='catalog_payer_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.CheckConstraint(condition=models.Q(('claim_period__in', ['weekly', 'biweekly', 'monthly', 'quarterly'])), name='catalog_payer_claim_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='payer',
            constraint=models.CheckConstraint(condition=models.Q(('contract_start__isnull', True), ('contract_end__isnull', True), ('contract_end__gte', models.F('contract_start')), _connector='OR'), name='catalog_payer_contract_dates'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_payerevent" ("active", "address", "claim_period", "code", "contact_name", "contract_end", "contract_no", "contract_start", "created_at", "email", "id", "kind", "name_ar", "name_en", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "price_list_id", "requires_card_number", "updated_at") VALUES (NEW."active", NEW."address", NEW."claim_period", NEW."code", NEW."contact_name", NEW."contract_end", NEW."contract_no", NEW."contract_start", NEW."created_at", NEW."email", NEW."id", NEW."kind", NEW."name_ar", NEW."name_en", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."price_list_id", NEW."requires_card_number", NEW."updated_at"); RETURN NULL;', hash='611263774fd3ee36364a5d0459a64e91002cd359', operation='INSERT', pgid='pgtrigger_insert_insert_af0a2', table='catalog_payer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "catalog_payerevent" ("active", "address", "claim_period", "code", "contact_name", "contract_end", "contract_no", "contract_start", "created_at", "email", "id", "kind", "name_ar", "name_en", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "price_list_id", "requires_card_number", "updated_at") VALUES (NEW."active", NEW."address", NEW."claim_period", NEW."code", NEW."contact_name", NEW."contract_end", NEW."contract_no", NEW."contract_start", NEW."created_at", NEW."email", NEW."id", NEW."kind", NEW."name_ar", NEW."name_en", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."price_list_id", NEW."requires_card_number", NEW."updated_at"); RETURN NULL;', hash='530bd8aa7358240ebe1212787668b9d95c5e36a2', operation='UPDATE', pgid='pgtrigger_update_update_22414', table='catalog_payer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payer',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_payerevent" ("active", "address", "claim_period", "code", "contact_name", "contract_end", "contract_no", "contract_start", "created_at", "email", "id", "kind", "name_ar", "name_en", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "price_list_id", "requires_card_number", "updated_at") VALUES (OLD."active", OLD."address", OLD."claim_period", OLD."code", OLD."contact_name", OLD."contract_end", OLD."contract_no", OLD."contract_start", OLD."created_at", OLD."email", OLD."id", OLD."kind", OLD."name_ar", OLD."name_en", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."price_list_id", OLD."requires_card_number", OLD."updated_at"); RETURN NULL;', hash='11f46ffda1eed971681b6805726e56a6d19abf6d', operation='DELETE', pgid='pgtrigger_delete_delete_fcf95', table='catalog_payer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelistevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='86d363697e8af8d6c7d02a8d17c5ccfd83a615b9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_72b16', table='catalog_pricelistevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='pricelistversion',
            constraint=models.UniqueConstraint(fields=('price_list', 'effective_from'), name='catalog_pricelistversion_unique'),
        ),
        migrations.AddConstraint(
            model_name='pricelistversion',
            constraint=models.CheckConstraint(condition=models.Q(('percent_change__isnull', True), ('percent_change__gt', -100), _connector='OR'), name='catalog_pricelistversion_percent_valid'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelistversion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_pricelistversionevent" ("based_on_id", "created_at", "created_by_id", "effective_from", "id", "note", "percent_change", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_list_id") VALUES (NEW."based_on_id", NEW."created_at", NEW."created_by_id", NEW."effective_from", NEW."id", NEW."note", NEW."percent_change", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."price_list_id"); RETURN NULL;', hash='ac0cca8ff11f8c5d5636d8a77a3c4b432b08e507', operation='INSERT', pgid='pgtrigger_insert_insert_50d56', table='catalog_pricelistversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelistversion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "catalog_pricelistversionevent" ("based_on_id", "created_at", "created_by_id", "effective_from", "id", "note", "percent_change", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_list_id") VALUES (NEW."based_on_id", NEW."created_at", NEW."created_by_id", NEW."effective_from", NEW."id", NEW."note", NEW."percent_change", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."price_list_id"); RETURN NULL;', hash='ef363068415f66520ee379d89cf4a5d29cb2620e', operation='UPDATE', pgid='pgtrigger_update_update_c0fb5', table='catalog_pricelistversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelistversion',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_pricelistversionevent" ("based_on_id", "created_at", "created_by_id", "effective_from", "id", "note", "percent_change", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "price_list_id") VALUES (OLD."based_on_id", OLD."created_at", OLD."created_by_id", OLD."effective_from", OLD."id", OLD."note", OLD."percent_change", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."price_list_id"); RETURN NULL;', hash='345719b842402b5e2eda1fa0d3eba1a01986b4a2', operation='DELETE', pgid='pgtrigger_delete_delete_71e07', table='catalog_pricelistversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelistversionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='78113445467a2dc52e527d9be709f5249003f0d0', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e6c1a', table='catalog_pricelistversionevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='priceitemevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='e3686950bb858a48025f2a035b6ed9ef8927a73a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_48b6c', table='catalog_priceitemevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='priceitem',
            index=models.Index(fields=['service', 'version'], name='catalog_priceitem_service_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.UniqueConstraint(fields=('version', 'service'), name='catalog_priceitem_unique'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='catalog_priceitem_price_non_negative'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='priceitem',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_priceitemevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "unit_price", "version_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."service_id", NEW."unit_price", NEW."version_id"); RETURN NULL;', hash='ee249f0b10d81aeaab19fa7869a600a9ecda2607', operation='INSERT', pgid='pgtrigger_insert_insert_30f45', table='catalog_priceitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='priceitem',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "catalog_priceitemevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "unit_price", "version_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."service_id", NEW."unit_price", NEW."version_id"); RETURN NULL;', hash='22ac0110670e8ad9089236c8f3c0416a60d4bf68', operation='UPDATE', pgid='pgtrigger_update_update_edc13', table='catalog_priceitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='priceitem',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_priceitemevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "unit_price", "version_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."service_id", OLD."unit_price", OLD."version_id"); RETURN NULL;', hash='9d06a773db3a87cf6722845b9c59529005a71de0', operation='DELETE', pgid='pgtrigger_delete_delete_e34a9', table='catalog_priceitem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exclusionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='8bf1e8dee86c64bbbc34e091778f6114cb1f8a16', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_73593', table='catalog_exclusionevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='exclusion',
            constraint=models.CheckConstraint(condition=models.Q(('service_kind', ''), ('service_kind__in', ['consultation', 'lab', 'procedure', 'drug', 'consumable', 'bed']), _connector='OR'), name='catalog_exclusion_service_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='exclusion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('service__isnull', False), ('service_kind', '')), models.Q(('service__isnull', True), models.Q(('service_kind', ''), _negated=True)), _connector='OR'), name='catalog_exclusion_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='exclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('payer', 'service'), name='catalog_exclusion_unique_service'),
        ),
        migrations.AddConstraint(
            model_name='exclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', True)), fields=('payer', 'service_kind'), name='catalog_exclusion_unique_kind'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exclusion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_exclusionevent" ("active", "created_at", "id", "note", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "service_kind") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."note", NEW."payer_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."service_id", NEW."service_kind"); RETURN NULL;', hash='1b90b4a4a4da4401e1b5955f50afbb1a3532d94c', operation='INSERT', pgid='pgtrigger_insert_insert_5b516', table='catalog_exclusion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exclusion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "catalog_exclusionevent" ("active", "created_at", "id", "note", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "service_kind") VALUES (NEW."active", NEW."created_at", NEW."id", NEW."note", NEW."payer_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."service_id", NEW."service_kind"); RETURN NULL;', hash='dcd4a9c99ff9c437120337a7d4ee0a0b5b653cf8', operation='UPDATE', pgid='pgtrigger_update_update_eafdc', table='catalog_exclusion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exclusion',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_exclusionevent" ("active", "created_at", "id", "note", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "service_kind") VALUES (OLD."active", OLD."created_at", OLD."id", OLD."note", OLD."payer_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."service_id", OLD."service_kind"); RETURN NULL;', hash='bc6a69dbf06c4ac78b48dc55ba816b4cf93f757e', operation='DELETE', pgid='pgtrigger_delete_delete_87a2a', table='catalog_exclusion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coverageruleevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='af2584ff161f4ee1e37b649007e5bbe6550db27e', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_81410', table='catalog_coverageruleevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(('rule_kind__in', ['percentage', 'copay', 'ceiling'])), name='catalog_coveragerule_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(('service_kind', ''), ('service_kind__in', ['consultation', 'lab', 'procedure', 'drug', 'consumable', 'bed']), _connector='OR'), name='catalog_coveragerule_service_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(('service__isnull', True), ('service_kind', ''), _connector='OR'), name='catalog_coveragerule_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(('payer_percent__isnull', True), models.Q(('payer_percent__gte', 0), ('payer_percent__lte', 100)), _connector='OR'), name='catalog_coveragerule_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('copay_amount__isnull', True), ('copay_amount__gte', 0), _connector='OR'), models.Q(('ceiling_amount__isnull', True), ('ceiling_amount__gte', 0), _connector='OR')), name='catalog_coveragerule_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_kind', 'percentage'), _negated=True), ('payer_percent__isnull', False), _connector='OR'), name='catalog_coveragerule_percentage_needs_percent'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_kind', 'copay'), _negated=True), ('copay_amount__isnull', False), _connector='OR'), name='catalog_coveragerule_copay_needs_amount'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_kind', 'ceiling'), _negated=True), ('ceiling_amount__isnull', False), _connector='OR'), name='catalog_coveragerule_ceiling_needs_amount'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('service__isnull', False)), fields=('payer', 'service'), name='catalog_coveragerule_one_per_service'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('service__isnull', True), models.Q(('service_kind', ''), _negated=True)), fields=('payer', 'service_kind'), name='catalog_coveragerule_one_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='coveragerule',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('service__isnull', True), ('service_kind', '')), fields=('payer',), name='catalog_coveragerule_one_default'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coveragerule',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_coverageruleevent" ("active", "ceiling_amount", "copay_amount", "created_at", "id", "note", "payer_id", "payer_percent", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requires_pre_approval", "rule_kind", "service_id", "service_kind", "updated_at") VALUES (NEW."active", NEW."ceiling_amount", NEW."copay_amount", NEW."created_at", NEW."id", NEW."note", NEW."payer_id", NEW."payer_percent", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requires_pre_approval", NEW."rule_kind", NEW."service_id", NEW."service_kind", NEW."updated_at"); RETURN NULL;', hash='db3180996009bd0b9e7e0757f0e4860d1d342276', operation='INSERT', pgid='pgtrigger_insert_insert_2f7ac', table='catalog_coveragerule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coveragerule',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "catalog_coverageruleevent" ("active", "ceiling_amount", "copay_amount", "created_at", "id", "note", "payer_id", "payer_percent", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requires_pre_approval", "rule_kind", "service_id", "service_kind", "updated_at") VALUES (NEW."active", NEW."ceiling_amount", NEW."copay_amount", NEW."created_at", NEW."id", NEW."note", NEW."payer_id", NEW."payer_percent", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requires_pre_approval", NEW."rule_kind", NEW."service_id", NEW."service_kind", NEW."updated_at"); RETURN NULL;', hash='42b5bd3d2943ba75e5d815e1c0fe37ae38854bd3', operation='UPDATE', pgid='pgtrigger_update_update_be30d', table='catalog_coveragerule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='coveragerule',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_coverageruleevent" ("active", "ceiling_amount", "copay_amount", "created_at", "id", "note", "payer_id", "payer_percent", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requires_pre_approval", "rule_kind", "service_id", "service_kind", "updated_at") VALUES (OLD."active", OLD."ceiling_amount", OLD."copay_amount", OLD."created_at", OLD."id", OLD."note", OLD."payer_id", OLD."payer_percent", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."requires_pre_approval", OLD."rule_kind", OLD."service_id", OLD."service_kind", OLD."updated_at"); RETURN NULL;', hash='48fb860e2fadfc00085e1f275f81366b6aab2bbc', operation='DELETE', pgid='pgtrigger_delete_delete_7db9c', table='catalog_coveragerule', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['kind', 'active'], name='catalog_service_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_ar'], name='catalog_service_name_ar_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='catalog_service_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['consultation', 'lab', 'procedure', 'drug', 'consumable', 'bed'])), name='catalog_service_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True), _connector='OR'), name='catalog_service_has_name'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='service',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_serviceevent" ("active", "category_id", "code", "created_at", "department_id", "description", "id", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at") VALUES (NEW."active", NEW."category_id", NEW."code", NEW."created_at", NEW."department_id", NEW."description", NEW."id", NEW."kind", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order", NEW."updated_at"); RETURN NULL;', hash='56fcb8e73ac25c6c693c8ca4f299ee7fdc0227f2', operation='INSERT', pgid='pgtrigger_insert_insert_b10d1', table='catalog_service', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='service',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "catalog_serviceevent" ("active", "category_id", "code", "created_at", "department_id", "description", "id", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at") VALUES (NEW."active", NEW."category_id", NEW."code", NEW."created_at", NEW."department_id", NEW."description", NEW."id", NEW."kind", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order", NEW."updated_at"); RETURN NULL;', hash='11bc7624eb92961fb20bd0bb512a5e062a1da1c5', operation='UPDATE', pgid='pgtrigger_update_update_58a68', table='catalog_service', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='service',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "catalog_serviceevent" ("active", "category_id", "code", "created_at", "department_id", "description", "id", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order", "updated_at") VALUES (OLD."active", OLD."category_id", OLD."code", OLD."created_at", OLD."department_id", OLD."description", OLD."id", OLD."kind", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order", OLD."updated_at"); RETURN NULL;', hash='3f713d6e728e9cf592db48569c499b6b206b94fe', operation='DELETE', pgid='pgtrigger_delete_delete_ad4ea', table='catalog_service', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='servicecategoryevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='7b1884ba1527bd2fe7931e487e1645614c7ebe81', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c4166', table='catalog_servicecategoryevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='serviceevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='b8ec8990808edad5fa5c64ae7cbb1aa50f80f473', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b0c73', table='catalog_serviceevent', when='BEFORE')),
        ),
    ]
