# Generated by Django 5.2.17 on 2026-10-07 17:21

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_cash_price_list'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='priceitem',
            trigger=pgtrigger.compiler.Trigger(name='item_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n    PERFORM 1 FROM catalog_pricelistversion v WHERE v.id = OLD.version_id FOR UPDATE;\n    IF EXISTS (\n    SELECT 1 FROM billing_invoiceline il WHERE il.price_list_version_id = OLD.version_id AND il.frozen\n) THEN\n        RAISE EXCEPTION 'PRICE_VERSION_LOCKED: version % priced approved invoices',\n            OLD.version_id;\n    END IF;\n    IF TG_OP = 'UPDATE' AND NEW.version_id IS DISTINCT FROM OLD.version_id THEN\n        PERFORM 1 FROM catalog_pricelistversion v WHERE v.id = NEW.version_id FOR UPDATE;\n        IF EXISTS (\n    SELECT 1 FROM billing_invoiceline il WHERE il.price_list_version_id = NEW.version_id AND il.frozen\n) THEN\n            RAISE EXCEPTION 'PRICE_VERSION_LOCKED: version % priced approved invoices',\n                NEW.version_id;\n        END IF;\n    END IF;\n    IF TG_OP = 'DELETE' THEN\n        RETURN OLD;\n    END IF;\n    RETURN NEW;\n", hash='9ae6090b6abf58a56295bfcd7d9b06fca6fc4ab6', operation='UPDATE OR DELETE', pgid='pgtrigger_item_guard_de58f', table='catalog_priceitem', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pricelistversion',
            trigger=pgtrigger.compiler.Trigger(name='version_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n    IF TG_OP = 'INSERT' THEN\n        IF EXISTS (\n    SELECT 1 FROM billing_invoiceline il\n      JOIN billing_invoice i ON i.id = il.invoice_id\n      JOIN catalog_pricelistversion v ON v.id = il.price_list_version_id\n     WHERE il.frozen AND v.price_list_id = NEW.price_list_id\n       AND v.effective_from < NEW.effective_from AND i.priced_on >= NEW.effective_from\n) THEN\n            RAISE EXCEPTION\n                'PRICE_VERSION_BACKDATED: a version from % would reprice frozen invoices',\n                NEW.effective_from;\n        END IF;\n        RETURN NEW;\n    END IF;\n    PERFORM 1 FROM catalog_pricelistversion v WHERE v.id = OLD.id FOR UPDATE;\n    IF EXISTS (\n    SELECT 1 FROM billing_invoiceline il WHERE il.price_list_version_id = OLD.id AND il.frozen\n) AND (TG_OP = 'DELETE'\n                OR NEW.price_list_id IS DISTINCT FROM OLD.price_list_id\n                OR NEW.effective_from IS DISTINCT FROM OLD.effective_from) THEN\n        RAISE EXCEPTION 'PRICE_VERSION_LOCKED: version % priced approved invoices', OLD.id;\n    END IF;\n    IF TG_OP = 'UPDATE' AND NEW.effective_from IS DISTINCT FROM OLD.effective_from THEN\n        IF OLD.effective_from <= current_date OR NEW.effective_from < current_date THEN\n            RAISE EXCEPTION 'PRICE_VERSION_LOCKED: version % is effective; its date is fixed',\n                OLD.id;\n        END IF;\n        IF EXISTS (\n    SELECT 1 FROM billing_invoiceline il\n      JOIN billing_invoice i ON i.id = il.invoice_id\n      JOIN catalog_pricelistversion v ON v.id = il.price_list_version_id\n     WHERE il.frozen AND v.price_list_id = NEW.price_list_id\n       AND v.effective_from < NEW.effective_from AND i.priced_on >= NEW.effective_from\n) THEN\n            RAISE EXCEPTION\n                'PRICE_VERSION_BACKDATED: a version from % would reprice frozen invoices',\n                NEW.effective_from;\n        END IF;\n    END IF;\n    IF TG_OP = 'DELETE' THEN\n        RETURN OLD;\n    END IF;\n    RETURN NEW;\n", hash='023156030f556f5d55c6cf58334ca3b3180e9ab2', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_version_guard_a2135', table='catalog_pricelistversion', when='BEFORE')),
        ),
    ]
