# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=30)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('revenue', 'Revenue'), ('contra_revenue', 'Contra revenue'), ('expense', 'Expense')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('invoice', 'Invoice approved'), ('credit_note', 'Credit note approved'), ('payment', 'Payment received'), ('allocation', 'Payment allocated'), ('transfer_confirm', 'Transfer confirmed'), ('transfer_reject', 'Transfer rejected'), ('refund', 'Refund paid'), ('shift_open', 'Shift opening float'), ('shift_close', 'Shift close variance'), ('handover', 'Cash handover'), ('claim_rebill', 'Payer rejection rebilled to patient'), ('claim_writeoff', 'Payer rejection written off'), ('payer_payment', 'Payer payment received')], max_length=30)),
                ('source_id', models.BigIntegerField()),
                ('entry_date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'journal entry',
                'verbose_name_plural': 'journal entries',
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('service_kind', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('lab', 'Laboratory test'), ('procedure', 'Procedure'), ('drug', 'Drug'), ('consumable', 'Consumable'), ('bed', 'Bed day')], max_length=20)),
                ('memo', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'journal line',
                'ordering': ['entry', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('revenue', 'Revenue'), ('contra_revenue', 'Contra revenue'), ('expense', 'Expense')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ledger account',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['asset', 'liability', 'revenue', 'contra_revenue', 'expense'])), name='ledger_account_kind_valid'), models.CheckConstraint(condition=models.Q(('normal_balance__in', ['debit', 'credit'])), name='ledger_account_balance_valid')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='account_code_fixed', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."kind" IS DISTINCT FROM (NEW."kind") OR OLD."normal_balance" IS DISTINCT FROM (NEW."normal_balance"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='d2fa8eb48e389f7845f323534aa21eacd85440d7', operation='UPDATE', pgid='pgtrigger_account_code_fixed_99e64', table='ledger_account', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='account_no_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'ACCOUNT_FIXED: the chart of accounts is fixed (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='5bc0cd6033ebb1c14905867ab80731ee7dcfc174', operation='DELETE', pgid='pgtrigger_account_no_delete_f1099', table='ledger_account', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ledger_accountevent" ("active", "code", "id", "kind", "name_ar", "name_en", "normal_balance", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."active", NEW."code", NEW."id", NEW."kind", NEW."name_ar", NEW."name_en", NEW."normal_balance", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='325b4a94e77100098819bfc9b11aa5107ebfefe6', operation='INSERT', pgid='pgtrigger_insert_insert_75e84', table='ledger_account', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ledger_accountevent" ("active", "code", "id", "kind", "name_ar", "name_en", "normal_balance", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."active", NEW."code", NEW."id", NEW."kind", NEW."name_ar", NEW."name_en", NEW."normal_balance", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='f374aa0da720b70a0bba209d5f638b986aa40f61', operation='UPDATE', pgid='pgtrigger_update_update_ea942', table='ledger_account', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ledger_accountevent" ("active", "code", "id", "kind", "name_ar", "name_en", "normal_balance", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (OLD."active", OLD."code", OLD."id", OLD."kind", OLD."name_ar", OLD."name_en", OLD."normal_balance", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order"); RETURN NULL;', hash='4cf7fc7dd428f3a5f1b0ffbaf2c5e08524903de8', operation='DELETE', pgid='pgtrigger_delete_delete_52d82', table='ledger_account', when='AFTER')),
        ),
        migrations.AddField(
            model_name='accountevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='accountevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='ledger.journalentry'),
        ),
    ]
