# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('catalog', '0001_initial'),
        ('core', '0006_reason_categories_consultation_service'),
        ('ledger', '0001_initial'),
        ('patients', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='shift',
            field=models.ForeignKey(blank=True, help_text="Shift the effect belongs to (the acting user's current shift for late effects).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.payer'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.shift'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='accountevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f5bf2874a902945030d1f414bbf217e2a0255dd6', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a5fd6', table='ledger_accountevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='ledger_entry_source_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_date'], name='ledger_entry_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['invoice', 'credit_note', 'payment', 'allocation', 'transfer_confirm', 'transfer_reject', 'refund', 'shift_open', 'shift_close', 'handover', 'claim_rebill', 'claim_writeoff', 'payer_payment'])), name='ledger_entry_source_type_valid'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalentry',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='93071b08ce6077405c2ea97d217741a252c73fc4', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d47c8', table='ledger_journalentry', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalentry',
            trigger=pgtrigger.compiler.Trigger(name='entry_balanced', sql=pgtrigger.compiler.UpsertTriggerSql(constraint='CONSTRAINT', declare='DECLARE n_lines integer; s_debit numeric; s_credit numeric;', func="\n    SELECT count(*), coalesce(sum(debit), 0), coalesce(sum(credit), 0)\n      INTO n_lines, s_debit, s_credit\n      FROM ledger_journalline WHERE entry_id = NEW.id;\n    IF n_lines < 2 OR s_debit <> s_credit THEN\n        RAISE EXCEPTION\n            'JOURNAL_UNBALANCED: entry % has % lines, debits % and credits %',\n            NEW.id, n_lines, s_debit, s_credit;\n    END IF;\n    RETURN NULL;\n", hash='dbc2db3518fca9be0aa01a065b78551c0bdcff6c', operation='INSERT', pgid='pgtrigger_entry_balanced_e4d88', table='ledger_journalentry', timing='DEFERRABLE INITIALLY DEFERRED', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'patient'], name='ledger_line_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'payer'], name='ledger_line_payer_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'invoice'], name='ledger_line_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'shift'], name='ledger_line_shift_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'department', 'service_kind'], name='ledger_line_revenue_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ledger_line_one_side'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('service_kind', ''), ('service_kind__in', ['consultation', 'lab', 'procedure', 'drug', 'consumable', 'bed']), _connector='OR'), name='ledger_line_service_kind_valid'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalline',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='07fc3916b1f4ab7e34d6ca626b2b4c3382580230', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_f8373', table='ledger_journalline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalline',
            trigger=pgtrigger.compiler.Trigger(name='line_entry_balanced', sql=pgtrigger.compiler.UpsertTriggerSql(constraint='CONSTRAINT', declare='DECLARE n_lines integer; s_debit numeric; s_credit numeric;', func="\n    SELECT count(*), coalesce(sum(debit), 0), coalesce(sum(credit), 0)\n      INTO n_lines, s_debit, s_credit\n      FROM ledger_journalline WHERE entry_id = NEW.entry_id;\n    IF n_lines < 2 OR s_debit <> s_credit THEN\n        RAISE EXCEPTION\n            'JOURNAL_UNBALANCED: entry % has % lines, debits % and credits %',\n            NEW.entry_id, n_lines, s_debit, s_credit;\n    END IF;\n    RETURN NULL;\n", hash='b9d9a819e69ae424ffbc1cc39e5e900f95a82387', operation='INSERT', pgid='pgtrigger_line_entry_balanced_75c91', table='ledger_journalline', timing='DEFERRABLE INITIALLY DEFERRED', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalline',
            trigger=pgtrigger.compiler.Trigger(name='line_dimensions', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE account_code text;', func="\n    SELECT a.code INTO account_code FROM ledger_account a WHERE a.id = NEW.account_id;\n    IF account_code IN ('AR_PATIENT', 'PATIENT_CREDIT') AND NEW.patient_id IS NULL THEN\n        RAISE EXCEPTION 'JOURNAL_DIMENSION: % lines need a patient', account_code;\n    END IF;\n    IF account_code IN ('AR_PAYER', 'WRITE_OFF') AND NEW.payer_id IS NULL THEN\n        RAISE EXCEPTION 'JOURNAL_DIMENSION: % lines need a payer', account_code;\n    END IF;\n    IF account_code IN ('CASH', 'CASH_OVER_SHORT') AND NEW.shift_id IS NULL THEN\n        RAISE EXCEPTION 'JOURNAL_DIMENSION: % lines need a shift', account_code;\n    END IF;\n    RETURN NEW;\n", hash='23985d7b56c0934db626b327aa76d46225c71936', operation='INSERT', pgid='pgtrigger_line_dimensions_7ac44', table='ledger_journalline', when='BEFORE')),
        ),
    ]
