# Generated by Django 5.2.17 on 2026-10-07 16:57

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_seed_accounts'),
        ('payments', '0003_allocation_reversal_partial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='ledger_entry_source_type_valid',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('invoice', 'Invoice approved'), ('credit_note', 'Credit note approved'), ('payment', 'Payment received'), ('allocation', 'Payment allocated'), ('transfer_confirm', 'Transfer confirmed'), ('transfer_reject', 'Transfer rejected'), ('refund', 'Refund paid'), ('shift_open', 'Shift opening float'), ('shift_close', 'Shift close variance'), ('shift_sweep', 'Counted cash to the safe at close'), ('handover', 'Cash handover'), ('handover_receipt', 'Cash handover received'), ('handover_cancel', 'Cash handover cancelled'), ('claim_rebill', 'Payer rejection rebilled to patient'), ('claim_writeoff', 'Payer rejection written off'), ('claim_short_writeoff', 'Payer short payment written off'), ('payer_payment', 'Payer payment received'), ('payer_cheque_clear', 'Payer cheque cleared'), ('payer_payment_reverse', 'Payer payment reversed')], max_length=30),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalentry',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='4949ab0ce7ed69e10b298fe1ea45c125cc9d873c', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_55f07', table='ledger_journalentry', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalentry',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id) THEN\n                PERFORM 1 FROM payments_shift s\n                 WHERE s.id = NEW.shift_id AND s.status = 'open' FOR SHARE;\n                IF NOT FOUND THEN\n                    RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                        NEW.shift_id, TG_TABLE_NAME;\n                END IF;\n            END IF;\n            RETURN NEW;\n        ", hash='15870005f8932c7d6f5d823a604889cd722d84bb', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_55914', table='ledger_journalentry', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalline',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='69af9e8b6815605b172813d6e32b508942520588', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_17f64', table='ledger_journalline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='journalline',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id) THEN\n                PERFORM 1 FROM payments_shift s\n                 WHERE s.id = NEW.shift_id AND s.status = 'open' FOR SHARE;\n                IF NOT FOUND THEN\n                    RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                        NEW.shift_id, TG_TABLE_NAME;\n                END IF;\n            END IF;\n            RETURN NEW;\n        ", hash='34def5f334c7e81abe34cb0c35b6d06a4ea3dce2', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_a4d86', table='ledger_journalline', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['invoice', 'credit_note', 'payment', 'allocation', 'transfer_confirm', 'transfer_reject', 'refund', 'shift_open', 'shift_close', 'shift_sweep', 'handover', 'handover_receipt', 'handover_cancel', 'claim_rebill', 'claim_writeoff', 'claim_short_writeoff', 'payer_payment', 'payer_cheque_clear', 'payer_payment_reverse'])), name='ledger_entry_source_type_valid'),
        ),
    ]
