# Generated by Django 5.2.17 on 2026-10-07 11:49

import apps.core.db
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_search_functions'),  # hs_normalize_* for the generated columns
        ('catalog', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=30, unique=True)),
                ('full_name_ar', models.CharField(blank=True, max_length=200)),
                ('full_name_en', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown (unidentified emergency)')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dob_is_estimated', models.BooleanField(default=False, help_text='Date of birth computed from an age the patient gave.')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone_alt', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_incomplete', models.BooleanField(default=False, help_text='Emergency registration with name and sex only; complete later (FEATURES 1.2).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_name', models.GeneratedField(db_persist=True, expression=apps.core.db.NormalizeText(django.db.models.functions.text.Concat(models.F('full_name_ar'), models.Value(' '), models.F('full_name_en'))), output_field=models.TextField())),
                ('phone_norm', models.GeneratedField(db_persist=True, expression=apps.core.db.NormalizePhone(models.F('phone')), output_field=models.TextField())),
                ('phone_alt_norm', models.GeneratedField(db_persist=True, expression=apps.core.db.NormalizePhone(models.F('phone_alt')), output_field=models.TextField())),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_files', to='patients.patient')),
            ],
            options={
                'verbose_name': 'patient',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=60)),
                ('member_name', models.CharField(blank=True, max_length=200)),
                ('relation', models.CharField(blank=True, help_text='Principal, spouse, child... as printed on the card.', max_length=30)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('patient_percent_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='patients.patient')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='catalog.payer')),
            ],
            options={
                'verbose_name': 'patient coverage',
                'verbose_name_plural': 'patient coverages',
                'ordering': ['patient', '-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientCoverageEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('card_number', models.CharField(blank=True, max_length=60)),
                ('member_name', models.CharField(blank=True, max_length=200)),
                ('relation', models.CharField(blank=True, help_text='Principal, spouse, child... as printed on the card.', max_length=30)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('patient_percent_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient')),
                ('payer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.payer')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='patients.patientcoverage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('file_no', models.CharField(max_length=30)),
                ('full_name_ar', models.CharField(blank=True, max_length=200)),
                ('full_name_en', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown (unidentified emergency)')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dob_is_estimated', models.BooleanField(default=False, help_text='Date of birth computed from an age the patient gave.')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone_alt', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_incomplete', models.BooleanField(default=False, help_text='Emergency registration with name and sex only; complete later (FEATURES 1.2).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_note', models.TextField()),
                ('source_snapshot', models.JSONField(default=dict, help_text='Demographics of the source file at merge time.')),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_out', to='patients.patient')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_in', to='patients.patient')),
            ],
            options={
                'verbose_name': 'patient merge',
                'ordering': ['-merged_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='patients_patient_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['phone_norm'], name='patients_patient_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_norm'], name='patients_patient_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_alt_norm'], name='patients_patient_phone_alt_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_of_birth'], name='patients_patient_dob_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_incomplete'], name='patients_incomplete_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('sex__in', ['male', 'female', 'unknown'])), name='patients_patient_sex_valid'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('full_name_ar', ''), _negated=True), models.Q(('full_name_en', ''), _negated=True), _connector='OR'), name='patients_patient_has_name'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='patients_patient_not_merged_into_self'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), ('is_active', False), _connector='OR'), name='patients_patient_merged_is_inactive'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('national_id', ''), _negated=True), ('merged_into__isnull', True)), fields=('national_id',), name='patients_patient_national_id_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patient',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "patients_patientevent" ("address", "created_at", "created_by_id", "date_of_birth", "dob_is_estimated", "emergency_contact_name", "emergency_contact_phone", "file_no", "full_name_ar", "full_name_en", "id", "is_active", "is_incomplete", "merged_into_id", "national_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "phone_alt", "sex", "updated_at") VALUES (NEW."address", NEW."created_at", NEW."created_by_id", NEW."date_of_birth", NEW."dob_is_estimated", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."file_no", NEW."full_name_ar", NEW."full_name_en", NEW."id", NEW."is_active", NEW."is_incomplete", NEW."merged_into_id", NEW."national_id", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."phone_alt", NEW."sex", NEW."updated_at"); RETURN NULL;', hash='23d746d2228b226d14f2537e8aa874626d2dae19', operation='INSERT', pgid='pgtrigger_insert_insert_62165', table='patients_patient', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patient',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."address" IS DISTINCT FROM (NEW."address") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."created_by_id" IS DISTINCT FROM (NEW."created_by_id") OR OLD."date_of_birth" IS DISTINCT FROM (NEW."date_of_birth") OR OLD."dob_is_estimated" IS DISTINCT FROM (NEW."dob_is_estimated") OR OLD."emergency_contact_name" IS DISTINCT FROM (NEW."emergency_contact_name") OR OLD."emergency_contact_phone" IS DISTINCT FROM (NEW."emergency_contact_phone") OR OLD."file_no" IS DISTINCT FROM (NEW."file_no") OR OLD."full_name_ar" IS DISTINCT FROM (NEW."full_name_ar") OR OLD."full_name_en" IS DISTINCT FROM (NEW."full_name_en") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_incomplete" IS DISTINCT FROM (NEW."is_incomplete") OR OLD."merged_into_id" IS DISTINCT FROM (NEW."merged_into_id") OR OLD."national_id" IS DISTINCT FROM (NEW."national_id") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."phone" IS DISTINCT FROM (NEW."phone") OR OLD."phone_alt" IS DISTINCT FROM (NEW."phone_alt") OR OLD."sex" IS DISTINCT FROM (NEW."sex") OR OLD."updated_at" IS DISTINCT FROM (NEW."updated_at"))', func='INSERT INTO "patients_patientevent" ("address", "created_at", "created_by_id", "date_of_birth", "dob_is_estimated", "emergency_contact_name", "emergency_contact_phone", "file_no", "full_name_ar", "full_name_en", "id", "is_active", "is_incomplete", "merged_into_id", "national_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "phone_alt", "sex", "updated_at") VALUES (NEW."address", NEW."created_at", NEW."created_by_id", NEW."date_of_birth", NEW."dob_is_estimated", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."file_no", NEW."full_name_ar", NEW."full_name_en", NEW."id", NEW."is_active", NEW."is_incomplete", NEW."merged_into_id", NEW."national_id", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."phone_alt", NEW."sex", NEW."updated_at"); RETURN NULL;', hash='ad0e6603c0cdf8db6ecfd5c59beb18b7d84166ff', operation='UPDATE', pgid='pgtrigger_update_update_546ce', table='patients_patient', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patient',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "patients_patientevent" ("address", "created_at", "created_by_id", "date_of_birth", "dob_is_estimated", "emergency_contact_name", "emergency_contact_phone", "file_no", "full_name_ar", "full_name_en", "id", "is_active", "is_incomplete", "merged_into_id", "national_id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "phone_alt", "sex", "updated_at") VALUES (OLD."address", OLD."created_at", OLD."created_by_id", OLD."date_of_birth", OLD."dob_is_estimated", OLD."emergency_contact_name", OLD."emergency_contact_phone", OLD."file_no", OLD."full_name_ar", OLD."full_name_en", OLD."id", OLD."is_active", OLD."is_incomplete", OLD."merged_into_id", OLD."national_id", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."phone_alt", OLD."sex", OLD."updated_at"); RETURN NULL;', hash='4fe53681b17e41e3c467d5129201a958f49b881c', operation='DELETE', pgid='pgtrigger_delete_delete_9898d', table='patients_patient', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='patientcoverage',
            index=models.Index(fields=['payer', 'card_number'], name='patients_coverage_card_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientcoverage',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='patients_coverage_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='patientcoverage',
            constraint=models.CheckConstraint(condition=models.Q(('patient_percent_override__isnull', True), models.Q(('patient_percent_override__gte', 0), ('patient_percent_override__lte', 100)), _connector='OR'), name='patients_coverage_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='patientcoverage',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('is_default', True)), fields=('patient',), name='patients_coverage_one_default'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patientcoverage',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "patients_patientcoverageevent" ("active", "card_number", "created_at", "created_by_id", "id", "is_default", "member_name", "patient_id", "patient_percent_override", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relation", "updated_at", "valid_from", "valid_to") VALUES (NEW."active", NEW."card_number", NEW."created_at", NEW."created_by_id", NEW."id", NEW."is_default", NEW."member_name", NEW."patient_id", NEW."patient_percent_override", NEW."payer_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."relation", NEW."updated_at", NEW."valid_from", NEW."valid_to"); RETURN NULL;', hash='e9d098f4f2b5242ea78fcb787e44ae5b301361b2', operation='INSERT', pgid='pgtrigger_insert_insert_a7d40', table='patients_patientcoverage', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patientcoverage',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "patients_patientcoverageevent" ("active", "card_number", "created_at", "created_by_id", "id", "is_default", "member_name", "patient_id", "patient_percent_override", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relation", "updated_at", "valid_from", "valid_to") VALUES (NEW."active", NEW."card_number", NEW."created_at", NEW."created_by_id", NEW."id", NEW."is_default", NEW."member_name", NEW."patient_id", NEW."patient_percent_override", NEW."payer_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."relation", NEW."updated_at", NEW."valid_from", NEW."valid_to"); RETURN NULL;', hash='342bfeb661c05469cece789e6476c656aefc3f6a', operation='UPDATE', pgid='pgtrigger_update_update_049a6', table='patients_patientcoverage', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patientcoverage',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "patients_patientcoverageevent" ("active", "card_number", "created_at", "created_by_id", "id", "is_default", "member_name", "patient_id", "patient_percent_override", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relation", "updated_at", "valid_from", "valid_to") VALUES (OLD."active", OLD."card_number", OLD."created_at", OLD."created_by_id", OLD."id", OLD."is_default", OLD."member_name", OLD."patient_id", OLD."patient_percent_override", OLD."payer_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."relation", OLD."updated_at", OLD."valid_from", OLD."valid_to"); RETURN NULL;', hash='ea79acb047d1ccc12cbe472987b5dd259c340ed6', operation='DELETE', pgid='pgtrigger_delete_delete_3500b', table='patients_patientcoverage', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patientcoverageevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='7eadeb94e51490295d2d153a60ea4cf8b1f3a308', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_8205d', table='patients_patientcoverageevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patientevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d56fc44e91ee8df71d41dd0265710731967b921c', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ade9e', table='patients_patientevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='patientmerge',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='patients_merge_distinct_files'),
        ),
        migrations.AddConstraint(
            model_name='patientmerge',
            constraint=models.CheckConstraint(condition=models.Q(('reason_note', ''), _negated=True), name='patients_merge_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='patientmerge',
            constraint=models.UniqueConstraint(fields=('source',), name='patients_merge_source_once'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='patientmerge',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='eb3c3818792c9686e09ffee1fd2a77f4d1af1bc9', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_6a21b', table='patients_patientmerge', when='BEFORE')),
        ),
    ]
