# Generated by Django 5.2.17 on 2026-10-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reason_categories_merge_appointment'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmerge',
            name='reason',
            field=models.ForeignKey(blank=True, help_text='A patient_merge reason code (invariant 4); null on merges recorded before.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
    ]
