# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0006_reason_categories_consultation_service'),
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('admission_diagnosis', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('cancelled', 'Cancelled')], default='admitted', max_length=20)),
                ('admitted_at', models.DateTimeField()),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('admitting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='core.doctorprofile')),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admission',
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, help_text='For callers without a patient file yet.', max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('arrived', 'Arrived (converted to a visit)'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('rescheduled', 'Rescheduled')], default='booked', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_note', models.CharField(blank=True, max_length=300)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.doctorprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('rescheduled_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rescheduled_to', to='visits.appointment')),
            ],
            options={
                'verbose_name': 'appointment',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('contact_name', models.CharField(blank=True, help_text='For callers without a patient file yet.', max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('arrived', 'Arrived (converted to a visit)'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('rescheduled', 'Rescheduled')], default='booked', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_note', models.CharField(blank=True, max_length=300)),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department')),
                ('doctor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.doctorprofile')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='visits.appointment')),
                ('rescheduled_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Out of service')], default='available', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('bed_service', models.ForeignKey(help_text="Service of kind 'bed' charged once per day of stay.", on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='catalog.service')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='core.room')),
            ],
            options={
                'verbose_name': 'bed',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BedCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_charges', to='visits.admission')),
                ('service_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bed_charge', to='orders.serviceline')),
            ],
            options={
                'verbose_name': 'bed charge',
                'ordering': ['admission', 'charge_date'],
            },
        ),
        migrations.CreateModel(
            name='BedEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Out of service')], default='available', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('bed_service', models.ForeignKey(db_constraint=False, help_text="Service of kind 'bed' charged once per day of stay.", on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='visits.bed')),
                ('room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_stays', to='visits.admission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='visits.bed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bed stay',
                'ordering': ['admission', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='BedChargeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('charge_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.admission')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='visits.bedcharge')),
                ('service_line', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.serviceline')),
                ('bed_stay', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.bedstay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bedcharge',
            name='bed_stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='visits.bedstay'),
        ),
        migrations.CreateModel(
            name='BedStayEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.admission')),
                ('bed', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.bed')),
                ('created_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='visits.bedstay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=15)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.doctorprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.room')),
            ],
            options={
                'verbose_name': 'doctor schedule',
                'ordering': ['doctor', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorScheduleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=15)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.doctorprofile')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='visits.doctorschedule')),
                ('room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateField()),
                ('token_no', models.PositiveIntegerField()),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher is served first (emergencies).')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'With the doctor'), ('done', 'Done'), ('no_show', 'Did not answer'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='core.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='core.doctorprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.room')),
            ],
            options={
                'verbose_name': 'queue entry',
                'verbose_name_plural': 'queue entries',
                'ordering': ['queue_date', '-priority', 'token_no'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('visit_type', models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('pharmacy_sale', 'Walk-in pharmacy sale'), ('inpatient', 'Inpatient admission')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=60)),
                ('chief_complaint', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_note', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_visit', to='visits.appointment')),
                ('cancel_reason', models.ForeignKey(blank=True, limit_choices_to={'category': 'visit_cancel'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patientcoverage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='core.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='core.doctorprofile')),
                ('follow_up_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='visits.visit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='catalog.payer')),
            ],
            options={
                'verbose_name': 'visit',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('queue_date', models.DateField()),
                ('token_no', models.PositiveIntegerField()),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher is served first (emergencies).')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'With the doctor'), ('done', 'Done'), ('no_show', 'Did not answer'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.doctorprofile')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='visits.queueentry')),
                ('room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.room')),
                ('visit', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='queueentry',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='visits.visit'),
        ),
        migrations.CreateModel(
            name='AdmissionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('admission_diagnosis', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('cancelled', 'Cancelled')], default='admitted', max_length=20)),
                ('admitted_at', models.DateTimeField()),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('admitting_doctor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.doctorprofile')),
                ('discharged_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='visits.admission')),
                ('visit', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admission', to='visits.visit'),
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('visit_type', models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('pharmacy_sale', 'Walk-in pharmacy sale'), ('inpatient', 'Inpatient admission')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=60)),
                ('chief_complaint', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_note', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.appointment')),
                ('cancel_reason', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'visit_cancel'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode')),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('coverage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patientcoverage')),
                ('created_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.doctorprofile')),
                ('follow_up_of', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit')),
                ('patient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient')),
                ('payer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.payer')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='visits.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'starts_at'], name='visits_appt_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'starts_at'], name='visits_appt_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'starts_at'], name='visits_appt_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['booked', 'arrived', 'cancelled', 'no_show', 'rescheduled'])), name='visits_appointment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='visits_appointment_positive_slot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('patient__isnull', False), models.Q(('contact_name', ''), _negated=True), _connector='OR'), name='visits_appointment_has_person'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False)), _connector='OR'), name='visits_appointment_cancel_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appointment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_appointmentevent" ("cancel_note", "cancelled_at", "cancelled_by_id", "contact_name", "contact_phone", "created_at", "created_by_id", "department_id", "doctor_id", "ends_at", "id", "notes", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rescheduled_from_id", "starts_at", "status", "updated_at") VALUES (NEW."cancel_note", NEW."cancelled_at", NEW."cancelled_by_id", NEW."contact_name", NEW."contact_phone", NEW."created_at", NEW."created_by_id", NEW."department_id", NEW."doctor_id", NEW."ends_at", NEW."id", NEW."notes", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rescheduled_from_id", NEW."starts_at", NEW."status", NEW."updated_at"); RETURN NULL;', hash='8047796e09035f6ae7e1a9f8fb10aa543949a4e0', operation='INSERT', pgid='pgtrigger_insert_insert_e3b47', table='visits_appointment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appointment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_appointmentevent" ("cancel_note", "cancelled_at", "cancelled_by_id", "contact_name", "contact_phone", "created_at", "created_by_id", "department_id", "doctor_id", "ends_at", "id", "notes", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rescheduled_from_id", "starts_at", "status", "updated_at") VALUES (NEW."cancel_note", NEW."cancelled_at", NEW."cancelled_by_id", NEW."contact_name", NEW."contact_phone", NEW."created_at", NEW."created_by_id", NEW."department_id", NEW."doctor_id", NEW."ends_at", NEW."id", NEW."notes", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rescheduled_from_id", NEW."starts_at", NEW."status", NEW."updated_at"); RETURN NULL;', hash='771cca0596aba6117df003296b8c956352b32a7c', operation='UPDATE', pgid='pgtrigger_update_update_e80b2', table='visits_appointment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appointment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_appointmentevent" ("cancel_note", "cancelled_at", "cancelled_by_id", "contact_name", "contact_phone", "created_at", "created_by_id", "department_id", "doctor_id", "ends_at", "id", "notes", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rescheduled_from_id", "starts_at", "status", "updated_at") VALUES (OLD."cancel_note", OLD."cancelled_at", OLD."cancelled_by_id", OLD."contact_name", OLD."contact_phone", OLD."created_at", OLD."created_by_id", OLD."department_id", OLD."doctor_id", OLD."ends_at", OLD."id", OLD."notes", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rescheduled_from_id", OLD."starts_at", OLD."status", OLD."updated_at"); RETURN NULL;', hash='1ad366caa36e6d26fc1315a3f1bd319175cbb8e6', operation='DELETE', pgid='pgtrigger_delete_delete_48c95', table='visits_appointment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appointmentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0a42434fbf6354e834767be64dd9e99cb38c67af', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a6126', table='visits_appointmentevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['available', 'occupied', 'maintenance'])), name='visits_bed_status_valid'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bed',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_bedevent" ("active", "bed_service_id", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "status") VALUES (NEW."active", NEW."bed_service_id", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."room_id", NEW."status"); RETURN NULL;', hash='71e661c6b31e4f116b4d03f2f2e861b458c05daa', operation='INSERT', pgid='pgtrigger_insert_insert_74bc2', table='visits_bed', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bed',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_bedevent" ("active", "bed_service_id", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "status") VALUES (NEW."active", NEW."bed_service_id", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."room_id", NEW."status"); RETURN NULL;', hash='802fe735d401ac5543be68edcc13fc247a3bd241', operation='UPDATE', pgid='pgtrigger_update_update_94cfc', table='visits_bed', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bed',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_bedevent" ("active", "bed_service_id", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "status") VALUES (OLD."active", OLD."bed_service_id", OLD."code", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."room_id", OLD."status"); RETURN NULL;', hash='8172a59c453324297f6f551a1719de2b85f3b732', operation='DELETE', pgid='pgtrigger_delete_delete_ae6af', table='visits_bed', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c3dfc5ac30490687ce2dbd385f0a59d53b56a064', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_a1ae2', table='visits_bedevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='bedstay',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='visits_bedstay_positive_span'),
        ),
        migrations.AddConstraint(
            model_name='bedstay',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('bed',), name='visits_bedstay_bed_free'),
        ),
        migrations.AddConstraint(
            model_name='bedstay',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('admission',), name='visits_bedstay_one_open_per_admission'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedstay',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_bedstayevent" ("admission_id", "bed_id", "created_by_id", "ended_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started_at") VALUES (NEW."admission_id", NEW."bed_id", NEW."created_by_id", NEW."ended_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."started_at"); RETURN NULL;', hash='03d6e2023c69609edff4571bb248bcbe90c29e81', operation='INSERT', pgid='pgtrigger_insert_insert_8d0cd', table='visits_bedstay', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedstay',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_bedstayevent" ("admission_id", "bed_id", "created_by_id", "ended_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started_at") VALUES (NEW."admission_id", NEW."bed_id", NEW."created_by_id", NEW."ended_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."started_at"); RETURN NULL;', hash='fec058ba9e7f2ca9fefafb5b54540dd05e195a22', operation='UPDATE', pgid='pgtrigger_update_update_52d60', table='visits_bedstay', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedstay',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_bedstayevent" ("admission_id", "bed_id", "created_by_id", "ended_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "started_at") VALUES (OLD."admission_id", OLD."bed_id", OLD."created_by_id", OLD."ended_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."started_at"); RETURN NULL;', hash='c2b30ba6bb888b37e2c3b30fbafe3f6ffe03833a', operation='DELETE', pgid='pgtrigger_delete_delete_6ad6e', table='visits_bedstay', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedchargeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='5bf034ba5ebca3c660777b1305526da11ba77339', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d0cb7', table='visits_bedchargeevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='bedcharge',
            constraint=models.UniqueConstraint(fields=('admission', 'charge_date'), name='visits_bedcharge_once_per_day'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedcharge',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_bedchargeevent" ("admission_id", "bed_stay_id", "charge_date", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_line_id") VALUES (NEW."admission_id", NEW."bed_stay_id", NEW."charge_date", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."service_line_id"); RETURN NULL;', hash='99d3811fb4b0fb8a9ef6eecdf3da0ffe40742252', operation='INSERT', pgid='pgtrigger_insert_insert_c6463', table='visits_bedcharge', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedcharge',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_bedchargeevent" ("admission_id", "bed_stay_id", "charge_date", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_line_id") VALUES (NEW."admission_id", NEW."bed_stay_id", NEW."charge_date", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."service_line_id"); RETURN NULL;', hash='046f26a5b7fb25c8fd421b81bf39f133f8746017', operation='UPDATE', pgid='pgtrigger_update_update_239e0', table='visits_bedcharge', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedcharge',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_bedchargeevent" ("admission_id", "bed_stay_id", "charge_date", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_line_id") VALUES (OLD."admission_id", OLD."bed_stay_id", OLD."charge_date", OLD."created_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."service_line_id"); RETURN NULL;', hash='0d163d67ba758f2fe600488dc7977f6847463230', operation='DELETE', pgid='pgtrigger_delete_delete_5696e', table='visits_bedcharge', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bedstayevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='50a66ff80aca16df2ad950c185b308708ac86929', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_360ca', table='visits_bedstayevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='visits_schedule_weekday'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='visits_schedule_positive_span'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('slot_minutes__gte', 1)), name='visits_schedule_slot_positive'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='visits_schedule_valid_dates'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorschedule',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_doctorscheduleevent" ("active", "doctor_id", "end_time", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "slot_minutes", "start_time", "valid_from", "valid_to", "weekday") VALUES (NEW."active", NEW."doctor_id", NEW."end_time", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."room_id", NEW."slot_minutes", NEW."start_time", NEW."valid_from", NEW."valid_to", NEW."weekday"); RETURN NULL;', hash='f23dcf53a9ccafdab09b2edb049dbc7a23577441', operation='INSERT', pgid='pgtrigger_insert_insert_21ec6', table='visits_doctorschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorschedule',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_doctorscheduleevent" ("active", "doctor_id", "end_time", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "slot_minutes", "start_time", "valid_from", "valid_to", "weekday") VALUES (NEW."active", NEW."doctor_id", NEW."end_time", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."room_id", NEW."slot_minutes", NEW."start_time", NEW."valid_from", NEW."valid_to", NEW."weekday"); RETURN NULL;', hash='4787d413ebea2615573ff9757f9d5c676bc9eb97', operation='UPDATE', pgid='pgtrigger_update_update_0d06c', table='visits_doctorschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorschedule',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_doctorscheduleevent" ("active", "doctor_id", "end_time", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "slot_minutes", "start_time", "valid_from", "valid_to", "weekday") VALUES (OLD."active", OLD."doctor_id", OLD."end_time", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."room_id", OLD."slot_minutes", OLD."start_time", OLD."valid_from", OLD."valid_to", OLD."weekday"); RETURN NULL;', hash='8953080e3a438e08f1d150554837195fbf4c64af', operation='DELETE', pgid='pgtrigger_delete_delete_d3e19', table='visits_doctorschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='doctorscheduleevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='15ce4470f6b38f3380f85544c4447fa01cbb6a08', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_88a62', table='visits_doctorscheduleevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-created_at'], name='visits_visit_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'department'], name='visits_visit_status_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['doctor', '-created_at'], name='visits_visit_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['-created_at'], name='visits_visit_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('visit_type__in', ['new', 'follow_up', 'emergency', 'pharmacy_sale', 'inpatient'])), name='visits_visit_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'closed', 'cancelled'])), name='visits_visit_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'closed'), _negated=True), ('closed_at__isnull', False), _connector='OR'), name='visits_visit_closed_has_time'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancel_reason__isnull', False), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False)), _connector='OR'), name='visits_visit_cancel_documented'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('coverage__isnull', True), ('payer__isnull', False), _connector='OR'), name='visits_visit_coverage_has_payer'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('follow_up_of', models.F('id')), _negated=True), name='visits_visit_not_follow_up_of_self'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='visit',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_visitevent" ("appointment_id", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "card_number", "chief_complaint", "closed_at", "closed_by_id", "coverage_id", "created_at", "created_by_id", "department_id", "doctor_id", "follow_up_of_id", "id", "number", "patient_id", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_type") VALUES (NEW."appointment_id", NEW."cancel_note", NEW."cancel_reason_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."card_number", NEW."chief_complaint", NEW."closed_at", NEW."closed_by_id", NEW."coverage_id", NEW."created_at", NEW."created_by_id", NEW."department_id", NEW."doctor_id", NEW."follow_up_of_id", NEW."id", NEW."number", NEW."patient_id", NEW."payer_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."updated_at", NEW."visit_type"); RETURN NULL;', hash='8e53cb1398d3cc95b7bbc25a6e74c74f797c39ef', operation='INSERT', pgid='pgtrigger_insert_insert_9d6da', table='visits_visit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='visit',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_visitevent" ("appointment_id", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "card_number", "chief_complaint", "closed_at", "closed_by_id", "coverage_id", "created_at", "created_by_id", "department_id", "doctor_id", "follow_up_of_id", "id", "number", "patient_id", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_type") VALUES (NEW."appointment_id", NEW."cancel_note", NEW."cancel_reason_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."card_number", NEW."chief_complaint", NEW."closed_at", NEW."closed_by_id", NEW."coverage_id", NEW."created_at", NEW."created_by_id", NEW."department_id", NEW."doctor_id", NEW."follow_up_of_id", NEW."id", NEW."number", NEW."patient_id", NEW."payer_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."updated_at", NEW."visit_type"); RETURN NULL;', hash='23306a8e4eb1fca4645f090c4e789577c0908f81', operation='UPDATE', pgid='pgtrigger_update_update_41cf1', table='visits_visit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='visit',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_visitevent" ("appointment_id", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "card_number", "chief_complaint", "closed_at", "closed_by_id", "coverage_id", "created_at", "created_by_id", "department_id", "doctor_id", "follow_up_of_id", "id", "number", "patient_id", "payer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_type") VALUES (OLD."appointment_id", OLD."cancel_note", OLD."cancel_reason_id", OLD."cancelled_at", OLD."cancelled_by_id", OLD."card_number", OLD."chief_complaint", OLD."closed_at", OLD."closed_by_id", OLD."coverage_id", OLD."created_at", OLD."created_by_id", OLD."department_id", OLD."doctor_id", OLD."follow_up_of_id", OLD."id", OLD."number", OLD."patient_id", OLD."payer_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."updated_at", OLD."visit_type"); RETURN NULL;', hash='8d7ebe19e86444dbed8de63e856547968de05b3c', operation='DELETE', pgid='pgtrigger_delete_delete_a3dfb', table='visits_visit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='queueentryevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='c1e0ff3d73e58c39c88ea7ee85736426de8d4509', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_6c154', table='visits_queueentryevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['doctor', 'queue_date', 'status'], name='visits_queue_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['department', 'queue_date', 'status'], name='visits_queue_dept_idx'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['waiting', 'called', 'in_progress', 'done', 'no_show', 'cancelled'])), name='visits_queue_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('department', 'queue_date', 'token_no'), name='visits_queue_token_unique'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'called', 'in_progress'])), fields=('visit',), name='visits_queue_one_active_per_visit'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('token_no__gte', 1)), name='visits_queue_token_positive'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='queueentry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_queueentryevent" ("called_at", "called_by_id", "created_at", "department_id", "doctor_id", "done_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "queue_date", "room_id", "started_at", "status", "token_no", "visit_id") VALUES (NEW."called_at", NEW."called_by_id", NEW."created_at", NEW."department_id", NEW."doctor_id", NEW."done_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."queue_date", NEW."room_id", NEW."started_at", NEW."status", NEW."token_no", NEW."visit_id"); RETURN NULL;', hash='26fb78b893f790d9bd656c0927f204bcacf4e416', operation='INSERT', pgid='pgtrigger_insert_insert_a8aec', table='visits_queueentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='queueentry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_queueentryevent" ("called_at", "called_by_id", "created_at", "department_id", "doctor_id", "done_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "queue_date", "room_id", "started_at", "status", "token_no", "visit_id") VALUES (NEW."called_at", NEW."called_by_id", NEW."created_at", NEW."department_id", NEW."doctor_id", NEW."done_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."queue_date", NEW."room_id", NEW."started_at", NEW."status", NEW."token_no", NEW."visit_id"); RETURN NULL;', hash='965feb0050a7cfd9a539c3b548da45638691c3bc', operation='UPDATE', pgid='pgtrigger_update_update_50977', table='visits_queueentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='queueentry',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_queueentryevent" ("called_at", "called_by_id", "created_at", "department_id", "doctor_id", "done_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "queue_date", "room_id", "started_at", "status", "token_no", "visit_id") VALUES (OLD."called_at", OLD."called_by_id", OLD."created_at", OLD."department_id", OLD."doctor_id", OLD."done_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."priority", OLD."queue_date", OLD."room_id", OLD."started_at", OLD."status", OLD."token_no", OLD."visit_id"); RETURN NULL;', hash='9cef96417d6039fa7298a5772f00f4a580e7fa5b', operation='DELETE', pgid='pgtrigger_delete_delete_bf432', table='visits_queueentry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admissionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='214caa3ebf6e1c54bfa0b08316ac7a7ada2e0824', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c6416', table='visits_admissionevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['status'], name='visits_admission_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['admitted', 'discharged', 'cancelled'])), name='visits_admission_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'discharged'), _negated=True), models.Q(('discharged_at__isnull', False), ('discharged_by__isnull', False)), _connector='OR'), name='visits_admission_discharge_documented'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(('discharged_at__isnull', True), ('discharged_at__gte', models.F('admitted_at')), _connector='OR'), name='visits_admission_discharge_after_admit'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (NEW."admission_diagnosis", NEW."admitted_at", NEW."admitted_by_id", NEW."admitting_doctor_id", NEW."discharge_summary", NEW."discharged_at", NEW."discharged_by_id", NEW."id", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='e404f40d63be8c98aabaed0fbc610bdd7101812b', operation='INSERT', pgid='pgtrigger_insert_insert_47f0b', table='visits_admission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (NEW."admission_diagnosis", NEW."admitted_at", NEW."admitted_by_id", NEW."admitting_doctor_id", NEW."discharge_summary", NEW."discharged_at", NEW."discharged_by_id", NEW."id", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='81ee1d136f1d81a22aff567ac09852840a39aad7', operation='UPDATE', pgid='pgtrigger_update_update_eef89', table='visits_admission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (OLD."admission_diagnosis", OLD."admitted_at", OLD."admitted_by_id", OLD."admitting_doctor_id", OLD."discharge_summary", OLD."discharged_at", OLD."discharged_by_id", OLD."id", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."updated_at", OLD."visit_id"); RETURN NULL;', hash='c7596f24eac08ea29bb94aaa4737adfb706093a9', operation='DELETE', pgid='pgtrigger_delete_delete_4c186', table='visits_admission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='visitevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='e5570e85b3827664bed2eb15b7c1b7ebdde09934', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c3153', table='visits_visitevent', when='BEFORE')),
        ),
    ]
