# Generated by Django 5.2.17 on 2026-10-07 16:57

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_printtemplate_printtemplateevent_and_more'),
        ('orders', '0003_remove_serviceline_line_guard_and_more'),
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='admission',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='admission',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='admission',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='admission',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='orders.performauthorization'),
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(help_text="The visit's patient (copied, so one open admission per patient is a rule).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='admissionevent',
            name='authorization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.performauthorization'),
        ),
        migrations.RunSQL(
            "UPDATE visits_admission a SET patient_id = v.patient_id "
            "FROM visits_visit v WHERE v.id = a.visit_id AND a.patient_id IS NULL",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(help_text="The visit's patient (copied, so one open admission per patient is a rule).", on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='admissionevent',
            name='patient',
            field=models.ForeignKey(db_constraint=False, help_text="The visit's patient (copied, so one open admission per patient is a rule).", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient'),
        ),
        migrations.RunSQL(
            "ALTER TABLE visits_admissionevent DISABLE TRIGGER USER; "
            "UPDATE visits_admissionevent e SET patient_id = v.patient_id "
            "FROM visits_visit v WHERE v.id = e.visit_id AND e.patient_id IS NULL; "
            "ALTER TABLE visits_admissionevent ENABLE TRIGGER USER;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='admissionevent',
            name='patient',
            field=models.ForeignKey(db_constraint=False, help_text="The visit's patient (copied, so one open admission per patient is a rule).", on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "authorization_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (NEW."admission_diagnosis", NEW."admitted_at", NEW."admitted_by_id", NEW."admitting_doctor_id", NEW."authorization_id", NEW."discharge_summary", NEW."discharged_at", NEW."discharged_by_id", NEW."id", NEW."number", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='b1fa985757110d6f1ee7ddebff3b91d0345560f2', operation='INSERT', pgid='pgtrigger_insert_insert_47f0b', table='visits_admission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "authorization_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (NEW."admission_diagnosis", NEW."admitted_at", NEW."admitted_by_id", NEW."admitting_doctor_id", NEW."authorization_id", NEW."discharge_summary", NEW."discharged_at", NEW."discharged_by_id", NEW."id", NEW."number", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='69ffbd01924e46faf68f4f1a96859aaeacd6f005', operation='UPDATE', pgid='pgtrigger_update_update_eef89', table='visits_admission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "authorization_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (OLD."admission_diagnosis", OLD."admitted_at", OLD."admitted_by_id", OLD."admitting_doctor_id", OLD."authorization_id", OLD."discharge_summary", OLD."discharged_at", OLD."discharged_by_id", OLD."id", OLD."number", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."updated_at", OLD."visit_id"); RETURN NULL;', hash='91468c268e4eaa6b56de3f77cc075394fa4bd2b6', operation='DELETE', pgid='pgtrigger_delete_delete_4c186', table='visits_admission', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'admitted')), fields=('patient',), name='visits_admission_one_open_per_patient'),
        ),
    ]
