# Generated by Django 5.2.17 on 2026-10-08 10:33

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reason_categories_merge_appointment'),
        ('visits', '0002_remove_admission_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='appointment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='appointment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='appointment',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, help_text='An appointment_cancel reason code (invariant 4).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='appointmentevent',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='An appointment_cancel reason code (invariant 4).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appointment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_appointmentevent" ("cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "contact_name", "contact_phone", "created_at", "created_by_id", "department_id", "doctor_id", "ends_at", "id", "notes", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rescheduled_from_id", "starts_at", "status", "updated_at") VALUES (NEW."cancel_note", NEW."cancel_reason_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."contact_name", NEW."contact_phone", NEW."created_at", NEW."created_by_id", NEW."department_id", NEW."doctor_id", NEW."ends_at", NEW."id", NEW."notes", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rescheduled_from_id", NEW."starts_at", NEW."status", NEW."updated_at"); RETURN NULL;', hash='532c19856dc15663923761a25112fae1da5e3fb8', operation='INSERT', pgid='pgtrigger_insert_insert_e3b47', table='visits_appointment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appointment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_appointmentevent" ("cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "contact_name", "contact_phone", "created_at", "created_by_id", "department_id", "doctor_id", "ends_at", "id", "notes", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rescheduled_from_id", "starts_at", "status", "updated_at") VALUES (NEW."cancel_note", NEW."cancel_reason_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."contact_name", NEW."contact_phone", NEW."created_at", NEW."created_by_id", NEW."department_id", NEW."doctor_id", NEW."ends_at", NEW."id", NEW."notes", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rescheduled_from_id", NEW."starts_at", NEW."status", NEW."updated_at"); RETURN NULL;', hash='33b4ecd2d831807c597473af5505e7878aaf07a9', operation='UPDATE', pgid='pgtrigger_update_update_e80b2', table='visits_appointment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appointment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_appointmentevent" ("cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "contact_name", "contact_phone", "created_at", "created_by_id", "department_id", "doctor_id", "ends_at", "id", "notes", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rescheduled_from_id", "starts_at", "status", "updated_at") VALUES (OLD."cancel_note", OLD."cancel_reason_id", OLD."cancelled_at", OLD."cancelled_by_id", OLD."contact_name", OLD."contact_phone", OLD."created_at", OLD."created_by_id", OLD."department_id", OLD."doctor_id", OLD."ends_at", OLD."id", OLD."notes", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rescheduled_from_id", OLD."starts_at", OLD."status", OLD."updated_at"); RETURN NULL;', hash='a2ef07fbc4b1529e51426f7f508c1b1ce19ec71c', operation='DELETE', pgid='pgtrigger_delete_delete_48c95', table='visits_appointment', when='AFTER')),
        ),
    ]
