# Generated by Django 5.2.17 on 2026-10-10 10:05

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_admission_cancel_reasons'),
        ('orders', '0003_remove_serviceline_line_guard_and_more'),
        ('patients', '0002_patientmerge_reason'),
        ('visits', '0003_appointment_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='admission',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='admission',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='admission',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='admission',
            name='cancel_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='cancel_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'admission_cancel'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='admission',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionevent',
            name='cancel_approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionevent',
            name='cancel_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionevent',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'admission_cancel'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='admissionevent',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionevent',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "authorization_id", "cancel_approved_by_id", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (NEW."admission_diagnosis", NEW."admitted_at", NEW."admitted_by_id", NEW."admitting_doctor_id", NEW."authorization_id", NEW."cancel_approved_by_id", NEW."cancel_note", NEW."cancel_reason_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."discharge_summary", NEW."discharged_at", NEW."discharged_by_id", NEW."id", NEW."number", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='6230a09ed491126717f0a96e749541d499316aba', operation='INSERT', pgid='pgtrigger_insert_insert_47f0b', table='visits_admission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "authorization_id", "cancel_approved_by_id", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (NEW."admission_diagnosis", NEW."admitted_at", NEW."admitted_by_id", NEW."admitting_doctor_id", NEW."authorization_id", NEW."cancel_approved_by_id", NEW."cancel_note", NEW."cancel_reason_id", NEW."cancelled_at", NEW."cancelled_by_id", NEW."discharge_summary", NEW."discharged_at", NEW."discharged_by_id", NEW."id", NEW."number", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."updated_at", NEW."visit_id"); RETURN NULL;', hash='0abd1e4a51077d0072c2d6424c7a5f356f7d5aee', operation='UPDATE', pgid='pgtrigger_update_update_eef89', table='visits_admission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='admission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "visits_admissionevent" ("admission_diagnosis", "admitted_at", "admitted_by_id", "admitting_doctor_id", "authorization_id", "cancel_approved_by_id", "cancel_note", "cancel_reason_id", "cancelled_at", "cancelled_by_id", "discharge_summary", "discharged_at", "discharged_by_id", "id", "number", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at", "visit_id") VALUES (OLD."admission_diagnosis", OLD."admitted_at", OLD."admitted_by_id", OLD."admitting_doctor_id", OLD."authorization_id", OLD."cancel_approved_by_id", OLD."cancel_note", OLD."cancel_reason_id", OLD."cancelled_at", OLD."cancelled_by_id", OLD."discharge_summary", OLD."discharged_at", OLD."discharged_by_id", OLD."id", OLD."number", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."updated_at", OLD."visit_id"); RETURN NULL;', hash='0e094729a1bca08f7b7d818c7623ff61a4b247a4', operation='DELETE', pgid='pgtrigger_delete_delete_4c186', table='visits_admission', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancel_approved_by__isnull', False), ('cancel_reason__isnull', False), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), models.Q(('cancel_approved_by', models.F('cancelled_by')), _negated=True)), _connector='OR'), name='visits_admission_cancel_documented'),
        ),
    ]
