# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('portal', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portalaccesscode',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='portalaccesscodeevent',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalaccesscodeevent',
            name='patient',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='portalaccesscodeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='portalaccesscodeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='portal.portalaccesscode'),
        ),
        migrations.AddField(
            model_name='portalaccesscodeevent',
            name='revoked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalaccesscodeevent',
            name='visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='portalaccesscode',
            index=models.Index(fields=['patient', 'expires_at'], name='portal_code_patient_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalaccesscode',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['results', 'receipt', 'appointments'])), name='portal_code_purpose_valid'),
        ),
        migrations.AddConstraint(
            model_name='portalaccesscode',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='portal_code_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='portalaccesscode',
            constraint=models.CheckConstraint(condition=models.Q(('failed_attempts__lte', models.F('max_attempts'))), name='portal_code_attempts_within_max'),
        ),
        migrations.AddConstraint(
            model_name='portalaccesscode',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='portal_code_expires_later'),
        ),
        migrations.AddConstraint(
            model_name='portalaccesscode',
            constraint=models.CheckConstraint(condition=models.Q(('code_hash', ''), _negated=True), name='portal_code_hash_required'),
        ),
        migrations.AddConstraint(
            model_name='portalaccesscode',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', False), _connector='OR'), name='portal_code_revoke_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='portalaccesscode',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "portal_portalaccesscodeevent" ("created_at", "created_by_id", "expires_at", "failed_attempts", "id", "last_used_at", "locked_at", "max_attempts", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purpose", "revoked_at", "revoked_by_id", "visit_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."expires_at", NEW."failed_attempts", NEW."id", NEW."last_used_at", NEW."locked_at", NEW."max_attempts", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."purpose", NEW."revoked_at", NEW."revoked_by_id", NEW."visit_id"); RETURN NULL;', hash='58ff847efcd6ada2157b8d09ddc688b1e7a61ee6', operation='INSERT', pgid='pgtrigger_insert_insert_0f6b0', table='portal_portalaccesscode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='portalaccesscode',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."created_by_id" IS DISTINCT FROM (NEW."created_by_id") OR OLD."expires_at" IS DISTINCT FROM (NEW."expires_at") OR OLD."failed_attempts" IS DISTINCT FROM (NEW."failed_attempts") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."last_used_at" IS DISTINCT FROM (NEW."last_used_at") OR OLD."locked_at" IS DISTINCT FROM (NEW."locked_at") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."patient_id" IS DISTINCT FROM (NEW."patient_id") OR OLD."purpose" IS DISTINCT FROM (NEW."purpose") OR OLD."revoked_at" IS DISTINCT FROM (NEW."revoked_at") OR OLD."revoked_by_id" IS DISTINCT FROM (NEW."revoked_by_id") OR OLD."visit_id" IS DISTINCT FROM (NEW."visit_id"))', func='INSERT INTO "portal_portalaccesscodeevent" ("created_at", "created_by_id", "expires_at", "failed_attempts", "id", "last_used_at", "locked_at", "max_attempts", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purpose", "revoked_at", "revoked_by_id", "visit_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."expires_at", NEW."failed_attempts", NEW."id", NEW."last_used_at", NEW."locked_at", NEW."max_attempts", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."purpose", NEW."revoked_at", NEW."revoked_by_id", NEW."visit_id"); RETURN NULL;', hash='11beeeb51c26fbc391a072df895b562347f95e4e', operation='UPDATE', pgid='pgtrigger_update_update_55295', table='portal_portalaccesscode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='portalaccesscode',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "portal_portalaccesscodeevent" ("created_at", "created_by_id", "expires_at", "failed_attempts", "id", "last_used_at", "locked_at", "max_attempts", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purpose", "revoked_at", "revoked_by_id", "visit_id") VALUES (OLD."created_at", OLD."created_by_id", OLD."expires_at", OLD."failed_attempts", OLD."id", OLD."last_used_at", OLD."locked_at", OLD."max_attempts", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."purpose", OLD."revoked_at", OLD."revoked_by_id", OLD."visit_id"); RETURN NULL;', hash='a7cbd62ed4065c327c79fde4e4621b21006cf95c', operation='DELETE', pgid='pgtrigger_delete_delete_197cd', table='portal_portalaccesscode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='portalaccesscodeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f48399966a5a060d11773dd5b6ba1abcd86fabe2', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_51e08', table='portal_portalaccesscodeevent', when='BEFORE')),
        ),
    ]
