# Generated by Django 5.2.17 on 2026-10-10 01:01

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientmerge_reason'),
        ('portal', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='portal.portalaccesscode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_sessions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'portal session',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortalThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('ip', 'Failed portal sign-ins per client address'), ('file', 'Failed portal sign-ins per file number (known or not)'), ('verify_ip', 'Public receipt checks per client address')], max_length=10)),
                ('key', models.CharField(max_length=64)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'portal throttle',
                'indexes': [models.Index(fields=['updated_at'], name='portal_throttle_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='portal_throttle_unique'), models.CheckConstraint(condition=models.Q(('scope__in', ['ip', 'file', 'verify_ip'])), name='portal_throttle_scope_valid')],
            },
        ),
        migrations.CreateModel(
            name='PortalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('code_issued', 'Access code issued'), ('login_success', 'Signed in'), ('login_failed', 'Sign-in refused: wrong details'), ('login_locked', 'Sign-in refused: file number locked'), ('login_throttled', 'Sign-in refused: too many failures from this address'), ('code_locked', 'Access code locked after repeated wrong codes'), ('logout', 'Signed out'), ('verify_throttled', 'Receipt check refused: too many from this address')], max_length=20)),
                ('file_no', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'portal event',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['code_issued', 'login_success', 'login_failed', 'login_locked', 'login_throttled', 'code_locked', 'logout', 'verify_throttled'])), name='portal_event_kind_valid')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='portalevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='7cfc7506c773a2dbf77216d6e85c600580091876', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_2d5fd', table='portal_portalevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['patient', 'created_at'], name='portal_session_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['last_seen_at'], name='portal_session_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalsession',
            constraint=models.CheckConstraint(condition=models.Q(('last_seen_at__gte', models.F('created_at'))), name='portal_session_seen_after'),
        ),
        migrations.AddConstraint(
            model_name='portalsession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), models.Q(('end_reason', ''), _negated=True), _connector='OR'), name='portal_session_end_documented'),
        ),
    ]
