# Generated by Django 5.2.17 on 2026-10-10 11:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientmerge_reason'),
        ('portal', '0003_sessions_throttles_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='portalaccesscode',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='portalaccesscode',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='portalaccesscode',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='portalevent',
            name='portal_event_kind_valid',
        ),
        migrations.AddField(
            model_name='portalaccesscode',
            name='revoke_note',
            field=models.CharField(blank=True, help_text='Why staff revoked it; empty when a newer code replaced it.', max_length=300),
        ),
        migrations.AddField(
            model_name='portalaccesscodeevent',
            name='revoke_note',
            field=models.CharField(blank=True, help_text='Why staff revoked it; empty when a newer code replaced it.', max_length=300),
        ),
        migrations.AlterField(
            model_name='portalevent',
            name='kind',
            field=models.CharField(choices=[('code_issued', 'Access code issued'), ('code_revoked', 'Access code revoked by staff'), ('login_success', 'Signed in'), ('login_failed', 'Sign-in refused: wrong details'), ('login_locked', 'Sign-in refused: file number locked'), ('login_throttled', 'Sign-in refused: too many failures from this address'), ('code_locked', 'Access code locked after repeated wrong codes'), ('logout', 'Signed out'), ('verify_throttled', 'Receipt check refused: too many from this address')], max_length=20),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='portalaccesscode',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "portal_portalaccesscodeevent" ("created_at", "created_by_id", "expires_at", "failed_attempts", "id", "last_used_at", "locked_at", "max_attempts", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purpose", "revoke_note", "revoked_at", "revoked_by_id", "visit_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."expires_at", NEW."failed_attempts", NEW."id", NEW."last_used_at", NEW."locked_at", NEW."max_attempts", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."purpose", NEW."revoke_note", NEW."revoked_at", NEW."revoked_by_id", NEW."visit_id"); RETURN NULL;', hash='97ef1245a604092f6b83e44a61d50afb727d5505', operation='INSERT', pgid='pgtrigger_insert_insert_0f6b0', table='portal_portalaccesscode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='portalaccesscode',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."created_by_id" IS DISTINCT FROM (NEW."created_by_id") OR OLD."expires_at" IS DISTINCT FROM (NEW."expires_at") OR OLD."failed_attempts" IS DISTINCT FROM (NEW."failed_attempts") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."last_used_at" IS DISTINCT FROM (NEW."last_used_at") OR OLD."locked_at" IS DISTINCT FROM (NEW."locked_at") OR OLD."max_attempts" IS DISTINCT FROM (NEW."max_attempts") OR OLD."patient_id" IS DISTINCT FROM (NEW."patient_id") OR OLD."purpose" IS DISTINCT FROM (NEW."purpose") OR OLD."revoke_note" IS DISTINCT FROM (NEW."revoke_note") OR OLD."revoked_at" IS DISTINCT FROM (NEW."revoked_at") OR OLD."revoked_by_id" IS DISTINCT FROM (NEW."revoked_by_id") OR OLD."visit_id" IS DISTINCT FROM (NEW."visit_id"))', func='INSERT INTO "portal_portalaccesscodeevent" ("created_at", "created_by_id", "expires_at", "failed_attempts", "id", "last_used_at", "locked_at", "max_attempts", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purpose", "revoke_note", "revoked_at", "revoked_by_id", "visit_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."expires_at", NEW."failed_attempts", NEW."id", NEW."last_used_at", NEW."locked_at", NEW."max_attempts", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."purpose", NEW."revoke_note", NEW."revoked_at", NEW."revoked_by_id", NEW."visit_id"); RETURN NULL;', hash='d76da251b79b954d1b1f7a602dd753a157ffcf9a', operation='UPDATE', pgid='pgtrigger_update_update_55295', table='portal_portalaccesscode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='portalaccesscode',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "portal_portalaccesscodeevent" ("created_at", "created_by_id", "expires_at", "failed_attempts", "id", "last_used_at", "locked_at", "max_attempts", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "purpose", "revoke_note", "revoked_at", "revoked_by_id", "visit_id") VALUES (OLD."created_at", OLD."created_by_id", OLD."expires_at", OLD."failed_attempts", OLD."id", OLD."last_used_at", OLD."locked_at", OLD."max_attempts", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."purpose", OLD."revoke_note", OLD."revoked_at", OLD."revoked_by_id", OLD."visit_id"); RETURN NULL;', hash='5ee54240ffd3c6600594b4a179d29378c887ac83', operation='DELETE', pgid='pgtrigger_delete_delete_197cd', table='portal_portalaccesscode', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='portalevent',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['code_issued', 'code_revoked', 'login_success', 'login_failed', 'login_locked', 'login_throttled', 'code_locked', 'logout', 'verify_throttled'])), name='portal_event_kind_valid'),
        ),
    ]
