"""Patient files, coverage on file and merge history (FEATURES 1.1-1.6).

Search (FEATURES 0.9): ``search_name``, ``phone_norm`` and ``phone_alt_norm`` are columns the
database generates with ``hs_normalize_text`` / ``hs_normalize_phone`` (migration
``core.0005``), with trigram GIN indexes for fuzzy and substring matching. Query them with the
same functions: ``Patient.objects.filter(search_name__contains=NormalizeText(Value(q)))``.

Merged files are never deleted (journal lines, invoices and payments reference them):
the source keeps ``merged_into`` and ``is_active=False`` and a ``PatientMerge`` row records
who merged what and why (FEATURES 1.4).
"""

from __future__ import annotations

from typing import ClassVar

import pgtrigger
from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.db import models
from django.db.models import F, Q, Value
from django.db.models.functions import Concat

from apps.core.db import (
    NormalizePhone,
    NormalizeText,
    append_only,
    choice_check,
    percent_field,
    track_history,
)


class Sex(models.TextChoices):
    MALE = "male", "Male"
    FEMALE = "female", "Female"
    UNKNOWN = "unknown", "Unknown (unidentified emergency)"


_GENERATED = ["search_name", "phone_norm", "phone_alt_norm"]


@track_history(exclude=_GENERATED)
class Patient(models.Model):
    """A patient file (FEATURES 1.1). ``file_no`` comes from the ``PT`` sequence."""

    file_no = models.CharField(max_length=30, unique=True)
    full_name_ar = models.CharField(max_length=200, blank=True)
    full_name_en = models.CharField(max_length=200, blank=True)
    sex = models.CharField(max_length=10, choices=Sex.choices)
    date_of_birth = models.DateField(null=True, blank=True)
    dob_is_estimated = models.BooleanField(
        default=False, help_text="Date of birth computed from an age the patient gave."
    )
    phone = models.CharField(max_length=30, blank=True)
    phone_alt = models.CharField(max_length=30, blank=True)
    address = models.CharField(max_length=300, blank=True)
    national_id = models.CharField(max_length=50, blank=True)
    emergency_contact_name = models.CharField(max_length=150, blank=True)
    emergency_contact_phone = models.CharField(max_length=30, blank=True)
    notes = models.TextField(blank=True)
    is_incomplete = models.BooleanField(
        default=False,
        help_text="Emergency registration with name and sex only; complete later (FEATURES 1.2).",
    )
    is_active = models.BooleanField(default=True)
    merged_into = models.ForeignKey(
        "self", on_delete=models.PROTECT, null=True, blank=True, related_name="merged_files"
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True, related_name="+"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Generated by PostgreSQL (STORED); never written by the application.
    search_name = models.GeneratedField(
        expression=NormalizeText(Concat(F("full_name_ar"), Value(" "), F("full_name_en"))),
        output_field=models.TextField(),
        db_persist=True,
    )
    phone_norm = models.GeneratedField(
        expression=NormalizePhone(F("phone")), output_field=models.TextField(), db_persist=True
    )
    phone_alt_norm = models.GeneratedField(
        expression=NormalizePhone(F("phone_alt")), output_field=models.TextField(), db_persist=True
    )

    class Meta:
        verbose_name = "patient"
        ordering: ClassVar[list[str]] = ["-created_at", "-id"]
        constraints: ClassVar[list[models.BaseConstraint]] = [
            choice_check("sex", Sex, "patients_patient_sex_valid"),
            models.CheckConstraint(
                condition=~Q(full_name_ar="") | ~Q(full_name_en=""),
                name="patients_patient_has_name",
            ),
            models.CheckConstraint(
                condition=~Q(merged_into=F("id")), name="patients_patient_not_merged_into_self"
            ),
            models.CheckConstraint(
                condition=Q(merged_into__isnull=True) | Q(is_active=False),
                name="patients_patient_merged_is_inactive",
            ),
            models.UniqueConstraint(
                fields=["national_id"],
                condition=~Q(national_id="") & Q(merged_into__isnull=True),
                name="patients_patient_national_id_unique",
            ),
        ]
        indexes: ClassVar[list[models.Index]] = [
            GinIndex(
                fields=["search_name"],
                opclasses=["gin_trgm_ops"],
                name="patients_patient_name_trgm",
            ),
            GinIndex(
                fields=["phone_norm"],
                opclasses=["gin_trgm_ops"],
                name="patients_patient_phone_trgm",
            ),
            models.Index(fields=["phone_norm"], name="patients_patient_phone_idx"),
            models.Index(fields=["phone_alt_norm"], name="patients_patient_phone_alt_idx"),
            models.Index(fields=["date_of_birth"], name="patients_patient_dob_idx"),
            models.Index(fields=["is_incomplete"], name="patients_incomplete_idx"),
        ]

    def __str__(self) -> str:
        return f"{self.file_no} {self.full_name_ar or self.full_name_en}"


@track_history()
class PatientCoverage(models.Model):
    """Coverage on file: payer, card number, validity (FEATURES 1.6).

    ``patient_percent_override`` replaces the payer's default patient share for this member
    when the contract says so; empty means the payer's coverage rules apply unchanged.
    """

    patient = models.ForeignKey(Patient, on_delete=models.PROTECT, related_name="coverages")
    payer = models.ForeignKey("catalog.Payer", on_delete=models.PROTECT, related_name="members")
    card_number = models.CharField(max_length=60, blank=True)
    member_name = models.CharField(max_length=200, blank=True)
    relation = models.CharField(
        max_length=30, blank=True, help_text="Principal, spouse, child... as printed on the card."
    )
    valid_from = models.DateField(null=True, blank=True)
    valid_to = models.DateField(null=True, blank=True)
    patient_percent_override = percent_field(null=True, blank=True)
    is_default = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True, related_name="+"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "patient coverage"
        verbose_name_plural = "patient coverages"
        ordering: ClassVar[list[str]] = ["patient", "-is_default", "-created_at"]
        constraints: ClassVar[list[models.BaseConstraint]] = [
            models.CheckConstraint(
                condition=Q(valid_from__isnull=True)
                | Q(valid_to__isnull=True)
                | Q(valid_to__gte=F("valid_from")),
                name="patients_coverage_valid_dates",
            ),
            models.CheckConstraint(
                condition=Q(patient_percent_override__isnull=True)
                | (Q(patient_percent_override__gte=0) & Q(patient_percent_override__lte=100)),
                name="patients_coverage_percent_range",
            ),
            models.UniqueConstraint(
                fields=["patient"],
                condition=Q(is_default=True, active=True),
                name="patients_coverage_one_default",
            ),
        ]
        indexes: ClassVar[list[models.Index]] = [
            models.Index(fields=["payer", "card_number"], name="patients_coverage_card_idx"),
        ]

    def __str__(self) -> str:
        return f"{self.patient_id} / {self.payer_id} {self.card_number}".strip()


class PatientMerge(models.Model):
    """Append-only record of a merge of ``source`` into ``target`` (FEATURES 1.4)."""

    source = models.ForeignKey(Patient, on_delete=models.PROTECT, related_name="merges_out")
    target = models.ForeignKey(Patient, on_delete=models.PROTECT, related_name="merges_in")
    reason = models.ForeignKey(
        "core.ReasonCode",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="+",
        help_text="A patient_merge reason code (invariant 4); null on merges recorded before.",
    )
    reason_note = models.TextField()
    source_snapshot = models.JSONField(
        default=dict, help_text="Demographics of the source file at merge time."
    )
    merged_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="+"
    )
    merged_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "patient merge"
        ordering: ClassVar[list[str]] = ["-merged_at", "-id"]
        constraints: ClassVar[list[models.BaseConstraint]] = [
            models.CheckConstraint(
                condition=~Q(source=F("target")), name="patients_merge_distinct_files"
            ),
            models.CheckConstraint(
                condition=~Q(reason_note=""), name="patients_merge_reason_required"
            ),
            models.UniqueConstraint(fields=["source"], name="patients_merge_source_once"),
        ]
        triggers: ClassVar[list[pgtrigger.Trigger]] = [append_only()]

    def __str__(self) -> str:
        return f"{self.source_id} -> {self.target_id}"
