"""Arabic and English titles of the reports, their sections, columns, metrics and values.

The report endpoints send these with each report (like ``name_ar``/``name_en`` on data rows),
so the screen and the Excel file use the same words (ADR 0013). Every key a report uses must
be here in both languages; ``test_labels`` walks every report and checks.
"""

from __future__ import annotations

from typing import Literal

Lang = Literal["ar", "en"]

LABELS: dict[str, tuple[str, str]] = {
    # --- reports -------------------------------------------------------------------------------
    "report.revenue": ("الإيراد اليومي", "Daily revenue"),
    "report.shift_variances": ("فروق الورديات", "Shift variances"),
    "report.pending_transfers": ("التحويلات المعلقة", "Pending transfers"),
    "report.adjustments": ("الخصومات والإلغاءات والاستردادات", "Discounts, cancellations, refunds"),
    "report.payer_receivables": ("مستحقات جهات التغطية", "Payer receivables"),
    "report.requested_not_invoiced": ("مطلوب غير مفوتر", "Requested, not invoiced"),
    "report.paid_not_performed": ("مدفوع غير منفذ", "Paid, not performed"),
    "report.performed_by_authorization": ("منفذ بتصريح", "Performed by authorization"),
    "report.stock_valuation": ("قيمة المخزون", "Stock valuation"),
    "report.stock_movement": ("حركة المخزون", "Stock movement"),
    "report.stock_variance": ("فروق الجرد", "Stock count variance"),
    "report.stock_expiry": ("صلاحية المخزون", "Stock expiry"),
    "report.visits": ("الزيارات", "Patient visits"),
    "report.lab_turnaround": ("زمن إنجاز المعمل وحجمه", "Lab turnaround and volume"),
    # --- sections ------------------------------------------------------------------------------
    "section.by_day": ("حسب اليوم", "By day"),
    "section.by_department": ("حسب القسم", "By department"),
    "section.by_doctor": ("حسب الطبيب", "By doctor"),
    "section.by_method": ("التحصيل حسب طريقة الدفع", "Collections by payment method"),
    "section.payer_payments": ("مدفوعات جهات التغطية", "Payer payments"),
    "section.shifts": ("الورديات المغلقة", "Closed shifts"),
    "section.by_cashier": ("حسب الكاشير", "By cashier"),
    "section.by_age": ("حسب العمر", "By age"),
    "section.transfers": ("التحويلات", "Transfers"),
    "section.payer_cheques": ("شيكات جهات التغطية غير المحصلة", "Payer cheques not cleared"),
    "section.discounts": ("الخصومات", "Discounts"),
    "section.credit_notes": ("الإشعارات الدائنة", "Credit notes"),
    "section.line_cancellations": ("سطور ألغيت قبل الفوترة", "Lines cancelled before billing"),
    "section.refunds": ("الاستردادات المصروفة", "Refunds paid"),
    "section.detail": ("التفاصيل", "Detail"),
    "section.by_stage": ("حسب المرحلة", "By stage"),
    "section.aging": ("أعمار المستحقات", "Aging"),
    "section.lines": ("السطور", "Lines"),
    "section.by_authorizer": ("حسب المصرح", "By authorizer"),
    "section.by_store": ("حسب المخزن", "By store"),
    "section.items": ("الأصناف", "Items"),
    "section.batches": ("التشغيلات", "Batches"),
    "section.tests": ("الفحوصات", "Tests"),
    # --- columns -------------------------------------------------------------------------------
    "column.date": ("التاريخ", "Date"),
    "column.department": ("القسم", "Department"),
    "column.doctor": ("الطبيب", "Doctor"),
    "column.gross": ("الإجمالي", "Gross"),
    "column.discount": ("الخصم", "Discount"),
    "column.credited": ("المسترد بإشعار دائن", "Credited"),
    "column.net": ("الصافي", "Net"),
    "column.payer_share": ("حصة الجهة", "Payer share"),
    "column.patient_share": ("حصة المريض", "Patient share"),
    "column.collected": ("المحصل المؤكد", "Collected"),
    "column.pending": ("بانتظار التحقق", "Pending"),
    "column.method": ("طريقة الدفع", "Method"),
    "column.count": ("العدد", "Count"),
    "column.confirmed": ("مؤكد", "Confirmed"),
    "column.rejected": ("مرفوض", "Rejected"),
    "column.shift": ("الوردية", "Shift"),
    "column.cashier": ("الكاشير", "Cashier"),
    "column.till": ("الصندوق", "Till"),
    "column.closed_at": ("وقت الإغلاق", "Closed at"),
    "column.expected": ("المتوقع", "Expected"),
    "column.counted": ("المعدود", "Counted"),
    "column.variance": ("الفرق", "Variance"),
    "column.reason": ("السبب", "Reason"),
    "column.note": ("ملاحظة", "Note"),
    "column.review": ("المراجعة", "Review"),
    "column.shifts": ("الورديات", "Shifts"),
    "column.short": ("عجز", "Short"),
    "column.over": ("زيادة", "Over"),
    "column.received_on": ("تاريخ الاستلام", "Received on"),
    "column.age": ("العمر بالأيام", "Age (days)"),
    "column.payment": ("رقم الدفعة", "Payment no."),
    "column.file_no": ("رقم الملف", "File no."),
    "column.patient": ("المريض", "Patient"),
    "column.bank": ("البنك", "Bank"),
    "column.reference": ("المرجع", "Reference"),
    "column.amount": ("المبلغ", "Amount"),
    "column.age_bucket": ("العمر", "Age"),
    "column.payer": ("الجهة", "Payer"),
    "column.user": ("المستخدم", "User"),
    "column.at": ("الوقت", "Time"),
    "column.kind": ("النوع", "Type"),
    "column.document": ("المستند", "Document"),
    "column.accrued": ("مستحق", "Accrued"),
    "column.claimed": ("مطالب به", "Claimed"),
    "column.accepted_unpaid": ("مقبول غير محصل", "Accepted, unpaid"),
    "column.rejected_unresolved": ("مرفوض غير معالج", "Rejected, unresolved"),
    "column.receivable": ("المستحق القائم", "Receivable"),
    "column.rebilled": ("محمل على المريض", "Rebilled"),
    "column.written_off": ("مشطوب", "Written off"),
    "column.days_0_30": ("0-30 يوماً", "0-30 days"),
    "column.days_31_60": ("31-60 يوماً", "31-60 days"),
    "column.days_61_90": ("61-90 يوماً", "61-90 days"),
    "column.days_over_90": ("أكثر من 90 يوماً", "Over 90 days"),
    "column.total": ("الإجمالي", "Total"),
    "column.ordered_at": ("وقت الطلب", "Ordered at"),
    "column.visit": ("الزيارة", "Visit"),
    "column.service": ("الخدمة", "Service"),
    "column.quantity": ("الكمية", "Qty"),
    "column.ordered_by": ("طلبه", "Ordered by"),
    "column.settled_at": ("وقت السداد", "Paid at"),
    "column.performed_at": ("وقت التنفيذ", "Performed at"),
    "column.authorization": ("نوع التصريح", "Authorization"),
    "column.authorized_by": ("المصرح", "Authorized by"),
    "column.performed_by": ("نفذه", "Performed by"),
    "column.billing": ("حالة الفوترة", "Billing"),
    "column.unbilled": ("غير مفوتر", "Not invoiced"),
    "column.item": ("الصنف", "Item"),
    "column.store": ("المخزن", "Store"),
    "column.unit": ("الوحدة", "Unit"),
    "column.on_hand": ("الرصيد", "On hand"),
    "column.batches": ("التشغيلات", "Batches"),
    "column.nearest_expiry": ("أقرب انتهاء", "Nearest expiry"),
    "column.value": ("القيمة", "Value"),
    "column.items": ("الأصناف", "Items"),
    "column.opening": ("رصيد أول المدة", "Opening"),
    "column.receipts": ("استلام", "Received"),
    "column.dispensed": ("مصروف", "Dispensed"),
    "column.returns": ("مرتجع", "Returned"),
    "column.adjustments": ("تسويات", "Adjustments"),
    "column.count_corrections": ("تصحيح جرد", "Count corrections"),
    "column.transfers": ("تحويلات", "Transfers"),
    "column.closing": ("رصيد آخر المدة", "Closing"),
    "column.received_value": ("قيمة المستلم", "Received value"),
    "column.dispensed_value": ("قيمة المصروف", "Dispensed value"),
    "column.posted_at": ("وقت الترحيل", "Posted at"),
    "column.batch": ("التشغيلة", "Batch"),
    "column.book": ("الدفتري", "Book"),
    "column.difference": ("الفرق", "Difference"),
    "column.counted_by": ("عدّه", "Counted by"),
    "column.expiry_date": ("تاريخ الانتهاء", "Expiry date"),
    "column.days_left": ("الأيام المتبقية", "Days left"),
    "column.new": ("جديد", "New"),
    "column.follow_up": ("مراجعة", "Follow-up"),
    "column.emergency": ("طوارئ", "Emergency"),
    "column.other": ("أخرى", "Other"),
    "column.cancelled": ("ملغاة", "Cancelled"),
    "column.test": ("الرمز", "Code"),
    "column.name": ("الفحص", "Test"),
    "column.target": ("الهدف بالدقائق", "Target (min)"),
    "column.ordered": ("مطلوب", "Ordered"),
    "column.performed": ("منفذ", "Performed"),
    "column.completed": ("مكتمل", "Completed"),
    "column.median": ("الوسيط بالدقائق", "Median (min)"),
    "column.p90": ("المئين 90 بالدقائق", "90th pct (min)"),
    "column.maximum": ("الأقصى بالدقائق", "Max (min)"),
    "column.within_target": ("ضمن الهدف %", "Within target %"),
    "column.open_overdue": ("متأخر الآن", "Overdue now"),
    # --- metrics -------------------------------------------------------------------------------
    "metric.gross": ("إجمالي المفوتر", "Gross billed"),
    "metric.discount": ("الخصومات", "Discounts"),
    "metric.credited": ("إشعارات دائنة", "Credit notes"),
    "metric.net_revenue": ("صافي الإيراد", "Net revenue"),
    "metric.payer_share": ("حصة الجهات (مستحق)", "Payer share (receivable)"),
    "metric.patient_share": ("حصة المرضى", "Patient share"),
    "metric.collected": ("المحصل المؤكد", "Confirmed collection"),
    "metric.cash": ("نقداً", "Cash"),
    "metric.bank_confirmed": ("تحويلات مؤكدة", "Confirmed transfers"),
    "metric.pending_transfers": ("تحويلات بانتظار التحقق", "Transfers pending verification"),
    "metric.rejected_transfers": ("تحويلات مرفوضة", "Rejected transfers"),
    "metric.credit_used": ("من رصيد المرضى", "Paid from patient credit"),
    "metric.shifts": ("الورديات المغلقة", "Closed shifts"),
    "metric.short": ("إجمالي العجز", "Total short"),
    "metric.over": ("إجمالي الزيادة", "Total over"),
    "metric.net_variance": ("صافي الفروق", "Net variance"),
    "metric.unreviewed": ("فروق لم تراجع", "Variances not reviewed"),
    "metric.pending_total": ("إجمالي المعلق", "Pending total"),
    "metric.pending_count": ("عدد التحويلات المعلقة", "Pending transfers"),
    "metric.oldest_age": ("أقدم عمر بالأيام", "Oldest (days)"),
    "metric.cheques_pending": ("شيكات جهات غير محصلة", "Payer cheques not cleared"),
    "metric.discounts": ("الخصومات", "Discounts"),
    "metric.credit_notes": ("الإشعارات الدائنة", "Credit notes"),
    "metric.refunds": ("الاستردادات", "Refunds"),
    "metric.cancellations": ("إلغاءات قبل الفوترة", "Cancelled before billing"),
    "metric.receivable": ("المستحق القائم", "Outstanding receivable"),
    "metric.claimed": ("مطالب به", "Claimed"),
    "metric.written_off": ("مشطوب", "Written off"),
    "metric.lines": ("السطور", "Lines"),
    "metric.amount": ("القيمة", "Value"),
    "metric.unbilled": ("لم تفوتر بعد", "Not invoiced yet"),
    "metric.stock_value": ("قيمة المخزون", "Stock value"),
    "metric.items": ("الأصناف", "Items"),
    "metric.batches": ("التشغيلات", "Batches"),
    "metric.expired_value": ("قيمة المنتهي", "Expired value"),
    "metric.expiring_value": ("قيمة ما ينتهي خلال المدة", "Expiring value"),
    "metric.received_value": ("قيمة المستلم", "Received value"),
    "metric.dispensed_value": ("قيمة المصروف", "Dispensed value"),
    "metric.items_moved": ("أصناف تحركت", "Items moved"),
    "metric.shortage_value": ("قيمة العجز", "Shortage value"),
    "metric.surplus_value": ("قيمة الزيادة", "Surplus value"),
    "metric.net_value": ("صافي الفرق", "Net difference"),
    "metric.visits": ("الزيارات", "Visits"),
    "metric.new": ("جديدة", "New"),
    "metric.follow_up": ("مراجعات", "Follow-ups"),
    "metric.emergency": ("طوارئ", "Emergency"),
    "metric.patients": ("مرضى مختلفون", "Distinct patients"),
    "metric.completed": ("فحوصات مكتملة", "Completed tests"),
    "metric.median": ("الوسيط بالدقائق", "Median (min)"),
    "metric.within_target": ("ضمن الهدف", "Within target"),
    "metric.open_overdue": ("متأخرة الآن", "Overdue now"),
    "metric.collected_today": ("المحصل المؤكد اليوم", "Confirmed collection today"),
    "metric.cash_today": ("نقداً اليوم", "Cash today"),
    "metric.bank_today": ("تحويلات مؤكدة اليوم", "Confirmed transfers today"),
    "metric.net_revenue_today": ("صافي إيراد اليوم", "Net revenue today"),
    "metric.queue_waiting": ("في الانتظار", "Waiting in queue"),
    "metric.with_doctor": ("مع الطبيب", "With the doctor"),
    "metric.visits_today": ("زيارات اليوم", "Visits today"),
    "metric.open_shifts": ("ورديات مفتوحة", "Open shifts"),
    "metric.oldest_pending_age": ("أقدم تحويل معلق بالأيام", "Oldest pending transfer (days)"),
    # --- values --------------------------------------------------------------------------------
    "method.cash": ("نقد", "Cash"),
    "method.bank_transfer": ("تحويل بنكي", "Bank transfer"),
    "method.qr": ("دفع QR", "QR payment"),
    "method.card": ("بطاقة", "Card"),
    "method.patient_credit": ("رصيد المريض", "Patient credit"),
    "payer_method.bank_transfer": ("تحويل بنكي", "Bank transfer"),
    "payer_method.cheque": ("شيك", "Cheque"),
    "payer_method.cash": ("نقد", "Cash"),
    "review.approved": ("معتمدة", "Signed off"),
    "review.flagged": ("للمتابعة", "Flagged"),
    "review.none": ("لم تراجع", "Not reviewed"),
    "bucket.age_0_1": ("0-1 يوم", "0-1 days"),
    "bucket.age_2_3": ("2-3 أيام", "2-3 days"),
    "bucket.age_4_7": ("4-7 أيام", "4-7 days"),
    "bucket.age_8_30": ("8-30 يوماً", "8-30 days"),
    "bucket.age_over_30": ("أكثر من 30 يوماً", "Over 30 days"),
    "adjustment.discount": ("خصم", "Discount"),
    "adjustment.credit_note": ("إشعار دائن", "Credit note"),
    "adjustment.line_cancellation": ("إلغاء سطر", "Line cancelled"),
    "adjustment.refund": ("استرداد", "Refund"),
    "authorization.insurance_approval": ("موافقة جهة التغطية", "Payer approval"),
    "authorization.emergency": ("طوارئ", "Emergency"),
    "authorization.credit_account": ("حساب آجل معتمد", "Approved credit account"),
    "authorization.other": ("أخرى", "Other"),
    "billing.unbilled": ("غير مفوتر", "Not invoiced"),
    "billing.invoiced": ("مفوتر", "Invoiced"),
    "billing.settled": ("مدفوع", "Paid"),
    "billing.credited": ("مسترد", "Credited"),
    "none.department": ("بدون قسم", "No department"),
    "none.doctor": ("بدون طبيب", "No doctor"),
    "none.user": ("غير محدد", "Not recorded"),
    "none.reason": ("بدون سبب", "No reason"),
    "none.till": ("بدون صندوق", "No till"),
    "none.bank": ("بدون بنك", "No bank"),
    # --- export --------------------------------------------------------------------------------
    "export.summary": ("الملخص", "Summary"),
    "export.period": ("الفترة", "Period"),
    "export.as_of": ("بتاريخ", "As of"),
    "export.department": ("القسم", "Department"),
    "export.user": ("المستخدم", "User"),
    "export.days": ("خلال (أيام)", "Within (days)"),
    "export.all": ("الكل", "All"),
    "export.generated_at": ("أنشئ في", "Generated at"),
    "export.totals": ("الإجمالي", "Total"),
    "export.truncated": (
        "تعرض أول {rows} سطر فقط؛ ضيّق الفترة لرؤية الباقي.",
        "Only the first {rows} rows are shown; narrow the period to see the rest.",
    ),
    "export.to": ("إلى", "to"),
}


def text(key: str, lang: Lang) -> str:
    """The label ``key`` in ``lang``. Raises ``KeyError`` for an unknown key."""
    ar, en = LABELS[key]
    return ar if lang == "ar" else en


def name(key: str) -> dict[str, str]:
    """The label ``key`` in both languages, shaped like a bilingual data name."""
    ar, en = LABELS[key]
    return {"ar": ar, "en": en}
