# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=60)),
                ('expiry_date', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per base unit.', max_digits=16)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ['item', 'expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DispenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_units', models.DecimalField(decimal_places=3, help_text='Quantity in the chosen unit.', max_digits=14)),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('batch_override', models.BooleanField(default=False, help_text='Pharmacist chose another batch than the FEFO suggestion.')),
                ('override_note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'dispense line',
                'ordering': ['dispense', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'drug class',
                'verbose_name_plural': 'drug classes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DrugClassEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('supplier_invoice_no', models.CharField(blank=True, max_length=60)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'goods receipt',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('supplier_invoice_no', models.CharField(blank=True, max_length=60)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=60)),
                ('expiry_date', models.DateField()),
                ('quantity_units', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per base unit.', max_digits=16)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'goods receipt line',
                'ordering': ['receipt', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('batch_no', models.CharField(max_length=60)),
                ('expiry_date', models.DateField()),
                ('quantity_units', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per base unit.', max_digits=16)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('infusion', 'Infusion'), ('cream', 'Cream or ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('sachet', 'Sachet'), ('supply', 'Medical supply'), ('other', 'Other')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, max_length=60)),
                ('base_unit_code', models.CharField(help_text='Smallest unit, e.g. tablet, ml.', max_length=20)),
                ('base_unit_name_ar', models.CharField(max_length=50)),
                ('base_unit_name_en', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=60)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, help_text='Low stock alert threshold (base units).', max_digits=14)),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=0, help_text='Suggested reorder quantity (base units).', max_digits=14)),
                ('storage', models.CharField(choices=[('room', 'Room temperature'), ('cool', 'Cool place'), ('fridge', 'Refrigerated (2-8 C)'), ('frozen', 'Frozen')], default='room', max_length=10)),
                ('is_controlled', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'stock item',
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('infusion', 'Infusion'), ('cream', 'Cream or ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('sachet', 'Sachet'), ('supply', 'Medical supply'), ('other', 'Other')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, max_length=60)),
                ('base_unit_code', models.CharField(help_text='Smallest unit, e.g. tablet, ml.', max_length=20)),
                ('base_unit_name_ar', models.CharField(max_length=50)),
                ('base_unit_name_en', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=60)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, help_text='Low stock alert threshold (base units).', max_digits=14)),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=0, help_text='Suggested reorder quantity (base units).', max_digits=14)),
                ('storage', models.CharField(choices=[('room', 'Room temperature'), ('cool', 'Cool place'), ('fridge', 'Refrigerated (2-8 C)'), ('frozen', 'Frozen')], default='room', max_length=10)),
                ('is_controlled', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Awaiting approval'), ('approved', 'Approved and posted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'stock adjustment',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Awaiting approval'), ('approved', 'Approved and posted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(decimal_places=3, help_text='Signed change in base units.', max_digits=14)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'stock adjustment line',
                'ordering': ['adjustment', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('qty_base', models.DecimalField(decimal_places=3, help_text='Signed change in base units.', max_digits=14)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'stock balance',
                'ordering': ['item', 'store', 'batch'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Counting'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'stock count',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('open', 'Counting'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_qty', models.DecimalField(decimal_places=3, help_text='On-hand when the count started (base units).', max_digits=14)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'stock count line',
                'ordering': ['count', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('book_qty', models.DecimalField(decimal_places=3, help_text='On-hand when the count started (base units).', max_digits=14)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('kind', models.CharField(choices=[('receipt', 'Goods receipt'), ('dispense', 'Dispense'), ('adjustment', 'Adjustment'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('count_correction', 'Count correction'), ('return', 'Return')], max_length=20)),
                ('source_type', models.CharField(help_text='Document kind, e.g. dispense_line, receipt_line, count_line.', max_length=40)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Batch cost per base unit at the time of the move.', max_digits=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'stock move',
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'stock transfer',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
            options={
                'verbose_name': 'stock transfer line',
                'ordering': ['transfer', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('main', 'Main store'), ('pharmacy', 'Pharmacy'), ('lab', 'Laboratory'), ('ward', 'Ward or department'), ('other', 'Other')], default='pharmacy', max_length=20)),
                ('allows_dispense', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'store',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StoreEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('main', 'Main store'), ('pharmacy', 'Pharmacy'), ('lab', 'Laboratory'), ('ward', 'Ward or department'), ('other', 'Other')], default='pharmacy', max_length=20)),
                ('allows_dispense', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('tax_no', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'supplier',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SupplierEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=30)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('tax_no', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('factor', models.DecimalField(decimal_places=3, max_digits=14)),
                ('barcode', models.CharField(blank=True, max_length=60)),
                ('is_dispensable', models.BooleanField(default=True)),
                ('is_purchase_unit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'unit conversion',
                'ordering': ['item', 'factor'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('unit_code', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('factor', models.DecimalField(decimal_places=3, max_digits=14)),
                ('barcode', models.CharField(blank=True, max_length=60)),
                ('is_dispensable', models.BooleanField(default=True)),
                ('is_purchase_unit', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('batch_no', models.CharField(max_length=60)),
                ('expiry_date', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per base unit.', max_digits=16)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dispense',
                'ordering': ['-dispensed_at', '-id'],
            },
        ),
    ]
