# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0006_reason_categories_consultation_service'),
        ('orders', '0002_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('pharmacy', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='dispenseline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='dispenseline',
            name='dispense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='pharmacy.dispense'),
        ),
        migrations.AddField(
            model_name='dispenseline',
            name='override_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'override'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='dispenseline',
            name='service_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_lines', to='orders.serviceline'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='drugclass',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_drugclassevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='ba243931148ac6480c1bde0bee86d30d00d9ebd5', operation='INSERT', pgid='pgtrigger_insert_insert_068dd', table='pharmacy_drugclass', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='drugclass',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_drugclassevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='880dad3b43de03a163b62df9bbe6bd88f8788088', operation='UPDATE', pgid='pgtrigger_update_update_080d1', table='pharmacy_drugclass', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='drugclass',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_drugclassevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."active", OLD."code", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='86e005eea2ae6a5b589f96ea5a0dbd0092c5bc39', operation='DELETE', pgid='pgtrigger_delete_delete_5e08d', table='pharmacy_drugclass', when='AFTER')),
        ),
        migrations.AddField(
            model_name='drugclassevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='drugclassevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.drugclass'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptevent',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='goodsreceiptevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptevent',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pharmacy.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlineevent',
            name='batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlineevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlineevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.goodsreceiptline'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlineevent',
            name='receipt',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='item',
            name='drug_classes',
            field=models.ManyToManyField(blank=True, related_name='items', to='pharmacy.drugclass'),
        ),
        migrations.AddField(
            model_name='item',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlineevent',
            name='item',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='dispenseline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='batchevent',
            name='item',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='batch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='service',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reason_code',
            field=models.ForeignKey(limit_choices_to={'category': 'stock_adjust'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentevent',
            name='decided_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='stockadjustmentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stockadjustmentevent',
            name='reason_code',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'category': 'stock_adjust'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='stockadjustmentevent',
            name='requested_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pharmacy.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='stockadjustmentlineevent',
            name='adjustment',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stockadjustmentlineevent',
            name='batch',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='stockadjustmentlineevent',
            name='item',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='stockadjustmentlineevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='stockadjustmentlineevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.stockadjustmentline'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcountevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='stockcountevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.stockcount'),
        ),
        migrations.AddField(
            model_name='stockcountevent',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcountevent',
            name='started_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pharmacy.stockcount'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='stockcountlineevent',
            name='batch',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='stockcountlineevent',
            name='count',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.stockcount'),
        ),
        migrations.AddField(
            model_name='stockcountlineevent',
            name='counted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcountlineevent',
            name='item',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='stockcountlineevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='stockcountlineevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.stockcountline'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='dispenseline',
            name='stock_move',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_line', to='pharmacy.stockmove'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='received_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='sent_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pharmacy.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferlineevent',
            name='batch',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='stocktransferlineevent',
            name='item',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='stocktransferlineevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='stocktransferlineevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.stocktransferline'),
        ),
        migrations.AddField(
            model_name='stocktransferlineevent',
            name='transfer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.stocktransfer'),
        ),
        migrations.AddField(
            model_name='store',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.department'),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='from_store',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='to_store',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stockcountevent',
            name='store',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stockadjustmentevent',
            name='store',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='goodsreceiptevent',
            name='store',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='storeevent',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.department'),
        ),
        migrations.AddField(
            model_name='storeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='storeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='goodsreceiptevent',
            name='supplier',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='pharmacy.supplier'),
        ),
        migrations.AddField(
            model_name='batchevent',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.supplier'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharmacy.supplier'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='supplier',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_supplierevent" ("active", "address", "code", "contact_name", "id", "name_ar", "name_en", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "tax_no") VALUES (NEW."active", NEW."address", NEW."code", NEW."contact_name", NEW."id", NEW."name_ar", NEW."name_en", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."tax_no"); RETURN NULL;', hash='9d10a176feb736ed07b93793b548ccf7b873f77a', operation='INSERT', pgid='pgtrigger_insert_insert_57103', table='pharmacy_supplier', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='supplier',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_supplierevent" ("active", "address", "code", "contact_name", "id", "name_ar", "name_en", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "tax_no") VALUES (NEW."active", NEW."address", NEW."code", NEW."contact_name", NEW."id", NEW."name_ar", NEW."name_en", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."tax_no"); RETURN NULL;', hash='0c45fb1753434a2d80a206a7245868b68e759ac0', operation='UPDATE', pgid='pgtrigger_update_update_c5c67', table='pharmacy_supplier', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='supplier',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_supplierevent" ("active", "address", "code", "contact_name", "id", "name_ar", "name_en", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "tax_no") VALUES (OLD."active", OLD."address", OLD."code", OLD."contact_name", OLD."id", OLD."name_ar", OLD."name_en", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."tax_no"); RETURN NULL;', hash='031a1b72a2eb4ed84202a7e6ed4dd33b1afeac53', operation='DELETE', pgid='pgtrigger_delete_delete_2c592', table='pharmacy_supplier', when='AFTER')),
        ),
        migrations.AddField(
            model_name='supplierevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='supplierevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.supplier'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlineevent',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.unitconversion'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.unitconversion'),
        ),
        migrations.AddField(
            model_name='dispenseline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.unitconversion'),
        ),
        migrations.AddField(
            model_name='unitconversionevent',
            name='item',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pharmacy.item'),
        ),
        migrations.AddField(
            model_name='unitconversionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='unitconversionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='pharmacy.unitconversion'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='drugclassevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='20df957b01f2668416a0897d5ac7bd8f32330500', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_27393', table='pharmacy_drugclassevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['generic_name'], name='pharmacy_item_generic_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['brand_name'], name='pharmacy_item_brand_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('form__in', ['tablet', 'capsule', 'syrup', 'suspension', 'injection', 'infusion', 'cream', 'drops', 'inhaler', 'suppository', 'sachet', 'supply', 'other'])), name='pharmacy_item_form_valid'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('storage__in', ['room', 'cool', 'fridge', 'frozen'])), name='pharmacy_item_storage_valid'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0), ('reorder_qty__gte', 0)), name='pharmacy_item_levels_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='pharmacy_item_barcode_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_itemevent" ("active", "barcode", "base_unit_code", "base_unit_name_ar", "base_unit_name_en", "brand_name", "created_at", "form", "generic_name", "id", "is_controlled", "min_stock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reorder_qty", "service_id", "storage", "strength", "updated_at") VALUES (NEW."active", NEW."barcode", NEW."base_unit_code", NEW."base_unit_name_ar", NEW."base_unit_name_en", NEW."brand_name", NEW."created_at", NEW."form", NEW."generic_name", NEW."id", NEW."is_controlled", NEW."min_stock", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reorder_qty", NEW."service_id", NEW."storage", NEW."strength", NEW."updated_at"); RETURN NULL;', hash='309a110be1bc9f7d35784efa731ba7928cb2db4d', operation='INSERT', pgid='pgtrigger_insert_insert_76e01', table='pharmacy_item', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_itemevent" ("active", "barcode", "base_unit_code", "base_unit_name_ar", "base_unit_name_en", "brand_name", "created_at", "form", "generic_name", "id", "is_controlled", "min_stock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reorder_qty", "service_id", "storage", "strength", "updated_at") VALUES (NEW."active", NEW."barcode", NEW."base_unit_code", NEW."base_unit_name_ar", NEW."base_unit_name_en", NEW."brand_name", NEW."created_at", NEW."form", NEW."generic_name", NEW."id", NEW."is_controlled", NEW."min_stock", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reorder_qty", NEW."service_id", NEW."storage", NEW."strength", NEW."updated_at"); RETURN NULL;', hash='080710b043813ceffa6836a9d82667f3343a2519', operation='UPDATE', pgid='pgtrigger_update_update_8732a', table='pharmacy_item', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_itemevent" ("active", "barcode", "base_unit_code", "base_unit_name_ar", "base_unit_name_en", "brand_name", "created_at", "form", "generic_name", "id", "is_controlled", "min_stock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reorder_qty", "service_id", "storage", "strength", "updated_at") VALUES (OLD."active", OLD."barcode", OLD."base_unit_code", OLD."base_unit_name_ar", OLD."base_unit_name_en", OLD."brand_name", OLD."created_at", OLD."form", OLD."generic_name", OLD."id", OLD."is_controlled", OLD."min_stock", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reorder_qty", OLD."service_id", OLD."storage", OLD."strength", OLD."updated_at"); RETURN NULL;', hash='c93c6bc4626c4a872999a1bf054d51dac417be3c', operation='DELETE', pgid='pgtrigger_delete_delete_dd905', table='pharmacy_item', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='itemevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='da1d9fdab5d440392156c15daf10ae589d1cad42', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e835c', table='pharmacy_itemevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='stockadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_base', 0), _negated=True), name='pharmacy_adjustmentline_non_zero'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustmentline',
            trigger=pgtrigger.compiler.Trigger(name='line_needs_draft_adjustment', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM pharmacy_stockadjustment p WHERE p.id = OLD.adjustment_id AND p.status = 'draft'\n            ) AND EXISTS (SELECT 1 FROM pharmacy_stockadjustment p WHERE p.id = OLD.adjustment_id) THEN\n                RAISE EXCEPTION 'DOCUMENT_FINAL: parent % of % row is locked', OLD.adjustment_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM pharmacy_stockadjustment p WHERE p.id = NEW.adjustment_id AND p.status = 'draft'\n            ) THEN\n                RAISE EXCEPTION 'DOCUMENT_FINAL: parent % of % row is locked', NEW.adjustment_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='1ae88b64e3431eee0ae36e3e0c7d9d65851551b8', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_line_needs_draft_adjustment_78a06', table='pharmacy_stockadjustmentline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustmentline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stockadjustmentlineevent" ("adjustment_id", "batch_id", "id", "item_id", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base") VALUES (NEW."adjustment_id", NEW."batch_id", NEW."id", NEW."item_id", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."qty_base"); RETURN NULL;', hash='7c566e87a38775af45063e3f2c0007ebb32e5a21', operation='INSERT', pgid='pgtrigger_insert_insert_96e3b', table='pharmacy_stockadjustmentline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustmentline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_stockadjustmentlineevent" ("adjustment_id", "batch_id", "id", "item_id", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base") VALUES (NEW."adjustment_id", NEW."batch_id", NEW."id", NEW."item_id", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."qty_base"); RETURN NULL;', hash='4ab16154b2f52131e61468b4caa1dd1ffe900ba5', operation='UPDATE', pgid='pgtrigger_update_update_32ca3', table='pharmacy_stockadjustmentline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustmentline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stockadjustmentlineevent" ("adjustment_id", "batch_id", "id", "item_id", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base") VALUES (OLD."adjustment_id", OLD."batch_id", OLD."id", OLD."item_id", OLD."note", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."qty_base"); RETURN NULL;', hash='408448ff2ee3faabe8403183b9c241e22517e4c4', operation='DELETE', pgid='pgtrigger_delete_delete_a66e5', table='pharmacy_stockadjustmentline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustmentlineevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='b8fb4c58669f041f444d2a47d4a493b2e61b567d', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_f6fa1', table='pharmacy_stockadjustmentlineevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.UniqueConstraint(fields=('count', 'batch'), name='pharmacy_countline_unique'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('book_qty__gte', 0), models.Q(('counted_qty__isnull', True), ('counted_qty__gte', 0), _connector='OR')), name='pharmacy_countline_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_qty__isnull', True), models.Q(('counted_at__isnull', False), ('counted_by__isnull', False)), _connector='OR'), name='pharmacy_countline_count_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcountline',
            trigger=pgtrigger.compiler.Trigger(name='line_needs_open_count', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM pharmacy_stockcount p WHERE p.id = OLD.count_id AND p.status = 'open'\n            ) AND EXISTS (SELECT 1 FROM pharmacy_stockcount p WHERE p.id = OLD.count_id) THEN\n                RAISE EXCEPTION 'DOCUMENT_FINAL: parent % of % row is locked', OLD.count_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM pharmacy_stockcount p WHERE p.id = NEW.count_id AND p.status = 'open'\n            ) THEN\n                RAISE EXCEPTION 'DOCUMENT_FINAL: parent % of % row is locked', NEW.count_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='0dd3590225e3d999ca011503c2c0fa806ff0e857', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_line_needs_open_count_6cc77', table='pharmacy_stockcountline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcountline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stockcountlineevent" ("batch_id", "book_qty", "count_id", "counted_at", "counted_by_id", "counted_qty", "id", "item_id", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."batch_id", NEW."book_qty", NEW."count_id", NEW."counted_at", NEW."counted_by_id", NEW."counted_qty", NEW."id", NEW."item_id", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='e351f5254aa82ee0ad572e7151e53d80c1ce5c14', operation='INSERT', pgid='pgtrigger_insert_insert_9e401', table='pharmacy_stockcountline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcountline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_stockcountlineevent" ("batch_id", "book_qty", "count_id", "counted_at", "counted_by_id", "counted_qty", "id", "item_id", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."batch_id", NEW."book_qty", NEW."count_id", NEW."counted_at", NEW."counted_by_id", NEW."counted_qty", NEW."id", NEW."item_id", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='718a8ff01adad2bb73379f9d88dc3c28253b99c3', operation='UPDATE', pgid='pgtrigger_update_update_4ba91', table='pharmacy_stockcountline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcountline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stockcountlineevent" ("batch_id", "book_qty", "count_id", "counted_at", "counted_by_id", "counted_qty", "id", "item_id", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."batch_id", OLD."book_qty", OLD."count_id", OLD."counted_at", OLD."counted_by_id", OLD."counted_qty", OLD."id", OLD."item_id", OLD."note", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='eac66f277af3da6e8907e65b7a0981470f9790c3', operation='DELETE', pgid='pgtrigger_delete_delete_0646d', table='pharmacy_stockcountline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcountlineevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='63d9dbf8df553e93895114741638fdb2d483afed', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_86d08', table='pharmacy_stockcountlineevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_base__gt', 0)), name='pharmacy_transferline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'batch'), name='pharmacy_transferline_batch_once'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransferline',
            trigger=pgtrigger.compiler.Trigger(name='line_needs_draft_transfer', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM pharmacy_stocktransfer p WHERE p.id = OLD.transfer_id AND p.status = 'draft'\n            ) AND EXISTS (SELECT 1 FROM pharmacy_stocktransfer p WHERE p.id = OLD.transfer_id) THEN\n                RAISE EXCEPTION 'DOCUMENT_FINAL: parent % of % row is locked', OLD.transfer_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM pharmacy_stocktransfer p WHERE p.id = NEW.transfer_id AND p.status = 'draft'\n            ) THEN\n                RAISE EXCEPTION 'DOCUMENT_FINAL: parent % of % row is locked', NEW.transfer_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='1793a1ccb7caede7f8cbb5814b99367633663c5d', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_line_needs_draft_transfer_65601', table='pharmacy_stocktransferline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransferline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stocktransferlineevent" ("batch_id", "id", "item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base", "transfer_id") VALUES (NEW."batch_id", NEW."id", NEW."item_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."qty_base", NEW."transfer_id"); RETURN NULL;', hash='5e5fa3f44fe5cd3cf7c440f6fea8a514ed295d3c', operation='INSERT', pgid='pgtrigger_insert_insert_0fa22', table='pharmacy_stocktransferline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransferline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_stocktransferlineevent" ("batch_id", "id", "item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base", "transfer_id") VALUES (NEW."batch_id", NEW."id", NEW."item_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."qty_base", NEW."transfer_id"); RETURN NULL;', hash='eaa32d444d14152df8c5684e31755a706f78de6c', operation='UPDATE', pgid='pgtrigger_update_update_6f156', table='pharmacy_stocktransferline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransferline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stocktransferlineevent" ("batch_id", "id", "item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base", "transfer_id") VALUES (OLD."batch_id", OLD."id", OLD."item_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."qty_base", OLD."transfer_id"); RETURN NULL;', hash='fa3dd7ec2ebcb5ece0658aac20f131b9ceef4724', operation='DELETE', pgid='pgtrigger_delete_delete_7cb40', table='pharmacy_stocktransferline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransferlineevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='68b0f230a5171766c24f682501e61e25204dd299', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_9fad0', table='pharmacy_stocktransferlineevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['main', 'pharmacy', 'lab', 'ward', 'other'])), name='pharmacy_store_kind_valid'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='store',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_storeevent" ("active", "allows_dispense", "code", "department_id", "id", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."allows_dispense", NEW."code", NEW."department_id", NEW."id", NEW."kind", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='ba249a46502fb6f2886a5cf8f361ad79968b5e90', operation='INSERT', pgid='pgtrigger_insert_insert_b2b6a', table='pharmacy_store', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='store',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_storeevent" ("active", "allows_dispense", "code", "department_id", "id", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."allows_dispense", NEW."code", NEW."department_id", NEW."id", NEW."kind", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='6c17835de8809efefc1a4e60e76acc255d12fe36', operation='UPDATE', pgid='pgtrigger_update_update_d6b38', table='pharmacy_store', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='store',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_storeevent" ("active", "allows_dispense", "code", "department_id", "id", "kind", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."active", OLD."allows_dispense", OLD."code", OLD."department_id", OLD."id", OLD."kind", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='18e0a17c8a00d5f22020ad47f8a2807c10bb794b', operation='DELETE', pgid='pgtrigger_delete_delete_fded9', table='pharmacy_store', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransferevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f6ce61b883a03407a79b634b2289216e8100378d', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b0964', table='pharmacy_stocktransferevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'sent', 'received', 'cancelled'])), name='pharmacy_transfer_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_store', models.F('to_store')), _negated=True), name='pharmacy_transfer_distinct_stores'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['sent', 'received']), _negated=True), models.Q(('sent_at__isnull', False), ('sent_by__isnull', False)), _connector='OR'), name='pharmacy_transfer_send_documented'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'received'), _negated=True), models.Q(('received_at__isnull', False), ('received_by__isnull', False)), _connector='OR'), name='pharmacy_transfer_receipt_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransfer',
            trigger=pgtrigger.compiler.Trigger(name='transfer_final', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'received\', \'cancelled\'))', func="RAISE EXCEPTION 'DOCUMENT_FINAL: received or cancelled transfers never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='85faa3281405f30c34f9842855d76985b30c6464', operation='UPDATE OR DELETE', pgid='pgtrigger_transfer_final_8f8fe', table='pharmacy_stocktransfer', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransfer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stocktransferevent" ("created_at", "created_by_id", "from_store_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "sent_at", "sent_by_id", "status", "to_store_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."from_store_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."sent_at", NEW."sent_by_id", NEW."status", NEW."to_store_id"); RETURN NULL;', hash='83d265c91ff750497c617780aec1ec30e695d35c', operation='INSERT', pgid='pgtrigger_insert_insert_c3a37', table='pharmacy_stocktransfer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransfer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_stocktransferevent" ("created_at", "created_by_id", "from_store_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "sent_at", "sent_by_id", "status", "to_store_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."from_store_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."sent_at", NEW."sent_by_id", NEW."status", NEW."to_store_id"); RETURN NULL;', hash='d04e38503dd54de5704fffa436e6568b9446bfef', operation='UPDATE', pgid='pgtrigger_update_update_0f325', table='pharmacy_stocktransfer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransfer',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stocktransferevent" ("created_at", "created_by_id", "from_store_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "sent_at", "sent_by_id", "status", "to_store_id") VALUES (OLD."created_at", OLD."created_by_id", OLD."from_store_id", OLD."id", OLD."note", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."received_at", OLD."received_by_id", OLD."sent_at", OLD."sent_by_id", OLD."status", OLD."to_store_id"); RETURN NULL;', hash='e4589268ec5883819bc545594edfee6454bc2ad5', operation='DELETE', pgid='pgtrigger_delete_delete_87107', table='pharmacy_stocktransfer', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['item', 'store', 'moved_at'], name='pharmacy_move_item_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['source_type', 'source_id'], name='pharmacy_move_source_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['kind', 'moved_at'], name='pharmacy_move_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmove',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['receipt', 'dispense', 'adjustment', 'transfer_out', 'transfer_in', 'count_correction', 'return'])), name='pharmacy_move_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockmove',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['receipt', 'transfer_in']), ('qty_base__gt', 0)), models.Q(('kind__in', ['dispense', 'transfer_out']), ('qty_base__lt', 0)), models.Q(('kind__in', ['adjustment', 'count_correction', 'return']), models.Q(('qty_base', 0), _negated=True)), _connector='OR'), name='pharmacy_move_sign_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='stockmove',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='pharmacy_move_cost_non_negative'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockmove',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='38701eb2530b2dfe75447d7a89d89dcae80474ab', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ce301', table='pharmacy_stockmove', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockmove',
            trigger=pgtrigger.compiler.Trigger(name='stock_balance', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n    IF NOT EXISTS (\n        SELECT 1 FROM pharmacy_batch b WHERE b.id = NEW.batch_id AND b.item_id = NEW.item_id\n    ) THEN\n        RAISE EXCEPTION 'STOCK_ITEM_MISMATCH: batch % does not belong to item %',\n            NEW.batch_id, NEW.item_id;\n    END IF;\n    -- A zero row first (always valid), then the signed change: the CHECK (qty_base >= 0)\n    -- judges the resulting balance, and the UPDATE row lock serializes concurrent moves.\n    INSERT INTO pharmacy_stockbalance (item_id, batch_id, store_id, qty_base, updated_at)\n    VALUES (NEW.item_id, NEW.batch_id, NEW.store_id, 0, now())\n    ON CONFLICT (batch_id, store_id) DO NOTHING;\n    UPDATE pharmacy_stockbalance\n       SET qty_base = qty_base + NEW.qty_base, updated_at = now()\n     WHERE batch_id = NEW.batch_id AND store_id = NEW.store_id;\n    RETURN NULL;\n", hash='32ec09c665f6afc3d9c44d2e66d8a838970c4570', operation='INSERT', pgid='pgtrigger_stock_balance_3e823', table='pharmacy_stockmove', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcountevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='11e1e0f2b68ce516ec3fc1089c7aefb1934a9f62', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_ee2ed', table='pharmacy_stockcountevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'posted', 'cancelled'])), name='pharmacy_count_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'posted'), _negated=True), models.Q(('posted_at__isnull', False), ('posted_by__isnull', False)), _connector='OR'), name='pharmacy_count_post_documented'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('store',), name='pharmacy_count_one_open_per_store'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcount',
            trigger=pgtrigger.compiler.Trigger(name='count_final', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'posted\', \'cancelled\'))', func="RAISE EXCEPTION 'DOCUMENT_FINAL: posted or cancelled counts never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='38ec20a81b2ef848f97e271f123e90670849e502', operation='UPDATE OR DELETE', pgid='pgtrigger_count_final_4c169', table='pharmacy_stockcount', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcount',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stockcountevent" ("id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "posted_at", "posted_by_id", "started_at", "started_by_id", "status", "store_id") VALUES (NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."posted_at", NEW."posted_by_id", NEW."started_at", NEW."started_by_id", NEW."status", NEW."store_id"); RETURN NULL;', hash='eb0a2509564fb289d07af13953189df028d96748', operation='INSERT', pgid='pgtrigger_insert_insert_de355', table='pharmacy_stockcount', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcount',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_stockcountevent" ("id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "posted_at", "posted_by_id", "started_at", "started_by_id", "status", "store_id") VALUES (NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."posted_at", NEW."posted_by_id", NEW."started_at", NEW."started_by_id", NEW."status", NEW."store_id"); RETURN NULL;', hash='402647e2de0911db7cbae0fe80a410371d5501fa', operation='UPDATE', pgid='pgtrigger_update_update_d1a37', table='pharmacy_stockcount', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockcount',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stockcountevent" ("id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "posted_at", "posted_by_id", "started_at", "started_by_id", "status", "store_id") VALUES (OLD."id", OLD."note", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."posted_at", OLD."posted_by_id", OLD."started_at", OLD."started_by_id", OLD."status", OLD."store_id"); RETURN NULL;', hash='75c66222ed64ae9d9534340b8fc08446eea72ae4', operation='DELETE', pgid='pgtrigger_delete_delete_fe717', table='pharmacy_stockcount', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['item', 'store'], name='pharmacy_balance_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('batch', 'store'), name='pharmacy_balance_unique'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('qty_base__gte', 0)), name='pharmacy_balance_never_negative'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockbalance',
            trigger=pgtrigger.compiler.Trigger(name='balance_only_from_moves', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (pg_trigger_depth() = 0)', func="RAISE EXCEPTION 'STOCK_BALANCE_DERIVED: stock balances change only through stock moves (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='4c1a3df5426d5843d1daa3a8c7dec5abcfa982dd', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_balance_only_from_moves_7d696', table='pharmacy_stockbalance', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustmentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='4f9487099d84a24046d17607a28f9c0f24e258ba', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_2ec4a', table='pharmacy_stockadjustmentevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'rejected'])), name='pharmacy_adjustment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False)), _connector='OR'), name='pharmacy_adjustment_decision_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustment',
            trigger=pgtrigger.compiler.Trigger(name='adjustment_final', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'approved\', \'rejected\'))', func="RAISE EXCEPTION 'DOCUMENT_FINAL: decided adjustments never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='68151dbb0766a8f379753256efe46c33f26ef3fb', operation='UPDATE OR DELETE', pgid='pgtrigger_adjustment_final_e494a', table='pharmacy_stockadjustment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stockadjustmentevent" ("decided_at", "decided_by_id", "decision_note", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "requested_at", "requested_by_id", "status", "store_id") VALUES (NEW."decided_at", NEW."decided_by_id", NEW."decision_note", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason_code_id", NEW."requested_at", NEW."requested_by_id", NEW."status", NEW."store_id"); RETURN NULL;', hash='87a1578851e9374f433f4f0735eda0e3dd035740', operation='INSERT', pgid='pgtrigger_insert_insert_9929d', table='pharmacy_stockadjustment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_stockadjustmentevent" ("decided_at", "decided_by_id", "decision_note", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "requested_at", "requested_by_id", "status", "store_id") VALUES (NEW."decided_at", NEW."decided_by_id", NEW."decision_note", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason_code_id", NEW."requested_at", NEW."requested_by_id", NEW."status", NEW."store_id"); RETURN NULL;', hash='e061cd0a581af0a3d995441e0b540ac15662c0f6', operation='UPDATE', pgid='pgtrigger_update_update_c7a17', table='pharmacy_stockadjustment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockadjustment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stockadjustmentevent" ("decided_at", "decided_by_id", "decision_note", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "requested_at", "requested_by_id", "status", "store_id") VALUES (OLD."decided_at", OLD."decided_by_id", OLD."decision_note", OLD."id", OLD."note", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reason_code_id", OLD."requested_at", OLD."requested_by_id", OLD."status", OLD."store_id"); RETURN NULL;', hash='1b662ab3cca924a191e800999c84ef15737ab40d', operation='DELETE', pgid='pgtrigger_delete_delete_3c3f9', table='pharmacy_stockadjustment', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='dispense',
            index=models.Index(fields=['visit'], name='pharmacy_dispense_visit_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dispense',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='bf6d714334dd31cbcf0d5eef3bb328e70300a863', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e286c', table='pharmacy_dispense', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='storeevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='e988d801b3937a2a6d07ecc476b1babe0a21f238', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e548b', table='pharmacy_storeevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceiptevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='4ad02fe10889bab9b7b513f467acb5edb60b7d8a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_9f3a4', table='pharmacy_goodsreceiptevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'posted', 'cancelled'])), name='pharmacy_receipt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='pharmacy_receipt_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'posted'), _negated=True), models.Q(('posted_at__isnull', False), ('posted_by__isnull', False)), _connector='OR'), name='pharmacy_receipt_post_documented'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('supplier_invoice_no', ''), _negated=True), models.Q(('status', 'cancelled'), _negated=True)), fields=('supplier', 'supplier_invoice_no'), name='pharmacy_receipt_supplier_invoice_once'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceipt',
            trigger=pgtrigger.compiler.Trigger(name='receipt_final', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'posted\', \'cancelled\'))', func="RAISE EXCEPTION 'DOCUMENT_FINAL: posted or cancelled receipts never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='7fc86bd8f27929e096d58c01ad042468dbcdf572', operation='UPDATE OR DELETE', pgid='pgtrigger_receipt_final_05292', table='pharmacy_goodsreceipt', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceipt',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_goodsreceiptevent" ("created_at", "created_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "posted_at", "posted_by_id", "status", "store_id", "supplier_id", "supplier_invoice_date", "supplier_invoice_no", "total_cost") VALUES (NEW."created_at", NEW."created_by_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."posted_at", NEW."posted_by_id", NEW."status", NEW."store_id", NEW."supplier_id", NEW."supplier_invoice_date", NEW."supplier_invoice_no", NEW."total_cost"); RETURN NULL;', hash='904d17bc618cd020bbd291e6aed491997f4a773f', operation='INSERT', pgid='pgtrigger_insert_insert_49ef5', table='pharmacy_goodsreceipt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceipt',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_goodsreceiptevent" ("created_at", "created_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "posted_at", "posted_by_id", "status", "store_id", "supplier_id", "supplier_invoice_date", "supplier_invoice_no", "total_cost") VALUES (NEW."created_at", NEW."created_by_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."posted_at", NEW."posted_by_id", NEW."status", NEW."store_id", NEW."supplier_id", NEW."supplier_invoice_date", NEW."supplier_invoice_no", NEW."total_cost"); RETURN NULL;', hash='c4bbd06ebd0cf255a8164179946e0df34b4f1288', operation='UPDATE', pgid='pgtrigger_update_update_ca308', table='pharmacy_goodsreceipt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceipt',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_goodsreceiptevent" ("created_at", "created_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "posted_at", "posted_by_id", "status", "store_id", "supplier_id", "supplier_invoice_date", "supplier_invoice_no", "total_cost") VALUES (OLD."created_at", OLD."created_by_id", OLD."id", OLD."note", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."posted_at", OLD."posted_by_id", OLD."status", OLD."store_id", OLD."supplier_id", OLD."supplier_invoice_date", OLD."supplier_invoice_no", OLD."total_cost"); RETURN NULL;', hash='7def3093ddb5022f83b0ed2d5d467de511b9aff7', operation='DELETE', pgid='pgtrigger_delete_delete_6778f', table='pharmacy_goodsreceipt', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='batchevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='282f1785bb6f2648c51cbab54512193856abeb67', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_7bb15', table='pharmacy_batchevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['item', 'expiry_date'], name='pharmacy_batch_fefo_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='pharmacy_batch_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('item', 'batch_no', 'expiry_date'), name='pharmacy_batch_unique'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='pharmacy_batch_cost_non_negative'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='batch',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_batchevent" ("batch_no", "created_at", "expiry_date", "id", "item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "supplier_id", "unit_cost") VALUES (NEW."batch_no", NEW."created_at", NEW."expiry_date", NEW."id", NEW."item_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_on", NEW."supplier_id", NEW."unit_cost"); RETURN NULL;', hash='5ad8c5fac5744629c6a766922f3fb706ce2754e1', operation='INSERT', pgid='pgtrigger_insert_insert_81649', table='pharmacy_batch', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='batch',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_batchevent" ("batch_no", "created_at", "expiry_date", "id", "item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "supplier_id", "unit_cost") VALUES (NEW."batch_no", NEW."created_at", NEW."expiry_date", NEW."id", NEW."item_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_on", NEW."supplier_id", NEW."unit_cost"); RETURN NULL;', hash='aafec57bb98986c4ba134ea42f88a74f96ec594a', operation='UPDATE', pgid='pgtrigger_update_update_ab584', table='pharmacy_batch', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='batch',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_batchevent" ("batch_no", "created_at", "expiry_date", "id", "item_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_on", "supplier_id", "unit_cost") VALUES (OLD."batch_no", OLD."created_at", OLD."expiry_date", OLD."id", OLD."item_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."received_on", OLD."supplier_id", OLD."unit_cost"); RETURN NULL;', hash='03a9559c34f5aaa40140c0001701dee63cf3be62', operation='DELETE', pgid='pgtrigger_delete_delete_311c6', table='pharmacy_batch', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='supplierevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='0e96ca56f0a9109642bf955a41810d50eef8a82a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_da8b3', table='pharmacy_supplierevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('item', 'unit_code'), name='pharmacy_unit_unique'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='pharmacy_unit_factor_positive'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unitconversion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_unitconversionevent" ("barcode", "factor", "id", "is_dispensable", "is_purchase_unit", "item_id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "unit_code") VALUES (NEW."barcode", NEW."factor", NEW."id", NEW."is_dispensable", NEW."is_purchase_unit", NEW."item_id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."unit_code"); RETURN NULL;', hash='397ec699227a043ec947735e56f02be40d664261', operation='INSERT', pgid='pgtrigger_insert_insert_f3805', table='pharmacy_unitconversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unitconversion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_unitconversionevent" ("barcode", "factor", "id", "is_dispensable", "is_purchase_unit", "item_id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "unit_code") VALUES (NEW."barcode", NEW."factor", NEW."id", NEW."is_dispensable", NEW."is_purchase_unit", NEW."item_id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."unit_code"); RETURN NULL;', hash='d705328051d11f5c9e585ea87065544edafe0a3c', operation='UPDATE', pgid='pgtrigger_update_update_60131', table='pharmacy_unitconversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unitconversion',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_unitconversionevent" ("barcode", "factor", "id", "is_dispensable", "is_purchase_unit", "item_id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "unit_code") VALUES (OLD."barcode", OLD."factor", OLD."id", OLD."is_dispensable", OLD."is_purchase_unit", OLD."item_id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."unit_code"); RETURN NULL;', hash='d3ba234dce5443d1432ffca8b38cebb60243ce26', operation='DELETE', pgid='pgtrigger_delete_delete_5ede8', table='pharmacy_unitconversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceiptlineevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='25819b99efb4c2c780cd78597993b7d0736faef4', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_1fcd3', table='pharmacy_goodsreceiptlineevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_units__gt', 0), ('qty_base__gt', 0)), name='pharmacy_receiptline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0), ('line_total__gte', 0)), name='pharmacy_receiptline_cost_non_negative'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceiptline',
            trigger=pgtrigger.compiler.Trigger(name='line_needs_draft_receipt', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF TG_OP IN ('UPDATE', 'DELETE') AND NOT EXISTS (\n                SELECT 1 FROM pharmacy_goodsreceipt p WHERE p.id = OLD.receipt_id AND p.status = 'draft'\n            ) AND EXISTS (SELECT 1 FROM pharmacy_goodsreceipt p WHERE p.id = OLD.receipt_id) THEN\n                RAISE EXCEPTION 'DOCUMENT_FINAL: parent % of % row is locked', OLD.receipt_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP IN ('INSERT', 'UPDATE') AND NOT EXISTS (\n                SELECT 1 FROM pharmacy_goodsreceipt p WHERE p.id = NEW.receipt_id AND p.status = 'draft'\n            ) THEN\n                RAISE EXCEPTION 'DOCUMENT_FINAL: parent % of % row is locked', NEW.receipt_id,\n                    TG_TABLE_NAME;\n            END IF;\n            IF TG_OP = 'DELETE' THEN\n                RETURN OLD;\n            END IF;\n            RETURN NEW;\n        ", hash='0b678e1c4d2db40fd87dcdb93025357521db06fe', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_line_needs_draft_receipt_b01d7', table='pharmacy_goodsreceiptline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceiptline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_goodsreceiptlineevent" ("batch_id", "batch_no", "expiry_date", "id", "item_id", "line_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base", "quantity_units", "receipt_id", "unit_cost", "unit_id") VALUES (NEW."batch_id", NEW."batch_no", NEW."expiry_date", NEW."id", NEW."item_id", NEW."line_total", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."qty_base", NEW."quantity_units", NEW."receipt_id", NEW."unit_cost", NEW."unit_id"); RETURN NULL;', hash='35b4cd64a0fbd431db725cd377463a0df1ae784e', operation='INSERT', pgid='pgtrigger_insert_insert_19f30', table='pharmacy_goodsreceiptline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceiptline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_goodsreceiptlineevent" ("batch_id", "batch_no", "expiry_date", "id", "item_id", "line_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base", "quantity_units", "receipt_id", "unit_cost", "unit_id") VALUES (NEW."batch_id", NEW."batch_no", NEW."expiry_date", NEW."id", NEW."item_id", NEW."line_total", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."qty_base", NEW."quantity_units", NEW."receipt_id", NEW."unit_cost", NEW."unit_id"); RETURN NULL;', hash='6a632b89e97a6a8a76d8dd767fae8f73a810a3e7', operation='UPDATE', pgid='pgtrigger_update_update_1eea1', table='pharmacy_goodsreceiptline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='goodsreceiptline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_goodsreceiptlineevent" ("batch_id", "batch_no", "expiry_date", "id", "item_id", "line_total", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "qty_base", "quantity_units", "receipt_id", "unit_cost", "unit_id") VALUES (OLD."batch_id", OLD."batch_no", OLD."expiry_date", OLD."id", OLD."item_id", OLD."line_total", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."qty_base", OLD."quantity_units", OLD."receipt_id", OLD."unit_cost", OLD."unit_id"); RETURN NULL;', hash='f34b165f9db6ae7b750329808ed93274c4f98b6c', operation='DELETE', pgid='pgtrigger_delete_delete_4dc78', table='pharmacy_goodsreceiptline', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='dispenseline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_units__gt', 0), ('qty_base__gt', 0)), name='pharmacy_dispenseline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='dispenseline',
            constraint=models.CheckConstraint(condition=models.Q(('batch_override', False), ('override_reason__isnull', False), _connector='OR'), name='pharmacy_dispenseline_override_reason'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dispenseline',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='b132abbd706e4aed5599b01bef913fec91c8cab5', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_2d0b5', table='pharmacy_dispenseline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unitconversionevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='78a1937ec86ad41c8c9ee9bf8892afcc96c29231', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_7d126', table='pharmacy_unitconversionevent', when='BEFORE')),
        ),
    ]
