# Generated by Django 5.2.17 on 2026-10-07 16:57

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_creditnote_credit_note_consistent_and_more'),
        ('core', '0008_printtemplate_printtemplateevent_and_more'),
        ('pharmacy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'dispense return',
                'ordering': ['-returned_at', '-id'],
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='stocktransfer',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='stocktransfer',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='stocktransfer',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='cancel_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shortage_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shortage_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shortage_reason',
            field=models.ForeignKey(blank=True, help_text='Why units sent did not arrive (lost or damaged in transit).', limit_choices_to={'category': 'stock_adjust'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='cancel_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='shortage_approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='shortage_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stocktransferevent',
            name='shortage_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Why units sent did not arrive (lost or damaged in transit).', limit_choices_to={'category': 'stock_adjust'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dispenseline',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='0220908669d34cb703e88edffbbbff1f34b05d02', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_9d891', table='pharmacy_dispenseline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dispenseline',
            trigger=pgtrigger.compiler.Trigger(name='dispense_line_eligible', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE line record;', func="\n                    SELECT sl.id, sl.visit_id, sl.quantity, sl.billing_status,\n                           sl.fulfilment_status, sl.authorization_id\n                      INTO line FROM orders_serviceline sl WHERE sl.id = NEW.service_line_id;\n                    IF line.fulfilment_status NOT IN ('pending', 'in_progress') OR NOT (\n                        line.billing_status = 'settled' OR EXISTS (\n                            SELECT 1 FROM orders_performauthorization a\n                             WHERE a.id = line.authorization_id AND a.revoked_at IS NULL\n                               AND a.visit_id = line.visit_id)\n                    ) THEN\n                        RAISE EXCEPTION\n                            'LINE_NOT_ELIGIBLE: service line % is not paid nor authorized', line.id;\n                    END IF;\n                    IF line.visit_id IS DISTINCT FROM (\n                        SELECT d.visit_id FROM pharmacy_dispense d WHERE d.id = NEW.dispense_id\n                    ) THEN\n                        RAISE EXCEPTION 'LINE_NOT_ON_VISIT: service line % is on another visit',\n                            line.id;\n                    END IF;\n                    IF NEW.qty_base + coalesce((\n                        SELECT sum(x.qty_base) FROM pharmacy_dispenseline x\n                         WHERE x.service_line_id = NEW.service_line_id), 0)\n                       > line.quantity - coalesce((\n                        SELECT sum(cl.quantity) FROM billing_creditnoteline cl\n                          JOIN billing_creditnote cn ON cn.id = cl.credit_note_id\n                          JOIN billing_invoiceline il ON il.id = cl.invoice_line_id\n                         WHERE il.service_line_id = NEW.service_line_id AND il.frozen\n                           AND cn.status = 'approved'), 0) THEN\n                        RAISE EXCEPTION\n                            'DISPENSE_EXCEEDS_LINE: more than service line % still needs', line.id;\n                    END IF;\n                    RETURN NEW;\n                ", hash='785dea7ede1f05f0cf3ddcb1c2d9d334218a103d', operation='INSERT', pgid='pgtrigger_dispense_line_eligible_4f819', table='pharmacy_dispenseline', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockbalance',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='f5793db59c4ec4421c0d7fbf283b6a668bb135c0', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_e04f8', table='pharmacy_stockbalance', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stockmove',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='9a52c61f9001083459222572b883c1de52155b61', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_b41b4', table='pharmacy_stockmove', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransfer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stocktransferevent" ("cancel_note", "cancelled_at", "cancelled_by_id", "created_at", "created_by_id", "from_store_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "sent_at", "sent_by_id", "shortage_approved_by_id", "shortage_note", "shortage_reason_id", "status", "to_store_id") VALUES (NEW."cancel_note", NEW."cancelled_at", NEW."cancelled_by_id", NEW."created_at", NEW."created_by_id", NEW."from_store_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."sent_at", NEW."sent_by_id", NEW."shortage_approved_by_id", NEW."shortage_note", NEW."shortage_reason_id", NEW."status", NEW."to_store_id"); RETURN NULL;', hash='ffa19a66eabc18501422a3493dbdf5a614983fed', operation='INSERT', pgid='pgtrigger_insert_insert_c3a37', table='pharmacy_stocktransfer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransfer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_stocktransferevent" ("cancel_note", "cancelled_at", "cancelled_by_id", "created_at", "created_by_id", "from_store_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "sent_at", "sent_by_id", "shortage_approved_by_id", "shortage_note", "shortage_reason_id", "status", "to_store_id") VALUES (NEW."cancel_note", NEW."cancelled_at", NEW."cancelled_by_id", NEW."created_at", NEW."created_by_id", NEW."from_store_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."sent_at", NEW."sent_by_id", NEW."shortage_approved_by_id", NEW."shortage_note", NEW."shortage_reason_id", NEW."status", NEW."to_store_id"); RETURN NULL;', hash='27a834eec43525701dd35508932645713c626070', operation='UPDATE', pgid='pgtrigger_update_update_0f325', table='pharmacy_stocktransfer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='stocktransfer',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_stocktransferevent" ("cancel_note", "cancelled_at", "cancelled_by_id", "created_at", "created_by_id", "from_store_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "sent_at", "sent_by_id", "shortage_approved_by_id", "shortage_note", "shortage_reason_id", "status", "to_store_id") VALUES (OLD."cancel_note", OLD."cancelled_at", OLD."cancelled_by_id", OLD."created_at", OLD."created_by_id", OLD."from_store_id", OLD."id", OLD."note", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."received_at", OLD."received_by_id", OLD."sent_at", OLD."sent_by_id", OLD."shortage_approved_by_id", OLD."shortage_note", OLD."shortage_reason_id", OLD."status", OLD."to_store_id"); RETURN NULL;', hash='0751e4eb2062c7b612d5fceaa7b1783d9b29a764', operation='DELETE', pgid='pgtrigger_delete_delete_87107', table='pharmacy_stocktransfer', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('shortage_reason__isnull', True), models.Q(('shortage_approved_by__isnull', False), ('status', 'received')), _connector='OR'), name='pharmacy_transfer_shortage_documented'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), ('sent_at__isnull', True), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), models.Q(('cancel_note', ''), _negated=True)), _connector='OR'), name='pharmacy_transfer_cancel_documented'),
        ),
        migrations.AddField(
            model_name='dispensereturn',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns', to='billing.creditnote'),
        ),
        migrations.AddField(
            model_name='dispensereturn',
            name='dispense_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pharmacy.dispenseline'),
        ),
        migrations.AddField(
            model_name='dispensereturn',
            name='reason_code',
            field=models.ForeignKey(limit_choices_to={'category': 'stock_adjust'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='dispensereturn',
            name='returned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensereturn',
            name='stock_move',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_return', to='pharmacy.stockmove'),
        ),
        migrations.AddConstraint(
            model_name='dispensereturn',
            constraint=models.CheckConstraint(condition=models.Q(('qty_base__gt', 0)), name='pharmacy_dispensereturn_qty_positive'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dispensereturn',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='467470853c37bff18ae1605ab91a2ef2eb8cec5f', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_0eeb6', table='pharmacy_dispensereturn', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dispensereturn',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='558407af39c2fb5a6c8575a1db505c1c65b899de', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_8bcd8', table='pharmacy_dispensereturn', when='BEFORE')),
        ),
    ]
