# Generated by Django 5.2.17 on 2026-10-10 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_creditnote_credit_note_consistent_and_more'),
        ('core', '0013_dispense_return_reasons'),
        ('pharmacy', '0004_batch_choice_reason_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensereturn',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The second person who approved returning units of a billed line (ADR 0018).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dispensereturn',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('returned_by')), _negated=True), _connector='OR'), name='pharmacy_dispensereturn_second_approver'),
        ),
    ]
