# Generated by Django 5.2.17 on 2026-10-10 11:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_dispense_return_approver'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='item',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='item',
            name='generic_name_ar',
            field=models.CharField(blank=True, help_text='Arabic generic name for the Arabic screens; empty shows the Latin one.', max_length=200),
        ),
        migrations.AddField(
            model_name='itemevent',
            name='generic_name_ar',
            field=models.CharField(blank=True, help_text='Arabic generic name for the Arabic screens; empty shows the Latin one.', max_length=200),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_itemevent" ("active", "barcode", "base_unit_code", "base_unit_name_ar", "base_unit_name_en", "brand_name", "created_at", "form", "generic_name", "generic_name_ar", "id", "is_controlled", "min_stock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reorder_qty", "service_id", "storage", "strength", "updated_at") VALUES (NEW."active", NEW."barcode", NEW."base_unit_code", NEW."base_unit_name_ar", NEW."base_unit_name_en", NEW."brand_name", NEW."created_at", NEW."form", NEW."generic_name", NEW."generic_name_ar", NEW."id", NEW."is_controlled", NEW."min_stock", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reorder_qty", NEW."service_id", NEW."storage", NEW."strength", NEW."updated_at"); RETURN NULL;', hash='4854eb1d7e1679404e4ff3a3511ac24028cbfa5c', operation='INSERT', pgid='pgtrigger_insert_insert_76e01', table='pharmacy_item', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pharmacy_itemevent" ("active", "barcode", "base_unit_code", "base_unit_name_ar", "base_unit_name_en", "brand_name", "created_at", "form", "generic_name", "generic_name_ar", "id", "is_controlled", "min_stock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reorder_qty", "service_id", "storage", "strength", "updated_at") VALUES (NEW."active", NEW."barcode", NEW."base_unit_code", NEW."base_unit_name_ar", NEW."base_unit_name_en", NEW."brand_name", NEW."created_at", NEW."form", NEW."generic_name", NEW."generic_name_ar", NEW."id", NEW."is_controlled", NEW."min_stock", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reorder_qty", NEW."service_id", NEW."storage", NEW."strength", NEW."updated_at"); RETURN NULL;', hash='22f28183f3f269f01546eeb6af61ebddaec52d6d', operation='UPDATE', pgid='pgtrigger_update_update_8732a', table='pharmacy_item', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='item',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pharmacy_itemevent" ("active", "barcode", "base_unit_code", "base_unit_name_ar", "base_unit_name_en", "brand_name", "created_at", "form", "generic_name", "generic_name_ar", "id", "is_controlled", "min_stock", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reorder_qty", "service_id", "storage", "strength", "updated_at") VALUES (OLD."active", OLD."barcode", OLD."base_unit_code", OLD."base_unit_name_ar", OLD."base_unit_name_en", OLD."brand_name", OLD."created_at", OLD."form", OLD."generic_name", OLD."generic_name_ar", OLD."id", OLD."is_controlled", OLD."min_stock", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reorder_qty", OLD."service_id", OLD."storage", OLD."strength", OLD."updated_at"); RETURN NULL;', hash='6cb658b58806135daf9071e738cf5fd7d5ab5cab', operation='DELETE', pgid='pgtrigger_delete_delete_dd905', table='pharmacy_item', when='AFTER')),
        ),
    ]
