# Generated by Django 5.2.17 on 2026-10-07 11:49

import apps.core.db
import django.db.models.deletion
import django.db.models.expressions
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('core', '0006_reason_categories_consultation_service'),
        ('orders', '0001_initial'),
        ('patients', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'bank',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BankEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('destination', models.CharField(choices=[('next_shift', 'Next shift'), ('safe', 'Safe'), ('bank_deposit', 'Bank deposit'), ('supervisor', 'Supervisor')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('handed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'cash handover',
                'ordering': ['-handed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashHandoverEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('destination', models.CharField(choices=[('next_shift', 'Next shift'), ('safe', 'Safe'), ('bank_deposit', 'Bank deposit'), ('supervisor', 'Supervisor')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('handed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('qr', 'QR payment'), ('card', 'Card'), ('patient_credit', 'Patient credit balance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reference_norm', models.GeneratedField(db_persist=True, expression=apps.core.db.NormalizeReference(models.F('reference')), output_field=models.TextField())),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('verification', models.CharField(choices=[('pending', 'Pending verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('duplicate_override', models.BooleanField(default=False, help_text='Supervisor accepted a reference already used for this bank.')),
                ('override_note', models.TextField(blank=True)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payment',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('qr', 'QR payment'), ('card', 'Card'), ('patient_credit', 'Patient credit balance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('verification', models.CharField(choices=[('pending', 'Pending verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('duplicate_override', models.BooleanField(default=False, help_text='Supervisor accepted a reference already used for this bank.')),
                ('override_note', models.TextField(blank=True)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Awaiting approval'), ('approved', 'Approved, not paid'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'refund',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RefundEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Awaiting approval'), ('approved', 'Approved, not paid'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance_note', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'shift',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance_note', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('approved', 'Signed off'), ('flagged', 'Flagged for follow-up')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'shift review',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Till',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'till',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TillEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('allocate', 'Allocation to an invoice'), ('reversal', 'Reversal of an allocation'), ('deallocation', 'De-allocation after a credit note')], default='allocate', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deallocations', to='billing.creditnote')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.invoice')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='payments.allocation')),
            ],
            options={
                'verbose_name': 'allocation',
                'ordering': ['created_at', 'id'],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bank',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_bankevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='b31ce415938b14b251e0024fb2a86dd1dcfb2888', operation='INSERT', pgid='pgtrigger_insert_insert_87063', table='payments_bank', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bank',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_bankevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='a7aaf40c3f89e41eed5cf5ca3b269b0fd2850bcb', operation='UPDATE', pgid='pgtrigger_update_update_5532b', table='payments_bank', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bank',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_bankevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (OLD."active", OLD."code", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order"); RETURN NULL;', hash='e6eca59f4e37d15f7ed9c4c24fdacc613742bfed', operation='DELETE', pgid='pgtrigger_delete_delete_e8cae', table='payments_bank', when='AFTER')),
        ),
        migrations.AddField(
            model_name='bankevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='bankevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='handed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='handed_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='payments.cashhandover'),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='received_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='to_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicates', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='override_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'override'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'transfer_reject'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='override_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='override_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'override'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='patient',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'transfer_reject'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='reversal_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='refund',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.creditnote'),
        ),
        migrations.AddField(
            model_name='refund',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='refund',
            name='reason_code',
            field=models.ForeignKey(limit_choices_to={'category': 'refund'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='service_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.serviceline'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='bank',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='credit_note',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.creditnote'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='decided_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='paid_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='patient',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='payments.refund'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='reason_code',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'category': 'refund'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='requested_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='service_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.serviceline'),
        ),
        migrations.AddField(
            model_name='shift',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='variance_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'variance'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='refundevent',
            name='shift',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='refund',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='shift',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='shift',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='to_shift',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_out', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='to_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers_in', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Shift of the acting user when the row was written.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='shiftevent',
            name='cashier',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftevent',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='shiftevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='shiftevent',
            name='variance_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'variance'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='core.reasoncode'),
        ),
        migrations.AddField(
            model_name='shiftreview',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftreview',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='payments.shift'),
        ),
        migrations.AddField(
            model_name='shiftevent',
            name='till',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.till'),
        ),
        migrations.AddField(
            model_name='shift',
            name='till',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='payments.till'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='till',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_tillevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='68240424049e152ff00cfbf400a31e03070405d0', operation='INSERT', pgid='pgtrigger_insert_insert_58aa5', table='payments_till', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='till',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_tillevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."code", NEW."id", NEW."name_ar", NEW."name_en", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='40f1ffb67e462ac3ee2cfd8d34e73c42c418e365', operation='UPDATE', pgid='pgtrigger_update_update_e71f1', table='payments_till', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='till',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_tillevent" ("active", "code", "id", "name_ar", "name_en", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."active", OLD."code", OLD."id", OLD."name_ar", OLD."name_en", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='894e9958419274aaf8962d262898a07f3080d379', operation='DELETE', pgid='pgtrigger_delete_delete_db47a', table='payments_till', when='AFTER')),
        ),
        migrations.AddField(
            model_name='tillevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='tillevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='payments.till'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bankevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='7602d8f092da47d683755f133a6c900841d99e4d', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_25171', table='payments_bankevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refundevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='7cf1b09faaeb257abbb702d0c27edf94016ca5fb', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_3a07e', table='payments_refundevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'requested_at'], name='payments_refund_status_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['patient'], name='payments_refund_patient_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['requested', 'approved', 'rejected', 'paid'])), name='payments_refund_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['cash', 'bank_transfer'])), name='payments_refund_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_refund_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('credit_note__isnull', False), ('service_line__isnull', False), _connector='OR'), name='payments_refund_has_source'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'requested'), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False)), _connector='OR'), name='payments_refund_decision_documented'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), models.Q(('paid_at__isnull', False), ('paid_by__isnull', False), ('shift__isnull', False)), _connector='OR'), name='payments_refund_payment_documented'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'bank_transfer'), _negated=True), ('bank__isnull', False), _connector='OR'), name='payments_refund_transfer_has_bank'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='refund_final', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" IN (\'paid\', \'rejected\'))', func="RAISE EXCEPTION 'REFUND_FINAL: paid or rejected refunds never change (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='4820b2346f5c3ba9111d2d886089cf7c89a802ca', operation='UPDATE OR DELETE', pgid='pgtrigger_refund_final_c8066', table='payments_refund', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id)\n               AND NOT EXISTS (\n                   SELECT 1 FROM payments_shift s WHERE s.id = NEW.shift_id AND s.status = 'open'\n               ) THEN\n                RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                    NEW.shift_id, TG_TABLE_NAME;\n            END IF;\n            RETURN NEW;\n        ", hash='52101fa416c656e227c782b94da1c44a887352a6', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_531f0', table='payments_refund', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_refundevent" ("amount", "bank_id", "credit_note_id", "decided_at", "decided_by_id", "decision_note", "id", "method", "number", "paid_at", "paid_by_id", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "reference", "requested_at", "requested_by_id", "service_line_id", "shift_id", "status") VALUES (NEW."amount", NEW."bank_id", NEW."credit_note_id", NEW."decided_at", NEW."decided_by_id", NEW."decision_note", NEW."id", NEW."method", NEW."number", NEW."paid_at", NEW."paid_by_id", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason_code_id", NEW."reason_note", NEW."reference", NEW."requested_at", NEW."requested_by_id", NEW."service_line_id", NEW."shift_id", NEW."status"); RETURN NULL;', hash='3a20e62bcb48ebd24c80b1686bd1e25ab832a8cd', operation='INSERT', pgid='pgtrigger_insert_insert_eff19', table='payments_refund', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_refundevent" ("amount", "bank_id", "credit_note_id", "decided_at", "decided_by_id", "decision_note", "id", "method", "number", "paid_at", "paid_by_id", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "reference", "requested_at", "requested_by_id", "service_line_id", "shift_id", "status") VALUES (NEW."amount", NEW."bank_id", NEW."credit_note_id", NEW."decided_at", NEW."decided_by_id", NEW."decision_note", NEW."id", NEW."method", NEW."number", NEW."paid_at", NEW."paid_by_id", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason_code_id", NEW."reason_note", NEW."reference", NEW."requested_at", NEW."requested_by_id", NEW."service_line_id", NEW."shift_id", NEW."status"); RETURN NULL;', hash='038735a6be3ea88fb91ffe9ced160bc9fa2bd1a8', operation='UPDATE', pgid='pgtrigger_update_update_1c17b', table='payments_refund', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_refundevent" ("amount", "bank_id", "credit_note_id", "decided_at", "decided_by_id", "decision_note", "id", "method", "number", "paid_at", "paid_by_id", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_code_id", "reason_note", "reference", "requested_at", "requested_by_id", "service_line_id", "shift_id", "status") VALUES (OLD."amount", OLD."bank_id", OLD."credit_note_id", OLD."decided_at", OLD."decided_by_id", OLD."decision_note", OLD."id", OLD."method", OLD."number", OLD."paid_at", OLD."paid_by_id", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reason_code_id", OLD."reason_note", OLD."reference", OLD."requested_at", OLD."requested_by_id", OLD."service_line_id", OLD."shift_id", OLD."status"); RETURN NULL;', hash='82d7702eb9c84b08f4fa76a99ed662e52b5b9bad', operation='DELETE', pgid='pgtrigger_delete_delete_28c57', table='payments_refund', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='paymentevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='899bbfbff907f735235a7313123b9775d62e0a14', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_20207', table='payments_paymentevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['shift', 'method'], name='payments_payment_shift_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', '-created_at'], name='payments_payment_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('verification', 'pending')), fields=['verification', 'created_at'], name='payments_payment_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank', 'reference_norm'], name='payments_payment_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['cash', 'bank_transfer', 'qr', 'card', 'patient_credit'])), name='payments_payment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('verification__in', ['pending', 'confirmed', 'rejected'])), name='payments_payment_verification_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_of__isnull', True), ('amount__gt', 0)), models.Q(('reversal_of__isnull', False), ('amount__lt', 0)), _connector='OR'), name='payments_payment_amount_sign'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['bank_transfer', 'qr', 'card']), models.Q(('bank__isnull', True), ('reference', ''), ('verification', 'confirmed')), _connector='OR'), name='payments_payment_cash_is_confirmed_without_bank'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method__in', ['bank_transfer', 'qr', 'card']), _negated=True), models.Q(('bank__isnull', False), models.Q(('reference', ''), _negated=True)), _connector='OR'), name='payments_payment_bank_needs_reference'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method__in', ['bank_transfer', 'qr', 'card']), _negated=True), ('verification', 'pending'), models.Q(('verified_at__isnull', False), ('verified_by__isnull', False)), _connector='OR'), name='payments_payment_verification_documented'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification', 'rejected'), _negated=True), ('rejection_reason__isnull', False), _connector='OR'), name='payments_payment_rejection_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('duplicate_override', False), models.Q(('duplicate_of__isnull', False), ('override_at__isnull', False), ('override_by__isnull', False), ('override_reason__isnull', False)), _connector='OR'), name='payments_payment_override_documented'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('method__in', ['bank_transfer', 'qr', 'card']), ('duplicate_override', False), ('reversal_of__isnull', True)), fields=('bank', 'reference_norm'), name='payments_payment_bank_reference_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='payment_money_readonly', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."number" IS DISTINCT FROM (NEW."number") OR OLD."shift_id" IS DISTINCT FROM (NEW."shift_id") OR OLD."patient_id" IS DISTINCT FROM (NEW."patient_id") OR OLD."method" IS DISTINCT FROM (NEW."method") OR OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."bank_id" IS DISTINCT FROM (NEW."bank_id") OR OLD."reference" IS DISTINCT FROM (NEW."reference") OR OLD."transfer_date" IS DISTINCT FROM (NEW."transfer_date") OR OLD."reversal_of_id" IS DISTINCT FROM (NEW."reversal_of_id") OR OLD."created_by_id" IS DISTINCT FROM (NEW."created_by_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='cb5d7c5081b3ccce407eab6a86d01d837693582c', operation='UPDATE', pgid='pgtrigger_payment_money_readonly_04cd1', table='payments_payment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='payment_no_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'PAYMENT_PERMANENT: payments are never deleted; reverse them (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='ce3153c040c2529266162c64d8e9ab1456e031b7', operation='DELETE', pgid='pgtrigger_payment_no_delete_4d721', table='payments_payment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='payment_rejected_final', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."verification" = \'rejected\')', func="RAISE EXCEPTION 'PAYMENT_REJECTED: a rejected transfer never changes (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='aa2fc170a355e5ef916b3c15b4e7914fedb03ec2', operation='UPDATE', pgid='pgtrigger_payment_rejected_final_6e8c6', table='payments_payment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id)\n               AND NOT EXISTS (\n                   SELECT 1 FROM payments_shift s WHERE s.id = NEW.shift_id AND s.status = 'open'\n               ) THEN\n                RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                    NEW.shift_id, TG_TABLE_NAME;\n            END IF;\n            RETURN NEW;\n        ", hash='dd9618cc8c9f3137b7d32822cb79e12fde76984b', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_b1f63', table='payments_payment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_paymentevent" ("amount", "bank_id", "created_at", "created_by_id", "duplicate_of_id", "duplicate_override", "id", "method", "note", "number", "override_at", "override_by_id", "override_note", "override_reason_id", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "rejection_note", "rejection_reason_id", "reversal_of_id", "sender_name", "shift_id", "transfer_date", "verification", "verified_at", "verified_by_id") VALUES (NEW."amount", NEW."bank_id", NEW."created_at", NEW."created_by_id", NEW."duplicate_of_id", NEW."duplicate_override", NEW."id", NEW."method", NEW."note", NEW."number", NEW."override_at", NEW."override_by_id", NEW."override_note", NEW."override_reason_id", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference", NEW."rejection_note", NEW."rejection_reason_id", NEW."reversal_of_id", NEW."sender_name", NEW."shift_id", NEW."transfer_date", NEW."verification", NEW."verified_at", NEW."verified_by_id"); RETURN NULL;', hash='44c516e943a5de2f2f2c6cd0d5fd79b31cc76e39', operation='INSERT', pgid='pgtrigger_insert_insert_24a65', table='payments_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."bank_id" IS DISTINCT FROM (NEW."bank_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."created_by_id" IS DISTINCT FROM (NEW."created_by_id") OR OLD."duplicate_of_id" IS DISTINCT FROM (NEW."duplicate_of_id") OR OLD."duplicate_override" IS DISTINCT FROM (NEW."duplicate_override") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."method" IS DISTINCT FROM (NEW."method") OR OLD."note" IS DISTINCT FROM (NEW."note") OR OLD."number" IS DISTINCT FROM (NEW."number") OR OLD."override_at" IS DISTINCT FROM (NEW."override_at") OR OLD."override_by_id" IS DISTINCT FROM (NEW."override_by_id") OR OLD."override_note" IS DISTINCT FROM (NEW."override_note") OR OLD."override_reason_id" IS DISTINCT FROM (NEW."override_reason_id") OR OLD."patient_id" IS DISTINCT FROM (NEW."patient_id") OR OLD."reference" IS DISTINCT FROM (NEW."reference") OR OLD."rejection_note" IS DISTINCT FROM (NEW."rejection_note") OR OLD."rejection_reason_id" IS DISTINCT FROM (NEW."rejection_reason_id") OR OLD."reversal_of_id" IS DISTINCT FROM (NEW."reversal_of_id") OR OLD."sender_name" IS DISTINCT FROM (NEW."sender_name") OR OLD."shift_id" IS DISTINCT FROM (NEW."shift_id") OR OLD."transfer_date" IS DISTINCT FROM (NEW."transfer_date") OR OLD."verification" IS DISTINCT FROM (NEW."verification") OR OLD."verified_at" IS DISTINCT FROM (NEW."verified_at") OR OLD."verified_by_id" IS DISTINCT FROM (NEW."verified_by_id"))', func='INSERT INTO "payments_paymentevent" ("amount", "bank_id", "created_at", "created_by_id", "duplicate_of_id", "duplicate_override", "id", "method", "note", "number", "override_at", "override_by_id", "override_note", "override_reason_id", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "rejection_note", "rejection_reason_id", "reversal_of_id", "sender_name", "shift_id", "transfer_date", "verification", "verified_at", "verified_by_id") VALUES (NEW."amount", NEW."bank_id", NEW."created_at", NEW."created_by_id", NEW."duplicate_of_id", NEW."duplicate_override", NEW."id", NEW."method", NEW."note", NEW."number", NEW."override_at", NEW."override_by_id", NEW."override_note", NEW."override_reason_id", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference", NEW."rejection_note", NEW."rejection_reason_id", NEW."reversal_of_id", NEW."sender_name", NEW."shift_id", NEW."transfer_date", NEW."verification", NEW."verified_at", NEW."verified_by_id"); RETURN NULL;', hash='bf6442c75d41e0089070ffab575fd29030ba9333', operation='UPDATE', pgid='pgtrigger_update_update_dd546', table='payments_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_paymentevent" ("amount", "bank_id", "created_at", "created_by_id", "duplicate_of_id", "duplicate_override", "id", "method", "note", "number", "override_at", "override_by_id", "override_note", "override_reason_id", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference", "rejection_note", "rejection_reason_id", "reversal_of_id", "sender_name", "shift_id", "transfer_date", "verification", "verified_at", "verified_by_id") VALUES (OLD."amount", OLD."bank_id", OLD."created_at", OLD."created_by_id", OLD."duplicate_of_id", OLD."duplicate_override", OLD."id", OLD."method", OLD."note", OLD."number", OLD."override_at", OLD."override_by_id", OLD."override_note", OLD."override_reason_id", OLD."patient_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reference", OLD."rejection_note", OLD."rejection_reason_id", OLD."reversal_of_id", OLD."sender_name", OLD."shift_id", OLD."transfer_date", OLD."verification", OLD."verified_at", OLD."verified_by_id"); RETURN NULL;', hash='50f454f0fae593a7da2e5cf34a3ad59d6692533c', operation='DELETE', pgid='pgtrigger_delete_delete_b2c62', table='payments_payment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandoverevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='d6e366f3829bb428dfce13097962318e63edc387', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_4696c', table='payments_cashhandoverevent', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='cashhandover',
            constraint=models.CheckConstraint(condition=models.Q(('destination__in', ['next_shift', 'safe', 'bank_deposit', 'supervisor'])), name='payments_handover_dest_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashhandover',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_handover_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashhandover',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination', 'next_shift'), _negated=True), ('to_shift__isnull', False), _connector='OR'), name='payments_handover_next_shift_named'),
        ),
        migrations.AddConstraint(
            model_name='cashhandover',
            constraint=models.CheckConstraint(condition=models.Q(('to_shift', models.F('shift')), _negated=True), name='payments_handover_not_to_itself'),
        ),
        migrations.AddConstraint(
            model_name='cashhandover',
            constraint=models.CheckConstraint(condition=models.Q(('received_at__isnull', True), ('received_by__isnull', False), _connector='OR'), name='payments_handover_receipt_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id)\n               AND NOT EXISTS (\n                   SELECT 1 FROM payments_shift s WHERE s.id = NEW.shift_id AND s.status = 'open'\n               ) THEN\n                RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                    NEW.shift_id, TG_TABLE_NAME;\n            END IF;\n            RETURN NEW;\n        ", hash='582b11bf919a26019fee36d1a5540bdb56f7c58f', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_68b4b', table='payments_cashhandover', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='to_shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.to_shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.to_shift_id IS DISTINCT FROM OLD.to_shift_id)\n               AND NOT EXISTS (\n                   SELECT 1 FROM payments_shift s WHERE s.id = NEW.to_shift_id AND s.status = 'open'\n               ) THEN\n                RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                    NEW.to_shift_id, TG_TABLE_NAME;\n            END IF;\n            RETURN NEW;\n        ", hash='8b95886922dfec6b5076344f232ec1f7b7f99f2b', operation='INSERT OR UPDATE', pgid='pgtrigger_to_shift_must_be_open_19f42', table='payments_cashhandover', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_cashhandoverevent" ("amount", "bank_reference", "destination", "handed_at", "handed_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "shift_id", "to_shift_id", "to_user_id") VALUES (NEW."amount", NEW."bank_reference", NEW."destination", NEW."handed_at", NEW."handed_by_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."shift_id", NEW."to_shift_id", NEW."to_user_id"); RETURN NULL;', hash='54baac466bcad6a7485e1d4711e4cf713f4ed7c2', operation='INSERT', pgid='pgtrigger_insert_insert_66fff', table='payments_cashhandover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_cashhandoverevent" ("amount", "bank_reference", "destination", "handed_at", "handed_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "shift_id", "to_shift_id", "to_user_id") VALUES (NEW."amount", NEW."bank_reference", NEW."destination", NEW."handed_at", NEW."handed_by_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."shift_id", NEW."to_shift_id", NEW."to_user_id"); RETURN NULL;', hash='9ad2744281fd1910c15e7796a1aa7d9c58d31ba5', operation='UPDATE', pgid='pgtrigger_update_update_fcacb', table='payments_cashhandover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_cashhandoverevent" ("amount", "bank_reference", "destination", "handed_at", "handed_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "shift_id", "to_shift_id", "to_user_id") VALUES (OLD."amount", OLD."bank_reference", OLD."destination", OLD."handed_at", OLD."handed_by_id", OLD."id", OLD."note", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."received_at", OLD."received_by_id", OLD."shift_id", OLD."to_shift_id", OLD."to_user_id"); RETURN NULL;', hash='db412773f6ff2d91f2434e166825afb9ca5f4147', operation='DELETE', pgid='pgtrigger_delete_delete_4965e', table='payments_cashhandover', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['invoice'], name='payments_alloc_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['allocate', 'reversal', 'deallocation'])), name='payments_allocation_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'allocate'), ('amount__gt', 0), ('reversal_of__isnull', True), ('credit_note__isnull', True)), models.Q(('kind', 'reversal'), ('amount__lt', 0), ('reversal_of__isnull', False)), models.Q(('kind', 'deallocation'), ('amount__lt', 0), ('credit_note__isnull', False), ('reversal_of__isnull', True)), _connector='OR'), name='payments_allocation_kind_shape'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocation',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='8fe118ea86aea8dce0630483a8e27492d04ab140', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_698ca', table='payments_allocation', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='shiftreview',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['approved', 'flagged'])), name='payments_shiftreview_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='shiftreview',
            constraint=models.CheckConstraint(condition=models.Q(('outcome', 'approved'), models.Q(('note', ''), _negated=True), _connector='OR'), name='payments_shiftreview_flag_explained'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shiftreview',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'APPEND_ONLY: rows are append-only (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='a93e31424589db1826bb95561cfe8cd3fbb88fd3', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_f0da0', table='payments_shiftreview', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shiftevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='7b05e0e398d09a547dc268b160dd4233cdaff206', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_b5209', table='payments_shiftevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['cashier', '-opened_at'], name='payments_shift_cashier_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', '-closed_at'], name='payments_shift_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'closed'])), name='payments_shift_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('cashier',), name='payments_shift_one_open_per_cashier'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_float__gte', 0)), name='payments_shift_float_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('counted_cash__isnull', True), ('counted_cash__gte', 0), _connector='OR'), name='payments_shift_counted_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'closed'), _negated=True), models.Q(('closed_at__isnull', False), ('closed_by__isnull', False), ('counted_cash__isnull', False), ('expected_cash__isnull', False), ('variance__isnull', False)), _connector='OR'), name='payments_shift_close_documented'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('variance__isnull', True), ('variance', django.db.models.expressions.CombinedExpression(models.F('counted_cash'), '-', models.F('expected_cash'))), _connector='OR'), name='payments_shift_variance_is_counted_minus_expected'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('variance__isnull', True), ('variance', 0), ('variance_reason__isnull', False), _connector='OR'), name='payments_shift_variance_explained'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), ('closed_at__gte', models.F('opened_at')), _connector='OR'), name='payments_shift_close_after_open'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shift',
            trigger=pgtrigger.compiler.Trigger(name='shift_closed', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" = \'closed\')', func="RAISE EXCEPTION 'SHIFT_CLOSED: a closed shift never changes (table %, operation %)', TG_TABLE_NAME, TG_OP; RETURN NULL;", hash='8d2fb3efc4658499cfbfc376db8730e47b5f0050', operation='UPDATE OR DELETE', pgid='pgtrigger_shift_closed_9dfad', table='payments_shift', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shift',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_shiftevent" ("cashier_id", "closed_at", "closed_by_id", "counted_cash", "expected_cash", "id", "note", "number", "opened_at", "opening_float", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "till_id", "variance", "variance_note", "variance_reason_id") VALUES (NEW."cashier_id", NEW."closed_at", NEW."closed_by_id", NEW."counted_cash", NEW."expected_cash", NEW."id", NEW."note", NEW."number", NEW."opened_at", NEW."opening_float", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."till_id", NEW."variance", NEW."variance_note", NEW."variance_reason_id"); RETURN NULL;', hash='a6abe6f182a000830be5800c796df76f5f52adf0', operation='INSERT', pgid='pgtrigger_insert_insert_6cace', table='payments_shift', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shift',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_shiftevent" ("cashier_id", "closed_at", "closed_by_id", "counted_cash", "expected_cash", "id", "note", "number", "opened_at", "opening_float", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "till_id", "variance", "variance_note", "variance_reason_id") VALUES (NEW."cashier_id", NEW."closed_at", NEW."closed_by_id", NEW."counted_cash", NEW."expected_cash", NEW."id", NEW."note", NEW."number", NEW."opened_at", NEW."opening_float", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."till_id", NEW."variance", NEW."variance_note", NEW."variance_reason_id"); RETURN NULL;', hash='a439aea1f8f2131a171bb3021d944e444d75abe6', operation='UPDATE', pgid='pgtrigger_update_update_36fb6', table='payments_shift', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shift',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_shiftevent" ("cashier_id", "closed_at", "closed_by_id", "counted_cash", "expected_cash", "id", "note", "number", "opened_at", "opening_float", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "till_id", "variance", "variance_note", "variance_reason_id") VALUES (OLD."cashier_id", OLD."closed_at", OLD."closed_by_id", OLD."counted_cash", OLD."expected_cash", OLD."id", OLD."note", OLD."number", OLD."opened_at", OLD."opening_float", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."till_id", OLD."variance", OLD."variance_note", OLD."variance_reason_id"); RETURN NULL;', hash='9e46493603594a990ac0ba618ab888caa39db28e', operation='DELETE', pgid='pgtrigger_delete_delete_c7952', table='payments_shift', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tillevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='1dc5f3c0d27a1616ba8d645382e3acebcf1ac917', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_f5e23', table='payments_tillevent', when='BEFORE')),
        ),
    ]
