# Generated by Django 5.2.17 on 2026-10-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_banks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='payments.allocation'),
        ),
    ]
