# Generated by Django 5.2.17 on 2026-10-07 16:57

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


def _fill_reference_norm(table: str, bank_only: bool):
    """Write ``reference_norm`` from the domain's one definition (it replaces the SQL
    function, whose normalization differed). User triggers are off for the backfill: the
    money columns of these rows are read-only and rejected payments never change."""

    def run(apps, schema_editor):
        from domain.payments import normalize_reference

        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"SELECT id, reference, {'method' if bank_only else 'NULL'} FROM {table}")
            rows = cursor.fetchall()
            if not rows:
                return
            cursor.execute(f"ALTER TABLE {table} DISABLE TRIGGER USER")
            for pk, reference, method in rows:
                keep = not bank_only or method in ("bank_transfer", "qr", "card")
                norm = normalize_reference(reference or "") if keep else ""
                cursor.execute(f"UPDATE {table} SET reference_norm = %s WHERE id = %s", [norm, pk])
            cursor.execute(f"ALTER TABLE {table} ENABLE TRIGGER USER")

    return run


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_creditnote_credit_note_consistent_and_more'),
        ('core', '0008_printtemplate_printtemplateevent_and_more'),
        ('orders', '0003_remove_serviceline_line_guard_and_more'),
        ('patients', '0001_initial'),
        ('payments', '0003_allocation_reversal_partial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashhandover',
            name='shift_must_be_open',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashhandover',
            name='to_shift_must_be_open',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashhandover',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashhandover',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashhandover',
            name='delete_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='payment_money_readonly',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='shift_must_be_open',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='refund',
            name='shift_must_be_open',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='shift',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='shift',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='shift',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_payment_bank_needs_reference',
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='cancel_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='cancel_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashhandoverevent',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='close_report',
            field=models.JSONField(blank=True, help_text='The shift report as it stood at close (FEATURES 7.3); never recomputed.', null=True),
        ),
        migrations.AddField(
            model_name='shiftevent',
            name='close_report',
            field=models.JSONField(blank=True, help_text='The shift report as it stood at close (FEATURES 7.3); never recomputed.', null=True),
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_payment_bank_reference_unique',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_payment_ref_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_norm',
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_norm',
            field=models.CharField(blank=True, default='', editable=False, help_text='``domain.payments.normalize_reference(reference)``, written by the service.', max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(_fill_reference_norm('payments_payment', True), migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('method__in', ['bank_transfer', 'qr', 'card']), ('duplicate_override', False), ('reversal_of__isnull', True)), fields=('bank', 'reference_norm'), name='payments_payment_bank_reference_unique'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank', 'reference_norm'], name='payments_payment_ref_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocation',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='3971fbcc5da9484ed62921370d5383a0a21b5db1', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_3dccb', table='payments_allocation', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocation',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id) THEN\n                PERFORM 1 FROM payments_shift s\n                 WHERE s.id = NEW.shift_id AND s.status = 'open' FOR SHARE;\n                IF NOT FOUND THEN\n                    RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                        NEW.shift_id, TG_TABLE_NAME;\n                END IF;\n            END IF;\n            RETURN NEW;\n        ", hash='bd187599d672d619f3336403fe859e64f2306baa', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_5ce32', table='payments_allocation', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='d26196502c104aeeb1b6e4d7ff4c96446e31cacf', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_df593', table='payments_cashhandover', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id) THEN\n                PERFORM 1 FROM payments_shift s\n                 WHERE s.id = NEW.shift_id AND s.status = 'open' FOR SHARE;\n                IF NOT FOUND THEN\n                    RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                        NEW.shift_id, TG_TABLE_NAME;\n                END IF;\n            END IF;\n            RETURN NEW;\n        ", hash='52a1a0abec2bbba0da8dce022851f8bf2eeae3f8', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_68b4b', table='payments_cashhandover', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='to_shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.to_shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.to_shift_id IS DISTINCT FROM OLD.to_shift_id) THEN\n                PERFORM 1 FROM payments_shift s\n                 WHERE s.id = NEW.to_shift_id AND s.status = 'open' FOR SHARE;\n                IF NOT FOUND THEN\n                    RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                        NEW.to_shift_id, TG_TABLE_NAME;\n                END IF;\n            END IF;\n            RETURN NEW;\n        ", hash='6c44be43314ca2ae3c415643b1c0574a5db99de6', operation='INSERT OR UPDATE', pgid='pgtrigger_to_shift_must_be_open_19f42', table='payments_cashhandover', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='handover_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF TG_OP = 'DELETE' THEN\n                        RAISE EXCEPTION 'HANDOVER_PERMANENT: handover % is never deleted', OLD.id;\n                    END IF;\n                    IF ROW(NEW.number, NEW.shift_id, NEW.destination, NEW.to_shift_id,\n                           NEW.to_user_id, NEW.amount, NEW.bank_reference, NEW.handed_by_id,\n                           NEW.handed_at)\n                       IS DISTINCT FROM\n                       ROW(OLD.number, OLD.shift_id, OLD.destination, OLD.to_shift_id,\n                           OLD.to_user_id, OLD.amount, OLD.bank_reference, OLD.handed_by_id,\n                           OLD.handed_at) THEN\n                        RAISE EXCEPTION 'HANDOVER_READONLY: handover % never changes', OLD.id;\n                    END IF;\n                    IF ROW(NEW.received_at, NEW.received_by_id)\n                       IS DISTINCT FROM ROW(OLD.received_at, OLD.received_by_id) THEN\n                        IF OLD.received_at IS NOT NULL OR OLD.cancelled_at IS NOT NULL THEN\n                            RAISE EXCEPTION 'HANDOVER_FINAL: handover % is already settled',\n                                OLD.id;\n                        END IF;\n                        IF NEW.to_shift_id IS NOT NULL AND NOT EXISTS (\n                            SELECT 1 FROM payments_shift s\n                             WHERE s.id = NEW.to_shift_id AND s.status = 'open'\n                        ) THEN\n                            RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                                NEW.to_shift_id, TG_TABLE_NAME;\n                        END IF;\n                    END IF;\n                    IF ROW(NEW.cancelled_at, NEW.cancelled_by_id, NEW.cancel_note)\n                       IS DISTINCT FROM ROW(OLD.cancelled_at, OLD.cancelled_by_id, OLD.cancel_note)\n                    THEN\n                        IF OLD.received_at IS NOT NULL OR OLD.cancelled_at IS NOT NULL THEN\n                            RAISE EXCEPTION 'HANDOVER_FINAL: handover % is already settled',\n                                OLD.id;\n                        END IF;\n                        IF NOT EXISTS (\n                            SELECT 1 FROM payments_shift s\n                             WHERE s.id = OLD.shift_id AND s.status = 'open'\n                        ) THEN\n                            RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                                OLD.shift_id, TG_TABLE_NAME;\n                        END IF;\n                    END IF;\n                    IF TG_OP = 'DELETE' THEN\n                        RETURN OLD;\n                    END IF;\n                    RETURN NEW;\n                ", hash='6146af54a8050285c2978fa5935fcb66f7b0fff9', operation='UPDATE OR DELETE', pgid='pgtrigger_handover_guard_ebeeb', table='payments_cashhandover', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_cashhandoverevent" ("amount", "bank_reference", "cancel_note", "cancelled_at", "cancelled_by_id", "destination", "handed_at", "handed_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "shift_id", "to_shift_id", "to_user_id") VALUES (NEW."amount", NEW."bank_reference", NEW."cancel_note", NEW."cancelled_at", NEW."cancelled_by_id", NEW."destination", NEW."handed_at", NEW."handed_by_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."shift_id", NEW."to_shift_id", NEW."to_user_id"); RETURN NULL;', hash='0a2e0d1b8542e2892056adf14c383ba11a59d843', operation='INSERT', pgid='pgtrigger_insert_insert_66fff', table='payments_cashhandover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_cashhandoverevent" ("amount", "bank_reference", "cancel_note", "cancelled_at", "cancelled_by_id", "destination", "handed_at", "handed_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "shift_id", "to_shift_id", "to_user_id") VALUES (NEW."amount", NEW."bank_reference", NEW."cancel_note", NEW."cancelled_at", NEW."cancelled_by_id", NEW."destination", NEW."handed_at", NEW."handed_by_id", NEW."id", NEW."note", NEW."number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."received_at", NEW."received_by_id", NEW."shift_id", NEW."to_shift_id", NEW."to_user_id"); RETURN NULL;', hash='73d5939d95d476880f1f7e8458985309b5ed52c8', operation='UPDATE', pgid='pgtrigger_update_update_fcacb', table='payments_cashhandover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashhandover',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_cashhandoverevent" ("amount", "bank_reference", "cancel_note", "cancelled_at", "cancelled_by_id", "destination", "handed_at", "handed_by_id", "id", "note", "number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "received_at", "received_by_id", "shift_id", "to_shift_id", "to_user_id") VALUES (OLD."amount", OLD."bank_reference", OLD."cancel_note", OLD."cancelled_at", OLD."cancelled_by_id", OLD."destination", OLD."handed_at", OLD."handed_by_id", OLD."id", OLD."note", OLD."number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."received_at", OLD."received_by_id", OLD."shift_id", OLD."to_shift_id", OLD."to_user_id"); RETURN NULL;', hash='fe251b623bda58a9d7a4d8729c5b7152e6a04aa2', operation='DELETE', pgid='pgtrigger_delete_delete_4965e', table='payments_cashhandover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='3a7c14787175afb908d335f7968e9af24f0e3623', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_a90db', table='payments_payment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='payment_money_readonly', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."number" IS DISTINCT FROM (NEW."number") OR OLD."shift_id" IS DISTINCT FROM (NEW."shift_id") OR OLD."patient_id" IS DISTINCT FROM (NEW."patient_id") OR OLD."method" IS DISTINCT FROM (NEW."method") OR OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."bank_id" IS DISTINCT FROM (NEW."bank_id") OR OLD."reference" IS DISTINCT FROM (NEW."reference") OR OLD."reference_norm" IS DISTINCT FROM (NEW."reference_norm") OR OLD."transfer_date" IS DISTINCT FROM (NEW."transfer_date") OR OLD."reversal_of_id" IS DISTINCT FROM (NEW."reversal_of_id") OR OLD."created_by_id" IS DISTINCT FROM (NEW."created_by_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='2bdde28ef5baef093baeb0c33cf79296503bb4ab', operation='UPDATE', pgid='pgtrigger_payment_money_readonly_04cd1', table='payments_payment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='payment_verification_forward', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF NEW.verification IS DISTINCT FROM OLD.verification AND NOT (\n                        (OLD.verification = 'pending'\n                         AND NEW.verification IN ('confirmed', 'rejected'))\n                        OR (OLD.verification = 'confirmed' AND NEW.verification = 'rejected')\n                    ) THEN\n                        RAISE EXCEPTION\n                            'PAYMENT_VERIFICATION_TRANSITION: payment % cannot go from % to %',\n                            OLD.id, OLD.verification, NEW.verification;\n                    END IF;\n                    RETURN NEW;\n                ", hash='f91bde41c44bedc195e3ae5fef5def55416fc05d', operation='UPDATE', pgid='pgtrigger_payment_verification_forward_0cbec', table='payments_payment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id) THEN\n                PERFORM 1 FROM payments_shift s\n                 WHERE s.id = NEW.shift_id AND s.status = 'open' FOR SHARE;\n                IF NOT FOUND THEN\n                    RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                        NEW.shift_id, TG_TABLE_NAME;\n                END IF;\n            END IF;\n            RETURN NEW;\n        ", hash='5b6be3904fb5b037bb20d15e729a49cdddc0b104', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_b1f63', table='payments_payment', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='f841a2aade8b239e1ee3c7008b05528c4ec84859', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_de4e1', table='payments_refund', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='refund_request_readonly', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."number" IS DISTINCT FROM (NEW."number") OR OLD."patient_id" IS DISTINCT FROM (NEW."patient_id") OR OLD."amount" IS DISTINCT FROM (NEW."amount") OR OLD."method" IS DISTINCT FROM (NEW."method") OR OLD."bank_id" IS DISTINCT FROM (NEW."bank_id") OR OLD."reference" IS DISTINCT FROM (NEW."reference") OR OLD."credit_note_id" IS DISTINCT FROM (NEW."credit_note_id") OR OLD."service_line_id" IS DISTINCT FROM (NEW."service_line_id") OR OLD."reason_code_id" IS DISTINCT FROM (NEW."reason_code_id") OR OLD."reason_note" IS DISTINCT FROM (NEW."reason_note") OR OLD."requested_by_id" IS DISTINCT FROM (NEW."requested_by_id") OR OLD."requested_at" IS DISTINCT FROM (NEW."requested_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='502535bfe8d860aa197f98af6e413ca648ac1f01', operation='UPDATE', pgid='pgtrigger_refund_request_readonly_09a9f', table='payments_refund', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='refund_forward', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF NEW.status IS DISTINCT FROM OLD.status AND NOT (\n                        (OLD.status = 'requested' AND NEW.status IN ('approved', 'rejected'))\n                        OR (OLD.status = 'approved' AND NEW.status IN ('paid', 'rejected'))\n                    ) THEN\n                        RAISE EXCEPTION 'REFUND_TRANSITION: refund % cannot go from % to %',\n                            OLD.id, OLD.status, NEW.status;\n                    END IF;\n                    IF OLD.status = 'approved' AND NEW.status IN ('approved', 'paid') AND (\n                        NEW.decided_by_id IS DISTINCT FROM OLD.decided_by_id\n                        OR NEW.decided_at IS DISTINCT FROM OLD.decided_at\n                        OR NEW.decision_note IS DISTINCT FROM OLD.decision_note) THEN\n                        RAISE EXCEPTION 'REFUND_DECISION_FINAL: refund % was already approved',\n                            OLD.id;\n                    END IF;\n                    RETURN NEW;\n                ", hash='0d3941c34c0cb624e3b874c1914e72ba8f0f1b66', operation='UPDATE', pgid='pgtrigger_refund_forward_f1973', table='payments_refund', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='refund',
            trigger=pgtrigger.compiler.Trigger(name='shift_must_be_open', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NEW.shift_id IS NOT NULL\n               AND (TG_OP = 'INSERT' OR NEW.shift_id IS DISTINCT FROM OLD.shift_id) THEN\n                PERFORM 1 FROM payments_shift s\n                 WHERE s.id = NEW.shift_id AND s.status = 'open' FOR SHARE;\n                IF NOT FOUND THEN\n                    RAISE EXCEPTION 'SHIFT_NOT_OPEN: shift % is not open (table %)',\n                        NEW.shift_id, TG_TABLE_NAME;\n                END IF;\n            END IF;\n            RETURN NEW;\n        ", hash='0550d0306370c64f55c09df3f5cbf35af474f886', operation='INSERT OR UPDATE', pgid='pgtrigger_shift_must_be_open_531f0', table='payments_refund', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shift',
            trigger=pgtrigger.compiler.Trigger(name='truncate_guard', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            IF NOT pg_has_role(\n                session_user,\n                (SELECT c.relowner FROM pg_class c WHERE c.oid = TG_RELID),\n                'MEMBER'\n            ) THEN\n                RAISE EXCEPTION 'APPEND_ONLY: % cannot be truncated', TG_TABLE_NAME;\n            END IF;\n            RETURN NULL;\n        ", hash='01c61c47fd9ff1c41d511073b0e3c753026d8639', level='STATEMENT', operation='TRUNCATE', pgid='pgtrigger_truncate_guard_7c479', table='payments_shift', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shift',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_shiftevent" ("cashier_id", "close_report", "closed_at", "closed_by_id", "counted_cash", "expected_cash", "id", "note", "number", "opened_at", "opening_float", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "till_id", "variance", "variance_note", "variance_reason_id") VALUES (NEW."cashier_id", NEW."close_report", NEW."closed_at", NEW."closed_by_id", NEW."counted_cash", NEW."expected_cash", NEW."id", NEW."note", NEW."number", NEW."opened_at", NEW."opening_float", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."till_id", NEW."variance", NEW."variance_note", NEW."variance_reason_id"); RETURN NULL;', hash='7b0aa56aaa369301cfcf8de8fa12139de74d8c77', operation='INSERT', pgid='pgtrigger_insert_insert_6cace', table='payments_shift', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shift',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_shiftevent" ("cashier_id", "close_report", "closed_at", "closed_by_id", "counted_cash", "expected_cash", "id", "note", "number", "opened_at", "opening_float", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "till_id", "variance", "variance_note", "variance_reason_id") VALUES (NEW."cashier_id", NEW."close_report", NEW."closed_at", NEW."closed_by_id", NEW."counted_cash", NEW."expected_cash", NEW."id", NEW."note", NEW."number", NEW."opened_at", NEW."opening_float", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."till_id", NEW."variance", NEW."variance_note", NEW."variance_reason_id"); RETURN NULL;', hash='8106a211d04da9768b81a6c708c0f2e8d6d37b7e', operation='UPDATE', pgid='pgtrigger_update_update_36fb6', table='payments_shift', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='shift',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_shiftevent" ("cashier_id", "close_report", "closed_at", "closed_by_id", "counted_cash", "expected_cash", "id", "note", "number", "opened_at", "opening_float", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "till_id", "variance", "variance_note", "variance_reason_id") VALUES (OLD."cashier_id", OLD."close_report", OLD."closed_at", OLD."closed_by_id", OLD."counted_cash", OLD."expected_cash", OLD."id", OLD."note", OLD."number", OLD."opened_at", OLD."opening_float", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."till_id", OLD."variance", OLD."variance_note", OLD."variance_reason_id"); RETURN NULL;', hash='b0e80f47430f8b5a741e73ee6137410afca9313a', operation='DELETE', pgid='pgtrigger_delete_delete_c7952', table='payments_shift', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='cashhandover',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_at__isnull', True), models.Q(('cancelled_by__isnull', False), models.Q(('cancel_note', ''), _negated=True), ('received_at__isnull', True)), _connector='OR'), name='payments_handover_cancel_documented'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method__in', ['bank_transfer', 'qr', 'card']), _negated=True), models.Q(('bank__isnull', False), models.Q(('reference', ''), _negated=True), models.Q(('reference_norm', ''), _negated=True)), _connector='OR'), name='payments_payment_bank_needs_reference'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'paid']), _negated=True), models.Q(('decided_by', models.F('requested_by')), _negated=True), _connector='OR'), name='payments_refund_approver_not_requester'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'closed'), _negated=True), ('close_report__isnull', False), _connector='OR'), name='payments_shift_close_report_frozen'),
        ),
    ]
