# Generated by Django 5.2.17 on 2026-10-07 11:49

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('patients', 'Patients'), ('services', 'Services'), ('prices', 'Price list'), ('items', 'Stock items'), ('batches', 'Batches'), ('opening_stock', 'Opening stock'), ('icd10', 'ICD-10 codes'), ('lab_tests', 'Lab tests')], max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated (preview)'), ('confirmed', 'Imported'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20)),
                ('file', models.FileField(upload_to='imports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'import job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJobEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('patients', 'Patients'), ('services', 'Services'), ('prices', 'Price list'), ('items', 'Stock items'), ('batches', 'Batches'), ('opening_stock', 'Opening stock'), ('icd10', 'ICD-10 codes'), ('lab_tests', 'Lab tests')], max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated (preview)'), ('confirmed', 'Imported'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20)),
                ('file', models.FileField(upload_to='imports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='imports.importjob')),
                ('uploaded_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Valid with warnings'), ('error', 'Error'), ('duplicate', 'Possible duplicate'), ('imported', 'Imported'), ('skipped', 'Skipped')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('duplicate_of_id', models.BigIntegerField(blank=True, null=True)),
                ('result_id', models.BigIntegerField(blank=True, help_text='Primary key of the created/updated row.', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importjob')),
            ],
            options={
                'verbose_name': 'import row',
                'ordering': ['job', 'row_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['patients', 'services', 'prices', 'items', 'batches', 'opening_stock', 'icd10', 'lab_tests'])), name='imports_job_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['uploaded', 'validated', 'confirmed', 'failed', 'cancelled'])), name='imports_job_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), _negated=True), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False)), _connector='OR'), name='imports_job_confirmation_documented'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='importjob',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "imports_importjobevent" ("confirmed_at", "confirmed_by_id", "created_at", "duplicate_rows", "error_rows", "file", "id", "imported_rows", "kind", "options", "original_filename", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "total_rows", "uploaded_by_id", "valid_rows", "validated_at") VALUES (NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."duplicate_rows", NEW."error_rows", NEW."file", NEW."id", NEW."imported_rows", NEW."kind", NEW."options", NEW."original_filename", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."summary", NEW."total_rows", NEW."uploaded_by_id", NEW."valid_rows", NEW."validated_at"); RETURN NULL;', hash='17f60e96878daabab5bf5d4a42f7c26de979ed0b', operation='INSERT', pgid='pgtrigger_insert_insert_d8b64', table='imports_importjob', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='importjob',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "imports_importjobevent" ("confirmed_at", "confirmed_by_id", "created_at", "duplicate_rows", "error_rows", "file", "id", "imported_rows", "kind", "options", "original_filename", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "total_rows", "uploaded_by_id", "valid_rows", "validated_at") VALUES (NEW."confirmed_at", NEW."confirmed_by_id", NEW."created_at", NEW."duplicate_rows", NEW."error_rows", NEW."file", NEW."id", NEW."imported_rows", NEW."kind", NEW."options", NEW."original_filename", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."summary", NEW."total_rows", NEW."uploaded_by_id", NEW."valid_rows", NEW."validated_at"); RETURN NULL;', hash='6bd078a8cf3dbe8de4454334d9124dc122fa6980', operation='UPDATE', pgid='pgtrigger_update_update_7be62', table='imports_importjob', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='importjob',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "imports_importjobevent" ("confirmed_at", "confirmed_by_id", "created_at", "duplicate_rows", "error_rows", "file", "id", "imported_rows", "kind", "options", "original_filename", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "total_rows", "uploaded_by_id", "valid_rows", "validated_at") VALUES (OLD."confirmed_at", OLD."confirmed_by_id", OLD."created_at", OLD."duplicate_rows", OLD."error_rows", OLD."file", OLD."id", OLD."imported_rows", OLD."kind", OLD."options", OLD."original_filename", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."summary", OLD."total_rows", OLD."uploaded_by_id", OLD."valid_rows", OLD."validated_at"); RETURN NULL;', hash='ffca4ec06c0b68038eb88d69adcc65e5d142c71f', operation='DELETE', pgid='pgtrigger_delete_delete_d917a', table='imports_importjob', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='importjobevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9fde5b1c8105ac10216d7964dad56244150da12a', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_d4943', table='imports_importjobevent', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'status'], name='imports_row_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['valid', 'warning', 'error', 'duplicate', 'imported', 'skipped'])), name='imports_row_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('job', 'row_no'), name='imports_row_unique'),
        ),
    ]
